### ISSUE TITLE
UI - Volume Integrity 

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#1007]
The backups seem to be corrupted. 

When mounting a restored volume, it shows: `cannot mount; probably corrupted filesystem`

Error:

`MountVolume.SetUp failed for volume "pvc-1c35c209-3ed2-4e15-8e25-6064e43f97c5" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-1c35c209-3ed2-4e15-8e25-6064e43f97c5 /var/lib/kubelet/pods/13fdbc0e-9380-4461-b998-78c36a9c0c32/volumes/kubernetes.io~csi/pvc-1c35c209-3ed2-4e15-8e25-6064e43f97c5/mount Output: mount: /var/lib/kubelet/pods/13fdbc0e-9380-4461-b998-78c36a9c0c32/volumes/kubernetes.io~csi/pvc-1c35c209-3ed2-4e15-8e25-6064e43f97c5/mount: cannot mount; probably corrupted filesystem on /dev/longhorn/pvc-1c35c209-3ed2-4e15-8e25-6064e43f97c5.`

This likely could be the fault of the backend (still currently troubleshooting)

But it could be helpful to show in the UI, which volumes are corrupted

**Comment by yasker** [comment]
It's hard for the storage system to know if the filesystem is corrupted or not, or even the block device has a filesystem or not, since unknown filesystem will be treated as raw data.

**Comment by ainiml** [comment]
> It's hard for the storage system to know if the filesystem is corrupted or not, or even the block device has a filesystem or not, since unknown filesystem will be treated as raw data.

Oh interesting. If Longhorn isn't intimately tied to the filesystem (and I don't have knowledge about this), how come it wasn't possible for Longhorn to be more filesystem agnostic?

Instead of limiting to specific filesystems with specific features? 

Where instead, it just needs to write and read files from *somewhere*, regardless of the underlying filesystem?

I may need to give up on Longhorn, because of the strict filesystem requirements. It was really fun to use though

**Comment by yasker** [comment]
I think there might be a bit of misunderstanding.

There are two parts in Longhorn related to a filesystem: the filesystem Longhorn used to store data (e.g. `/var/lib/rancher/longhorn/replicas/` on the host), and the filesystem user built on top of the Longhorn volume.

Longhorn requires certain filesystem (e.g. ext4) on the host to store data because Longhorn depends on the file extent feature of the filesystem to store the metadata of the volume (e.g. which part of the volume has been written).

But Longhorn doesn't care (or know) how the user uses the Longhorn volume, which is normally present as a block device on the host. Users can format it with any filesystem, or just use it as a raw block device.

The original issue was related to how the user used the Longhorn block device, which Longhorn doesn't know much about, at least at the moment.

I admit that Longhorn might not be fit for everyone. We designed Longhorn with the backing of high-performance block devices in mind, and we don't think much about how it works with e.g. s3backer/s3fs as in your case.

In fact, I am wondering, what's the usage case of Longhorn in your case with s3backer? It seems easier to just expose the filesystem s3backer provided to the Kubernetes, instead of put Longhorn in between.

**Comment by ainiml** [comment]
> I think there might be a bit of misunderstanding.
> 
> There are two parts in Longhorn related to a filesystem: the filesystem Longhorn used to store data (e.g. `/var/lib/rancher/longhorn/replicas/` on the host), and the filesystem user built on top of the Longhorn volume.
> 
> Longhorn requires certain filesystem (e.g. ext4) on the host to store data because Longhorn depends on the file extent feature of the filesystem to store the metadata of the volume (e.g. which part of the volume has been written).
> 
> But Longhorn doesn't care (or know) how the user uses the Longhorn volume, which is normally present as a block device on the host. Users can format it with any filesystem, or just use it as a raw block device.
> 
> The original issue was related to how the user used the Longhorn block device, which Longhorn doesn't know much about, at least at the moment.
> 
> I admit that Longhorn might not be fit for everyone. We designed Longhorn with the backing of high-performance block devices in mind, and we don't think much about how it works with e.g. s3backer/s3fs as in your case.
> 
> In fact, I am wondering, what's the usage case of Longhorn in your case with s3backer? It seems easier to just expose the filesystem s3backer provided to the Kubernetes, instead of put Longhorn in between.

I think the `file extent` feature is the feature not many has.

I wonder why give Longhorn a path to a mounted volume, instead of the offering the block device to Longhorn, and let Longhorn format it, mount it. 

Granted it actually worked better having control over mounting flags for the block device.

We only have the option of either gluster or ceph for PV/PVC. Neither solution was great, especially with the process for setting it up; it's nothing as simple as Longhorn

Using s3backer came about, because Longhorn needed an XFS or EXT4 file system. And there weren't many options for offering a block device over S3.
