### ISSUE TITLE
Upgrade path from v0.7.0 to v0.8.0

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1055]
Need to implement the upgrade path from v0.7.0 to v0.8.0

**Comment by shuo-wu** [comment]
Test steps:
1. Deploy Longhorn v0.7.0
2. Launch a pod with Longhorn volume, write data into the volume
3. Upgrade Longhorn system to the latest
4. Check if the running pod and the existing volume is still available (by writing/reading data)
5. Upgrade the volume engine image to the latest. --> The CurrentImage of this volume won't change since the old engine image is incompatible. (offline upgrade)
6. Delete the pod. --> The volume gets detached. 
7. Recreate the pod. --> The volume becomes running with the existing data unchanged and the current image is the latest one.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
