### ISSUE TITLE
default storage path in helm deployment

### ISSUE THREAD

**Issue by runningman84** [longhorn/longhorn#1056]
I have tried to install longhorn in my 3 node k3s cluster. I do not really understand why this causes some files to be stored in /var/longhorn and similar files in /var/lib/rancher/longorn
I would like to have a consistent behaviour. It looks like real disk images are stored in /var/longhorn and the controller binaries are stored in the other folder.

**Comment by runningman84** [comment]
I have tried to create a volume in /var/longhorn and create a symbolic link from /var/lib/rancher/longhorn to it.

But now I cannot create any volume:
```
longhorn-system/longhorn-manager-74bmt[longhorn-manager]: time="2020-02-14T21:43:31Z" level=warning msg="pvc-f92e5ed6-f7b6-4125-886b-3e5a595a2103-r-3e7111d1: time=\"2020-02-14T21:41:24Z\" level=info msg=\"Creating volume /host/var/lib/rancher/longhorn/replicas/pvc-f92e5ed6-f7b6-4125-886b-3e5a595a2103-d075eb0f, size 2147483648/512\""
longhorn-system/longhorn-manager-74bmt[longhorn-manager]: time="2020-02-14T21:43:31Z" level=warning msg="pvc-f92e5ed6-f7b6-4125-886b-3e5a595a2103-r-3e7111d1: time=\"2020-02-14T21:41:24Z\" level=fatal msg=\"Error running start replica command: mkdir /host/var/lib/rancher/longhorn/replicas/pvc-f92e5ed6-f7b6-4125-886b-3e5a595a2103-d075eb0f: no such file or directory\""
```

What is the correct way to deploy it via helm and store all data in /var/longhorn?

**Comment by yasker** [comment]
I think you meant `/var/lib/longhorn`. But which version are you using? We don't use `/var/lib/longhorn` in our latest release v0.7.0.

**Comment by runningman84** [comment]
I am just using the Helm Chart in this repo with default values.

**Comment by yasker** [comment]
@runningman84 

The Longhorn volume data is stored at each `disk` of Longhorn, that directory can be specified through the Longhorn UI -> Node -> Edit Node or through the [Default Data Path in the settings](https://github.com/longhorn/longhorn/blob/master/docs/settings.md#default-data-path).

For other metadata files on the disk, we're moving from `/var/lib/rancher/longhorn` to `/var/lib/longhorn`, so if you see some disparity between the two, it would be resolved in the next two releases.

Though when I've double-checked our chart file, I realized we'd made a mistake on one setting. https://github.com/longhorn/longhorn/blob/7aa122b10ec6902f27558f35b8cdd717d64886d5/chart/templates/daemonset-sa.yaml#L47

This should point to `/var/lib/longhorn-settings` as in https://github.com/longhorn/longhorn/blob/ed02804b203a24955c037fa60bbfc5810ccae2df/deploy/longhorn.yaml#L270 instead of `/var/lib/longhorn/settings`. The same issue was found in the Rancher chart https://github.com/rancher/charts/blob/28cb367ac24077aad3d667db7bc9c59002b03ad1/proposed/longhorn/latest/templates/daemonset-sa.yaml#L47

cc @shuo-wu . We might need to delay the directory migration into the next release because of the recurring mount issue. @shuo-wu  can you double-check if recreating manager pod can help with the issue?

**Comment by yasker** [comment]
@shuo-wu Can you provide the steps to verify the issue? I believe you found that the recursive mount doesn't exist for the helm chart after the upgrade.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Comment by sumanusk** [comment]
i want to change the default path of data from /var/lib/longhornhorn to other. may i know how and where to change

**Comment by simonjcarr** [comment]
> i want to change the default path of data from /var/lib/longhornhorn to other. may i know how and where to change
> 
> 
See @runningman84 comment above.

The Longhorn volume data is stored at each disk of Longhorn, that directory can be specified through the Longhorn UI -> Node -> Edit Node or through the Default Data Path in the settings.
