### ISSUE TITLE
[question] 2 Longhorn instances in the same cluster

### ISSUE THREAD

**Issue by jocarren** [longhorn/longhorn#1062]
I need to backup 2 volumes to different S3 backupstores:

Vol1 --> S3-1 
Vol2 --> S3-2

Would it be a problem to run 2 instances of Longhorn (each one in it's own namespace) in the same cluster? 
Is there another way to do this?

**Comment by yasker** [comment]
@jocarren we don't support installing multiple Longhorn systems in a cluster since we're also operating depends on some configuration files on the node.

Currently, we also don't support multiple backup targets but that sounds like a better approach to your problem. We can put `multiple backup target` support into consideration.

**Comment by jocarren** [comment]
Thanks!

If I come up with a workaround I'll let you guys know.
