### ISSUE TITLE
nfsv3 backup

### ISSUE THREAD

**Issue by h3yduck** [longhorn/longhorn#107]
Hi folks,

We are trying to configure nfs backup with a version 3 nfs server. On Ubuntu 18.04 '-t nfs4' fallbacks to nfs version 3, however on Ubuntu 16.04 it doesn't and raises an error. Since Longhorn's Docker images are built from 'Ubuntu 16.04' and '-t nfs4' mount option is used we cannot backup using v3.

Wouldn't '-t nfs' be enough since it tries v4.2, v4.1, v4.0, v3...?
I think building images from Ubuntu 18.04 would solve this as well.

Thank you in advance,
Szabolcs Gelencsér

**Comment by yasker** [comment]
Hi @h3yduck 

We've decided early not to support NFSv3 because it's not easy to set up the NFS client inside the container compared to the NFSv4. We will need to run `rpcbind` inside the container, probably as a privileged container as well, among other things. NFSv4 in comparison is much easier.

Is there a reason that NFSv3 is preferred in your setup?

**Comment by n00bsi** [comment]
>Is there a reason that NFSv3 is preferred in your setup?

because the Storage system did only offer NFSv3

**Comment by derekbit** [comment]
> > Is there a reason that NFSv3 is preferred in your setup?
> 
> because the Storage system did only offer NFSv3

backup target supports customized options. You can try to use NFSv3.
https://longhorn.io/docs/1.6.2/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-nfs-backupstore

**Comment by dberardo-com** [comment]
would be nice to see nfsv3 support too
