### ISSUE TITLE
[BUG] Longhorn instance manager image is too long to fit in the labels when installing from private registry

### ISSUE THREAD

**Issue by martinounap** [longhorn/longhorn#1097]
**Describe the bug**
Error in manager logs

E0311 08:35:46.710610       1 node_controller.go:298] fail to sync node for longhorn-system/rke-worker06: InstanceManager.longhorn.io "instance-manager-e-5b7cf9df" is invalid: metadata.labels: Invalid value: "{PRIVATE_REGISTRY}-longhornio-longhorn-instance-manager-v1_20200301": must be no more than 63 characters

**To Reproduce**
Use longhorn from private registry

**Environment:**
 - Longhorn version: 0.8.0

**Comment by martinounap** [comment]
I switched back to public registry with instance manager. And can go on right now. But it would be nice to be able to use private registry.

**Comment by martinounap** [comment]
Ok, I managed to use private registry.
I changed docker name, so it would fit to 63 char:

{PRIVATE_REGISTRY}/longhornio/longhorn-i-manager:v0.8.0

**Comment by meldafrawi** [comment]
it's a Kubernetes limitations
Instance manager pods have labels with key
`longhorn.io/instance-manager-image` and value 
`REGISTRY_URL-USER-IMAGE_NAME-TAG` which is required to be 63 characters or less
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set (edited)

**Comment by yasker** [comment]
Move to 1.0.0, see if we can find a more easy way for user to solve it, without manual renaming. At least we can provide the guide on how to rename to workaround this issue.

**Comment by yasker** [comment]
@meldafrawi is there anything we can do about this? Or we can provide instructions on how to work around this.

**Comment by sowmyav27** [comment]
**Verified in `https://staging.longhorn.io/`**

Can we change the following texts

1. `Longhorn manager would report errors in the log when this happened:` **to** `Longhorn manager would report errors in the log when this happens:`
2. `it’s known Kubernetes limitaion that label value should be no more than 63 characters` **to** `It’s a known Kubernetes limitation that label value should be no more than 63 characters`
3. `it’s highly recommended not to maniplute image tags, specially instance manager image tag e.g v1_20200301, since we intentionally used date so it is not assoctiated with Longhorn version.` **to** `It’s highly recommended not to manipulate image tags, especially the instance manager image tag e.g v1_20200301, since we intentionally use date so it is not associated with Longhorn version.`

**Comment by yasker** [comment]
@sowmyav27 : @catherineluse is working on the document. She has a new PR to update some of the documentations. Can you check https://github.com/longhorn/website/pull/104/commits to see if the air gap part looks to you?

**Comment by sowmyav27** [comment]
@yasker I verified air gap in this PR. https://github.com/longhorn/website/pull/104/commits

I have one comment (from my previous one)

We could change 

`It's highly recommended not to manipulate image tags, especially instance manager image tags such as v1_20200301, because we intentionally used the date to avoid associating it with a Longhorn version.` 

**to** 

`It's highly recommended not to manipulate image tags, especially instance manager image tags such as v1_20200301, because we intentionally use the date to avoid associating it with a Longhorn version.`

**Comment by yasker** [comment]
@sowmyav27 Can you leave the comment in the PR? Thanks.

**Comment by yasker** [comment]
@meldafrawi remember to move this issue to `Merged` when the doc is merged.

**Comment by sowmyav27** [comment]
**Verified in https://staging.longhorn.io/**
Changes are available.

`It’s highly recommended not to manipulate image tags, especially instance manager image tags such as v1_20200301, because we intentionally use the date to avoid associating it with a Longhorn version.`
