### ISSUE TITLE
[FEATURE] Improve node failure handling

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1105]
Current status: ~~https://github.com/longhorn/longhorn/blob/master/docs/node-failure.md~~ moved to https://longhorn.io/docs/0.8.0/users-guide/node-failure/

We require users to manually remove the workload in order get volume reattached. It's not ideal even given the limitation of Kubernetes.

We need to figure out a better way to make the workload recovery automatic.

**Comment by rsoika** [comment]
Just for information: I read [this](https://www.ibm.com/support/knowledgecenter/SSRQ8T_1.0.0/csi_ug_node_crash.html) problem description and tried it out.
Deleting the volumeattachment

    $ kubectl delete volumeattachment csi-08d9842e.......

This leads into a situation where the volume can be attached to the new pod and the pod starts. Ok still the old pod is listed in 'terminating' status. 

Maybe there is a way to delete the volumeattachment in such a scenario after a while automatically?

**Comment by yasker** [comment]
Thanks @rsoika . If deleting the volumeattachment works in this scenario, we can do that. It's better than deleting a pod from Longhorn. We will investigate.

**Comment by rsoika** [comment]
I now reproduced the same behavior with a ceph cluster (octopus release). I think this is a general kubernetes problem and not a problem from longhorn. 

I try to describe the problem now once again just for documentation ([this link](https://github.com/longhorn/longhorn/blob/master/docs/node-failure.md) is no longer working).

Environment: 
- Kubernetes Cluster 1.18.1.
- 3 worker nodes (node1,node2,node3)

How to reproduce:

1. POD (e.g. a posgress dabase) is deployed on node1. The POD defies a PersistentVolumeClaim for storage (hosted on longhorn)
1. Hard shutdown from node1
1. Kubernetes (after 5 minutes) recognize lost node and starts a rescheduling of the POD to node2
1. POD on node2 does not start because the volume is still attached to the terminating POD on node1 which is in a durable terminating status

Solution: manually delete the volumeattachment or kill the terminating pod.

**Comment by yasker** [comment]
Thanks for the update @rsoika . I've updated the doc link (since we've moved our docs to https://longhorn.io/docs/).

**Comment by yasker** [comment]
Btw, we're totally aiming to solve this in the Longhorn's framework, if Kubernetes cannot solve it by itself.

**Comment by rsoika** [comment]
It looks like there are discussions since nearly 2 years about this issue:

https://github.com/kubernetes/kubernetes/issues/65392
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/181

I am not a kubernets expert - just a 'normal' user not understanding enough to give further help. But there still seems to be no solution.

**Comment by rsoika** [comment]
as you may have seen, I have had continued the discussions about the 'node-fancing' topic in the kubernetes-sigs project. It seems that there will be no solution in kubernetes in the near future. If you find a way to address this in Longhorn, I think this would be a unique feature compared to other solutions.

**Comment by yasker** [comment]
@rsoika We've decided to add support to auto-detach volume from failed deployment pod in the next release, which will be tracked at https://github.com/longhorn/longhorn/issues/820 , since this scenario is relatively straightforward and doesn't require extra permissions from Kubernetes.

We will start investigating other options after the GA.

**Comment by yasker** [comment]
We also want to implement the automatically recovery for the stateful set.

**Comment by PhanLe1010** [comment]
**To reproduce**
1. Set up a cluster of 3 nodes. 
1. Install Longhorn and set `Default Replica Count = 2`
1. create a SetfullSet. Ex:
```
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml
```
1. Find the node which contains one pod of the StatefullSet. Power off the node
1. After about 5 minutes, checking `kubectl` shows that the pod stuck in terminating state forever.

**Comment by yasker** [comment]
What are the validation steps?

**Comment by PhanLe1010** [comment]
It is in the manual test plan here https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan#improve-node-failure-handling

I will create a PR to move it to `longhorn-test` repo though

**Comment by PhanLe1010** [comment]
I updated manual test plan at the PR https://github.com/longhorn/longhorn-tests/pull/395

**Comment by yasker** [comment]
This issue has been in Review for 21 days. What's blocking this issue moving to Merged?

**Comment by PhanLe1010** [comment]
I think this one should be good to merge. I just re-requested reviews from Joshua and Shuo.

**Comment by khushboo-rancher** [comment]
Verified on Longhorn master - 08-27-2020

Validation - **Pass**

**Scenarios Tested:**
1. The default value for setting ```Pod Deletion Policy When Node is Down``` is ```do-nothing```
2. The setting doesn't take empty value.
3. The setting takes input ```do-nothing, delete-statefulset-pod, delete-deployment-pod and delete-both-statefulset-and-deployment-pod```, anything other than these inputs throws an error.
```
level=error msg="Error in request: fail to set settings with invalid node-down-pod-deletion-policy: value dummy of settings node-down-pod-deletion-policy is invalid: value dummy is not a valid choice, available choices [do-nothing delete-statefulset-pod delete-deployment-pod delete-both-statefulset-and-deployment-pod]"
```
4. The test cases from https://longhorn.github.io/longhorn-tests/manual/pre-release/node/improve-node-failure-handling/
5. Pods with ```scaling/upgrade policy``` as ```Start upgraded pods only when old ones are manually deleted, Rolling: stop old pods, then start new and Kill ALL pods, then start new```. With all these policies, pods behavior is intact as mentioned https://longhorn.github.io/longhorn-tests/manual/pre-release/node/improve-node-failure-handling/
5. No impact on pods don't have longhorn volume attached.
