### ISSUE TITLE
[Doc] dynamic created persistence volumes and durable persistence volumes

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#1160]
Hi,
I am working on a open source infrastructure project to setup a self managed kubernetes cluster for small and medium organizations. In this setup I use longhorn for distributed storage. Everything works fine and longhorn is really a great project!

Only the concept of dynamic created persistence volumes and durable persistence volumes take me  some time to understand.
In my project I am now trying to explain the difference between these to approaches and how you create a durable volume with Longhorn (not being deleted with your POD). 

Maybe you can take a look at this documentation: 

https://github.com/imixs/imixs-cloud/blob/master/doc/STORAGE.md#create-longhorn-volumes

If it makes sense to you to supplement the documentation in Longhorn about manually created persistence volumes please let me know. Perhaps I can help with this. I hope not that my description is absolute nonsense ;-)

**Comment by yasker** [comment]
Hi @rsoika ,

One thing I noticed in the doc: you specify the replicas in Longhorn as `PODS` in the diagram, which can be confusing because the reader might think it's the workload, instead of the process provide Longhorn access to the local node's disk. A diagram similar to https://longhorn.io/ might be more clear on how Longhorn works.

**Comment by rsoika** [comment]
yes - that's true. I have improved the diagram a little bit.  Thanks for your feedback
