### ISSUE TITLE
[BUG] Error during backup process will be removed quickly without user knowing

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1249]
**Describe the bug**
No error message is presented when a user takes a backup when incorrect backup target is entered 

**To Reproduce**

- Steps to reproduce the behavior:
- Give. an incorrect value in Backup target in Settings page on Longhorn.
- create a volume, attach it to a workload, write data into the volume.
- Go to volume details page on Longhorn UI.
- Click on create. backup.
- Backup creation fails

**Expected behavior**
As the backup creation fails because of incorrect backup target data in the settings page, an error should be displayed.

**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.17.4
 - Node OS type and version: rke DO

**Comment by sowmyav27** [comment]
Similar to - https://github.com/longhorn/longhorn/issues/1217

**Comment by yasker** [comment]
I am not sure it's a backend issue or frontend. @sowmyav27 can you check if API returns any errors? e.g. in backup status field of the volume.

**Comment by sowmyav27** [comment]
On clicking on Create backup the api call - `https://<ip>/v1/volumes/vol1?action=snapshotBackup` gives - response: 200

Error in one of the replicas of the volume
```
[vol1-r-7d3e8f0b] time="2020-05-01T21:43:20Z" level=info msg="Replica server starts to snapshot [12109fd7-e150-4885-8e10-410ca6ad4c99] volume, user created true, created time 2020-05-01T21:43:20Z, labels map[]"
[vol1-r-7d3e8f0b] time="2020-05-01T21:43:20Z" level=error msg="{\n\n}" pkg=s3
time="2020-05-01T21:43:20Z" level=error msg="Fail to list s3: AWS Error:  MissingRegion could not find region configuration <nil>\n" pkg=s3
time="2020-05-01T21:43:20Z" level=error msg="Error creating backup: AWS Error:  MissingRegion could not find region configuration <nil>\n"
```

**Comment by yasker** [comment]
The backup will be started but the error should show up in the volume's backup status. You can check the `v1` API endpoint to see if it's there.

**Comment by sowmyav27** [comment]
Backup status does not have the failed backup's status. Only the good ones (already existing ones) are available

```
"backupStatus": [
        {
          "actions": null,
          "backupURL": "<URL>",
          "error": "",
          "id": "backup-15c3baca4d1c4072",
          "links": null,
          "progress": 100,
          "replica": "vol1-r-7d3e8f0b",
          "snapshot": "5017ddd3-cb83-47fb-ad2d-2f4ea2f5fd3a",
          "state": "complete"
        },
        {
          "actions": null,
          "backupURL": "<URL>",
          "error": "",
          "id": "backup-67afe98a4d094d73",
          "links": null,
          "progress": 100,
          "replica": "vol1-r-7d3e8f0b",
          "snapshot": "71a71476-87bf-47d8-a90f-a9cc0880066f",
          "state": "complete"
        },
        {
          "actions": null,
          "backupURL": "<URL>",
          "error": "",
          "id": "backup-f3f1a00958eb412b",
          "links": null,
          "progress": 100,
          "replica": "vol1-r-7d3e8f0b",
          "snapshot": "4e01b1a4-7a76-47b5-b0ec-5d1616596e26",
          "state": "complete"
        }
      ],
```

**Comment by yasker** [comment]
This might due to we've removed the failed backups very soon after it was reported.

Use this bug to track the error reporting in the Longhorn engine for backup status.

**Comment by joshimoo** [comment]
To solve this we need a persistentence layer for backup information. We might get that as part of the kubernetes csi snapshoter #304

**Comment by jenting** [comment]
After the backup refactoring, we did not design if the backup target is incorrect, update the Backup CR state to error.
We design it as if the backup target is incorrect, the backup_controller will keep reconciling the Backup CR. If the Backup CR state changes to error, the backup_controller will not reconcile it.

Also, we have the BackupTarget CR to know whether the backup target is available or not.
The UI will show the backup target is unavailable when the user clicks the Backup page.

Therefore, if the user misconfigures the backup target, once the user fixes the backup target, the backup_controller will reconcile the Backup CR and perform a snapshot backup.

**Comment by joshimoo** [comment]
Backup target monitor is responsible for determining availability of the target.

The backup API call should fail when the target is not available (down, incorrect information) before creation of a backup.

**Comment by joshimoo** [comment]
For backup Cr, transient Errors can be retried with backoff and maxRetries terminal errors should lead to final backup failure.

Example for target, last heartbeat 1min ago, but now when the controller tries to reconcile a new backup the connection Initiation times out. 

Since the target was healthy once we can treat this as a transient error and have the controller reconcile.

The API would still block the creation of the backup Cr while a backup target is unhealthy.

**Comment by joshimoo** [comment]
Typing from the phone, sorry if the tone sounds short 🙂

**Comment by joshimoo** [comment]
Example for a Terminal error, backup Cr refers a non existing snapshot. Since this backup can never be done this can be marked immediately as failure, with completion time set to the time the Cr entered a Termin state.

**Comment by shuo-wu** [comment]
> After the backup refactoring, we did not design if the backup target is incorrect, update the Backup CR state to error.
We design it as if the backup target is incorrect, the backup_controller will keep reconciling the Backup CR. If the Backup CR state changes to error, the backup_controller will not reconcile it.

Actually, by design, all existing backup CRs will become history and the controllers will do nothing for them if somehow the backup target is unavailable. And all CRs will be resyned when the backup target is modified and back to running.

Of course, updating all backup CRs to error for this case is a feasible solution.

**Comment by mantissahz** [comment]
@longhorn/qa
Could you please check if this issue is still there?
I think it is solved by current implemented codes and my testing.
GUI would not allow to create a backup if backup target was invalid.
And By using a manifest to create a backup CR with invalid backup target, the backup would be failed and show the state is `error` in the end.

**Comment by innobead** [comment]
> @longhorn/qa Could you please check if this issue is still there? I think it is solved by current implemented codes and my testing. GUI would not allow to create a backup if backup target was invalid. And By using a manifest to create a backup CR with invalid backup target, the backup would be failed and show the state is `error` in the end.

@mantissahz please check if the above validations all work to the existing supported release branches (1.3/1.4/1.5, surely master).

**Comment by mantissahz** [comment]
A backup of v1.3.x will **NOT** be failed if backup target is invalid.
A backup will not be failed for an invalid S3 backup target.

A backup of v1.4.x, v1.5.x and master-head will be failed with backup target is invalid because the nfs mount timeout mechanism. https://github.com/longhorn/longhorn/issues/5662, https://github.com/longhorn/longhorn/issues/5628
That causes a `DeadlineExceeded` error at [ReplicaClient/CreateBackup](https://github.com/longhorn/longhorn-engine/blob/master/pkg/replica/client/client.go#L516-L525) when mounting is still in progress at [GetBackupStoreDriver](https://github.com/longhorn/backupstore/blob/master/nfs/nfs.go#L114-L115).

**Comment by chriscchien** [comment]
Verified **pass** in longhorn master(longhorn-manager `840dbf`) with test [steps](https://github.com/longhorn/longhorn/issues/1249#issuecomment-1638054420)

With a invalld backup target set
- From UI, backup can not created. The button is gray out and will show an error message when mouse move over that button
- Create backup by manifest, that backup will state `Error` as below

```
status:
  backupCreatedAt: ""
  compressionMethod: ""
  error: |
    proxyServer=10.42.1.16:8501 destination=10.42.2.16:10010: failed to backup snapshot 95343dfd-9d6f-4536-8ce6-634792656810 to backup-7326b5fd40574fdc123a: rpc error: code = Unknown desc = failed to create backup to s3://chrsdfsdfsdfsdfis816@us-east-1/backup/backupstore/ for volume pvc-62e74529-a07b-47ae-b588-828648bbc569: rpc error: code = Unknown desc = failed to list objects with param: {
      Bucket: "chrsdfsdfsdfsdfis816",
      Delimiter: "/",
      Prefix: "backup/backupstore/"
    } error: AWS Error:  NoSuchBucket The specified bucket does not exist <nil>
    404 X9H9CK82PHAZ0HJJ
  labels: null
  lastSyncedAt: "2023-08-10T06:15:36Z"
  messages: null
  ownerID: ip-172-31-42-27
  progress: 0
  replicaAddress: ""
  size: ""
  snapshotCreatedAt: "2023-08-10T06:11:07Z"
  snapshotName: ""
  state: Error
```
