### ISSUE TITLE
[FEATURE] Preserve the data from existing disks on the new nodes

### ISSUE THREAD

**Issue by all4innov** [longhorn/longhorn#1269]
**Description**
As shown in the figure, Longhorn is completely off when all EC2 k8s workers was recreated via an ASG (the red down nodes are the old and the green schedulable are the new) knowing that the new instances are attaching the same EBS volumes with the same datapath (so in theory preserving all replicas).

![image](https://user-images.githubusercontent.com/520080/80543253-d3dcd000-89ae-11ea-8242-0b7f70f4f197.png)

**NB**
- RKE cluster deployed as custom via Rancher 2.3
- Kubernetes 1.15

**Comment by yasker** [comment]
This might impact the design on https://github.com/longhorn/longhorn/issues/1151

**Comment by shuo-wu** [comment]
Test step 1:
1. Deploy Longhorn v1.0.2.
2. Add an extra disk to a node and disable the default disk for the node. (So that all replicas scheduled on this node will use the extra disk.)
3. Create and attach volumes then write data to the volumes.
4. Upgrade Longhorn to the latest version.
5. Verify all running volumes **keep** `Healthy` during/after the upgrade.
6. Verify the existing volume rebuilding works fine.
7. Detach some running volumes.
8. Directly shut down the node containing the extra disk. Then verify all running replicas on the node will become failed.
9. Verify if all disk of the node becomes `Disconnected` in the UI Node page.
10. In the cloud vendor platform, Attach the extra physical disk to another running node (not Longhorn disk and Longhorn node). Then mount the disk to a mount point in the node host.
11. On the Longhorn Node page, Click `connect`, use the mount point as a Longhorn disk for the node. 
12. Verify 
    1. the disconnected Longhorn disk object (which represents the extra physical disk) will be reused by the node.
    2. the node ID of all replicas (failed replicas are included) that use the extra disk will be updated.
13. Attach the `detached` volumes. Verify r/w works fine.

Test step 2:
    1. Launch the latest Longhorn.
    2. Create and attach some volumes.
    3. Disable the setting `retain-disks-during-node-deletion`.
    4. Delete a node.
    5. Verify all disks on the node are gone with the node.
    6 Verify all volumes/replicas on the removed node/disks can be deleted.

**Comment by yasker** [comment]
Need doc and test skeleton. Also, add one more test case (also doable by e2e test)
1. Add a disk to node A in path A (e.g. `/opt/disk1`).
2. Create a volume, write data to it, detach the volume.
3. Disconnect the disk and add it to node B on a different path (e.g. `/opt/disk1-new`)
4. Make sure it's recognized.
5. Attach the volume, check the data. Make sure there is no rebuild happening.

**Comment by yasker** [comment]
Didn't make it to v1.1.0. Punt to v1.2.0.

**Comment by yasker** [comment]
We have a new design that should reduce the time to implement significantly. Move back to v1.1.0.

**Comment by khushboo-rancher** [comment]
Verified with longhorn master - 11/16/2020

Validation - **Partially Passed**

Scenario 1 - With ```Replica Replenishment Wait Interval``` is set to 1200 sec
1. Add a disk to node A in path A (e.g. `/opt/disk1`).
2. Create a volume, write data to it, detach the volume.
3. Disconnect the disk and add it to node B on a different path (e.g. `/opt/disk1-new`)
4. The failed replica should be reused and no new replica rebuilding should be happening.
5. Attach the volume, check the data.

Scenario 2 - With ```Replica Replenishment Wait Interval``` is set to 60 sec
1. Add a disk to node A in path A (e.g. `/opt/disk1`).
2. Create a volume, write data to it, detach the volume.
3. Disconnect the disk.
4. Longhorn should try to schedule a new replica after 60 sec, It should fail to do so if ```Replica Node Level Soft Anti-Affinity``` is not enabled.
5. Add the disk to node B on the same path (e.g. `/opt/disk1`)
6. A new replica should be created not node B.
7. Attach the volume, check the data.

Validation with ASG is in progress, will update the result here.

**Comment by khushboo-rancher** [comment]
I tried with ASG and observed that on instance refresh in ASG, the EBS volume also gets created with ec2 instances and doesn't use the same EBS volumes.

@all4innov Could you please provide the details of your set up and how ec2 uses the same EBS on instance refresh in ASG?

The steps I took are as below.
Scenario -1
1. Created a launch template in AWS and configured root EBS volume and additional EBS volume. Disabled the option ```deletion of the volumes on instance termination```.
2. Created an Autoscaling group with the above launch template.
3. Created a cluster with the instances created by ASG using RKE.
4. Imported the cluster in Rancher.
5. Deployed Longhorn and created a few volumes and wrote some data into them.
6. Updated the launch template in ASG with user data to add the node to the cluster.
7. Refreshed the instances in the ASG.
8. With new instances, new EBS volumes also got created in AWS.

Scenario - 2
1. Created a launch template in AWS with user data to add the node in a cluster in Rancher. Configured root EBS volume and additional EBS volume (```deletion of the volumes on instance termination``` disabled) in the template.
2. Created an Autoscaling group using the above launch template.
3. ASG created instances and a cluster with those nodes got created in Rancher.
4. Deployed longhorn and created a few volumes and wrote some data into it.
5. Did an instance refresh in ASG.
6. With new instances, new volumes also got created in AWS.

**Comment by all4innov** [comment]
@khushboo-rancher similar to the last 2 lines, a script (based on cloud-init) where at boot of each new instance there is a check of available pre-provisioned EBS volumes (created as a seperate step from ASG) to attach and mount one that is available or detached from an older/terminated instance.

**Comment by khushboo-rancher** [comment]
@all4innov In this case, to use this feature in Longhorn v1.1.0, you will have to adjust ```Replica Replenishment Wait Interval``` depending on how fast you're adding those disks in Longhorn. 
By default ```Replica Replenishment Wait Interval``` is 600 secs, so Longhorn will try to use the existing replica till 600 sec and if couldn't find it, Longhorn will rebuild a new replica.

**Comment by all4innov** [comment]
@khushboo-rancher sounds perfect and great having the flexibility with `Replica Replenishment Wait Interval` as it's related to the ASG process and disk attachment process (e.g., AWS or OnPrem environment)
Just another point: In case of longhorn started rebuilding the replicas and just few seconds later the disk was attached, it will be nuked ? Replicas integrated and taken into account ? 
What is the workflow process ?

**Comment by yasker** [comment]
@all4innov If Longhorn already decides to rebuild a new replica, it will not stop the ongoing replica rebuild process even the old replica comes back a few seconds later.

**Comment by khushboo-rancher** [comment]
Validation - **Pass** with longhorn-master ```11/18/2020``` image.

Apart from https://github.com/longhorn/longhorn/issues/1269#issuecomment-728738178 below scenarios also passed.

Scenario 1 - ASG set up with a script to migrate existing EBS volume. Trigger rolling update with **volume detached**.
1. Create an Autoscaling group in AWS with user data to migrate EBS volume on the creation of new instances.
2. Create a Longhorn volume and attach it to a pod, and write some data to it.
3. Detach the volume.
4. Refresh the instances.
5. Add the additional disk in longhorn.
6. Attach the volume by scaling up the pod.
7. Longhorn will detect the disk and use the existing replica.

Scenario 2 - ASG set up with a script to migrate existing EBS volume. Trigger rolling update with **volume attached**.
1.  Create an Autoscaling group in AWS with user data to migrate EBS volume on the creation of new instances.
2. Create a Longhorn volume and attach it to a pod, and write some data to it.
3. Refresh the instances.
4. The replica on the disk which is attached to the terminating node becomes failed.
5. Add the migrated disk in longhorn. Make sure the migrated disk is added in longhorn before the ```staleReplicaTimeout``` for the replica and ```Replica Replenishment Wait Interval``` so that longhorn can use the existing replica.
6. Longhorn will detect the disk and use the existing replica.
