### ISSUE TITLE
[BUG] Engine crash makes volume throw input/output error

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1280]
**Describe the bug**
If the engine manager crashes on the node where pod is running, the volume attached to it throws error. User is unable to access the volume. After redeploying the pod it works fine.

**To Reproduce**
1. Create a volume (3 replicas 3 nodes), attach to a workload
2. Delete the instance-manager-e pod running on the same node where the workload is running.
3. Go to the pod of workload, try to access the volume (use ```ls``` command to list the data in the volume)
4. The ```ls``` command throws error. ```input/output error```

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.17.5
 - Node OS type and version: ubuntu 18.04

**Comment by yasker** [comment]
This is expected since here the engine was crashed. The block device endpoint will lost so `input/output error` will be shown. However, Longhorn will automatically reattach the volume, but the workload pod needs to be restarted to recognize the updated mount point. That's why we need to use `liveness check` for workloads. See https://longhorn.io/docs/0.8.1/high-availability/recover-volume/ for details.
