### ISSUE TITLE
[BUG] Backup the same name but different volumes can result in corrupt data

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1294]
**Describe the bug**
Backup the same name but different volumes can result in corrupt data

**To Reproduce**
1. Create a volume called `test` and attach and format it.
2. Make two backups
3. Delete the volume `test` and recreate it with the same name. Now the volume size is 0.
4. Make a backup again.
5. Notice the new backup size in the backup list is the same as the old backup, but it should be 0 instead.

**Expected behavior**
The new backup from the new volume should contain 0 data, instead of old volume's data.

**Environment:**
 - Longhorn version: v0.8.1

**Comment by meldafrawi** [comment]
Validation: **PASSED**

**Steps to test:**

1. Create a volume called `test` and attach and format it.
2. Make two backups
3. Delete the volume test and recreate it with the same name. Now the volume size is 0.
4. Make a backup again.
5. The new backup from the new volume should contain 0 data, instead of old volume's data. (**PASSED**)

![image](https://user-images.githubusercontent.com/18232258/81751337-86348d00-94af-11ea-9e88-68b2d63cad2a.png)
