### ISSUE TITLE
Use persistent volume claim for more than one deployment?

### ISSUE THREAD

**Issue by klauskobald** [longhorn/longhorn#1302]
The only tutorial one can find is how to deploy a wordpress - great ;-)

But, how would I solve this tiny real world setup:
Run one nginx container with a volume claim mounted at /var/www/html 
Run a sftp container for uploading files mounted to the same claim?

People on Slack are telling me: "no you can´t do that" - what? I cannot believe this is not possible!
Please help!

**Comment by yasker** [comment]
You can have two pods with pod affinity to make sure they're running on the same node, then you can use Longhorn volume for it.

Longhorn is like AWS EBS volume. It can only be used with one node. If you have multiple pods within the same node, then you can share the volume since it's the same filesystem. But since Longhorn is a distributed block device solution instead of a distributed filesystem, you cannot share Longhorn (or EBS volume) across different nodes.

You can setup a NFS server on top of Longhorn. We're working on https://github.com/longhorn/longhorn/issues/1183 to document the best practice for that.

**Comment by klauskobald** [comment]
This is exactly what I do not want to do. I have this now. I want to get rid of NFS shares back and forth between nodes. So, will the update which will be presented the next days be able to handle multiple nodes and mount points?

**Comment by yasker** [comment]
@klauskobald Sorry missed your reply. What's the reason for you wanting to get rid of NFS? Stability or something else?

**Comment by klauskobald** [comment]
well, what I have now is 3 Nodes, each with a 40gb space. So I have to export mountpoints on each node. When the node goes down, the storage is gone. I would like to have one virtual filesystem, like a raid 5 or something. I have tried all of the promising systems out there, but cannot get any of them to "really" work. A bit frustrating - so I live now with my nfs solution and wait for better times :-) @yasker

**Comment by yasker** [comment]
In fact, Longhorn can help. In Longhorn v1.0.1, we have an experimental NFS server on top of Longhorn block devices. If the node went down, the Kubernetes will migrate the pod to another node and bring up the NFS server again. There will be a downtime about 60 - 90 seconds, but it will recover automatically. We're planning to have a full HA RWX setup for v1.1.0.

See https://longhorn.io/docs/1.0.1/advanced-resources/rwx-workloads/ for more details on our RWX solution in v1.0.1.
