### ISSUE TITLE
UI: Show up the volume, node, disk conditions

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1359]
Currently, the volume, node, disk objects all have conditions that may provide extra information to the user about why something doesn't work.

We need to have a way to show those conditions in the UI, in additional to handle each condition separately.

**Comment by sowmyav27** [comment]
Related use case for this issue:

- When the volume is faulted during a backup restoration process because of an invalid target URL, the UI presents option Salvage to the user.
- On clicking Salvage, and selecting 1 replica, the replica is seen running.

<img width="1315" alt="Screen Shot 2020-05-18 at 11 52 51 AM" src="https://user-images.githubusercontent.com/26032343/82251417-03be2a00-9902-11ea-9a40-c8fd493bad73.png">

**Expected -** It should show "restoring failure" message

**Comment by sowmyav27** [comment]
**verified on master ui tag, longhorn version `1.0.0-rc1`**

Validation: **`Passed`**
- When the restore is in progress
<img width="581" alt="Screen Shot 2020-05-21 at 7 36 55 PM" src="https://user-images.githubusercontent.com/26032343/82625612-79442780-9b9a-11ea-905d-3f28cc9122b6.png">

- When the restore fails due to an invalid target in the settings
<img width="616" alt="Screen Shot 2020-05-21 at 7 35 49 PM" src="https://user-images.githubusercontent.com/26032343/82626224-1a7fad80-9b9c-11ea-9573-ff1f1a326bde.png">
<img width="560" alt="Screen Shot 2020-05-21 at 7 35 44 PM" src="https://user-images.githubusercontent.com/26032343/82626228-1d7a9e00-9b9c-11ea-8cd1-1342cf6b817c.png">

- On a Healthy volume
<img width="899" alt="Screen Shot 2020-05-21 at 7 34 56 PM" src="https://user-images.githubusercontent.com/26032343/82626243-2bc8ba00-9b9c-11ea-9855-89d95dfb0d38.png">

- Nodes and Disk show correctly
<img width="836" alt="Screen Shot 2020-05-21 at 3 58 41 PM" src="https://user-images.githubusercontent.com/26032343/82626334-67fc1a80-9b9c-11ea-8179-73bb118d666c.png">
