### ISSUE TITLE
Scalability test and optimization for v1.0.0

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1463]
Test and optimize Longhorn's scalability on a large number of nodes.

**Comment by joshimoo** [comment]
**Context:**
We noticed that once we reached around 200 volumes, attach/detach operations started taking longer and longer.
Related: longhorn/longhorn#1058

This issue was created to see if we can identify the root cause of this slow down and fix it.
I was able to identify the issue and verify that the slow down wasn't caused by the longhorn components.
Instead this failure mode would happen to all storage solutions that are utilize the kubernetes csi plugin.

The problem is caused by kubernetes AD Controller resync loop checking that all volumes that should be attached are still attached. Todo this kubernetes needs to query the API server for each `VolumeAttachment` object, since there was no bulk listing/informer implemented. (The reason this doesn't happen to kubernetes in tree plugins is that they implemented bulk retrieval for this operation (GCE, AWS, etc)

-------- 

**Kubernetes issue description:**
Once a single iteration of the sync loop takes longer then the sync loop interval period, the system will end up throttling itself into infinity, since there will be overlapping sync routines and since a single routine already takes longer then a single interval, the amount of sync routines will just keep increasing. Which will result in even more `VolumeAttachment` requests, which all end up being throttled by the rest client.

So in reality kubernetes correctly detected that there is a PVC that wants to use a volume, and immediately requested that volume be attached but because the actual call `POST` call for the `VolumeAttachment` creation get's throttled with the other GET calls from the `VolumeAttachment` checks.

Example below:
```
{"log":"I0724 02:53:17.111947       1 request.go:565] Throttling request took 5m50.595934236s, request: POST:https://127.0.0.1:6443/apis/storage.k8s.io/v1/volumeattachments\n","stream":"stderr","time":"2020-07-24T02:53:17.11343459Z"}
```
The actual throttling time will just keep increasing till infinity or the kubernetes controller-manager dies and another one takes its place which will start from 0 to infinity.

-------- 

**Solution:**
The issue got addressed in https://github.com/kubernetes/kubernetes/pull/91307
Where the `VolumeAttachment` checks got implemented via a lister/informer.

Which is available in kubernetes version  **1.18.5  / 1.17.8**
For older versions there isn't a solution only mitigations/workarounds.
See https://github.com/kubernetes/kubernetes/issues/84169#issuecomment-545692734 for additional details.

> * Set `disable-attach-detach-reconcile-sync` flag on the kube-controller-manager to `true`.
>   
>   * This would completely disable the feature where k8s periodically verifies that the volumes that it thinks are attached are actually attached.
>   * For now this should be safe because although the k8s side checks the VolumeAttachment, the CSI `external-attacher` object doesn't periodically update the VolumeAttachment object (#79743 to fix that.)
> * Set the `attach-detach-reconcile-sync-period` value to a longer period (longer then 1 minute).
>   
>   * This flag controls the frequency of the verification. The default value is 1 minute. If you find that you really need the feature, you could keep it on and increase the frequency to mitigate this issue.





-------- 

**References:**

_AD controller slow down (due to singular verify volumes attached call)_
https://github.com/kubernetes/kubernetes/issues/84169
https://github.com/ceph/ceph-csi/issues/1109
https://github.com/kubernetes/kubernetes/issues/86281

_Some work on the external csi-attacher, to do reconciliation
this would require us to update the csi plugin to support the bulk volume <-> node list calls._
https://github.com/kubernetes/kubernetes/issues/79743

_some pr's with more discussion and insight_
https://github.com/kubernetes-csi/external-attacher/pull/184
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/392
https://github.com/kubernetes/kubernetes/pull/91307

_more issues related to csi/ad performance_
https://github.com/kubernetes/kubernetes/issues/86281

**Comment by yasker** [comment]
@joshimoo Good analysis! We will share more information about the scalability of Longhorn in the upcoming Performance and Scalability report. #1637

**Comment by yasker** [comment]
Done.
