### ISSUE TITLE
[Question]How to split replicas by host labels?

### ISSUE THREAD

**Issue by arturmon** [longhorn/longhorn#1482]
given:
3 hosts with one label (PV1)
1 host with a different label (PV2)
It is required to separate replicas by labels. For example: 3 replicas, one must go to the host with the PV2 tag, the rest of the replicas can be scattered across the hosts with the PV1 tag. How to implement this? at the moment we get error 'Scheduling Failure Replica Scheduling Failure'
![image](https://user-images.githubusercontent.com/7686999/84377996-22a39980-abec-11ea-9df0-f68de978f067.png)
![image](https://user-images.githubusercontent.com/7686999/84378047-3818c380-abec-11ea-9576-a60e05d1d8b9.png)

**Comment by joshimoo** [comment]
@arturmon 
From your question, it sounds like you are trying to setup multiple failure zones. If your nodes are indeed in different [zones](https://kubernetes.io/docs/setup/best-practices/multiple-zones/). 
Additional information about zone setup [here](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesioregion).

Using multiple zones has impact on your kubernetes cluster, so make sure that this is what you really want. For an example use case where a similar setup was requested, have a look at this issue #929.

We do support this via the zone anti affinity, create a zone for hosts x and a separate zone just for host y. hard Zone anti affinity would create a replica in each zone then hard node anti affinity would lead to creating additional replicas in zone x since y only has a single node.

Let us know if this is what you are trying to implement?

**Comment by arturmon** [comment]
Yes, it turned out exactly what you need. guaranteed hit of one replica on the kube-pv4-external-test host. but why is there nothing in the documentation about this ??
![image](https://user-images.githubusercontent.com/7686999/84449090-0daf2080-ac55-11ea-8fc9-bd8850d1868e.png)
![image](https://user-images.githubusercontent.com/7686999/84449098-13a50180-ac55-11ea-84a3-35f664fbd919.png)

**Comment by joshimoo** [comment]
@arturmon Just to confirm that the above setup with multiple failure zones is what you wanted and it works as expected?

**Comment by arturmon** [comment]
yes

**Comment by joshimoo** [comment]
@arturmon Thanks for confirming, I will review the documentation to see if we can improve it :)
