### ISSUE TITLE
[IMPROVEMENT] Improve 'recovery from longhorn backup without system installed' doc.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1522]
**Describe the bug**
Need to change below in the 'recovery from longhorn backup without system installed' document.
https://longhorn.io/docs/1.0.0/advanced-resources/data-recovery/recover-without-system/

1. Elaborate 4th point of the document on entering ```BACKUP_URL``` - Indicate the location we can retrieve the ```backup name``` and ```volume name``` and then form the url. for example - In the ```backup.cfg``` file, these information exist in the beginning.
```
{"Name":"backup-580cb9538adb4da9","VolumeName":"volume-1","SnapshotName":"8adb8b45-4c13-4ff5-a2f5-a95b2cb4f35d" ...
```
2. Better/simple way of putting ```set Backup Target Credential Secret```
3. A link to understand ```qcow2 vs raw``` format or get files out of a ```qcow2```

Note: This should be taken care in sync with https://github.com/longhorn/longhorn/issues/1521

**Comment by nickramser** [comment]
This isn't 100% related to the updating the documentation and this issue, but I thought it was worth mentioning since I came across this issue and #1521 looking for a similar information. I created a separate container which can export longhorn backups out of the system and extract the files from `qcow2` into a `tgz` per volume, https://github.com/nickramser/longhorn-backup. 

Someone looking for updated documentation or updating the documentation could leverage some of the same logic to create a docker container/command for (1) and to have an example using nbd for getting files out of `qcow2` for (3).

**Comment by roger-ryao** [comment]
**Verified on master 20221121**

- https://longhorn.io/docs/ 
- website master ([e266055c](https://github.com/longhorn/website/commit/e266055c08a2814be5870eae79854e6dd694ab6f)) 

**The test steps**

1. Check PR review conversation.
2. Verify the result on https://longhorn.io/docs/

**Result Passed**
