### ISSUE TITLE
[Question] what's longhorn storage capacity？

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1534]
I have 5 nodes for longhorn scheduling, each node have 100G storage.

So what's longhorn total storage capacity? 500GB or depends on replicas quantity?

**Comment by shuo-wu** [comment]
The actual **space** available for Longhorn = The total storage of all nodes in the cluster - The used space - The reserved space. This number is actually is the value of `Schedulable` in the UI Dashboard page.

As for how much **actual data** the Longhorn can store, it does depend on the replica number.

**Comment by hillbun** [comment]
@shuo-wu 

how to calculate actual data？

**Comment by shuo-wu** [comment]
Here is the example (For simplicity, let's ignore the space used to store the meta info):
1. Create a 10Gi volume with 3 replicas. This means the nominal/claimed size of this volume is always 10Gi. And the actual space used in the cluster is 3 times of the actual data size.
2. Write 10Gi data into the volume. Then the actual data is 10Gi but the actual space used is 30Gi.
3. Create a snapshot then write another 10Gi data into the volume. Now the actual data is 20Gi (10GI history data + 10Gi new data) and the used space is 60Gi.

Now you would find:
1. Due to the snapshot mechanism, the actual size can be greater than the nominal/claimed size. And the actual size will be shown in the UI volume detail page when the volume is attached.
2. The actual space used by the volume = The actual data size of the volume * The replica number

**Comment by hillbun** [comment]
@shuo-wu 

1. if 5 nodes for longhorn scheduling, each node have 100G storage,  pvc with 3 replicas.
2. a single PVC maximal storage capacity is 100G
3. total storage capacity (no snapshots) is 100G*5/3= 166G
4. total storage capacity (each pvc with 1 snapshots) is 100G*5/3/2= 83G
5. total storage capacity (each pvc with 2 snapshots) is 100G*5/3/3= 55G

is that right?

**Comment by shuo-wu** [comment]
No.

1. If the 3 replicas are on different nodes, it means each replica can use all space (100Gi) of the node. Then the volume max storage capacity is 100Gi. 
2. In brief, the volume capacity is decided by the min node available space on which the replicas reside. e.g., there are 3 replicas on different nodes. And the available space of these nodes is 100Gi, 110Gi, and 120Gi. Then the volume max capacity is 100Gi rather than (100Gi+110Gi+120Gi)/3
3. The space used by a snapshot is decided by the active data size (the data written after the latest snapshot) in the volume before snapshotting. e.g., If you write 10Gi data to a 100Gi volume then create a snapshot, the snapshot size is 10Gi rather than 100Gi. Since we cannot record the current data size each time before snapshotting in the real world, it's hard to manually calculate the actual size of one volume. Hence I recommend to check the volume detail page and directly get the value.
