### ISSUE TITLE
[Question] Volume actual size is almost full, while application (elasticsearch) reports only 10% usage

### ISSUE THREAD

**Issue by aandrushchenko** [longhorn/longhorn#1555]
Hi! 

We are using longhorn 1.0.0 to provision PV for Elasticsearch Cluster. We have set PV size to 25Gb. 

Longhorn UI reports Actual Size of each volume at around 33Gb, where 24Gb is the initial system snapshot size (recovered from backup) and 8Gb is a size of newer system snapshot. 

By logging to server we can find the respective replica with following console output:
```
[root@node3 pvc-d68b78c1-d048-4ba4-b140-32180eb89875-0575783a]# ls -la
total 33952116
drwx------.  2 root root        4096 Jul  8 16:15 .
drwxr-xr-x. 16 root root        4096 Jul  8 16:15 ..
-rw-------.  1 root root        4096 Jul  8 16:53 revision.counter
-rw-r--r--.  1 root root 26843545600 Jul  8 16:53 volume-head-002.img
-rw-r--r--.  1 root root         178 Jul  8 16:15 volume-head-002.img.meta
-rw-r--r--.  1 root root 26843545600 Jul  7 07:56 volume-snap-981f8c6c-c38b-4d39-8d0d-9f10b301258e.img
-rw-r--r--.  1 root root         178 Jul  7 07:56 volume-snap-981f8c6c-c38b-4d39-8d0d-9f10b301258e.img.meta
-rw-r--r--.  1 root root 26843545600 Jul  7 07:56 volume-snap-9981d37d-359f-4475-a7e8-dadb3ad0ca07.img
-rw-r--r--.  1 root root          14 Jul  7 07:56 volume-snap-9981d37d-359f-4475-a7e8-dadb3ad0ca07.img.meta
-rw-r--r--.  1 root root 26843545600 Jul  8 16:15 volume-snap-a20caa64-386f-4419-9392-a97a4b6da427.img
-rw-r--r--.  1 root root         178 Jul  8 16:15 volume-snap-a20caa64-386f-4419-9392-a97a4b6da427.img.meta
-rw-r--r--.  1 root root         184 Jul  8 16:15 volume.meta
[root@node3 pvc-d68b78c1-d048-4ba4-b140-32180eb89875-0575783a]# du -h
33G	.
```

Nonetheless, when using ElasticSearch node stats api, we get following response (excerpt from one node):

```
"fs" : {
        "timestamp" : 1594241263913,
        "total" : {
          "total_in_bytes" : 26288033792,
          "free_in_bytes" : 24036290560,
          "available_in_bytes" : 24019513344
        },
```

If we look at the indices size, the cumulative size of indices is closer to the Elasticsearch API response: around 2Gb vs 24Gb being the size of snapshot. 

Please advise if we need to expand the volume to bigger size or we are fine to keep going. It is confusing, what's the actual disk usage and available capacity.

Thank you,
Anton

**Comment by shuo-wu** [comment]
1. Replicas of the Longhorn volume are using **sparse files** to store data, each snapshot or volume head file size shown by `ls` is the same as the specified size during the volume creation (let's call it "nominal size"). And the size reported by `du` is the actual space used by the replica directory.
2. `Actual Size` in the volume detail page is the total size of the historical data and the active data. The tooltip/hover of the snapshots will reflect the historical size. The tooltip/hover of volume head will tell you the space occupied by the active data. Then the available size before the next snapshotting is (volume nominal size - volume head actual size). 
3. I think this doc may help you have a better understanding: https://longhorn.io/docs/1.0.0/concepts/#21-thin-provisioning-and-volume-size.
And we plan to provide a more detailed doc in v1.0.1 and it's tracked in #1519

**Comment by aandrushchenko** [comment]
@shuo-wu that's an amazing answer! thank you so much!

**Comment by aandrushchenko** [comment]
@shuo-wu is there any guidance on how to shrink the volume size as it grows due to historic data?

**Comment by shuo-wu** [comment]
Historic data is stored in snapshots. Hence you can delete the snapshots if there is too much history.

Or you can rely on the recurring job to automatically create and delete snapshots. Here are the docs:
https://longhorn.io/docs/1.0.0/concepts/#242-recurring-snapshots
https://longhorn.io/docs/1.0.0/snapshots-and-backups/scheduling-backups-and-snapshots/

**Comment by timmy59100** [comment]
> @shuo-wu is there any guidance on how to shrink the volume size as it grows due to historic data?

@aandrushchenko I think at the moment you can only create a new volume and transfer the data to it.

**Comment by shuo-wu** [comment]
> > @shuo-wu is there any guidance on how to shrink the volume size as it grows due to historic data?
> 
> @aandrushchenko I think at the moment you can only create a new volume and transfer the data to it.

Not exactly. Sometimes deleting snapshots do help shrink the volume actual size. Here is an example:
1. Create a volume with 10Gi size.
2. Write 1st 10Gi data to the volume (use up all of the 10Gi space), create the 1st snapshot then delete the 10Gi data. Now the 1st 10Gi data is historical data and is stored in the 1st snapshot only.
2. Write 2nd 10Gi data to the volume, create the 2nd snapshot then delete the 10Gi data. Similarly, the 2nd 10Gi data is historical data and is stored in the 2nd snapshot only. Now the volume actual size is 20Gi.
3. Delete the 1st snapshot. Here Longhorn actually coalesces the 1st snapshot with the 2nd snapshot. Since the 2nd snapshot also uses up all of the 10Gi space, and the truth of the coalescing is that only the newer data will be retained when the related space is used in both snapshots, the data in the 1st snapshot is gone after the snapshot deletion. It means the space stores the 1st 10Gi historical data is released.

**Comment by oscni** [comment]
> * Create a volume with 10Gi size. Attach and mount the volume.
> * Write 1st 10Gi data to the volume (use up all of the 10Gi space)
I did some tests without snapshots and when you do the above the host filesystem will never get the 10G back. From what I understand longhorn does not support space reclaim (TRIM,UNMAP,discard,deletenotification) so that explains why it happens.

>Volume actual size is almost full, while application (elasticsearch) reports only 10% usage
If you have a database/application which is both writing and deleting files/data then eventually the longhorn volume will be 100% full even if the container knows the correct usage is lower. If the longhorn volume is 10G then the host will also think 10G is used, even if it is filled with zeros. The filesystem closests to the application always knows when files/data gets deleted but it need to pass that through or write zeros via TRIM,UNMAP,discard,deletenotification etc to underlaying filesystems and hosts.

**Comment by Moumouls** [comment]
Hi,
I currently have the same issue with an Elastic deployment with high I/O operations (many create and delete).

`du` and `eslastic _cat/allocation`  reports about 3GB of disk usage

```
shards disk.indices disk.used disk.avail disk.total disk.percent host       ip         node
     4        1.5gb     1.7gb       57gb     58.8gb            2 10.42.0.27 10.42.0.27 elasticsearch-master-0
     3      536.9mb   605.5mb     58.2gb     58.8gb            1 10.42.1.23 10.42.1.23 elasticsearch-master-2
     3        1.1gb     1.3gb     57.4gb     58.8gb            2 10.42.0.26 10.42.0.26 elasticsearch-master-1
```

but longhorn replicas use respectively : " 30GB, 16GB, 15GB "

Is there any way to shring the `.img`

Note: I do not use the snapshot system.

**Comment by korenlev** [comment]
https://docs.portworx.com/reference/cli/volume-trim/   longhorn muat develop the same capability
