### ISSUE TITLE
[FEATURE] Add node selector or node affinity to limit the deployment of DaemonSets.

### ISSUE THREAD

**Issue by laeo** [longhorn/longhorn#1584]
**Is your feature request related to a problem? Please describe.**
longhorn's DaemonSet is deploy to all the nodes by default, but i have some VPS only have 512M RAM and 10GB disk, so it shouldn't run longhorn.

**Describe the solution you'd like**
I think we should add a nodeSelector into longhorn.yaml, so people can make a choice of which node will run longhorn. This should be a default action, so it's more flexible.

**Describe alternatives you've considered**
1. Add nodeSelector manually.
2. Recharge money to upgrade server resources. :P

**Additional context**
NO.

**Comment by laeo** [comment]
The `Create Default Disk With Node Labeled` setting only used for new nodes, and doesn't effect existed nodes. So when i deploy Longhorn on cluster which already has some nodes, the DaemonSet will be deployed on all of nodes.

And i can't choice which node should have Longhorn DaemonSet deployed, this is my question.

Need some help, thanks.

**Comment by boknowswiki** [comment]
> The `Create Default Disk With Node Labeled` setting only used for new nodes, and doesn't effect existed nodes. So when i deploy Longhorn on cluster which already has some nodes, the DaemonSet will be deployed on all of nodes.
> 
> And i can't choice which node should have Longhorn DaemonSet deployed, this is my question.
> 
> Need some help, thanks.

@laeo , I think your understand is correct. @shuo-wu, please correct me if I am wrong. Thanks.

After the node label changed, only changes will only apply when scheduler trying to schedule a new volume on the nodes.
And I think for now, in the DaemonSet, we don't have the choice for the the node, and it will deployed on all the nodes in the cluster.

Thanks.

**Comment by shuo-wu** [comment]
Setting `Create Default Disk With Node Labeled` only decides if **a default disk will be created when a new node is (already) introduced by Longhorn**. It doesn't control if Longhorn workloads will be deployed on a new cluster node. In brief, this setting is related to disk config of Longhorn nodes rather than the Longhorn workloads deployment.

If you want to evict Longhorn workloads from some nodes, you can add taints for the nodes and don't set the corresponding toleration in Longhorn. (Remember to set the toleration for some applications which should be run on the taint nodes.) For more info about taint, you can refer to [this Kubernetes doc](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)

BTW, setting `Create Default Disk With Node Labeled` can be used to config [the default disks of the new nodes](https://longhorn.io/docs/1.0.0/advanced-resources/default-disk-and-node-config/), too.

**Comment by yasker** [comment]
@laeo Another thing is, Longhorn indeed needs to be deployed on all the worker nodes in order to provide volumes to those node. The node that provides the storage can be limited to certain nodes, but Longhorn no only needs to be deployed on the nodes that provide the storage, but also the nodes that consume the storage. So generally it's not a good idea to limit the daemonset deployment using the node selector.

If a node doesn't provide storage to Longhorn, then `instance-manager-r` won't be started on that node. Other components are still needed for that node though.

**Comment by laeo** [comment]
> @laeo Another thing is, Longhorn indeed needs to be deployed on all the worker nodes in order to provide volumes to those node. The node that provides the storage can be limited to certain nodes, but Longhorn no only needs to be deployed on the nodes that provide the storage, but also the nodes that consume the storage. So generally it's not a good idea to limit the daemonset deployment using the node selector.
> 
> If a node doesn't provide storage to Longhorn, then `instance-manager-r` won't be started on that node. Other components are still needed for that node though.

Thanks for the answer, i'll close this issue.
