### ISSUE TITLE
[Question] How to set backup target to aliyun OSS?

### ISSUE THREAD

**Issue by hillbun** [longhorn/longhorn#1627]
what's URL format? and where to put api key and secret?

**Comment by shuo-wu** [comment]
Since OSS is S3 compatible, the way to use aliyun OSS in Longhorn is almost the same as that of S3. And of course, the URL format is the same as S3. e.g.:
If the endpoint of your OSS bucket is `oss-eu-central-1.aliyuncs.com`, the region name is `oss-eu-central-1`, and your bucket name is `shuo-longhorn-eu`, the URL should be `s3://shuo-longhorn-eu@oss-eu-central-1/`.

Besides setting key, secret, and endpoint in the secret, you need to enable virtual-hosted-style as an extra step. See this doc for more details:
https://longhorn.io/docs/1.0.1/snapshots-and-backups/backup-and-restore/set-backup-target/#enable-virtual-hosted-style-access-for-s3-compatible-backupstore
