### ISSUE TITLE
[BUG] ignoring Storage Reserved 

### ISSUE THREAD

**Issue by strowi** [longhorn/longhorn#1693]
**Describe the bug**
Longhorn seems to ignore the "Storage Reserved"-parameter:

Longhorn-UI
```
default disk:
Path: /var/lib/longhorn
Storage Available 24.65Gi
Storage Scheduled 101Gi
Storage Max 217.61Gi
Storage Reserved 65.28Gi
```
On-Disk:
```
/dev/mapper/ranch34--vg-root  218G    193G   14G   94% /

173G	/var/lib/longhorn/
```

There are also other 2TB disks mounted and configured on other locations, which are 0Gi used.
```
/srv/longhorn/sd(a|b|c)1/ 
```

**To Reproduce**
1. Deploy Longhorn in Rancher-2.4.5
2. Use up all available space via PV
3. see on-disk that > 95% get used..

**Expected behavior**
Longhorn shouldn't use up more than its configured storage.

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version: v1.18.6
 - Node OS type and version: Ubuntu 18.04

regards,
strowi

**Comment by shuo-wu** [comment]
1. The schedulable size = (the total size - the reserved size) * Storage Over Provisioning Percentage - the size scheduled for existing volumes. In brief, the reserved size determines the max schedule size for Longhorn.
2. For existing volumes, Longhorn does not block/interrupt the volume writing even if all available space dedicated for Longhorn is used up(Longhorn will continue to use the reserved space in this case). I think it's better to guarantee the existing data writing rather than crash the volume functionality in this case. Maybe Longhorn needs to notify/alarm users when it is trying to consume the reserved space


The following docs may be helpful:
https://longhorn.io/docs/1.0.2/volumes-and-nodes/node-space-usage/#space-usage-of-each-node
https://longhorn.io/docs/1.0.2/volumes-and-nodes/volume-size/#volume-actual-size

**Comment by strowi** [comment]
Thx for the explanation and sorry for the noise, maybe i should've dug deeper into the docs!
Seems i was missing the over-provisioning percentage.

But to be clear:
Longhorn will allow scheduling up to (in case of sda1 above) (217GB-65GB)*200% ~ 304GB ?

It would be very useful to at least notify, since this can quickly become a problem creating an unstable node.

**Comment by shuo-wu** [comment]
Yes. And you can directly check the schedulable size of each node in the Longhorn UI Node page. 

As for the setting `over-provisioning percentage`, you can modify it based on your use case. If most of the volumes in your cluster are not heavily used, it's fine to set the value over 100. But if the volumes are written frequently and will be snapshotted periodically, it's better to decrease the value.
https://longhorn.io/docs/1.0.2/references/settings/#storage-over-provisioning-percentage

**Comment by strowi** [comment]
Thx again;) Found the settings. For the time being i just disabled the /var/lib/longhorn on those nodes, since we have enough with separate disks/mounts. I will have to dig into this deeper when i get some more spare time.
