### ISSUE TITLE
[Question] Max number of mount points limited to just /dev/sd(a-z)?

### ISSUE THREAD

**Issue by dcplaya** [longhorn/longhorn#1737]
A specific node in my cluster seems to love to grab all the mounts, unfortunately it tries to grab more than it can handle apparently. Are the max number of mounts longhorn can do really just 26 (a-z)? 

The error I get is below 

```
cannot proceed to remount pvc-7a4b3257-0bab-4ced-a943-b7163a721765 on node10: there is not any available mount point for volume pvc-7a4b3257-0bab-4ced-a943-b7163a721765
```

I am running longhorn v1.0.2

**Comment by yasker** [comment]
The error message isn't related to the block device name. This is the `remount` feature we've built for the unexpected volume detachment. See https://longhorn.io/docs/1.0.2/high-availability/recover-volume/ 

The error message here simply means:
1. This volume has been detached unexpectedly due to some reason
2. Now we've reattached it automatically
3. But somehow there isn't one mount point on the node that using this volume, so we will skip the auto-remount process.

For the block device name, it's built-in in the Linux. It will continue as `/dev/sdaa` after `/dev/sdz` IIRC. I don't think there is a limit on that.

**Comment by boknowswiki** [comment]
One possible Longhorn will skip the auto-remount is that the mount point is being used by other devices.

**Comment by dcplaya** [comment]
@yasker 

`But somehow there isn't one mount point on the node that using this volume, so we will skip the auto-remount process.` seems to be the correct answer. This PVC is linked to a influxDB that is currently scaled down to 0. But now I am wondering why longhorn keeps trying to mount it. If the container isn't running but I manually attach the volume, will Longhorn continue to try and keep it attached during an unexpected detachment? I'm thinking I manually attached it and forgot I did?

**Comment by shuo-wu** [comment]
Longhorn always tries to automatically reattach the volume if the **attached** volume somehow gets detached unexpectedly.

**Comment by yasker** [comment]
@dcplaya is the volume attached or detached when this error message is showing up?

**Comment by dcplaya** [comment]
@yasker I haven't had this issue since I started solving my other issue (#1738). I think the two are related. I am going to post an update over there in that but report since that has the bulk of the important info.
