### ISSUE TITLE
Setting up recurring backups

### ISSUE THREAD

**Issue by tulanian** [longhorn/longhorn#1751]
The docs talk about setting up recurring jobs for new PVs via a StorageClass, but I can't figure out how to do this. Neither kubectl nor the rancher GUI will let me modify the parameters for the StorageClass created by the longhorn install. How do I go about this? Thanks

**Comment by yasker** [comment]
@tulanian You need to create another storage with Longhorn driver to update the parameters. Kubernetes doesn't allow user to modify the existing parameters in the storage class.

See https://longhorn.io/docs/1.0.2/references/examples/#storageclass for the example StorageClass (Yes, you only need to change the name of it to use it).

**Comment by tulanian** [comment]
@yasker Thanks, that makes sense, but may leave us in a quandry. We already have some PVs based on the existing longhorn storage class. Are we stuck with that sttorage class now, having to tell devs that if they use that class backups won't automatically be configured?

**Comment by yasker** [comment]
@tulanian for any existing volumes, you can configure the backup policy for the volumes already provisioned using the existing storage class. It can be done easily via batch operation in UI. For any new volumes, you can ask users to switch to use the new storage class. 

Also, don't modify/delete/recreate the default storage class. It might result in future upgrade failure, since the new deployment might try to modify the storage class back and fail during the upgrade process.
