### ISSUE TITLE
[Question] Replicas constantly faulting

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#1756]
I observed, that in the last few days we have constantly replicas that are failing and then get rebuilded.

Volume Event log:
Detected replica UNKNOWN-tcp://10.42.4.108:10225 (10.42.4.108:10225) in error

I will send you the support bundle. What else could we do?

Thanks

**Comment by yasker** [comment]
In the support bundle, I saw lots of replica reconnecting. It's normally caused by the CPU or network. Can you check the CPU utilization on your nodes? And load average etc. Also, do you have any network issues between your nodes? Are they connected by 10G (at least 1G) network?

**Comment by timmy59100** [comment]
One Node 05 has CPU usage of about 90%. Partly because the longhorn engine manager "instance-manager-e-1b9c1476" uses over 1000 mCPU which seems high. 

The nodes are connected by a 25G network.

**Comment by yasker** [comment]
@timmy59100 `instance-manager-e` is running all the engine processes inside it, so normally it would have the highest CPU utilization among the Longhorn components. Can you give the node more CPU in the meantime? We're working on bringing the engine CPU utilization down as well.

**Comment by timmy59100** [comment]
@yasker we added another node to reduce cpu load on the nodes, but the disconnects still happens and the volumes get read-only as a result.

**Comment by yasker** [comment]
What's the load on the nodes that have read-only volumes now? You can migrate replicas to new nodes to reduce the load on existing nodes. For v1.0.x it needs to be done manually:
1. Disable the node scheduling except for the new node.
2. Increase the volume replica count by one. This should allow the volume to rebuild a replica on the new node.
3. Decrease the volume replica count. Then remove one replica of the volume on the node you want to reduce the load.
4. Repeat 2-3
5. Enable nodes' scheduling.

In the upcoming v1.1.0 release, we will have a replica eviction feature that can help to evict the replica on a single node or disk.

**Comment by timmy59100** [comment]
@yasker 
The load is max 50 % per Node.
The volumes are distributed, but it keeps happening.

**Comment by yasker** [comment]
@timmy59100 What's the underlying disk? Is it SSD/NVMe or spinning disk?

**Comment by timmy59100** [comment]
@yasker The disks are SSD. Over the weekend it was stable.

**Comment by yasker** [comment]
@timmy59100 Can you check how many engines and replicas are there on each node? Only need to count the attached ones. You can find the replicas on the node page. For engines, you can check it through the Volume Overview page and filter by the attached node name.

**Comment by timmy59100** [comment]
@yasker 
Just had another incident where the volumes failed.
Node01: 10 replicas + 2 failed, 7 engines
Node02: 11 replicas + 2 failed, 1 engine
Node03:   9 replicas + 0 failed, 7 engines

**Comment by timmy59100** [comment]
@yasker on this cluster we have only one etcd/controlplane node
On the other where we don't have the problem we have 3.

In https://github.com/longhorn/longhorn/issues/1475#issuecomment-641462673 you explained longhorn uses etcd to store metadata. 

Could that be an issue?

**Comment by yasker** [comment]
@timmy59100 It's probably not etcd.

How many CPUs you have for each node? And what's the CPU utilization when the issue happened? You mentioned you have a total of 4 replicas failures, so where do those volumes attach to?

We can try reserving more CPUs for Longhorn on the nodes in the setting `GuaranteedEngineCPU`, but it will require all the volumes to be detached before setting it(since it will restart all the instance managers). Based on your replica and engine count on the node, 750m(instead of the default 250m) sounds like a better value, but you have to make sure you have at least 4 * 750m = 3 VCPUs can be reserved on each node.

**Comment by timmy59100** [comment]
@yasker we have 4 CPUs per Node at the moment.
So 3 vcpus would be a bit much.

On a second Cluster we have 5 nodes same ressources ,but a few volumes more. Here we dont have the problem.

**Comment by yasker** [comment]
@timmy59100 OK, is it possible to try set GuaranteedEngineCPU to 500m? Also, I guess even the replica failed on node 2, the volumes with failed replicas are probably attached to node 1 or 3 instead of node 2. 

Regarding the second cluster, are they in the same data center? running a similar workload? How is the CPU utilization look like on the second cluster? It might be some workload on certain nodes demands more CPU than others.

**Comment by wirwolf** [comment]
Hello. I have the same error.
I have cluster setup by kubespray v1.21.13, longhorn 1.2.4
Network - 10G
In events i see 
```
Detected replica UNKNOWN-tcp://100.64.67.28:10000 (100.64.67.28:10000) in error
```

**Comment by uGiFarukh** [comment]
In my cluster also the replica's are failing often. I am guessing it might be a CPU issue because some of my nodes only have 1vCPU. Is there any way to tame the longhorn engine to now use so much CPU at the cost of replica performance? Instead of replica errors and dropping them, can it be tailored to work on low cpu environments with low performance? Also, how do I check which replica is being used by my attached pod to do read write operations? Are all the replicas used at random? Or if I have data locality set, only the local replica will be used for the pod I/O until the pod gets rescheduled somewhere else? How do I check this?
