### ISSUE TITLE
[Question] Other external data center 

### ISSUE THREAD

**Issue by bor8** [longhorn/longhorn#1769]
I seem to recall that in the presentation at KubeCon 2020 it was mentioned that there are two types of storage: A normal type for the storage in your own data center and an external (loosely coupled?) type for the storage in a remote data center (for me that would be 300 km). I didn't find anything about this in a hurry. Can someone write something about it or refer me to the right place?

**Comment by yasker** [comment]
@bor8 I believe what you heard are the main cluster and backup cluster. Longhorn support replicating data from the main cluster to the backup cluster asynchronizedly using the Disaster Recovery volume feature. So if the main cluster went down, you can quickly bring up the backup cluster with the same workload and data. You can take a look at the demo in my KubeCon EU 2020 talk here: https://www.youtube.com/watch?v=zJY2uxLtwUk . It starts around 12:30 mark.

**Comment by bor8** [comment]
Thank you!

Looks like I have to fisrt make Rancher HA - otherwise I can't open index.html from Longhorn if one datacenter fails.

**Comment by AntonOfTheWoods** [comment]
You wouldn't happen to have a description of how to do this with manifests or the command line? Google sent me here so it might be worth updating this ticket. Thanks!

**Comment by bor8** [comment]
I have to work on it from work in the near future. So maybe - maybe I can help you then. What I already have: Basically, I'm setting up a build environment with Docker-Rancher, in which I install Rancher HA. From there, I will set up the other environments in which the productive pods will run. If you have Rancher HA, you can always access Longhorn via the graphical interface and perform a manual data recovery. An automatic recovery is not possible and might be too risky?

Translated with www.DeepL.com/Translator (free version)

**Comment by yasker** [comment]
@AntonOfTheWoods Regarding the cmd line way of doing it, the only way right now is through Longhorn python client (which is used by Longhorn integration test as well), e.g. https://github.com/longhorn/longhorn-tests/blob/5d49ba73a29009a08efc5efd9ab092d499a21e2b/manager/integration/tests/test_basic.py#L1082 . We will introduce a Longhorn CLI and app backup/restore in v1.2.0 which will make it easy to do through the command line.

**Comment by AntonOfTheWoods** [comment]
Thanks @yasker . I see that you had exactly the same response almost 1.5 years ago here https://github.com/longhorn/longhorn/issues/610, which makes me think that it is not a high priority. 

I may be wrong but it looks like this is using you're `rancher/client-python`. Is there somewhere that explains how `client-python` works and how to get started with it? That looks like something that is used over a variety of the company's products. Trying to ramp up by looking at your integration tests is obviously possible, but a little frustrating as a new user. It's also totally non-obvious - `longhorn` is supposed to be a CNCF project for CNI block storage, so having to come and look at the python API for a Kubernetes management platform from a different github organisation was a little confusing.

What would be really useful would just be a short blogpost from one of your awesome trainers - that way there would be a reasonably easy entry point, rather than having to come to this from a github issue to an integration test! It would also likely be useful for the other products that use this, so could give users a great way to move forward while you guys take your time to do a good job on the CLI. Thanks for an awesome project anyway!

**Comment by yasker** [comment]
@AntonOfTheWoods ok, you caught me. :) 

In fact, CLI is a high priority item, but there are other functional features and bug fixes that get ahead it for the last few releases. Also, even though the API framework called `rancher/client-python`, it's treated just like any other framework in Longhorn. And we are planning to replace it, that's the main reason we haven't created the official CLI yet. It was planned for v1.1 release, but later we decide to push it to v1.2 release, as you can see in our [roadmap](https://github.com/longhorn/longhorn/wiki/Roadmap). The reason for delay the API change is because we want to incorporate declarative CRD style API but there are certain operations that are still imperative, like take a snapshot. To get it done correctly requires some major efforts. 

But of course, you're right. We should provide more tools for the users when they're waiting for our new API and CLI. Yes, we will take some time to document the way to use the current API to interact with Longhorn. I've created https://github.com/longhorn/longhorn/issues/1976 to get the doc ready by Longhorn v1.1.0 release.

**Comment by bor8** [comment]
Coming back to my question.

I managed to install Rancher HA.

But HMPF, it is not HA: an etcd setup with five instances tolerates only two failed instances. I have two locations A and B. A hast 3 etcd instances and B has 2 etcd instances. If A goes offline B will only throw etcd timeouts. :(

But no worries. I will split everything into two clusters and use S3 or NFS backup in Longhorn.

Btw, would be nice to have more than one NFS endpoint and/or secure NFS connection!?

**Comment by yasker** [comment]
@bor8 Regarding the HA case, I am afraid that's more like an etcd limitation. You can raise an issue in Rancher for that.

S3 endpoint can be secured by SSL if you chose to do so. We looked into NFS authentication (https://github.com/longhorn/longhorn/issues/1388 ) but decided not to move forward with it due to what we've documented in the comment.

**Comment by bor8** [comment]
Wow thanks for your quick answers.

I think the RAFT algorithm will not be changed that fast. I'm going to open a ticket anyway.

NFS can't easily be set up redundantly, especially since the locations are 300 km away from each other and that gives performance problems (tested with GlusterFS). Since I can only specify one NFS endpoint in Longhorn, it must be at location A or B. For another location C, NFS would have to be secure - in my case. However, since the locations alone are not 100% fail-safe, I would like to specify an NFS at both locations. Maybe I could build a workaround and copy the DR backups over via cronjob, but then I would still have to change the NFS endpoint if the other location fails. I find that too complicated, because in case of failure other colleagues should be able to operate Longhorn.

**Comment by yasker** [comment]
In this scenario, I would recommend using some third-party S3 storage in this case, e.g. AWS. For multiple backup targets, yeah we thought about that years ago but decide to go with the simple approach. We might need to revisit the decision later. But are you fine with duplicating the backup to both NFS server? The non-local distance one, as you said, might need authentication and can be very slow. And there is still possibility that two NFS server doesn't have the same content.

**Comment by bor8** [comment]
Thank you. Anyway, this is no show-stopper and I will try it with Longhorn. I have implemented your hint and created a ticket regarding Rancher or etcd: https://github.com/rancher/rancher/issues/30352.

**Comment by bor8** [comment]
Sorry, I don't use Longhorn any more. The reasons are the following. I don't have S3 storage and won't be getting any anytime soon. So I would have to use NFS as a backup. With Longhorn you can only configure one NFS. Since I have two locations, I have to choose one. If this location fails, I have a problem. Of course, I can try to mirror the data via script. But then Longhorn doesn't do me much good.

At the moment I'm using my existing NFS again (which runs outside of Kubernetes) in conjunction with Ubuntu+Autofs, Rancher+extra_binds and Local Storage. This also has the advantage of being easier to copy files and folders (which I have to do in my case) because it's not block storage.

I will come back to Longhorn when I get S3-like storage.
