### ISSUE TITLE
[BUG] UI - The longhorn URL incorrectly redirect in upgraded set up on refreshing the page.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1777]
**Describe the bug**
The URL incorrectly redirects in upgraded set up on refresh to something like ```https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/volume#/node```

**To Reproduce**
1. Install longhorn v1.0.2 app on a cluster in a Rancher set up.
2. Click the app link appears on the App page and open the longhorn page.
3. Upgrade the longhorn to Master.
4. Refresh the longhorn page.
5. It redirects ```https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/volume#/node```

**Expected behavior**
It should redirect to link ```https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/#/dashboard```

**Environment:**
 - Longhorn version: Longhorn Master commit id - 717e50a
 - Kubernetes version: 18.6
 - Node OS type and version: Ubuntu 18.04

**Comment by smallteeths** [comment]
This issue cannot be solved. Because our v1.0.2 rancher-proxy has access to the address `https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http: longhorn-frontend:80/proxy/volume`
Ifuser refresh the page directly after upgrading, the user will request the same address. Therefore, the user will be redirected to the wrong address. If the user clicks on the link on the rancher-ui instead of refreshing the page, then the problem should not occur.

Can we make some hints when upgrading. Prompt the user to re-visit the rancher-proxy or remove longhorn-frontend's own domain（volume, dashborad,  node, backup, setting, engineimage） from the original longhorn url. @khushboo-rancher @yasker

**Comment by smallteeths** [comment]
This issue cannot be solved. Because our v1.0.2 rancher-proxy access address is ` https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http: longhorn-frontend:80/proxy/volume`
Ifuser refresh the page directly after upgrading, the user will request the same address. Therefore, the user will be redirected to the wrong address. If the user clicks on the link on the rancher-ui instead of refreshing the page, then the problem should not occur.

Can we make some hints when upgrading. Prompt the user to re-visit the rancher-proxy or remove longhorn-frontend's own domain（volume, dashborad,  node, backup, setting, engineimage） from the original longhorn url. @khushboo-rancher @yasker

**Comment by yasker** [comment]
@smallteeths So the problem should affect the new installation? @khushboo-rancher Is it an upgrade or new installation?

**Comment by smallteeths** [comment]
It won't affect the new installation, it will only affect the existing user's browser which has our longhorn access path. For example, if a user still accesses `https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/' after upgrading. proxy/volume` This access will fail. He should be accessing `https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy`. 
Of course, if the user clicks on the longhorn-ui link directly from our rancher-ui, it will redirect correctly. Because the address of the rancher-proxy is `https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy` @yasker

**Comment by smallteeths** [comment]
It won't affect the new installation, it will only affect the existing user's browser which has our longhorn access path. For example, if a user still accesses `https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/volume` after upgrading, there will be an access error. He should be accessing `https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/`.
Of course, if the user clicks on the longhorn-ui link directly from our rancher-ui, it will redirect correctly. Because the address of the rancher-proxy is `https://rancher-server/k8s/clusters/c-l4d8s/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy` @yasker

**Comment by yasker** [comment]
OK, that should be fine. We can add a release note to this.

**Comment by yasker** [comment]
It is too minor to be mentioned in the release note. Close this as `won't fix` for now.

**Comment by mluds** [comment]
In my case I upgraded from 1.0.2 to 1.1.0, and went to a bookmarked URL `http://mylonghorndomain/volume` which was getting redirected to the invalid URL `http://mylonghorndomain/volume#/dashboard`.

The fix is to just visit `http://mylonghorndomain` which redirects to `http://mylonghorndomain/#/dashboard`.
