### ISSUE TITLE
[Question] Volumes in Degraded state

### ISSUE THREAD

**Issue by lomori** [longhorn/longhorn#1782]
We have a couple of Rancher K8s clusters with Longhorn as the default storage class. We've noticed Volumes going into Degraded state in both clusters. See data below. This is happening with an alarming frequency.

Questions:

1. How should I handle degraded volumes? I'm not even sure where to find any logs about it, like what exactly happened.
2. In the attached screenshot, you see two replicas. What happened to the third? The volume is configured with three replicas and we never changed this setting, either at global level or for this particular volume.

Volume Details

State: attached
Health: degraded
Ready for workload:Ready
Conditions: restore scheduled
Frontend:Block Device
Attached Node & Endpoint: vlt-catskube02 /dev/longhorn/back-restoration-3
Size: 2 Gi
Actual Size:234 Mi
Base Image:
Engine Image:longhornio/longhorn-engine:v1.0.2
Created:6 days ago
Node Tags:
Disk Tags:
Last Backup:backup-ff6728d82ab84863
Last Backup At:15 hours ago
Instance Manager: instance-manager-e-2cec9150
Namespace:default
PVC Name:mysql-pvc-3
PV Name:back-restoration-3
PV Status:Bound
Pod Name:mysql-74cfd897f6-4bxcn
Pod Status:Running
Workload Name:mysql-74cfd897f6
Workload Type:ReplicaSet

![Screenshot from 2020-09-10 11-22-55](https://user-images.githubusercontent.com/11261704/92753636-11d40280-f358-11ea-8e2e-05fc3a28ebf8.png)

**Comment by yasker** [comment]
Is there a scheduling error with the volume? That means Longhorn cannot find enough space to rebuild this replica, that's why you only saw two replicas here - one healthy and another one seems unscheduable.

The replica failure can due to network connectivity issues or CPU pressure. You might want to check the CPU load on your nodes to make there are enough CPU for the workload and Longhorn. We're tracking a more detail answer to this common question at https://github.com/longhorn/longhorn/issues/1783

**Comment by alt4** [comment]
Hi,
I've had the same issue (i.e. volume stuck in degraded state with greyed out replicas I cannot delete) and it turned out to be a very large amount of snapshots seemingly clogging up the volume and preventing any further operations:
```
alt@adm:~$ ./lhexec <degraded pvc> snapshot ls
ID
24e35fbc-b173-421a-a4e6-3718a7fe903e
500bc7a9-7549-407e-986d-99a323f2d1ea
b3f71b16-4a72-458b-b464-f4becb04b217
90a485a7-424f-4d5d-8164-2577dfce6fa1
3106be91-ee8f-487a-bf4a-8e8163ac1737
3d0f53f2-d09d-4ef3-9199-e2688e41f985
7717b055-637d-4fba-acf9-750e97227e8b
e44b30e3-4f71-41d3-97f7-f6159890f8f8

--- snip 228 (!!!) similar lines  ---

62191185-f691-4740-885d-5ffece545c14
d4192495-dfa0-4b58-972f-637ee7dc8bcf
0e3dc65c-88d0-4a2d-b974-95d8dcc850d8
c-w2at4o-4036e9ab
c-koay04-10ec0bbf
c-w2at4o-f9f145b9
c-w2at4o-8e9db8ea
c-koay04-5a1f6719
c-u8b8mx-5e0b8269
```
Following @yasker's instructions on https://github.com/longhorn/longhorn/issues/1010#issuecomment-573899942, the volume began recovering pretty much instantly after running a `purge`, and only the `c-*` snapshots remain, which is the expected behavior I suppose.

I think the massive amount of snapshots were created/attempted during a failed kubernetes upgrade on my end which rendered inter-nodes communications impossible for about an hour.
