### ISSUE TITLE
[FEATURE] Improve replica rebuilding speed when using 10Gb/s

### ISSUE THREAD

**Issue by onedr0p** [longhorn/longhorn#1795]
**Is your feature request related to a problem? Please describe.**

I am finding that when using Longhorn I see that when replicas are being rebuilt, the speeds are not saturating my 10Gb network.

**Describe the solution you'd like**

While replicas are being rebuilt it would be nice to see it going faster than 100MB/s

**Additional context**

I asked this first on the cloud-native slack in the longhorn channel, below is the link with some more context and debugging. I have confirmed from host to host and container to container speeds able to reach near 10Gb/s.

https://cloud-native.slack.com/archives/CNVPEL9U3/p1600260401112400

**Comment by shuo-wu** [comment]
1. It seems that Longhorn can launch multiple goroutines to speed up the rebuilding when there are multiple snapshot files in the replica: https://github.com/longhorn/longhorn-engine/blob/9db1eed79a0144526259846a78d9f80df664c823/pkg/sync/rpc/server.go#L404
2. Due to there are some additional checks during the file syncing, the single file rebuilding may not be able to eat up all of the bandwidth. We may need to test all much bandwidth the single file syncing can take first: https://github.com/longhorn/sparse-tools/blob/e548e37f91af9a7a53149b433d37d68bd7a051d7/sparse/client.go#L244

**Comment by onedr0p** [comment]
I forgot to mention that my longhorn volumes are SSDs, formatted as ext4 filesystem.

**Comment by boknowswiki** [comment]
My understand of replica rebuilding is not only about the network bandwidth, CPU and memory resources also play important roles here, also the SSD read/write bandwidth. It's like a chain. Say first need to have enough CPU and memory resource to read the data from one replica (SSD drive in this case) and send it over TCP to another host and then write the data to another replica, Just found [SSD speed: 500MB/s read, 200MB/s write, ](https://www.quora.com/What-is-the-average-read-write-speed-of-an-SSD-hard-drive). I think this this case regardless of CPU and memory resources, due to the write speed limitation, it can not reach 10Gb/s. And if the CPU are very busy with other tasks, it won't 100% focus on this replica rebuilding. This could be another impact on the speed as well.

Please let me know if anything doesn't make sense to you or any question. Thanks.

**Comment by onedr0p** [comment]
I should have corrected my post, these are NVMe drives.

**Comment by boknowswiki** [comment]
Could you run a bandwidth test on the local disk directly to get the performance? Then try using Longhorn with one replica which is locally on this host and see what's the performance difference? In this case we can first focus on the same node and disk to limit the factors. Thanks.

**Comment by yasker** [comment]
Hi @onedr0p ,

Is this issue concerned about the replica rebuilding speed or it's the Longhorn volume speed in general?

For the rebuilding, we don't aim to saturate the network.

For Longhorn volumes, the bandwidth Longhorn provided for the block device should be at the same level of disk provides (given enough CPU to Longhorn).

**Comment by onedr0p** [comment]
Originally I was concerned with the replica rebuilding speed, but I suppose it could be both. I know debugging this issue is hard, you would need a test environment with 10Gb. But if there's ever time a developer could look into it that would be great.

**Comment by yasker** [comment]
@onedr0p for the replica rebuild, we don't aim to saturate the network or disk, since rebuild is a secondary operation. The most important operation for the volume is read/write, which can cause more pressure on the disk and network. So we currently use a single thread for the rebuilding purpose, and don't expect it to use the maximum bandwidth of the disk or network. Do you think it makes sense?

Regarding the Longhorn volume performance, we do aiming to provide higher bandwidth and IOPS. The result will be likely constrained by the disk speed and CPU. So unless you only have a 1G network, network bandwidth isn't a major concern here.

**Comment by onedr0p** [comment]
@yasker that does make sense! We should not be taking away from the read/write of the volumes. I'll close this issue. Thanks for describing it to me!
