### ISSUE TITLE
[Question] Data consistency during automated cluster upgrades?

### ISSUE THREAD

**Issue by HubbeKing** [longhorn/longhorn#1798]
Howdy!

I'm running a few small test-clusters on bare metal to try out kubespray.

During automated kubernetes cluster upgrades, nodes are drained, upgraded, sometimes rebooted, and then uncordoned in pretty quick fashion, which usually means any active replicas on the node in question are marked as Failed in longhorn.

This is obviously not really a problem in testing, but in a production environment where low downtime and data consistency are important, potential data loss if all replicas fail out during upgrades is obviously not ideal.

Is there a way to integrate ansible and longhorn, to allow kubespray to wait for volumes to become Healthy before continuing with a cluster upgrade?

Does Rancher handle in-cluster Longhorn better during cluster upgrades, and would that thus be a better option than kubespray?

**Comment by shuo-wu** [comment]
There are 2 parts we need to consider in order to maintain the data consistency during the upgrade:
1. The node the workloads and the volume engine resides on. In this part, the volume engine (it's a process in pod `instance-manager-e-xxxxxx`) will be restarted along with the workload itself. Hence the data won't be modified in this part. As long as the filesystem is ext4 and [this recommended setting](https://longhorn.io/docs/1.0.2/high-availability/recover-volume/) is applied, the volume can be reused immediately after the node upgrade.
2. The nodes that the volume replicas (it's a process in pod `instance-manager-r-xxxxxx` and it's used to handle data r/w) reside on are upgraded. In this part, all replicas of a volume cannot be shutted down simultaneously. Otherwise, the volume has nowhere to write data then leads to data loss. I think maybe we can use [PDB](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) to slow down the node upgrade that contain replicas. But since Longhorn needs some time to recover the volume replica (processes) after the node upgrade and the pod `instance-manager-r-xxxxxx` reboots, we may need to find a way to control the node upgrade interval so that all replicas can be recovered before the next node upgrade starts. 

In general, we need more check and investigation part before providing the formal solution/answer.

**Comment by yasker** [comment]
Our community member has found a way to coordinate the behavior of `drain` with Longhorn and Kubernetes, https://github.com/longhorn/longhorn/issues/1631 . We will incorporate that in v1.1.0.
