### ISSUE TITLE
[FEATURE] Longhorn with managed Kubernetes cluster(EKS, GKE, AKS)

### ISSUE THREAD

**Issue by johnnyhuy** [longhorn/longhorn#1800]
We're currently running Longhorn `1.0.0` on our VMSS AKS clusters. Each time we upgrade a node pool we lose the disk created on the node due to _Azure_ re-imaging the node based on their [node rolling deployment strategy](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#upgrade-an-aks-cluster).

We're wondering if this is expected behaviour for node upgrades & _potentially_ node failures.

How should we approach this? Should there always be a tear down process prior to each upgrade?

**Comment by shuo-wu** [comment]
The case you encounter seems to be similar to this issue: https://github.com/longhorn/longhorn/issues/1269

If a single node failure or upgrade, now Longhorn volumes will directly mark the replica on the down/old node as failed, then rebuilds a new replica. 
But if all nodes of a volume are upgraded within a short period, the volume will become `Faulted`(unavailable). We will improve this part in the upcoming v1.1.0 so that the volume can be recovered after the node upgrades.

**Comment by yasker** [comment]
This reminds me we need to have a story around how to use Longhorn with managed Kubernetes services.

Use root disk won't be a good idea because they will get nuked during node upgrade.

One thing we need to investigate is how can users attach additional disks and use them for Longhorn in the managed Kubernetes services, like EKS, GKE, AKS.

**Comment by braghettos** [comment]
HI @yasker , what do you suggest to do in order to leverage Longhorn on EKS? There is the hard requirement to have the iscsi driver installed, which is not included in AMI images.

**Comment by PhanLe1010** [comment]
@braghettos 

If AMI image doesn't have iscsi, you can install iscsi on all nodes in the cluster by deploying this DaemonSet:
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/iscsi/longhorn-iscsi-installation.yaml
```
See more at https://longhorn.io/docs/1.1.0/deploy/install/#installing-open-iscsi

**Comment by dbpolito** [comment]
I would love to see how to attach additional disk on EKS, did a lot of research and it's pretty hard to find how to do it.

**Comment by dpstratascale** [comment]
> I would love to see how to attach additional disk on EKS, did a lot of research and it's pretty hard to find how to do it.

ditto, we have been looking at how to add the additional disk on EKS without success.
Rancher seems to be able to do it, but it uses its own API.

**Comment by smoell** [comment]
Hi all, I was wondering if Longhorn now supports EKS?

**Comment by vitosans** [comment]
Same boat,

**Comment by innobead** [comment]
ref: For EKS node group for node upgrade/replacement supported, https://github.com/longhorn/longhorn/issues/3481#issuecomment-1037890048.

**Comment by c3y1huang** [comment]
**To Add extra disk on AWS EKS**
1. Modify the launch template of the eks nodegroup to add new volume under `Configure storage`.
    1. Go to EKS cluster - EKS > Cluster > ${CLUSTER_NAME}
    2. Go to cluster node group - Configuration > Compute > Node Groups ${GROUP_NAME}
    3. Go to Launch template - Node Group Configuration > ${LAUNCH_TEMPLATE}
    4. Go to Modify template - Detail > Action > Modity template (Create new version)
    5. Add new volume - Configure storage
    6. Add device mount during launch > Advanced detail > User data
```example
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash

# https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data
echo "Running custom user data script"

DEV_PATH="/dev/sdb"
mkfs -t ext4 ${DEV_PATH}

MOUNT_PATH="/mnt/longhorn"
mkdir ${MOUNT_PATH}
mount ${DEV_PATH} ${MOUNT_PATH}

--==MYBOUNDARY==--
```
3. Update the EKS cluster node group `Launch template version`.
    1. Go to EKS cluster - EKS > Cluster > ${CLUSTER_NAME}
    2. Go to cluster node group - Configuration > Compute > Node Groups ${GROUP_NAME}
    3. Change Launch template version - Node Group configuration. The statue can be tracked in `Update history`.
4. Add disk and enable scheduling in Longhorn nodes page. Here also should disable scheduling on the default disk.

**Test use case after adding extra disk**
1. Set replica-replenishment-wait-interval to 0.
2. Create [deployment](https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml) and write some data to it.
3. Update something in the launch template, for example, add another storage.
4. Update the `Launch template version` in the EKS cluster node group with `Rolling update` strategy.
5. Wait for the update to complete.
6. Check the deployment in step 2 still running and data exist.

**Comment by c3y1huang** [comment]
### Add extra disk on Azure AKS (not supported)
AKS does not support additional disk in its (template)(https://docs.microsoft.com/en-us/azure/templates/Microsoft.ContainerService/2022-01-01/managedclusters?tabs=bicep#template-format). It is possible for manual disk attachment. Then raw device needs to be mounted either by manually mounting in VM or during launch with CustomScriptExtension that is [not supported in AKS](https://docs.microsoft.com/en-us/azure/aks/support-policies#user-customization-of-agent-nodes). 

Both ways do not seem to work. Because the mount will persist after the AKS upgrade, but the device for the additional disk does not, hence it will try to mount it to the (next mount point)[https://github.com/Azure-Samples/compute-automation-configurations/blob/master/prepare_vm_disks.sh#L85] that Longhorn doesn't know.

Without having an additional disk for expansion, it is possible to expand by replacing the node pool with a larger OS disk size. The node pool replacement also works for the AKS upgrade.

## Expend Node Volume Size by Replace node pool
1. Add new nodepool.
```
AZ_NODEPOOL_REPLACE=${AZ_AKS_NODE_POOL_NAME}1
AZ_AKS_NODE_DISK_SIZE_REPLACE=500
az aks nodepool add \
    --resource-group ${AZ_RG_NAME} \
    --cluster-name ${AZ_AKS_NAME} \
    --name ${AZ_NODEPOOL_REPLACE} \
    --node-count 3 \
    --node-osdisk-size ${AZ_AKS_NODE_DISK_SIZE_REPLACE} \
    --kubernetes-version ${AZ_K8S_VERSION} \
    --mode System
```
2. On Longhorn UI, disable schedule and enable evict nodes.
3. Cordon and drain K8s nodes.
```
for n in `kubectl get nodes | grep $AZ_AKS_NODE_POOL_NAME- | awk '{print $1}'`; do
  kubectl cordon $n && \
  kubectl drain $n --ignore-daemonsets --delete-emptydir-data
done
```
4. Delete node pool.
```
az aks nodepool delete \
  --cluster-name ${AZ_AKS_NAME} \
  --name ${AZ_AKS_NODE_POOL_NAME} \
  --resource-group ${AZ_RG_NAME}
```

## Upgrade K8s by node pool replacement
Cannot use `az aks upgrade` because AKS upgrade does image replacement and persists the node CRs. Hence no data disk gets created. Working around this, we can replace the current node pool with a new node pool at a higher K8s version.
1. Upgrade control plane.
```
AZ_K8S_VERSION_UPGRADE=1.21.9
az aks upgrade \
    --resource-group ${AZ_RG_NAME} \
    --name ${AZ_AKS_NAME} \
    --kubernetes-version ${AZ_K8S_VERSION_UPGRADE} \
    --control-plane-only
```
2. Add new nodepool.
```
AZ_NODEPOOL_REPLACE=${AZ_AKS_NODE_POOL_NAME}1
AZ_AKS_NODE_DISK_SIZE_REPLACE=500
az aks nodepool add \
    --resource-group ${AZ_RG_NAME} \
    --cluster-name ${AZ_AKS_NAME} \
    --name ${AZ_NODEPOOL_REPLACE} \
    --node-count 3 \
    --node-osdisk-size ${AZ_AKS_NODE_DISK_SIZE_REPLACE} \
    --kubernetes-version ${AZ_K8S_VERSION_UPGRADE} \
    --mode System
```
    
3. On Longhorn UI, disable schedule and enable evict lower version node pool nodes.
4. Cordon and drain K8s nodes.
```
for n in `kubectl get nodes | grep $AZ_AKS_NODE_POOL_NAME- | awk '{print $1}'`; do
  kubectl cordon $n && \
  kubectl drain $n --ignore-daemonsets --delete-emptydir-data
done
```
4. Delete node pool.
```
az aks nodepool delete \
  --cluster-name ${AZ_AKS_NAME} \
  --name ${AZ_AKS_NODE_POOL_NAME} \
  --resource-group ${AZ_RG_NAME}
```

**Comment by yangchiu** [comment]
Verified **AWS EKS** + v1.3.0-preview1 **passed**.

The following 3 scenarios are tested:

(1) Create additional volume

(1-1) Before creating additional volume, create [deployment](https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml) and write some data to it.
(1-2) Create additional volume by following the [instructions](https://v1-3-0--longhornio.netlify.app/docs/1.3.0/advanced-resources/support-managed-k8s-service/manage-node-group-on-eks/#create-additional-volume).
(1-3) After the launch template updated successfully, check the deployment in step (1-1), it's still running and data exists, and the newly created volume can be added to longhorn without problems.

(2) Expand volume

(2-1) Before expanding volume, create [deployment](https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml) and write some data to it.
(2-2) Expand volume by following the [instructions](https://v1-3-0--longhornio.netlify.app/docs/1.3.0/advanced-resources/support-managed-k8s-service/manage-node-group-on-eks/#expand-volume).
(2-3) After the launch template updated successfully, check the deployment in step (2-1), it's still running and data exists, and the expanded volume can be added to longhorn without problems and the size is correct.

(3) Upgrade k8s

(3-1) Before upgrading k8s, create [deployment](https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml) and write some data to it.
(3-2) Upgrade k8s by following the [instructions](https://v1-3-0--longhornio.netlify.app/docs/1.3.0/advanced-resources/support-managed-k8s-service/upgrade-k8s-on-eks/).
(3-3) After k8s upgraded, check the deployment in step (3-1), it's still running and data exists, and longhorn ui can be access without problems.

**Comment by innobead** [comment]
@yangchiu could you help create the manual test plan in longhorn-tests based on engineering input as well? (we have `manual-test-plan`) thanks.
