### ISSUE TITLE
task: Clean up Longhorn chart

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1818]
1. Remove questions.yaml
2. Move CRDs into `/crd` directory.

**Comment by yasker** [comment]
Regarding this issue, @boknowswiki please work with @shuo-wu to understand the context and what should we do.

**Comment by yasker** [comment]
We won't able to remove `questions.yaml` for now since we don't have the new UI ready yet.

**Comment by shuo-wu** [comment]
It seems that we cannot move `crd.yaml` in this version. Since Helm will try to delete the CRDs defined in the crd yaml file when the crd yaml file is moved out from the template directory. 
In order to let Helm ignore the `templates/crd.yaml` removal, we can add an annotation `"helm.sh/hook": "pre-install"` for all CRDs in advance. But I haven't found a way to automatically add this annotation at the 1st step of the upgrade. Instead, I think we can modify the package `longhorn-manager/upgrade` to append the annotation. Then we can move the crd file after v1.1.0.

**Comment by yasker** [comment]
Do we have any solution?

**Comment by shuo-wu** [comment]
We can add [a special annotation `helm.sh/resource-policy: keep`](https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases) for the CRDs in v1.1.0 release, then separate the CRD file in the following release. Since some users may not follow the upgrade guide, requiring users to add the annotation manually and separating the CRD file in v1.1.0 is not a good choice.

**Comment by yasker** [comment]
@shuo-wu sounds good to me. Can you create a new issue to remind us to move it in v1.2.0?

**Comment by shuo-wu** [comment]
OK. The CRD separation is tracked in https://github.com/longhorn/longhorn/issues/1879

**Comment by yasker** [comment]
@shuo-wu this issue has been moved directly to `Merged` without having test steps ready.

**Comment by shuo-wu** [comment]
Use the branch `master` of `https://github.com/rancher/charts` to test the updated chart.
The version `v1.1.0` in this branch is actually using the `master` images. And this chart is not for Rancher dev-v2.5. Instead, it's for the old-style Rancher APP.

Test 1:
Test if the private registry setting still works fine

Test 2:
1. Launch Longhorn v1.0.2
2. Deploy some workloads using Longhorn volumes.
3. Upgrade Longhorn to v1.1.0 via Rancher APP
4. Check if Longhorn system still works fine.

**Comment by yasker** [comment]
@shuo-wu There shouldn't be a Longhorn v1.1.0 release in upstream Rancher Chart. Are you referring to your own chart repo?

**Comment by shuo-wu** [comment]
Sorry for the typo. I have updated the PR.

**Comment by meldafrawi** [comment]
Validation: **Partially FAILED**

- Longhorn Manager will fail to deploy Longhorn Cluster Role is missing 
```
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["*"]
```

- `questions.yml` fils is missing `csi-snapshotter image Repository` on `Longhorn Images` section
![image](https://user-images.githubusercontent.com/18232258/96741711-655b5680-13c2-11eb-80de-416fe2971516.png)

**Comment by shuo-wu** [comment]
This is a newly introduced resource after the PR. I will update/sync the chart later.

**Comment by yasker** [comment]
Need to update the chart according to the new fields.

**Comment by shuo-wu** [comment]
> [Updated] Use the branch `master` of `https://github.com/shuo-wu/charts` to test the updated chart.
> Please set the image tags to `master` for version `v1.1.0`. And this chart is not for Rancher dev-v2.5. Instead, it's for the old-style Rancher APP.
> 
> Test 1:
> Test if the private registry setting still works fine for v1.1.0. And check if the default StorageClass works fine.
> 
> Test 2:
> 
> 1. Launch Longhorn v1.0.2 with the private registry set.
> 2. Deploy some workloads using Longhorn volumes.
> 3. Upgrade Longhorn to v1.1.0 via Rancher APP
> 4. Check if Longhorn system still works fine.

Please check this updated comment and re-test the Chart after the PR merge.

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test: https://github.com/longhorn/longhorn/issues/1818#issuecomment-726053295

Validated using the provided charts
```
The test Chart for Cluster Manager: https://github.com/shuo-wu/charts/ branch master
The test Chart for Cluster Explorer: https://github.com/shuo-wu/charts/ branch dev-v2.5
```

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/2035#issuecomment-739799909
