### ISSUE TITLE
[BUG] Upgrade fails on a cluster with a node having taint.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1924]
**Describe the bug**
Longhorn manager fails to come up healthy after upgrade if one of the nodes has taint.

**To Reproduce**
1. Deploy longhorn v1.0.2 on a cluster (1 etcd/control plane, 3 worker) nodes
2. Add taint to a node ```persistence=true:NoExecute```
3. Add toleration to ```persistence=true:NoExecute``` to longhorn.
4. Wait for all the pods of longhorn become healthy.
5. Upgrade longhorn to Master.
6. The pod of daemon set engine image fails to come up on the tainted node.
7. The longhorn-manager (all pods) fail to come healthy.

**Expected behavior**
The engine image should come up healthy as in step 4, all the pods on tainted node become healthy.

**Log**
```
time="2020-10-29T07:02:58Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:master to be ready"
time="2020-10-29T07:03:04Z" level=debug msg="Waiting for engine image longhornio/longhorn-engine:master to be ready"
time="2020-10-29T07:03:10Z" level=fatal msg="Error starting manager: failed to wait for engine image longhornio/longhorn-engine:master: Wait for engine image longhornio/longhorn-engine:master timed out"
```

**Environment:**
 - Longhorn version: Longhorn-master
 - Kubernetes version: v1.18
 - Node OS type and version: Ubuntu 18.04

**Comment by PhanLe1010** [comment]
Seems like `engine image` controller doesn't add toleration to `engine image` daemonset

**Comment by PhanLe1010** [comment]
After discuss with @khushboo-rancher 

The reproduce steps were:
1. Deploy longhorn v1.0.2 on a cluster (1 etcd/control plane, 3 worker) nodes
1. Add taint to a node ```persistence=true:NoExecute```
1. Add toleration to ```persistence=true:NoExecute``` to longhorn.
1. Wait for all the pods of longhorn become healthy.
1. Create a volume, create a recurring job for the for volume.
1. Wait for the recurring job starts, see that there are many pods created.
1. Upgrade longhorn to Master.
1. The pod of daemon set engine image fails to come up on the tainted node.
1. The longhorn-manager (all pods) fail to come healthy.

The root cause was that at step 6 above, the node was already in a bad condition in which it was overloaded by thousand of pods. Therefore, `engine image` daemonset, manager daemonset, etc, ... cannot create a new pod on the bad node. So, the upgrade failed.

In order to recover from this situation, users can follow the step describe at https://github.com/longhorn/longhorn/issues/1903#issuecomment-717636744. There is nothing we can do from code perspective.

**Comment by khushboo-rancher** [comment]
Closing the issue as Taint is not creating the problem and it is because of the large numbers of pods on the node.
