### ISSUE TITLE
My volumes keep getting "Degraded"

### ISSUE THREAD

**Issue by yurividal** [longhorn/longhorn#1949]
My volumes often get "Degraded" with Scheduling Failure Replica Scheduling Failure errors. Seems to happen with most of my volumes. What could be causing this?

![image](https://user-images.githubusercontent.com/8555749/97990519-f6c1c400-1dd7-11eb-9320-bc0b5f145713.png)

---
Version: `v1.0.2`

**Comment by yasker** [comment]
Regarding the scheduling failure, it's likely caused by lacks of space on the node, so there isn't another node has space to accommodate the volume. You can find more details at https://longhorn.io/docs/1.0.2/volumes-and-nodes/scheduling/

Also, the volume shouldn't get into the degraded state often. It can be caused by temporarily network issue or CPU issue on the node that's running the replica. Once a replica failed, you should see it as red in the UI. If all the failure replicas are on the same node, then it's likely there are some issues with that node caused the replica failure frequently.

**Comment by yurividal** [comment]
Thanks. I will check cpu and disk space. It's not a network issue since it happens mostly on one of the 2 nodes that I have in a very same datacenter. How do I fix these volumes and take them out of degraded state? I keep trying to delete the Grey "stopped" volumes, but  it just keeps popping new stoped ones, forever.

**Comment by yasker** [comment]
Once you solve the disk space issue, the replica will start rebuilding to maintain the healthy replica count (likely it's 3 in your case). After the rebuilding finished, the volume will be back to healthy.

Btw, do you have only two nodes in the cluster? Longhorn is set to hard anti-affinity by default so you need to have at least 3 nodes for 3 replicas. If you only have two nodes, you can reduce the replica count to 2.

**Comment by yurividal** [comment]
Thankffor you answer. Ill check the disk-spaces now. And yes, i have 3 nodes in my cluster. One of them (colo1-ros) is on a separate datacenter, though, connected over site-to-site vpn. But, its the one that i have the least issues with. Haven't seen any stopped volumes in it.

**Comment by yasker** [comment]
Hmm, what's your bandwidth between two sites? Normally it's hard to sustain the bandwidth and latency needed for storage between different regions.

**Comment by yurividal** [comment]
We have 10Gig internet on both locations

**Comment by yasker** [comment]
Is that 10G for each location, or the site-to-site VPN between two locations?

**Comment by yurividal** [comment]
Each datacenter have a 10G uplink, through which the Site-to-site VPN connect
