### ISSUE TITLE
[FEATURE] Longhorn LocalPV

### ISSUE THREAD

**Issue by michaelpearce-gain** [longhorn/longhorn#1965]
**Is your feature request related to a problem? Please describe.**
Ability to provision a Longhorn LocalPV.

**Describe the solution you'd like**
Ability to provision a Longhorn LocalPV.

Using K8s native LocalPV's are useful as no network-based storage can keep up with baremetal in write IOPS/latency/throughput, when using NVME/Optane disks.  Giving Direct I/O: Near-zero disk performance overhead

Many systems replicate between their stateful sets already such as Kafka, Cassandra etc.

Why you might ask don't just use the LocalPV, and there is where Longhorn LocalPV could be a much better operational model, using whats there already in longhorn.

Ability to thin provision and dynamic provision
Ability to monitor LocalPV volume usage and other metrics centrally along side DistributedPV.
Ability to apply central limits and quotas
Ability to perform the same easy backup as can be done with DistributedPV
Ability to move a LocalPV volume whilst detached if needed from one host to another

Making Longhorn a single place to manage all storage, for k8s, regardless if it is distributed or local, rwo (block) or rwx (file)

**Describe alternatives you've considered**
Kubernetes LocalPV - see above to why longhorn can add value
OpenEBS rawfile localpv - requires us to move away from longhorn :( :( 

**Additional context**

**Comment by yasker** [comment]
With the combination of a single replica and the upcoming v1.1.0 feature #1045 , we probably already satisfied the majority of the requests here (if not all). See https://v1-1-0.longhorn.io/docs/1.1.0/high-availability/data-locality/ for a preview version of the doc for the `data locality` feature, especially it will allow moving data of the volume from one node to another.

Let me know what do you think.

**Comment by michaelpearce-gain** [comment]
Do you have any perf stats of running it like this, e.g. data locality + 1 replica vs K8s LocalPV on fast disks such as nvme / optane, and the write latency overheads?

I know https://longhorn.io/blog/performance-scalability-report-aug-2020/, it had for a 100us write with longhorn that had a write perf penalty of 400us, which for this kind of use case takes longhorn out the equation currently thus this rfe.

The main use case here we are thinking of is where we have NVME and Optane disks and run workloads above it that can make use of this low latency write IO and have their own replication.

**Comment by yasker** [comment]
The storage overhead will still be there for v1.1.0 release, as you saw in the last performance report. There is feature #508 we will have in v1.1.0 release, which should cut the latency by about 15%. It's one small step though. We're planning on a rewriting of the frontend implementation, hope to greatly reduce the overhead in the v1.2.0 release. Since Longhorn is built on top of local storages, the overhead won't be 0 anyway (unless we provide unprocessed local PV to the user), but we're working on improving the overhead.

**Comment by michaelandrepearce** [comment]
Thats kinda what this is asking for. Ability to get Direct IO just it managed by longhorn. I wonder if when replication is set to 1 and data is local, if theres a way to switch to direct.

**Comment by yasker** [comment]
Implement local PV as a special case would be tricker, since then we need to reimplement all the features you listed above. And the management plane will become much more complex since it needs to deal with two kinds of backend engine.

At least for now, we want to focus on reducing the overhead for all use cases, which will benefit the case for a single replica as well.

Btw, I think we might have a different understanding of what's `direct IO`. In Longhorn, it's a mechanism to guarantee crash consistency. It doesn't mean 0 overhead though.

**Comment by michaelandrepearce** [comment]
So essentially we should be looking to switch to openebs / mayadata then? If this is important for us?

**Comment by yasker** [comment]
@michaelandrepearce maybe that's the solution. Creating a local PV version in Longhorn right now is essentially write another Longhorn and try to make the two Longhorns work together without the change of the user interface. It needs a significant amount of effort. But we already have CSI or Kubernetes PV/PVC interface, which should act as the common interface between different storage vendors.

I hope Longhorn can satisfy your requirement, but at this moment, I am not sure creating a special Local PV engine is the direction we want to go. I will still incline to use the current Longhorn engine/replica framework, and somehow optimize it to near-native performance (e.g. shortcut the engine-replica communication, or even skip engine in the single replica case, plus integration with SPDK), then present to the user. Then all the features you needed will be there automatically without we reimplement everything once again.

**Comment by michaelpearce-gain** [comment]
@yasker if "near-native performance (e.g. shortcut the engine-replica communication, or even skip engine in the single replica case, plus integration with SPDK)" whats the roadmap for this, and what is the target latency hit, remembering we live in an age of Enterprise DC NVMe and Optane drives where disk write latency is below 100us quite happily these days.

**Comment by michaelpearce-gain** [comment]
"skip engine in the single replica case" this sounds like a better strategy to get near native performance than the first option.

**Comment by yasker** [comment]
We don't have a target latency at the moment. We will know more once we start the SPDK integration and see how much we can improve with it.

**Comment by michaelandrepearce** [comment]
@yasker can you put a label on this so it doesnt auto close (i assume like other open source repos e.g. k8s theres an auto close if in active bot enabled)

**Comment by yasker** [comment]
Sure. I've added `enhancement` label so this issue won't be auto closed.

**Comment by michaelandrepearce** [comment]
Is there any progress on SPDK and in single replica to skip the engine?

**Comment by yasker** [comment]
@michaelandrepearce it's one of the top items in our mind right now. Due to the complexity of the problem, we cannot commit a date yet. But we know there are many users out there who want to have a near-native performance for local persistent storage but still want the convenience of Longhorn snapshot/backup. We'd like to address this in the next couple of minor releases.

**Comment by michaelandrepearce** [comment]
Is there any update on spdk and single replica skip engine? Did it make 1.2.0?

**Comment by yasker** [comment]
@michaelandrepearce We're working on a new SPDK based engine. The initial result is very promising. We're able to achieve the near-native performance in terms of IOPS, even with replicas. The project is in a very early stage right now and it will take probably a year or two for us to match the functionality and stability of the current Longhorn engine.  Hopefully, we will have something experimental to show it's potential in v1.3.0.
