### ISSUE TITLE
[BUG] Post-upgrade job uses "always" image pull policy

### ISSUE THREAD

**Issue by gitlawr** [longhorn/longhorn#1986]
**Describe the bug**
I'm running longhorn in an offline environment without a private registry. All images are imported to the nodes. When I try to upgrade longhorn via helm, the post-upgrade pod stucks in `ContainerCreating`, given that the imagePullPolicy is `Always`.

**To Reproduce**
1. Import offline images to the nodes.
2. Install longhorn
3. helm upgrade the longhorn release
4. wait and check pods' status.

**Expected behavior**
Be able to upgrade successfully.
I would expect that the `image.pullPolicy` value applies to the job as well.

**Log**
N/A

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes version: v1.18.9+k3s1
 - Node OS type and version: k3OS v0.11.1

**Comment by PhanLe1010** [comment]
https://github.com/longhorn/longhorn/pull/2007 should affect/fix this issue.

**Comment by PhanLe1010** [comment]
**Reproduce steps:**
1. Using Rancher, create a cluster of 1 node (with controller, etcd, worker roles) on Amazon EC2 provider. It is easier to control the network for a one-node cluster. 
1. Wait until the cluster is created, SSH into the EC2. 
1. Follow the document at https://longhorn.io/docs/1.0.2/advanced-resources/deploy/airgap/ to download all images of Longhorn v1.0.1, Longhorn v1.0.2, Longhorn master to the EC2
1. Log in to AWS console, find the EC2, open the security group setting for the EC2. We disconnect the EC2 from the internet by setting the  the security group as below:
   <img width="1622" alt="Screen Shot 2020-11-24 at 4 49 21 PM" src="https://user-images.githubusercontent.com/22139961/100167927-10a17480-2e75-11eb-98c1-ba496923bedb.png">
   Make sure to open the appropriate ports so that Rancher and your computer can communicate with the EC2
1. From Rancher, Install Longhorn v1.0.1
1. Create a volume, write some data, attached it to the node, verify everything is ok.
1. From Rancher, Upgrade Longhorn to v1.0.2. Verify that the `Post-upgrade` job is stuck since its `imagePullPolicy=Always` and it cannot pull the image.

**Comment by PhanLe1010** [comment]
@gitlawr Thank you for reporting.

We will fix this bug in the coming v1.1.0 release. When v1.1.0 is out, you can download v1.0.1 images to the cluster and update Longhorn.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
