### ISSUE TITLE
[BUG] Longhorn didn't choose to rebuild on an existing replica if there is a scheduling failed replica after 

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1992]
**Describe the bug**
Longhorn didn't choose to rebuild on an existing replica if there is a scheduling failed replica.

**To Reproduce**
1. Create a volume with 3 replicas on a three-node cluster.
2. Shutdown one of the replica node.
3. Wait for more than `Replica Replenishment Wait Interval` which is by default 600 seconds.
4. See volume scheduled another replica to replace the down replica, but unable to trigger rebuild since it's not scheduable.
5. Bring back the node.
6. See rebuild was started on scheduled replica instead of the existing replica.

**Expected behavior**
Ideally, the rebuild should start on the existing replica to save space in this case.

**Log**
N/A.

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.19.3
 - Node OS type and version: Ubuntu 20.04

**Additional context**
N/A

**Comment by innobead** [comment]
@nitendra-suse can you check if this is still a valid case? 

cc @longhorn/qa

**Comment by nitendra-suse** [comment]
> @nitendra-suse can you check if this is still a valid case?

I think this is still valid cases. After following above mentioned steps.It looks like  rebuilt is not happening on existing replica. 
Please find below events captured from Event Log on longhorn UI.

**Comment by derekbit** [comment]
@roger-ryao Can you help revalidate? Thank you.

**Comment by roger-ryao** [comment]
This issue still valid.

**Comment by c3y1huang** [comment]
Root cause:

1. volume controller [creates a new replica](https://github.com/longhorn/longhorn-manager/blob/0a1a10867fa6843447eb262abfef5e8eafb80481/controller/volume_controller.go#L2244) when [checkBackDuration == 0](https://github.com/longhorn/longhorn-manager/blob/0a1a10867fa6843447eb262abfef5e8eafb80481/controller/volume_controller.go) based on return of [timeToReplacementReplica](https://github.com/longhorn/longhorn-manager/blob/master/scheduler/replica_scheduler.go#L911).
1. volume controller attempts to [schedule the new replica](https://github.com/longhorn/longhorn-manager/blob/0a1a10867fa6843447eb262abfef5e8eafb80481/controller/volume_controller.go#L1745) but fails because the node is still down. And the [volume gets enqueued](https://github.com/longhorn/longhorn-manager/blob/0a1a10867fa6843447eb262abfef5e8eafb80481/controller/volume_controller.go#L1765) for later handling.

Eventually, the node powers up, and the new replica gets successfully scheduled.

**Comment by c3y1huang** [comment]
Proposed fix:

Before creating a new replica, check if there are any available node or disk candidates. If none are found, wait until the next reconcile loop.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 0a1d3a7) following [the test steps](https://github.com/longhorn/longhorn/issues/1992#issue-744982618). The existing replica is reused instead of creating a new one. Also e2e test case `Power Off Replica Node Should Not Rebuild New Replica On Same Node` passed: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/682/
