### ISSUE TITLE
[BUG] Remove hard-coded namespace in uninstall controller

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#2034]
**Describe the bug**
`longhorn-system` namespace should not be hardcoded inside [uninstall controller](https://github.com/longhorn/longhorn-manager/blob/master/controller/uninstall_controller.go#L39).

**Comment by yasker** [comment]
One note: the uninstaller is designed to run in default namespace, since if `longhorn-system` namespace is deleting, we cannot creating a new pod in it.

**Comment by joshimoo** [comment]
The fix here is to use the uninstall-controller namespace variable.
https://github.com/longhorn/longhorn-manager/blob/master/controller/uninstall_controller.go#L48

Which is set based on the passed longhorn-namespace env variable which must be specified in the uninstall.yaml.
https://github.com/longhorn/longhorn-manager/blob/master/deploy/uninstall/uninstall.yaml#L78

**Comment by shuo-wu** [comment]
> One note: the uninstaller is designed to run in default namespace, since if `longhorn-system` namespace is deleting, we cannot creating a new pod in it.

IIRC, for Helm 3, the namespace won't be created and deleted automatically by Helm. Do we need to update the uninstallation YAML file for the Chart to make it run in default namespace?

**Comment by joshimoo** [comment]
@shuo-wu I don't know about helm, but if you look at the code you will see that instead of using the passed namespace var, which the user could set to the namespace that should be cleaned up, we will use the hardcoded `longhorn-system` namespace for the informers, so we won't be getting the add/update/delete events for namespaced objects if longhorn is not installed in `longhorn-system`. therefore we should use the dynamically passed namespace env, which can be set to the namespace that should be cleaned up.

**Comment by joshimoo** [comment]
My point is the code already creates the uninstallation pod in the default namespace, and passes a `LONGHORN_NAMESPACE` env
Which gets used by the controller as it's namespace variable instead of the actual namespace it's runnig in.
https://github.com/longhorn/longhorn-manager/blob/master/deploy/uninstall/uninstall.yaml#L77

At the moment if the user want's to uninstall longhorn that is not installed in longhorn-system, he needs to change that anyway, but we hardcoded the `longhorn-system` and use that in the informers instead of the passed namespace.
Which means our informers aren't working correctly during installation.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested both helm2 and helm3 with install and uninstall v1.3.0-dev(master-head image*) on rke2 cluster, and there is no problem with customized namespace.

<sup>* docker.io/longhornio/longhorn-manager@sha256:121ec7cdf95f3f702f1d0a41436aab1b1150255ae36302304ea20687ebf0bf7a</sup>

---
Test note:
| helm version | install | show install | uninstall |
| :- | :- | :- | :- |
| 3 | helm install longhorn ./ --set namespaceOverride="not-in-lh-sys" --namespace not-in-lh-sys --create-namespace | helm list -n  not-in-lh-sys | helm uninstall longhorn -n not-in-lh-sys |
| 2<sup>**</sup> | helm install ./ --name longhorn --set namespaceOverride="not-in-lh-sys" --namespace not-in-lh-sys | helm list | helm delete longhorn |

<sup>** Preparation for helm2: `kubectl create serviceaccount --namespace kube-system tiller && kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller && kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'`</sup>
