### ISSUE TITLE
[Question] About performance enhanced frontend using SPDK

### ISSUE THREAD

**Issue by benqwu** [longhorn/longhorn#2095]
**Question**
We know that SPDK uses a polling model, and one thread needs to consume one cpu. In this case, how to support multiple independent engine processes, because the number of cpus in the server is limited.
Does the design philosophy of longhorn microservices need to be changed? For example, all engines run in the same process to share SPDK threads.

**Environment:**
 - Longhorn version:
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by yasker** [comment]
@benqwu We can still design sharing one thread with multiple Longhorn engines, through some kind of internal communication mechanism. We still need to dive deep into SPDK before we can say that for sure. For now, I don't think the microservice approach will be changed, since the separation of the concern is still very important for us.

**Comment by benqwu** [comment]
I have another questions. According to the test results here [](https://longhorn.io/blog/performance-scalability-report-aug-2020/) , I suspect that compared with native, the main latency increase is on the network side. Is this guess correct?
If using dpdk as the frontend, how much latency can be reduced, could you share some experimental results?
Thank you. @yasker

**Comment by yasker** [comment]
The test result shows we are getting almost the same result regardless of the replica is remote or local, so we believe the majority of the latency is introduced by our current frontend stack instead of the network. That's why we're looking forward to update our block device front end implementation to SPDK.

We don't have concrete data yet since we're in the early stage of the experimenting. We will share more data when we get better ideas.

**Comment by benqwu** [comment]
> The test result shows we are getting almost the same result regardless of the replica is remote or local, so we believe the majority of the latency is introduced by our current frontend stack instead of the network. That's why we're looking forward to update our block device front end implementation to SPDK.
> 
> We don't have concrete data yet since we're in the early stage of the experimenting. We will share more data when we get better ideas.

Thank you for your sharing.
