### ISSUE TITLE
[Question] How to handle failed replicas and how to evaluate the error.

### ISSUE THREAD

**Issue by connde** [longhorn/longhorn#2123]
**Question**
Hi, I'm running Longhorn with in K3S HA mode and set my replicas to 3.

Today one of my nodes failed and I saw that Longhorn had degraded status and after some time it was restored again.
My nodes, correct number of replicas would be 16.
![image](https://user-images.githubusercontent.com/1514559/102675975-3e2ec480-417a-11eb-96c5-b1b855d0728e.png)

All nodes have 16 Healthy volumes, but I'm also seeing a lot of Failed.
![image](https://user-images.githubusercontent.com/1514559/102676011-60284700-417a-11eb-82c8-82566c723aea.png)

My question is, what is the correct procedure to eliminate those, do I need to manually delete the Failed status since it was recovered or they will disappear at some point? What is the best method/command to evaluate why my Longhorn node failed?

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: v1.19.5+k3s1
 - Node config
   - OS type and version Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8gb
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: First node 2ms, second 10ms
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VPS

**Additional context**
Running high CPU usage application.

**Comment by PhanLe1010** [comment]
> My question is, what is the correct procedure to eliminate those, do I need to manually delete the Failed status since it was recovered or they will disappear at some point?

The fail replicas will be deleted automatically after a timeout specified by `staleReplicaTimeout ` in storageclass. I think you don't have to manually delete them.

> What is the best method/command to evaluate why my Longhorn node failed?

One reason I am think of is that Longhorn node fails because the pod of the `manager` DaemonSet in `longhorn-system` namespace fails. You can check to see if it is true by looking at the events of the `manager` DaemonSet and the `startTime` of the pods. cc @yasker Do you have more inside?

**Comment by yasker** [comment]
I assume 16 replicas per node is because many of them are failed. But we do have a recommendation regarding how much CPU resources you should reserve per node, check https://longhorn.io/docs/1.1.0/best-practices/#guaranteed-engine-cpu for details.

Also, I noticed that you didn't show the network bandwidth between the node. If you only have a 1Gbps network between the node, it can only reliable provide full throughput of three Longhorn volumes at the same time. Any additional loads might result in communcation timeout thus replica failure.

**Comment by connde** [comment]
Hi, thanks for the feedback.

The application is not read/write intensive, just some logs are being added from time to time, but I will see what can be optimized.

I will also review CPU reserve as it is below the recommended, but this might be associated to the bandwidth between each node as stated by you.
