### ISSUE TITLE
[BUG] instance pvc-454dc5eb-f... NodeID node-19 is not the same as the instance manager instance-manager-r-0983818b NodeID node-20

### ISSUE THREAD

**Issue by teknologista** [longhorn/longhorn#2125]
**Describe the bug**

After upgrading from 1.0.2 to 1.1.0
the nodes page of the longhorn UI was acting weird with nodes displaying a rapid changing number of replicas (up and down).

Everything is operating fine on the storage provisioning to pods side.

We started exploring pods logs and found out the longhorn manager pod log for the affected nodes was spammed with messages like this:

```
time="2020-12-19T09:37:21Z" level=error msg="BUG: instance pvc-4aa83d0c-c0e4-4c2f-81b2-af8a0301851a-r-6a118a25 NodeID node-21 is not the same as the instance manager instance-manager-r-5fe432a5 NodeID node-13"

time="2020-12-19T09:37:21Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-4aa83d0c-c0e4-4c2f-81b2-af8a0301851a-r-6a118a25: fail to sync replica for longhorn-system/pvc-4aa83d0c-c0e4-4c2f-81b2-af8a0301851a-r-6a118a25: BUG: instance pvc-4aa83d0c-c0e4-4c2f-81b2-af8a0301851a-r-6a118a25 NodeID node-21 is not the same as the instance manager instance-manager-r-5fe432a5 NodeID node-13"

time="2020-12-19T09:37:21Z" level=error msg="BUG: instance pvc-454dc5eb-f47f-4bc0-bf8a-042e21c55d02-r-a8bf65ed NodeID node-19 is not the same as the instance manager instance-manager-r-0983818b NodeID node-20"
E1219 09:37:21.454770       1 replica_controller.go:169] fail to sync replica for longhorn-system/pvc-454dc5eb-f47f-4bc0-bf8a-042e21c55d02-r-a8bf65ed: BUG: instance pvc-454dc5eb-f47f-4bc0-bf8a-042e21c55d02-r-a8bf65ed NodeID node-19 is not the same as the instance manager instance-manager-r-0983818b NodeID node-20

time="2020-12-19T09:37:21Z" level=warning msg="Dropping Longhorn replica longhorn-system/pvc-454dc5eb-f47f-4bc0-bf8a-042e21c55d02-r-a8bf65ed out of the queue: fail to sync replica for longhorn-system/pvc-454dc5eb-f47f-4bc0-bf8a-042e21c55d02-r-a8bf65ed: BUG: instance pvc-454dc5eb-f47f-4bc0-bf8a-042e21c55d02-r-a8bf65ed NodeID node-19 is not the same as the instance manager instance-manager-r-0983818b NodeID node-20"
```

And this for some of our pvcs.

**To Reproduce**
1. Live-Upgrade a perfectly healthy 1.0.2 cluster to 1.1.0 using rancher app catalog
2. Find that some nodes don't have enough reservable resources to deploy the new lh 1.1.0 pods
3. Try stopping non essential services
4. Try do drain some nodes
5. when enough resources are available the upgrade continues on those nodes
6. everything is back to normal except for the bugs/errors/warnings described above

**Expected behavior**
We expected a clean upgrade

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

Support Bundle too large to attach. For example longhorn manager logs have grown to ~600MB since yesterday.
We attached a single manager's log:
[container-2.log](https://github.com/longhorn/longhorn/files/5720760/container-2.log)

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE / Rancher 2.4.10 / kubernetes 1.18
 - Node config
   - OS type and version: Ubuntu 18.04.4 LTS
   - CPU per node: 4
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes:  1Gbps / 1ms private network
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VPS on DigitalOcean

**Additional context**

`
`

**Comment by PhanLe1010** [comment]
@teknologista 

1. As a workaround, can you try to see if the replica `pvc-4aa83d0c-c0e4-4c2f-81b2-af8a0301851a-r-6a118a25` and similar replicas are in error state on Longhorn UI? If they are and there are other healthy replicas of the volume, you can manually delete the failed replicas. That way, the longhorn manager will not be spammed with the above messages.

2. I am having a hard time reproducing this issue. Steps I have taken are:
* Deploy Longhorn 1.0.2  and some workload using Longhorn volumes
* Deploy an `abuse` deployment with the scale big enough to reach pod limit on `node-1`
* Live upgrade Longhorn to v1.1.0
* Force drain `node-1`
* scale down the `abuse` deployment
* when enough resources are available the upgrade continues on those nodes
I don't see the above error message. Is there any additional steps you took? Is it possible to send us a support bundle to longhorn-support-bundle@rancher.com ?

**Comment by PhanLe1010** [comment]
@yasker @shuo-wu 

From the code perspective, Do you recall why we return an error message [here](https://github.com/longhorn/longhorn-manager/blob/24300a52841e7f66b6568e05c327b2797df8abca/controller/instance_handler.go#L317 )? should we not return that error? Because if we return the error, the changes to `replicas.status` are not persisted in `etcd` and so the error message is printed again and again.

**Comment by shuo-wu** [comment]
Since this is definitely a bug rather than a handleable special case like node-down, it's better to expose this error rather than **directly tries** to recover it. Otherwise, we may miss the error, and it will degrade the system's reliability silently.

**Comment by teknologista** [comment]
@PhanLe1010 Unfortunately your suggestion doesn't change anything.
We have shared the requested full support bundle (200MB) for issue via a Dropbox link you should have received.

We have also added 2 screen recordings (also attached below) so you can see what we are facing in the longhorn manager UI.
The problem show happens for several nodes, but not all.
We have tried manually deleting replicas for the affected nodes but they immediately trigger a rebuild.

https://user-images.githubusercontent.com/48756870/103205566-1cf87180-48fa-11eb-8af1-cb24374610a6.mov

https://user-images.githubusercontent.com/48756870/103205558-17029080-48fa-11eb-8e6b-f8f0e9e52db9.mov

**Comment by PhanLe1010** [comment]
@teknologista 

1. For the workaround:

Yeah, they will imediately triggle a rebuild for the deleted replica but I think that after finishing rebuilding, the new replica should not spam `longhorn-manager` with the error messages. 

Since I couldn't reproduce the issue, I cannot try it on on my setup. Can you make sure that all replicas on `node-20` are ok to delete and try to delete them? Then wait for the replicas to finish rebuidling. Then check the logs of `longhorn-manager` on node-20 to see if it is still spammed. 

2. We are investgating at the support bundle you sent

**Comment by PhanLe1010** [comment]
@teknologista 
After checking the support bundle we see that there are multiple nodes that have disks with the same DiskUuid (e.g `444ee229-c78d-4519-85c3-542e42cbe171`). This leads to the problem in this issue. Did you mount the same disk to multiple nodes or did you move the same disk around?

**Comment by teknologista** [comment]
@PhanLe1010  No didn't move around or share the disks but as we use a snapshot to create new Kubernetes Nodes, some share the save UUID for disk /dev/vda1 indeed.

This was not an issue on Longhorn 1.0.2.

What can we do about this ?

Many thanks.

**Comment by PhanLe1010** [comment]
@teknologista

Okay. We understand the root cause now.

It is a problem in Longhorn 1.1.0 only because Longhorn 1.1.0 supports disk migration to new node. So, Longhorn 1.1.0 depends on the uniqueness of disk's uuid to identify the disk. 

Since it is late in my time, I will discuss with you the workaround tomorrow.

**Comment by teknologista** [comment]
@PhanLe1010 

Brilliant! many thanks!

**Comment by PhanLe1010** [comment]
@teknologista 

These are the steps I have tested. 

**Prepare:**
1. In the Longhorn UI node page, Disable scheduling on problematic nodes (node-2 and node-3 in the below video). After doing this step, you should have something like this:
   

https://user-images.githubusercontent.com/22139961/104077323-1e654c00-51ce-11eb-865f-c79160d65a92.mov


2. Make sure that all the volumes that have a replica on problematic nodes have a replica on other healthy nodes. If it doesn't have a replica on a healthy node, increase replica count for volumes so Longhorn build a replica on a healthy node.
3. Backup all Longhorn volumes. Make sure that the volumes' data is in a safe place outside of the cluster. If anything wrong we can use restore the data from the backups.
4. Scale down all of the workloads that use Longhorn volumes. Make sure that all Longhorn volumes are detached before proceed to the next step
5. Change the `Replica Replenishment Wait Interval` setting in Longhorn UI to `0` so that Longhorn rebuilds a new replica immediately.
   
<img width="550" alt="Screen Shot 2021-01-08 at 4 27 22 PM" src="https://user-images.githubusercontent.com/22139961/104077400-6d12e600-51ce-11eb-9737-b7193269fc55.png">

6. In the Longhorn UI node page, Enable scheduling on problematic nodes that were disabled in step 1

**We will fix the problem node by node.**
1. Pick a problematic node. e.g `worker-3`
2. SSH into the `worker-3`
3. `cd /var/lib/longhorn/`.  and `rm longhorn-disk.cfg`. and `rm replicas/ -r`
4. Go back to the Longhorn UI node page. Select `worker-3`. Disable scheduling for the default disk. Click delete the default disk. Click save.
   

https://user-images.githubusercontent.com/22139961/104077604-473a1100-51cf-11eb-9c0c-63fd6dbb8443.mov


6. Still in the Longhorn UI node page. Select `worker-3`. Add new disk. Name is `default-disk`, path is `/var/lib/longhorn/`. Click enable scheduling. And click save.
   

https://user-images.githubusercontent.com/22139961/104077690-a39d3080-51cf-11eb-8633-3ef1d7c576c0.mov

7. Repeat for all problematic nodes


**Clean up**
1. Scale-up the workloads.
2. Longhorn attaches all volumes and rebuild replica on the problematic nodes 
3. Verify that the diskUuid on different nodes are distinct. Verify that Longhorn manager is no longer spammed by the error messages.
   

https://user-images.githubusercontent.com/22139961/104078731-743cf280-51d4-11eb-9b43-cc601d5149bf.mov


4. Make sure all workloads working ok. data is ok. Then delete failed replicas. 
   

https://user-images.githubusercontent.com/22139961/104078698-4d7ebc00-51d4-11eb-8792-e9066bd30a65.mov


5.  Change the `Replica Replenishment Wait Interval` setting in Longhorn UI to `600` which is the default value. 

**What if things went wrong?**
1. If there is a volume that cannot recover. Scale down the workload. Delete the volume. restore the volume from backups. Scale up the workload.

**Comment by teknologista** [comment]
Thanks @PhanLe1010 .

Sorry for the late reply but as we have to do this on 8 out of 22 nodes we had postponed the task.

We will do it this weekend and report back here on the outcome.

**Comment by teknologista** [comment]
An update to let you know all went well @PhanLe1010 !

Many thanks for the great support!
