### ISSUE TITLE
[Question] - Is it possible to export the longhorn configuration using Velero/Restic ? 

### ISSUE THREAD

**Issue by Raboldar** [longhorn/longhorn#2134]
**Question**
Hy ! 
I did a cluster export using Velero/Restic, Lognhorn got deployed without issues, the storage classes and volumes were created, the only problem is the configuration of Longhorn and the Nodes. All the settings that I had defined rolled back to defaults. All disk configurations for each node have been lost (had 3 disks per node, now I have only one that goes to the default storage /var/longhorn ).
I would love to know if there's a way to export the Longhorn config 
**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: v1.19.3
 - Node config
   - OS type and version : Dedian 10 Buster
   - CPU per node: x
   - Memory per node: x
   - Disk type: HDD
   - Network bandwidth and latency between the nodes: x
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**
If you need any aditional information don't hesitate :) . 
Thanks a lot for any advice or tips!!

**Comment by shuo-wu** [comment]
1. All Longhorn node & disk info, as well as other settings, are stored in the Longhorn CRs(Custom Resources). If Velero and Restic would back up and restore the whole ETCD, the CRs and the underlying CRDs(Custom Resource Definitions) of other applications would be backed up and restored. Since I am not familiar with Velero And Restic, I cannot tell what & how Velero/Restic apply the restore, and if they work for Longhorn.
2. If you are looking for Cluster snapshot & restore. Rancher would help. If you are looking for workload volume snapshot/backup/restore, Longhorn already provides these functionalities.
3. BTW, Longhorn is designed for SSD/NVMe. You can encounter some volume/replica crash errors if you try to use HDD.

**Comment by Raboldar** [comment]
Hy ! Thanks for the reply,
I will take a look at why it didn't include the Longhorn CR and maybe ask in the Velero Forum aswell.
Would have loved to use directly Rancher for the backups (mostly to transfer a cluster from prod to dev etc..) but we don't use rke.
The security is an important part for us so we are using containerd with kata-conainer. I would be great to have options for rke other than the docker in docker one.
I will update any findings about the Longhorn CR !

**Comment by shuo-wu** [comment]
I used Velero to backup & restore some Longhorn resources in https://github.com/longhorn/longhorn/issues/3166#issuecomment-953804773 and it worked. 
I think this method can be applied to the configuration-related resource as well. e.g.,
```
~ velero backup create longhorn-config --include-resources settings.longhorn.io,nodes.longhorn.io
~ velero velero restore create --from-backup longhorn-config
```

**Comment by EugenMayer** [comment]
Velero really does add a great piece to the puzzle to be even able to recover from a disaster with longhorn.

The main point is here, Velero should not be used to backup PVC/PV at all, or Longhorns backup-tools cannot do there magic.
The statement above is not precise, Velero should not backup PVC of PVs of longhorn, nor PVs of Longhorn - but there is no good way to exclude a partial list here without going with very fragile label selectors during includin-selector.

When doing an entire disaster recovery, one would

- spawn RKE server/agents via IaaS via terraform/alike (and install RKE via Cloud-Init or Chef/Ansible)
- install Velero on the cluster attaching to your backup S3
- Restore the backup of velero from S3 - everything except PVC/PVs are restored
  Now everything starts that is core like longhorn, local-path and things. Every 'app' is still on pending due to missing PVCs
- now you can bulk-select your Longhorn backups, use 'Create disaster recover volume' (for all backups at once). Wait until they are dettached
- Now select them all under 'volume' and use 'Creat PV/PVS' as patch, select 'use old PVC' as checkbox

That's it. Wait a couple of minutes and your entire cluster comes back online.

Of course, like for us, that last step is using e.g. crunchydata to restore the PG-Cluster data from s3 too, which is nothing then a one-liner. Since PG-leader/follower have been using local-host as storage, they would be blank otherwise. After that, every bit of data is back in the cluster.

Considering how important the ETCD based restore of pods with the old PVC claim is for longhorns own backup concept of restoring that old PVCs, i would love to see that promoted a lot more. I think Velera and Longhorn can go together very well, extremely well - but neither of those 2 goes really well alone for disaster recoveries.

I think it would help Longhorn to include Velero restore ideas and concepts - to make Longhors USP (backups) really shine even more!

**Comment by shuo-wu** [comment]
The doc for this question is already handled in https://github.com/longhorn/longhorn/issues/3367.
