### ISSUE TITLE
change row size of volumes page in web ui [FEATURE]

### ISSUE THREAD

**Issue by amir-hg** [longhorn/longhorn#2142]
**Is your feature request related to a problem? Please describe.**
The problem is i want to see all volumes ( or backups) in one page (in the web ui)
right now the default size is 10 and it is sooo little for me that i have many volumes and backup
i need to see all of them in one page and even sort them 

**Describe the solution you'd like**
I think there should be field in settings that can be configurable.

thanks for your great product 
best wishes

**Comment by khushboo-rancher** [comment]
Verified with the Longhorn-UI  `image: wangsiye/longhorn-ui:fdfce44`

The design is as follows
1. The node/volume/backup page will have the option to change the page number at the bottom to one of the `10, 30, 50, 100` rows per page.
2. Changing rows per page in any page reflects the same rows in all the page.

<img width="1535" alt="Screen Shot 2021-01-08 at 11 56 48 AM" src="https://user-images.githubusercontent.com/60111667/104222596-61eece80-53f7-11eb-8668-69a5d103734d.png">

After discussing with @yasker, we concluded that
1. If possible the row per page should be customizable, user can enter any value they want instead of selecting one of the `10, 30, 50, 100`
2. The row per page should be applicable per page . For example, volumes might have 20 but node can have 10.

@smallteeths Can you please have a look on the design change and make necessary changes?

**Comment by yasker** [comment]
@smallteeths @khushboo-rancher any update on this one?

**Comment by smallteeths** [comment]
I don't think it's necessary to let users change the number of pages at will. Replacing with  `input` can also lead to Misoperation. Because as soon as the input changes it will trigger a change in the page number.
The second point I agree with.  @khushboo-rancher @yasker

**Comment by yasker** [comment]
It's hard to say for sure if a customized row number is needed or not. We can use the current version for now. If there are users who want to customize it, we can add an enhancement later.

**Comment by joshimoo** [comment]
@smallteeths @yasker I am assuming we don't do pagination on the backend, do we even need a limited page size at all? instead of just showing all volumes?

**Comment by yasker** [comment]
@joshimoo The API supports pagination in theory, but it's unused at the moment. E.g. https://github.com/longhorn/longhorn-manager/blob/master/client/generated_volume.go#L161

**Comment by khushboo-rancher** [comment]
Created https://github.com/longhorn/longhorn/issues/2183 to track the API support for pagination.

With the Longhorn UI image: `wangsiye/longhorn-ui:7e36922`, modification of rows per pages to `10, 30, 50, 100` is working fine.

**Comment by khushboo-rancher** [comment]
Validated with Longhorn master `01/15/2021`

Validation - **Pass**

The number of rows on the page can be change to `10, 30, 50, 100` .
<img width="1760" alt="Screen Shot 2021-01-15 at 11 14 54 AM" src="https://user-images.githubusercontent.com/60111667/104768803-19028700-5723-11eb-985b-0534ced444be.png">
