### ISSUE TITLE
[Question] Chart helm installation from rancher dashboard

### ISSUE THREAD

**Issue by Angelinsky7** [longhorn/longhorn#2150]
I would like to know where is the official helm repo to use to install longhorn.

the default charts repo from rancher is `https://git.rancher.io/charts` (for my default installation) and currently has `longhorn:1.0.201` but i've seen that on `https://github.com/rancher/charts` the current version is  `longhorn:1.1.0` which is the last correct version. (that i would like to upgrade to)

I would prefere to have only one official helm repo but it's hard to understand which is the correct one.
Could you give some clarification on which one is the better to use and why.
(i imagine that swiching from one helm repo to another is not possible too :-) )

Thanks for your support and help !

**Comment by PhanLe1010** [comment]
@Angelinsky7 

I believe that you are using Rancher with  `Cluster Explorer` UI  to install Longhorn. Is it correct? If so, the default repo `https://git.rancher.io/charts` on the `main` branch is the correct one. You should use this default one because it is fully tested with Rancher  `Cluster Explorer` UI. 

The `Cluster Explorer` UI tracks the `main` branch of `https://git.rancher.io/charts` so it currently has Longhorn v1.0.201. Rancher is going to update the `main` branch of `https://git.rancher.io/charts` soon so you will have Longhorn v1.0.201 in `Cluster Explorer` UI. 


If you just use Helm to install and manage Longhorn. `https://github.com/longhorn/charts` is the official Longhorn chart repo. It currently has the latest Longhorn v1.1.0

**Comment by Angelinsky7** [comment]
@PhanLe1010 thanks for your answer.
Yes i use the Cluster Explorer (i don't really have a choice there, don't i...) and so i will wait for the v.1.1.0 to be updated by the rancher team.
