### ISSUE TITLE
[FEATURE] Allow use of existing private registry secret

### ISSUE THREAD

**Issue by pulberg** [longhorn/longhorn#2157]
**Is your feature request related to a problem? Please describe.**
When using a private registry, the installation requires the private registry user/pass to be entered and the name of the secret that will be created.  I already have a cluster-wide (all namespaces) private registry secret, it doesn't make sense to have to create a new one for the Longhorn installation.

**Describe the solution you'd like**
The installation will let me enter the name of the existing private registry secret to use.

**Comment by PhanLe1010** [comment]
Sure! That makes sense.

**Comment by kaxing** [comment]
Validation - **PASSED**

This was first validated within v1.2.0 release test cycle: https://github.com/longhorn/longhorn/issues/2432#issuecomment-957551309

**Comment by kaxing** [comment]
This was validated within v1.2.0 release test cycle: https://github.com/longhorn/longhorn/issues/2432#issuecomment-957551309

But the current function says it will auto-generate new secret rather giving an option as requested in the original description. cc @innobead 
![image](https://user-images.githubusercontent.com/602540/161934858-f546c913-4272-4880-80eb-783abe6ae726.png)

**Comment by innobead** [comment]
Yeah we need to update the description.

**Comment by innobead** [comment]
> This was validated within v1.2.0 release test cycle: https://github.com/longhorn/longhorn/issues/2432#issuecomment-957551309
> 
> 
> 
> But the current function says it will auto-generate new secret rather giving an option as requested in the original description. cc @innobead 
> 
> ![image](https://user-images.githubusercontent.com/602540/161934858-f546c913-4272-4880-80eb-783abe6ae726.png)

@kaxing u should verify on 1.3.0 instead of 1.2.x. I would suggest to wait to test until we have rc1 chart.

**Comment by yangchiu** [comment]
verified passed on master-head by importing repo: longhorn/longhorn/chart master-head into rancher (using https://github.com/yangchiu/rancher-charts/tree/longhorn-v1.3.0) and try to install the imported latest longhorn.

https://github.com/longhorn/longhorn/pull/3954 is needed since there's some incorrect indent and missing double-quote on the original master-head cause the questions unable to be displayed while the installation.

with https://github.com/longhorn/longhorn/pull/3954, the "using existing private registry secret" options displays and functions as expected.
