### ISSUE TITLE
[BUG] Postgres crashed, recovery unsuccessful

### ISSUE THREAD

**Issue by virus2016** [longhorn/longhorn#2160]
Hi @yasker!

I have an issue with Postgres and a the volume attached via longhorn. I noticed in rancher it has this random error:

`RunContainerError: failed to start container "35a3f58a67abfd9d8c1257595e8bb15cfa6caecf58fa295d32f5f0fd72e6bc72": Error response from daemon: error while creating mount source path '/var/lib/kubelet/pods/f33fd55b-b842-4ee4-aaa3-1d286d2e37ef/volumes/kubernetes.io~csi/pvc-0adbb315-cbe0-436f-9e16-c1e8554bb987/mount': mkdir /var/lib/kubelet/pods/f33fd55b-b842-4ee4-aaa3-1d286d2e37ef/volumes/kubernetes.io~csi/pvc-0adbb315-cbe0-436f-9e16-c1e8554bb987/mount: file exists
`

I'm not sure how to create the bug as it is completely random when it happens. Never at the same time, just randomly. 

I have attached the bundle here: [longhorn-support-bundle_4cf5d64d-8e6b-4d04-bae6-1d32852aa6ee_2021-01-08T02-43-05Z.zip](https://github.com/longhorn/longhorn/files/5784938/longhorn-support-bundle_4cf5d64d-8e6b-4d04-bae6-1d32852aa6ee_2021-01-08T02-43-05Z.zip)

I did have 'best-effort' on so have turned it off to see if that is related to the issue. 

Many thanks,

**Comment by joshimoo** [comment]
@virus2016 thank you for the support bundle, it looks like your system ran out of resources, particularly threads 
(pthread_create failed: Resource temporarily unavailable)

There are also some io errors and a high number of snapshot syncs, the tread exhausting could potentially be caused by longhorn leaking go routines, but also any other activity on the node. Can you attach a dmesg of the two nodes in your cluster?

Generally looks like your cluster might be taxed, can you specify the environment you are running in.
CPU, Memory, disk, network

**Comment by virus2016** [comment]
@joshimoo Thank you for coming back to me so quickly! 

Where do you want me to run the dmesg? On the pod or on the node? We use digitalocean kubernetes management so I can't see how to login the nodes directly. 

We were only using 2x 4vcpu 8gb 160gb running kubernetes 1.19.3-do.0. I've added another couple of nodes to see how that goes.

Do you think limits of cpu and memory should be set for all pods?

**Comment by joshimoo** [comment]
@virus2016 if your host distro does not prevent access to the dmesg, you can run it inside of a pod.
Here is more information about this: https://stackoverflow.com/questions/41171349/why-is-a-shell-within-a-docker-container-showing-dmesg-content-from-the-host

The important thing is to find out what is consuming all your threads, you can try the below suggestions to monitor thread count on your host, we have never encountered this issue in our environments so far.
https://stackoverflow.com/questions/268680/how-can-i-monitor-the-thread-count-of-a-process-on-linux
https://unix.stackexchange.com/questions/515496/pthread-create-resource-temporarily-unavailable-when-running-multiple-docker
https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel

Please let us know if you find that longhorn's go process is responsible for the excessive thread creation, since this would imply that we are leaking go routines which we would want to investigate further.

**Comment by joshimoo** [comment]
Since I haven't heard anything back, I am closing this issue.
Feel free to reopen if this is still a problem.
