### ISSUE TITLE
[Question] What do you suggest for storages that used by kafka

### ISSUE THREAD

**Issue by amir-hg** [longhorn/longhorn#2165]
**Question**
Hi
I have a system that stores temporary files on storages (kafka) and i could verify that in file system at max is around 500MB
I have 2GB storage in longhorn.
The problem is the actual size is around 4GB. I see that 2GB is the generated system snapshot and marked for removing (but still there even after i create new snapshot)

I did read about actual size ans block storage in documents but still i have problem when volume full filled and crashes
What should i do for a such system?
Did i miss any configuration that i should do?

**Comment by PhanLe1010** [comment]
Hi @amir-hg 

The size of the filesystem reflects the space occupied by existing files. The actual size of the Longhorn block device reflects the space occupied by all blocks that were ever written to the Longhorn volume. For example, you create a filesystem on top of a Longhorn block device. you create 2 files in the filesystem: file1 of size 0.5GM, and file2 of size 1.5GB. Now the size of the filesystem and the actual size of the Longhorn block device are both 2GB. Now, you delete file2 from the filesystem. The size of the filesystem goes down to 0.5GB but the actual size of the Longhorn block device remains as 2GB.

In Longhorn, it is possible that the actual size of the Longhorn volume is bigger than the volume's capacity. This happens when the volume has a lot of snapshots as you already noticed. There are 2 types of snapshots: system-generated and user-created. To delete system generated snapshots you can delete a snapshot in Longhorn UI, it will trigger deletion for system-generated snapshots. For user-created snapshot, we can delete it in Longhorn UI.

**Comment by joshimoo** [comment]
We scheduled a task to write a KB article on this #2148
If you have additional questions feel free to reopen or file a new issue.
