### ISSUE TITLE
[BUG] Problems with volumes after changing storage class affinity settings

### ISSUE THREAD

**Issue by tabnul** [longhorn/longhorn#2179]
**Describe the bug**
Last night, 02:00 all the sudden 50% of my volumes went to the ' failed ' state.
Nothing is scheduled at that moment, strangely.
This has been an indirect result of changing the node and disk affinity in the storage classes. (recreated the storage classes) without touching the volumes.
Note: storage class was changed a few days ago! No clue why this night the volumes went failed!

**To Reproduce**
This is what happened;
- volumes were created using no disk or storage affinity in their storage class
- storage classes were recreated to include node and disk affinity - a few days ago!
- all the sudden at 02:00 volumes started failing

I fixed the volumes by setting their node affinity through editing the storage
`kubectl -n longhorn-system edit volumes.longhorn.io <Volume Name>
`
Afterwards some reboots and detaches were done to fix it.

Strangely, the volumes had a variety of disk and node affinity syntax in their config. I think this is somehow related;
**Value 1:**
```
  nodeSelector: null
  diskSelector: null
```

**Value 2:** 
```
  nodeSelector: []
  diskSelector: []
```

Now correct and working values;
```
  nodeSelector:
  - normal
  diskSelector:
  - ssd
```

**Expected behavior**
The volumes to remain unaffected when a storage class changes. 
Or to add an option to apply changes in storage class to underlying volumes.

**Log**
Manager was throwing errors like;
`no node name provided to check node down or deleted
`
**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster 4
 - Node config
   - OS type and version: ubuntu 1804 lts
   - CPU per node: 4
   - Memory per node: 4gb
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1gbit/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox, write cache disabled

**Additional context**

https://github.com/longhorn/longhorn/issues/2169

**Comment by joshimoo** [comment]
@tabnul Can you attach a support bundle or submit one with reference to this issue to `longhorn-support-bundle@rancher.com`

**Comment by tabnul** [comment]
> @tabnul Can you attach a support bundle or submit one with reference to this issue to `longhorn-support-bundle@rancher.com`

Just sent it via mail.

**Comment by shuo-wu** [comment]
1. The volumes suddenly failing at 02:00 maybe not related to the storageclass change. Instead, it seems to be caused by the node down/disconnection.
```
2021-01-13T01:01:22.725539100Z time="2021-01-13T01:01:22Z" level=warning msg="The related node k8s2slave2 of instance pvc-29622d4a-42d1-4acf-bed6-734d4d975908-e-3bc92ca1 is down or deleted, will mark the instance as state UNKNOWN"

2021-01-13T01:01:23.526652901Z time="2021-01-13T01:01:23Z" level=warning msg="The related node k8s2slave2 of instance pvc-19bcb1c6-f55c-474d-9518-e7e1d84b525b-e-d1195e61 is down or deleted, will mark the instance as state UNKNOWN"
```
2. I am not sure why the volume selector somehow becomes weird? Do you mean the new volumes created by the modified storageclass, or the existing volume? If you mean the new volumes, then you need to check if the modification on the storageclass is valid or not.
3. When you use `kubectl -n longhorn-system edit volumes.longhorn.io <Volume Name>` to update the selectors for volumes, there is no way to Longhorn to validate the format/value hence you need to take care of it by yourself. The correct format is like:
```
  diskSelector: []
  nodeSelector:
  - tag1
```

**Comment by tabnul** [comment]
> 1. The volumes suddenly failing at 02:00 maybe not related to the storageclass change. Instead, it seems to be caused by the node down/disconnection.
> 
> ```
> 2021-01-13T01:01:22.725539100Z time="2021-01-13T01:01:22Z" level=warning msg="The related node k8s2slave2 of instance pvc-29622d4a-42d1-4acf-bed6-734d4d975908-e-3bc92ca1 is down or deleted, will mark the instance as state UNKNOWN"
> 
> 2021-01-13T01:01:23.526652901Z time="2021-01-13T01:01:23Z" level=warning msg="The related node k8s2slave2 of instance pvc-19bcb1c6-f55c-474d-9518-e7e1d84b525b-e-d1195e61 is down or deleted, will mark the instance as state UNKNOWN"
> ```
> 
> 1. I am not sure why the volume selector somehow becomes weird? Do you mean the new volumes created by the modified storageclass, or the existing volume? If you mean the new volumes, then you need to check if the modification on the storageclass is valid or not.
> 2. When you use `kubectl -n longhorn-system edit volumes.longhorn.io <Volume Name>` to update the selectors for volumes, there is no way to Longhorn to validate the format/value hence you need to take care of it by yourself. The correct format is like:
> 
> ```
>   diskSelector: []
>   nodeSelector:
>   - tag1
> ```

Thanks for your reply.
Strange i didnt see issues on my node but maybe this triggered indeed the issue.

However, after node came back, volumes didnt go online.

The strange values (value 1 and value 2) were the existing volumes.

After editing the volumes as you describe, i was able to get them back online.

I also created new volumes using the storage class, which went allright as well.

**Comment by shuo-wu** [comment]
When a Longhorn volume is created via StorageClass, the empty selector value is `null`. But if a Longhorn volume is created via UI, the empty selector value is `[]`. Hence both value1 and value2 you mentioned above should be valid for Longhorn. I am sorry for the mistake in the previous response.

Typically, after a node comes back, the volumes attached to the node will be detached then reattached automatically. I did see volume `pvc-d0062a9f-7bb9-4e53-9b5f-c01375cad0d3` failed to schedule replicas due to `LocalReplicaSchedulingFailure`. I am not sure if it's the cause. But please make sure there is no conflict when you set selectors as well as enabling data locality.

**Comment by tabnul** [comment]
> When a Longhorn volume is created via StorageClass, the empty selector value is `null`. But if a Longhorn volume is created via UI, the empty selector value is `[]`. Hence both value1 and value2 you mentioned above should be valid for Longhorn. I am sorry for the mistake in the previous response.
> 
> Typically, after a node comes back, the volumes attached to the node will be detached then reattached automatically. I did see volume `pvc-d0062a9f-7bb9-4e53-9b5f-c01375cad0d3` failed to schedule replicas due to `LocalReplicaSchedulingFailure`. I am not sure if it's the cause. But please make sure there is no conflict when you set selectors as well as enabling data locality.

Thanks, so i drew wrong conclusions, thanks for investigating.

I still wonder why all volumes.failed, both nodes were operational , my heartbeat skipped a few times.when i saw it .

**Comment by shuo-wu** [comment]
When the node is down and not recovered, the volumes are state `unknown` rather than state `failed`. The volumes will become `failed`/`faulted` from state`unknown` only if the node is back. That's why you said `nodes were operational` when all volumes become failed.

You need to figure out when and why the node is down first. There are multiple node-down events in the log. It seems that your node encounter down/rebooted several times these days.
```
2021-01-10T15:39:38.588459000Z time="2021-01-10T15:39:38Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s2slave1\", UID:\"b02b0bb5-a049-4095-b0fd-deaec65b742c\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"34285918\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Kubernetes node k8s2slave1 not ready: NodeStatusUnknown"
```
```
2021-01-13T01:10:56.160136885Z time="2021-01-13T01:10:56Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s2slave1\", UID:\"b02b0bb5-a049-4095-b0fd-deaec65b742c\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"35388072\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Kubernetes node k8s2slave1 not ready: NodeStatusUnknown"
```
```
2021-01-10T15:34:35.362988719Z time="2021-01-10T15:34:35Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s2slave2\", UID:\"59d95071-9a0f-41ff-9998-773f042c8438\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"34282919\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Kubernetes node k8s2slave2 not ready: NodeStatusUnknown"
```
......

**Comment by tabnul** [comment]
thanks i miss information about why they failed but if it happens again i will troubleshoot.
