### ISSUE TITLE
[Question] Multiple pods, single RWO pvc

### ISSUE THREAD

**Issue by antonum** [longhorn/longhorn#2185]
**Question**

What is the expected behaviour for multiple pods, trying to mount the same ReadWriteOnce pvc? My expectation would be that one would successfully start and others would stuck either in Pending or ContainerCreating state, unable to attach the volume.

However, that's not what I'm observing.

The following would deploy a deployment with replicas=1, mounting the single ReadWriteOnce Longhorn pvc:

`kubectl apply -f https://github.com/antonum/ha-iris-k8s/raw/main/tldr.yaml`

If I change # of replicas to 4 https://github.com/antonum/ha-iris-k8s/blob/e474ac16b7a9c85fda61d1130f3d00be97898d0c/tldr.yaml#L11 unexpected things starting to happen.

Yes, I know, what I'm trying to do is wrong. No questions here. The question is about how the system is reacting to my wrongdoing.

```
kubectl get pods
NAME                    READY   STATUS              RESTARTS   AGE
iris-65dcfd9f97-527qv   0/1     CrashLoopBackOff    6          9m59s
iris-65dcfd9f97-75vld   0/1     ContainerCreating   0          9m59s
iris-65dcfd9f97-tg9gf   1/1     Running             2          9m59s
iris-65dcfd9f97-wr2wp   0/1     CrashLoopBackOff    7          9m59s
snapshot-controller-0   1/1     Running             0          6d19h
```

One iris pod is operational and behaves as expected (iris-65dcfd9f97-tg9gf).

Another one (iris-65dcfd9f97-75vld), as expected indicates the failure to attach volume:
`
  Warning  FailedMount         48s (x3 over 9m54s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[iris-external-sys], unattached volumes=[iris-external-sys cpf-merge default-token-nxkpw]: timed out waiting for the condition
`
But the other two are stuck in the cycle like this:

```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Warning  FailedScheduling        13m                  default-scheduler        persistentvolumeclaim "iris-pvc" not found
  Warning  FailedScheduling        13m                  default-scheduler        persistentvolumeclaim "iris-pvc" not found
  Warning  FailedScheduling        13m                  default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               13m                  default-scheduler        Successfully assigned default/iris-65dcfd9f97-wr2wp to aks-agentpool-29845772-vmss000001
  Normal   SuccessfulAttachVolume  13m                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-549f57d5-b498-431b-82eb-1dad59b6c376"
  Warning  Unhealthy               12m (x3 over 12m)    kubelet                  Liveness probe failed:
  Normal   Killing                 12m                  kubelet                  Container iris failed liveness probe, will be restarted
  Normal   Created                 10m (x5 over 13m)    kubelet                  Created container iris
  Normal   Started                 10m (x5 over 13m)    kubelet                  Started container iris
  Normal   Pulled                  8m2s (x7 over 13m)   kubelet                  Container image "store/intersystems/iris-community:2020.4.0.524.0" already present on machine
  Warning  BackOff                 3m3s (x38 over 11m)  kubelet                  Back-off restarting failed container

```
If I examine the log of that pod - the application successfully starts but crashes as it tries to access the volume mount.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: 1.18.10
 - Node config: Standard_DS2_v2
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AKS

**Additional context**

**Comment by joshimoo** [comment]
@antonum are you using an RWO pvc, I assume so?
And rwo volume can be used by multiple pods on the same node. 
Which nodes are your iris pods on?

By doing the above you will actually make the failover longer, since kubernetes uses an exponential backoff for the attach/detach reconciliation :)

**Comment by zrml** [comment]
@joshimoo I'm confused.
ReadWriteOnce -- the volume can be mounted as read-write by a single node
from
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

Did you mean ROX - ReadOnlyMany?

**Comment by joshimoo** [comment]
@zrml RWO allows for multiple pods on the same **node** to use a volume.
`ReadWriteOnce -- the volume can be mounted as read-write by a single **node**`

RWX/ROX allows a volume to be used by multiple **nodes**

**Comment by antonum** [comment]
Yes, it's RWO.

```
iris-65dcfd9f97-527qv   0/1     CrashLoopBackOff    24         106m    10.244.0.68   aks-agentpool-29845772-vmss000001   <none>           <none>
iris-65dcfd9f97-75vld   0/1     ContainerCreating   0          106m    <none>        aks-agentpool-29845772-vmss000002   <none>           <none>
iris-65dcfd9f97-tg9gf   1/1     Running             2          106m    10.244.0.67   aks-agentpool-29845772-vmss000001   <none>           <none>
iris-65dcfd9f97-wr2wp   0/1     CrashLoopBackOff    25         106m    10.244.0.66   aks-agentpool-29845772-vmss000001   <none>           <none>
```
The "property failing one" is indeed running on a different node. The "node vs. pod" explains the behaviour I'm seeing. I was wrongly assuming "pod" here.

Is there a way to enforce "one PVC mounted exclusively to one pod" behaviour in Longhorn?

**Comment by joshimoo** [comment]
Not on longhorn's side, but you can influence kubernetes scheduler.
https://stackoverflow.com/questions/34668887/allow-only-one-pod-of-a-type-on-a-node-in-kubernetes

By doing the above you will actually make the failover longer, since kubernetes uses an exponential backoff for the attach/detach reconciliation :)

**Comment by antonum** [comment]
Thanks @joshimoo ! - no doubt I'm doing the wrong thing here, so exponential backoff is past the point I want to be at. 

Currently, I suppose only the application level locking is preventing one pod from messing with the PVC, used by another.

The solution you suggesting restricts # of pods of a type per node but doesn't prevent one from creating multiple pods of different types, mounting the same pvc.

**Comment by joshimoo** [comment]
@antonum correct it's perfectly valid for an RWO pvc to be accessed on the same node by 2 different pods. An example use case for this is, application pod and log collector side car.

If you want to elaborate on what you are trying to do, we might be able to provide guidance on how to best accomplish your task at hand.

What I think you want to accomplish is faster failover, to get this you can manually override the default tolerations that kubernetes puts on a pod. Read this part https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions then override the 2 default taints with a lower tolerationSeconds. Also set the deletion graceperiod to a low value > 0.

```
node.kubernetes.io/unreachable
node.kubernetes.io/not-ready
```

Now on the longhorn side you can enable the below settings:
This allows us to cleanup the faulted pod which allows kubernetes to bring up a new one on a different node.
https://longhorn.io/docs/1.1.0/references/settings/#pod-deletion-policy-when-node-is-down

Set the policy to `delete-both-statefulset-and-deployment-pod` and longhorn will force delete the failed pod form the api server so kubernetes can bring up a new one.

The reason kubernetes is unable to delete this failed pod on a down node, is that `kubelet` is responsible for this deletion and since the node is down `kubelet` is no longer running. So the pod will stick around in the failed state till the node comes back.

**Comment by antonum** [comment]
@joshimoo - you already answered my original question. Observed behaviour is actually expected. 

The follow-up one is more a hypothetical made-up situation than a real problem at hand. I just need to make sure not to [accidentally] set replica count to more than one and use a unique pvc per deployment.  

Your suggestions on reducing failover time are great - I'll try them out.

Thanks again for your help and feel free to close this issue.

**Comment by balleza316** [comment]
Dear @joshimoo nice to meet you

I need to implement the follow architecture, 1 pod 2 containers 1 PVS RWO in order to use de same info allocted in the PVC for the 2 containers, 1 container write files and the other container only read the files, i have Openshift 4.13, is impossible in this moment use RWX because don't have the storage class for this PVC, is possible ti do that?

Thanks

**Comment by balleza316** [comment]
**** PVC RWO sorry
