### ISSUE TITLE
[BUG] Changing toleration to remove node after Eviction of volumes keeps the node as Down

### ISSUE THREAD

**Issue by caimez** [longhorn/longhorn#2186]
**Changing toleration to remove node after Eviction of volumes keeps the node as Down, how may I remove it ?**

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: v1.20.0
 - Node config
   - OS type and version: Ubuntu 20.10
   - CPU per node: 4
   - Memory per node: 2 to 16GB
   - Disk type: SD and HDD
   - Network bandwidth and latency between the nodes: 1GB/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**
Hi,
In order to remove a node, I descheduled, then evicted all the volumes on that node after adding a new fourth node.
I changed the toleration of the deployments and daemonsets to remove my 2GB node from longhorn.
All pods have been correctly evicted from that node, however the node stays in the UI with a Down state, and I have found nowhere, where I may delete the node in the UI.
![longhorn](https://user-images.githubusercontent.com/8994956/104764946-61906380-5768-11eb-966d-30957e183773.png)

Could you help me out to fix this issue ?

Thanks in advance

**Comment by PhanLe1010** [comment]
@caimez 

Yeah, in the current implementation, Longhorn UI doesn't allow users to delete a node. The workaround is using kubectl: `kubectl delete nodes.longhorn.io NODE_NAME -n longhorn-system`

A note for Longhorn team, we need to consider:
1. Expose the node deletion API to Longhorn UI. Need to figure out when it is safe to delete a node (i.e., Kubernetes node object doesn't exist, Longhorn manager pod is not running, ...)
2. It is a little confusing when the node is down but the `Readiness` still showing `ready` (It is because the manager pod went down so no one updates the status for instance manager CR. So the instance manager CRs on the failed node still have `running`status ). We might want to change is to `NotReady` or leave it as an empty value.

**Comment by yasker** [comment]
We need to add back the node deletion with certain conditions in the next release.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - `03/08/2021`

Validation - **Pass**

Validated below scenarios:
1. Once the node is evicted and taint was added to the node, the node shows `down` status on the Longhorn-UI and can be deleted by clicking the remove node.
<img width="1458" alt="Screen Shot 2021-03-08 at 2 13 58 PM" src="https://user-images.githubusercontent.com/60111667/110305443-b04cd200-8022-11eb-82cb-426241005296.png">

2. Deleted node can be added back after removing the taint.
3. The node with `down` status but have at least one replica is not allowed to remove from the Longhorn UI.

Logged https://github.com/longhorn/longhorn/issues/2308 to track the `Enable Scheduling` option becoming available for the `down` node.
