### ISSUE TITLE
[BUG] Secret doesn't refresh in Longhorn-manager unless longhorn-manager is restarted or access the backupstore

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2198]
**Describe the bug**
Secret doesn't refresh in Longhorn-manager unless longhorn-manager is restarted or access the backupstore

**To Reproduce**
1. Deploy Longhorn on a set up of 4 nodes cluster (1 etcd/control plane, 3 worker)
2. Set up a proxy like [Squid](https://github.com/wernight/docker-squid)
3. Create a secret without `NO_PROXY` or wrong `NO_PROXY`. e.g.
```
AWS_ACCESS_KEY_ID: <your_aws_access_key_id>
AWS_SECRET_ACCESS_KEY: <your_aws_secret_access_key>
HTTP_PROXY: <your_proxy_ip_and_port>
HTTPS_PROXY: <your_proxy_ip_and_port>
NO_PROXY: <excluded-ip-list>
```
4. Operations like attach/detach volume stop working.
5. Delete the secret or edit the secret with correct `NO_PROXY`, still user can't do operations on Longhorn volumes.

**Expected behavior**
There should be a way of update env variable in longhorn-manager automatically.

**Environment:**
 - Longhorn version: Lognhorn-master `01/19/2021`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8s v1.19.7 RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 18.04
   - CPU per node: 2 vcpus
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 5 Gi
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Digital Ocean

**Additional context**
Found this while validating the issue https://github.com/longhorn/longhorn/issues/1967

**Comment by yasker** [comment]
The secret should be automatically refreshed.

**Comment by PhanLe1010** [comment]
The `NO_PROXY` environment variable is not reset until the next time Longhorn manager access the backupstore. It causes the Longhorn system to crash if the `NO_PROXY` environment variable set to wrong value. 

We might want to consider not to set the `NO_PROXY` environment variable directly in the Longhorn manager process but in the child engine process when access backupstore

**Comment by jenting** [comment]
I tried to reproduce the Secret does not refresh by longhorn-manager with changing the value of AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY. With changing wrong values on it, taking backup with failed on an invalid credential.

The issue would be more accurate related to `NO_PROXY` setting rather than the whole secret doesn't refresh in longhorn-manager.

**Comment by jenting** [comment]
> The `NO_PROXY` environment variable is not reset until the next time Longhorn manager access the backupstore

IMO, this behavior is expected. So, should we need to continue addressing this issue?

**Comment by PhanLe1010** [comment]
@jenting Thank you for working on this issue.

I think this is still a problem. I.e., Longhorn system will crash if user set the wrong NO_PROXY for the S3 Backupstore's proxy. I think that Longhorn should only fail to access the S3 Backupstore in this case. All other features should still be able to function.

More specifically, in the current implementation,  when Longhorn access S3 Backupstore, it sets all the credential in the environment variables in its process (e.g., https://github.com/longhorn/longhorn-manager/blob/c0881e179e6a109423afaf377a899b8e21de5385/engineapi/backups.go#L48). Then the manager launches a new process (the engine process https://github.com/longhorn/longhorn-manager/blob/c0881e179e6a109423afaf377a899b8e21de5385/engineapi/backups.go#L52) to make request to the S3 Backupstore. The new child process will inherit all the credential environment of the parent process (the longhorn manager process), so it is able to authenticate with the S3 Backupstore.

However, setting the backup credential env variable directly on Longhorn manager is a problem because if `N0-PROXY` is set to a wrong value, Longhorn manager (which is the control plane of Longhorn) will not able to communicate with other Longhorn components inside the cluster. We need to consider where we can set the backup credential env variable only on the child process (the engine process) when making request to S3. If we can do that, then the wrong `N0-PROXY` value will only affect the access to S3 Backupstore, but not affect other Longhorn's functions.

**Comment by jenting** [comment]
My first idea is running a snapshot backup in Kubernetes Job. The environment variable is configured in the Job pod, it won't affect manager pods.

**Comment by yasker** [comment]
Running the backup job inside another pod still cannot solve the problem with the backup list within the manager. Sounds like we need to look into how to set the environment variable precisely for the engine process first.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn Master - `02/19/2021`

Validation - **Pass**

On editing the value of Proxy in the secret, the values are getting refreshed.
