### ISSUE TITLE
[FEATURE] Find a way to backup and restore Longhorn cluster before v1.2.0

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2228]
**Is your feature request related to a problem? Please describe.**
Before Longhorn v1.2.0 and [this feature achievement](), We need to provide a way to backup and restore the cluster using Longhorn as the storage.

**Describe the solution you'd like**
Possible Solution 1:
Use VM snapshot and restore. But this requires taking snapshots simultaneously among all worker nodes.

Possible Solution 2:
1. Do backups for all Longhorn volumes
2. Backup ETCD via Rancher
3. Destroy the Kubernetes cluster
4. Restore the cluster with the ETCD backup. After the restore, all Longhorn volumes, as well as the related pods, may be faulted.
5. Recover all Longhorn volumes
    5.1. Delete all Longhorn volumes, maybe as well as the related PVC/PV. Then restore them from the backups. (Not sure if we can skip this step if the volume data is still in the worker nodes.)
    5.2. Or directly delete and recreate the whole Longhorn system, then restore all volumes and recreate PVC/PVs.
6. Relaunch related pods.

**Comment by JSN-1** [comment]
just a side note
after etcd restore longhorn system is working fine if you make sure to restore old longhorn-disk.cfg on each of the storage nodes.

**Comment by JSN-1** [comment]
could also be very nice, if you where able restore default backup/snapshot schedule, when restoring using web ui.

**Comment by shuo-wu** [comment]
**This is a draft of the investigation only. It hasn't been verified**

## Rancher snapshot restore

This is more like a cluster snapshot rollback.

### Assumptions:
1. All or most of the data still exist in the cluster and can be directly reused before the restoration.
2. There is a backupstore holding valid and non-expired data.
3. The setting `Disable Revision Counter` is false. (It's false by default.) Otherwise, users need to check if the data among volume replicas are consistent, or directly restore volumes from backup.

### Expectation:
1. All settings and node & disk configs will be restored.
2. All volumes will be restored. And if there is a valid volume after the restore, the volume can be up without restoring data from backup. In other words, we need to avoid restoring backups if the data exists.
2. Detect the invalid or out-of-sync replicas as long as the related volume still contains a valid replica after the restore.

### Behaviors of Rancher restore
All Kubernetes related service will be stopped, cleaned up, and restarted, including CNI. This will lead to instance manager pod becoming unhealthy then restart. Then all volumes will get crash then reattached. 

### Actions after the restore
- Since all volumes will be reattached. If a Longhorn volume is used by a single pod, users need to shut down then recreate it. For deployments or statefulsets, Longhorn will automatically kill then restart the related pods.

- Users need to check the Longhorn volumes if the following happens in the volumes after the snapshot and before the cluster restoration:
  1. Unchaged: Users don't need to do anything.
  2. Volume creation: users need to manually launching [a single replica volume](https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/export-from-replica/) for the data recovery. Or directly restoring a new volume while cleaning up the data content.
  3. Volume Deletion: Since the data is cleaned up when the volume is removed (after the snapshot and before the restore), the restored volume is actually invalid. Users need to re-delete it.
  4. Some operations are applied for a volume:
    1. Data modifications: Longhorn will automatically fail the replicas don't contain the latest data based on the revision counter.
    2. Volume operations:
      1. Backup: The backup info of the volume should be resynced automatically.
      2. Snapshot: The snapshot info of the volume should be resynced with engine process after attachment.
      3. Replica count update: Similar to volume creation and volume deletion after the snapshot.
      4. Engine image upgrade: May need to redo the upgrade.
      5. Expansion: TBD

- For DR volumes, Longhorn should redo the full restoration after the auto reattachment.

**Comment by JSN-1** [comment]
Here is my way to restore cluster, hope this helps.

### k8s cluster recovery using longhorn

+ on all worker nodes restore longhorn-disk.cfg from backup
scp /backup/workers/node01/longhorn-disk.cfg workernode01:/var/lib/longhorn/
scp /backup/workers/node02/longhorn-disk.cfg workernode01:/var/lib/longhorn/
scp /backup/workers/node03/longhorn-disk.cfg workernode01:/var/lib/longhorn/

#### On all master nodes (at the same time, or as close as possible)
+ Restore etcd snapshot

#### On master node 01
+ Wait for all pods to recreate / recover before continuing...  
*note: ok to continue if pods using pvs does not recreate / recover*  
+ Scale down your deployments using PVCs to zero  
```kubectl scale deployment <deployment> --replicas=0 -n <namespace>```  
*note: Wait for pods to scale down before continuing...*  
+ Delete your PVCs (as they will be empty)  
```kubectl delete pvc <pvc-name> -n <namespace>```
+ Verify PVs and PVCs are deleted  
```kubectl get pv; kubectl get pvc -A```

#### Restore PVCs using Longhorn web ui.  

+ Open **Dashboard** -> **Backup**
+ Select pvc to recover and click **Create Disaster Recovery Volume**
+ Make sure to select correct Access Mode: **ReadWriteOnce** or **ReadWriteMany**, Click OK.
+ Goto -> **Volume** in top bar and select name to recover
+ under **Operation** click **Activate Disaster recovery volume**
+ Frontend: **Block Device** (default)
+ Click **OK**
+ Wait for volume to be **Detached**
+ select volume again and under **Operation** click **Create PV/PVC**
+ Enable both **Create PVC [v]** and **Use Previous PVC [v]**
+ Select correct filesystem **EXT4** or **XFS**
+ Click **OK**  
+ Wait for PVC to be **bound**...

#### On master node 01
+ Verify PVs and PVCs are deleted is created  
```kubectl get pv; kubectl get pvc -A```  
+ Scale up your deployment again  
```kubectl scale deployment <deployment> --replicas=<number> -n <namespace>```  
+ Verify pods are up and running  
```kubectl get all -n <namespace>```

#### Back in Longhorn web ui add schedule again
+ Open **Dashboard** -> Volume
+ under **Operation** click **add schedule** and type in your schedule for snapshot / backup manually (because it's not added when created from Longhorn)
+ Click **OK**

**Comment by shuo-wu** [comment]
@JSN-1 Thank you for the sharing! In your case, you are restoring the Longhorn system to a new cluster that doesn't contain any data. This is a different scenario that we are investigating. Hence, it's a great complement!

BTW, I think the prerequisite of your method is that the nodes (naming and count number) of the new cluster should be the same as that of the old cluster.

**Comment by shuo-wu** [comment]
> 2 things i would like to remove if possible.
> 
> * the need for having to restore longhorn-disk.cfg.
> * the need for having to add back default schedule when pvs are created using web ui.

Yeah. Storing the recurring job info in backups is already in planning. 

As for the disk config file restoring, if you can clean up then recreate disks for all Longhorn nodes after the cluster restore, this step is not required. Here is the reason for restoring the disk config files: when the Longhorn node objects that contain the previous disk info are restored once Longhorn is up, Longhorn then considers it keeps using those disks. If Longhorn suddenly cannot find the config or metafile or there is a mismatching, Longhorn will consider something is wrong with the node (e.g., mount error).

**Comment by meldafrawi** [comment]
Validation: **Partially failed**

- Test Case 1:  **PASSED**
Steps: https://longhorn.github.io/longhorn-tests/manual/pre-release/cluster-restore/
- Test Case 2:  **PASSED**
Steps: https://longhorn.github.io/longhorn-tests/manual/pre-release/cluster-restore/node-creation-deletion-with-restore/

- Test Case 3:  **Failed**
Steps: https://longhorn.github.io/longhorn-tests/manual/pre-release/cluster-restore/recover-volumes-after-restore/

Failed at step 6 (validation):
1. For Volume C & D:
> **New replicas is removed, and old replicas is restored but not shown in UI.**
> **Scaling down the statefulset and then scaling it back up, will result the following error**
```
Warning  FailedAttachVolume  111s       attachdetach-controller  Multi-Attach error for volume "pvc-010883fc-596d-44ef-986c-37b0384ebddc" Volume is already exclusively attached to one node and can't be attached to another
```

2. For Volume C, D, E:
> **Scaling down the workload, will not be reflected on UI, but pods will be shown to be deleted using `kubectl`**
