### ISSUE TITLE
[IMPROVEMENT] Add a new settings that allows Longhorn to evict replicas automatically when a node is drained

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2238]
**Is your feature request related to a problem? Please describe.**
See the title

**Additional context**
Derived from https://github.com/longhorn/longhorn/issues/2235

**Comment by innobead** [comment]
remove stale due to the incorrect exempt label

**Comment by rahul3002** [comment]
i would like to contribute on this issue

**Comment by shuo-wu** [comment]
This feature is related to the manager repo only: https://github.com/longhorn/longhorn-manager

There are 2 parts you can refer to before starting:
1. Pick up a random setting and see how other guys add a setting: https://github.com/longhorn/longhorn-manager/blob/master/types/setting.go
2. Check how Longhorn controllers handle replicas when receiving eviction requests: https://github.com/longhorn/longhorn-manager/blob/a0ce2d22899f0d3a0831ca4c032383ecc6691121/controller/replica_controller.go#L342

If you need any help, feel free to contact us.

Again, thank you for your contribution!

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by weizhe0422** [comment]
Just for notes: 
 - Replica eviction ticket & PR: https://github.com/longhorn/longhorn/issues/298

**Comment by weizhe0422** [comment]
I've read the context of this question and tried to prepare the LEP, there is a short version and wanted to ask if there was any misunderstanding.

 - Main purpose
   - Auto evict the replica on the deleted node to another schedulable node to rebuilding
 - What I need to do are
   - Having a new setting: `automatically-evict-replica-when-node-drained`
   - In node contoller reconcile, if the setting is `true`, then
     - Checks to see if any nodes are drained (Node-Status=`UnSchedulable`), and if so, sets `node.Spec.EvictionRequested` to `true` to let replicas coordinate to trigger replica eviction.
 - Remark
   - Replica eviction from the node (LEP: [Replica Eviction Support for Disks and Nodes](https://github.com/longhorn/longhorn/blob/master/enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md))
     - If the volume is detached, it is attached first and then detached after replica eviction is complete.
     - Steps:
       - `rc.UpdateReplicaEvictionStatus(replica)` in replica reconcile ([code](https://github.com/longhorn/longhorn-manager/blob/bbd16cd33eb32c9cfe51c296ac72d9d12e297f44/controller/replica_controller.go#L344)): Check if the replica of node has eviction request (`node.Spec.EvictionRequested` is `true`), and if so, mark `replica.Status.EvictionRequested` as `true`
       - `EvictReplicas()` of `ReconcileEngineReplicaState()` in VolumeContoller: count the volume replica count and replensh replias ([code](https://github.com/longhorn/longhorn-manager/blob/bbd16cd33eb32c9cfe51c296ac72d9d12e297f44/controller/volume_controller.go#L492))
   - Wait to check
     - How to exactly check the node is drained not cordoned.

**Comment by ejweber** [comment]
Following along with @weizhe0422's comment, I think it is impossible for us to know if a node is being drained. Drain is an active operation undertaken by kubectl, which attempts to use the eviction API to delete pods and a NoSchedule taint to ensure they don't end up back on the same node. Its repeated attempts to use the eviction API do not result in any retrievalbe information being stored in etcd. We can easily detect the NoSchedule taint (and already do for related behaviors), but we cannot detect attempts to evict pods.

So the real question is, do we want an `automatically-evict-replica-when-node-unschedulable` setting? We can call it `automatically-evict-replica-when-node-drained` if we want, but that name won't be quite accurate.

- When enabled, we would immediately evict all replicas as soon as we detected the NoSchedule taint. This might be annoying to users if they are only temporarily disabling scheduling (maybe to try to force some workload to a different node) and not actually draining, but it would meet the stated goal.
- We should probably default to disabled, since enabled could cause a lot of pointless rebuilding for unexpecting users.
- When disabled, we would maintain our current behavior.

Critically, the user can already force this eviction by disabling scheduling on a node or a disk, but the original requester wanted this behavior to be more tightly integrated with kubectl.

@shuo-wu @innobead, does the feature as described still sound worthwhile? If so, I will get to work implementing it.

**Comment by ejweber** [comment]
After discussing with @PhanLe1010 offline, one major issue with the current implementation is that many/most users are upgrading Longhorn using the [system upgrade controller](https://github.com/rancher/system-upgrade-controller) (e.g. anyone managing k3s or RKE2 clusters through Rancher). There is no way for automated cluster upgrades undertaken with this approach to interact with the node.longhorn.io CRD to request an eviction. It turns out that the system-upgrade-controller labels nodes it is attempting to upgrade. I need to do more digging to figure out exactly what label can be expected here in all situations, but RKE2 uses the label `plan.upgrade.cattle.io/system-agent-upgrader = <some_hash>`.

The following strategy might meet our needs:

Introduce a slightly modified setting:

```
automatically-evict-replicas-from-nodes-when-cordoned
-> true
-> false (default)
```

Also introduce an additional setting:

```
automatic-eviction-node-selector
-> Defaults to:
     - matchExpressions:
	     key: plan.upgrade.cattle.io/system-agent-upgrader
	     operator: exists
     - ...
-> Set to a custom value.
-> Set to "" to enable behavior for all nodes.
```

If the user sets `automatically-evict-replicas-from-nodes-when-cordoned = true`, the behavior still only takes effect if a node is being upgraded by system-agent-upgrader. Normal cordons don't result in evictions. However, the user can replace the default node selector with one of their own (if desired) to have the behavior take effect for some cordons, or simply set it to "" to have the behavior take effect during all cordons.

**Comment by ejweber** [comment]
Sadly, the above was based on a misunderstanding about the behavior of the system upgrade controller. While it DOES label nodes as indicated, it doesn't remove these labels afterwards, so the benefit provided is minimal.

It seems if users want this auto-eviction feature, they have to be made aware that it will trigger on cordon (and not just on drain). They can modify the setting before planned maintenance and modify it back after planned maintenance to avoid unwanted rebuilding at other times.

**Comment by ejweber** [comment]
Extra doc TODO:

- [ ] Create a KB as suggested in https://github.com/longhorn/longhorn/pull/6643#discussion_r1370847717

**Comment by innobead** [comment]
@ejweber Although originally this was regarded as a new feature because there are some new options introduced, I would prefer we backport this to 1.5 and 1.4 to allow users to have more options when draining nodes by seeing this as an improvement instead. WDYT? feasible?

**Comment by innobead** [comment]
BTW, this is still under review, but it seems all codes merged. We should move it forward for QA.

**Comment by ejweber** [comment]
I am still waiting on the UI code to merge. I think QA will want to test that part of it too.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `b51760`, longhorn-ui `d916e4`) with test [steps](https://github.com/longhorn/longhorn/blob/master/enhancements/20230905-automatically-evict-replicas-while-draining.md)

- [x] Test normal behavior with `block-for-eviction`
- [x] Test normal behavior with `block-for-eviction-if-contains-last-replica`
- [x] Test unschedulable behavior with `block-for-eviction` 
- [x] Can see `AutoEvicting`(yellow) in UI nodes page when replica evicting during node drain
- In v1.5.3  there only have `status.evictionRequested` in `replicas.longhorm.io`, after upgrade to master-head,  `status.evictionRequested` appeared in all replicas.
- In v1.5.3, there are no `status.autoEvicting` in `nodes.longhon.io`, afrer upgrade to master-head, `status.autoEvicting` added to all nodes.
