### ISSUE TITLE
[FEATURE] Engine image version to be displayed in the UI for volumes

### ISSUE THREAD

**Issue by anupama2501** [longhorn/longhorn#2249]
**Is your feature request related to a problem? Please describe.**
On the longhorn UI, under the volume tabs, engine image version is shown in the volume details

**Describe the solution you'd like**
Request to add in the engine image version under the volume name as for every volume we need to go in the volume details to check the version

**Describe alternatives you've considered**
Alternatives can be to add an info button next to the name to see the image versions we have for each volume

![Screen Shot 2021-02-11 at 1 40 09 PM](https://user-images.githubusercontent.com/38144301/107702167-b1caea80-6c6e-11eb-99ae-87fc2f76595a.png)

**Comment by yasker** [comment]
We don’t show the engine version in the overview because it’s considered a minor detail. For each volume, if it’s not the default version, then a green up arrow will show up, remind the user to upgrade. Also, there are already too many items listed in the volume overview page, I don’t think it’s necessary to have the engine version listed there since except for the upgrade, they’re always the same.

Talked with @anupama2501 , we decide to close this issue.
