### ISSUE TITLE
[Question] Delete nodes in v1.10

### ISSUE THREAD

**Issue by dragon2611** [longhorn/longhorn#2267]
Is there a way to force delete nodes in v1.10?

I replaced several of my nodes in k3s (I actually only have 1 node running in a VM on a dedicated at the moment) and for whatever reason they didn't get deleted from longhorn when I deleted them from kubernetes.

**Comment by shuo-wu** [comment]
Longhorn v1.1.0 node will be removed automatically when the related Kubernetes objects are deleted from the cluster. Hence there are 2 options to delete the node from Longhorn:
1. Delete the related Kubernetes node objects in the cluster: `kubectl delete node <node name>`
2. Or directly delete the Longhorn node objects: `kubectl -n longhorn-system delete nodes.longhorn.io <node name>`

Warning: Please make sure there is no replica on the node before removing/replacing a node. Otherwise, you may encounter unexpected volume crashing/data losing/HA downgrading.
