### ISSUE TITLE
[BUG] DR volume is not getting upgraded automatically by default

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2268]
**Describe the bug**
The feature auto upgrade is not working for DR volume when it is not activated.

**To Reproduce**
1. Deploy Longhorn v1.1.0 on a K8s cluster.
2. Create a DR volume, (Don't activate it)
3. Upgrade longhorn to master and provide `Concurrent Automatic Engine Upgrade Per Node Limit`
4. The DR volume is not upgraded automatically.

**Expected behavior**
The DR volume should also get upgraded automatically.

**Log**
[longhorn-support-bundle_85893cbe-571f-4f10-911a-22ba3c7d8187_2021-02-23T11-43-12Z.zip](https://github.com/longhorn/longhorn/files/6028705/longhorn-support-bundle_85893cbe-571f-4f10-911a-22ba3c7d8187_2021-02-23T11-43-12Z.zip)

**Environment:**
 - Longhorn version: Longhorn-master `02/23/2021`
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8s v1.20.7 - RKE
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 18.04
   - CPU per node: 2 vcpus
   - Memory per node: 4
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 5 Gigabyte
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 4

**Comment by PhanLe1010** [comment]
As discussed with @khushboo-rancher , It is expected that Longhorn doesn't automatically upgrade the DR volume's engine image since doing so would require a full restoration on the DR. This behavior is documented in the manual test https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/pre-release/upgrade/auto-upgrade-engine.md

closing this issue.
