### ISSUE TITLE
[BUG] /engineUpgrade API error handling

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2289]
**Describe the bug**
 `/engineUpgrade` API allows upgrading the volume that is in degraded state 
 `/engineUpgrade` API allows live upgrading the volume when the current engine image is not ready on all replicas nodes and the attaching node.

**To Reproduce**
1. Install Longhorn v1.1.0 in the cluster of 3 worker nodes
2. Create a volume of 3 replicas and attach it to a node
3. Increase the number of replicas to 4 to make the volume degraded
4. Deploy `longhornio/longhorn-engine:v1.0.2` image
5. Using UI to upgrade engine image for the volume to `longhornio/longhorn-engine:v1.0.2`
6. Observe that the API call succeed  but the volume actually cannot finish the upgrade since we block it inside the volume controller https://github.com/longhorn/longhorn-manager/blob/71adb0123b077982a7fe306ec7f986963debf238/controller/volume_controller.go#L1578
7. Create a new volume, `vol-2`, and attach it to a `node-1`
8. Taint `node-1` with `k=v:NoSchedule`
9. Delete the pod of `longhornio/longhorn-engine:master` engine image daemonset on `node-1`
11. Using UI to upgrade engine image for the volume to `longhornio/longhorn-engine:v1.0.2`
12. Observe that the API call succeed  but the volume actually cannot finish the upgrade since we block it inside the volume controller https://github.com/longhorn/longhorn-manager/blob/1e24ad76a3d5a649ebc32e9a1ef1ec89db566458/controller/volume_controller.go#L1636

**Expected behavior**
 `/engineUpgrade` API should return an error when the input volume is in degraded state 
 `/engineUpgrade` API should return an error when the current engine image is not ready on all replicas nodes and the attaching node.

**Environment:**
 - Longhorn version: v1.1.0

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master - `05/25/2021`

Validation - **Pass**

1. The degraded volume can't be upgraded now, the API call returns 500 error and it shows below error.
<img width="799" alt="Screen Shot 2021-05-25 at 3 12 17 PM" src="https://user-images.githubusercontent.com/60111667/119575334-bfaf0200-bd6b-11eb-889e-e9a4f6a293ee.png">

2. For current engine-image not in deployed state, if upgrade is triggered the API returns 500 and shows below error.
<img width="798" alt="Screen Shot 2021-05-25 at 3 13 57 PM" src="https://user-images.githubusercontent.com/60111667/119575547-161c4080-bd6c-11eb-8f53-e2701e4e56f0.png">

@PhanLe1010 is going to rephrase the error message, minor changes.

**Comment by khushboo-rancher** [comment]
Reopening it, need it to be merged on v1.1.2 branch

**Comment by PhanLe1010** [comment]
Created PRs to fix typo and cherry-pick into branch `v1.1.2`

**Comment by khushboo-rancher** [comment]
Thanks @PhanLe1010,
Verified with image Longhorn-v1.1.2-head `05/27/2021`

Validation - **Pass**

The typo is fixed and the error messages are as below:
1. `cannot upgrade engine for volume pvc-a5786ee2-d445-4ac4-923d-c2d539e2c3df using image longhornio/longhorn-engine:v1.1.1: cannot do live upgrade for a unhealthy volume pvc-a5786ee2-d445-4ac4-923d-c2d539e2c3df`
2. `cannot upgrade engine image for volume pvc-a5786ee2-d445-4ac4-923d-c2d539e2c3df from image longhornio/longhorn-engine:v1.1.2-head to image longhornio/longhorn-engine:v1.1.1 because the volume's current engine image longhornio/longhorn-engine:v1.1.2-head is not deployed on the replicas' nodes or the node that the volume is attached to`
