### ISSUE TITLE
[QUESTION] After attaching volume in maintenance mode, the volume can't no longer be attached or detached

### ISSUE THREAD

**Issue by krisko** [longhorn/longhorn#2338]
**Describe the bug**
After attaching volume in maintenance mode, the volume can't no longer be attached or detached. I cannot see the /dev/longhorn/ device for the volume.

**To Reproduce**
1. Downscale deployment to 0 (volume will be detached), Attach volume with maintenance mode. Create snapshot. Scale deployment back to desired replica count. 
2. Error from pod: 
```
  Normal   Scheduled           3m4s                default-scheduler        Successfully assigned default/nextcloud-postgresql-0 to green
  Warning  FailedMount         61s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-jcf52 data dshm]: timed out waiting for the condition
  Warning  FailedAttachVolume  56s (x9 over 3m4s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-2f93a647-63e0-426c-8f85-ff7aaff14393" : rpc error: code = Aborted desc = The volume pvc-2f93a647-63e0-426c-8f85-ff7aaff14393 is not ready for workloads
```

**Expected behavior**
I should be able to detach and reuse the volume.

**Log**
[longhorn-support-bundle_f915b513-bf53-4eec-bc4d-e00b5fa3a200_2021-03-13T21-01-07Z.zip](https://github.com/longhorn/longhorn/files/6135573/longhorn-support-bundle_f915b513-bf53-4eec-bc4d-e00b5fa3a200_2021-03-13T21-01-07Z.zip)
You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.19.5+k3s2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: RasbianOS on RAspberry Pi4 8GB
   - CPU per node:
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes: 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by joshimoo** [comment]
@krisko after attaching in maintenance mode the volume will remain in maintenance mode, till it gets manually attached by the user. Did you try detaching the volume after finishing your maintenance?

**Comment by krisko** [comment]
After attaching in maintenance mode, I am not able to attach or detach the volume - buttons are grayed out.

![image](https://user-images.githubusercontent.com/2367953/111085887-c3c3d580-8519-11eb-8910-d442e922bf55.png)

I've noticed that not only volumes which were attached in maintenance mode have this issue. Some other volumes, like in the picture cannot be detached either.
I can see that **/dev/longhorn/pvc-19fcefc4-0646-42cc-8742-c14c5daebd73** device exists on  the node blue (from the picture). That's why gitea was able to start with this volume. On the other hand for the nextcloud volume, longhorn did not create device at all, so nextcloud pods were unable to start. I had to delete the volume and restore from backup.

**Comment by PhanLe1010** [comment]
@krisko 

A few points:
1. Why do you need to attach the volume in the maintenance mode, btw? 
1. When you attach the volume in maintenance, Longhorn will not create a block device on the host. The workload will not be able to use the volume because it is in "maintenance".  You will need to detach the volume first.
1. From the picture you sent, I notice that you might have selected multiple volumes and try to `detach` them at the same time. The `detach` button on the top will not be enabled if there exists a volume in the selected list that cannot be detached. To try detach a volume click on the `operation` on the right:
   ![111085887-c3c3d580-8519-11eb-8910-d442e922bf55](https://user-images.githubusercontent.com/22139961/111539869-a5352880-872b-11eb-9fc1-ed993d99eaf9.png)

**Comment by krisko** [comment]
@PhanLe1010 
1. I had to attach the volume in order to create backup/snapshot
2. ok, I didn't realize that there's no device when attaching in maintenance mode.
3. no, I only selected the volume in the pic. Using `operation` drop down does not help ):
![Screenshot_20210317_222427](https://user-images.githubusercontent.com/2367953/111541092-52319480-8770-11eb-9cfe-5310bdbdb935.png)
4. What I did was I scaled my deployments down to 0 in order to shutdown the DB (to prevent data loss/corruption), so I could create a backup before doing DB upgrade. (maybe not necessary, but the DB complains when it's recovered from backup taken when DB was running)

**Comment by PhanLe1010** [comment]
@krisko 

1. I see
2. __
3. Checking on it
4. I see. How does the DB complains? We are trying to have minimize the effect of snapshot action on the workload. The issue is track at https://github.com/longhorn/longhorn/issues/2187. We would like to collect data about your use case.

**Comment by PhanLe1010** [comment]
@krisko 

For point #2, I see that the volume is detached and in faulted state in the backend:
```
  status:
    ownerid: blue
    state: detached
    robustness: faulted
    currentnodeid: ""
    currentimage: longhornio/longhorn-engine:v1.1.0
    kubernetesstatus:
      pvname: pvc-19fcefc4-0646-42cc-8742-c14c5daebd73
```
Not sure why Longhorn UI still show that the volume is healthy. Can you try to refresh the UI page?

For the reason why the volume is in faulted state, it is because all 2 replicas of the volumes is in error state. For why the replicas are in faulted state. It could be because of the CPU pressure on the nodes or networking. I notice that you have 12 volumes in the cluster. With 1Gbps network, it is not enough for 12 volumes. See more about the minimum requirement at https://github.com/longhorn/longhorn/issues/1691#issuecomment-729633995

**Comment by cocampbe** [comment]
I am having a similar issue. I scaled down some deployments and statefulsets of a RWX volume. I did this to expand the volume. I attached the device to a node in mainatence mode. I then went to detach and am not able to. The device shows attached to one of the workers. But I am not sure how to detach it.

**Comment by cocampbe** [comment]
In order to detach the volume, I edited the volume via kubectl. I set the nodeID to ""  and set disableFrontend to false. For grins, I reattached the volume again in maintenance mode. And once again, I was not able to detach it. I edited the volume again and then scaled my workloads up. This has worked for me in the past.

**Comment by cocampbe** [comment]
I created a new volume and attached it in maintenance mode. I was able to detach it. It worked as expected. I am not sure why a specific volume is having this issue.

**Comment by cocampbe** [comment]
I think I may understand the issue. For one, I did not need to put a volume in maintenance mode to resize it. And the reason It cannot be detached afterwards is because there is a PVC bound. My understanding of when to use maintenance mode was not correct.

https://longhorn.io/docs/1.1.0/concepts/#22-reverting-volumes-in-maintenance-mode

**Comment by cocampbe** [comment]
@PhanLe1010 This is an interesting issue. What I cannot understand is why the detach option is grayed out. Let's say a user, like me, attaches a volume in maintenance mode on a host for reasons that don't make sense, ie, did not know what I was doing. In this instance, where the change was made based on a bad understanding of when o use maintenance mode, the user is kind of stuck. I fortunately have a decent level of understanding of kubernetes and linux. So I was able to edit the volume via kubectl to detach it. This seems like a bug IMO.

**Comment by PhanLe1010** [comment]
Thanks @cocampbe ! yeah, this is indeed a bug.

Reproduce steps:
1. Deploy Longhorn v1.1.0
2. Create a workload using a Longhorn volume in RWX mode
3. Scale down the workload to detach the volume
4. Attach the volume in mantainance mode
5. See that user cannot detach the volume using UI. Workload cannot use the volume again.

**Comment by PhanLe1010** [comment]
This is an UI bug. We block the `detach` action here At https://sourcegraph.com/github.com/longhorn/longhorn-ui/-/blob/src/routes/volume/VolumeActions.js#L167

We should modify the function [isRwxVolumeWithWorkload()](https://sourcegraph.com/github.com/longhorn/longhorn-ui/-/blob/src/routes/volume/VolumeActions.js#L136) so that it only returns true when there is a workload pod that is actually currently using the volume. I.g., there some workload in `selected.kubernetesStatus.workloadsStatus` that has `lastPodRefAt != ""`

**Comment by cocampbe** [comment]
@PhanLe1010 When you put a volume into maintenance mode, is that stored somewhere? I assumed I would see a reference to it in the volume spec, but I did not see anything.  I am not sure how much work it would take, but it seems to make sense to record that a volume is in maintenance mode and use that as a flag.

**Comment by joshimoo** [comment]
@cocampbe maintenance mode is equivalent with `spec.disabledFrontend = true`

**Comment by cocampbe** [comment]
> @cocampbe maintenance mode is equivalent with `spec.disabledFrontend = true`

Cool. Thank you.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn-master `03/27/2021`

Validation - **Pass**

Validated with RWX volume, the detach option is available to a RWX when attached to a node only and not available when attached to a pod.
Observed one regression for attach button https://github.com/longhorn/longhorn/issues/2411

**Comment by taxilian** [comment]
I'm still seeing this issue on 1.2.0, same exact symptoms -- I attached in maintenance mode after an upgrade just so I could make sure all the replicas came up, etc, before starting the pods to attach the RWX volume to. It wouldn't let me attach without maintenance mode (wish it would, so I could use as a block device, but whatever); now I can't detach it, detach is grayed out.

**Comment by khushboo-rancher** [comment]
@taxilian Which browser are you using? Do you see any error in the console of the browser?
I just tried the same with Longhorn v1.2.0 on chrome and detach button is enabled and working for RWX volumes. Only in case, the RWX volume is attached to a pod, the detach button gets greyed out.
<img width="1768" alt="Screen Shot 2021-09-07 at 3 36 17 PM" src="https://user-images.githubusercontent.com/60111667/132419402-67309e72-e56d-4072-9820-fa584a5680d5.png">
