### ISSUE TITLE
[BUG][e2e] test_running_volume_with_scheduling_failure fails

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2350]
**Describe the bug**
After replica process crashes, it takes a lot longer(~10m) for scheduling to fail.

**To Reproduce**
Run test

**Expected behavior**
Should pass

**Log**
`n/a`

**Environment:**
`n/a`

**Additional context**
`none`

**Comment by c3y1huang** [comment]
Don't think the long wait for scheduling to fail is expected. @shuo-wu @joshimoo any ideas?

**Comment by shuo-wu** [comment]
Why will replica process crash lead to scheduling failure? Can you paste the error log here?

**Comment by c3y1huang** [comment]
Could you check if the test skeleton needs to be updated?

https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_basic.py#L2310-L2312

**Comment by PhanLe1010** [comment]
Thanks @c3y1huang 

It was because of the reusing failed replica that makes Longhorn to wait for 6 minutes before attempting to create a new replica. 

@shuo-wu 
> Why will replica process crash lead to scheduling failure? Can you paste the error log here?

It is because we disable node `soft anti-affinity`, volume has 3 replicas, cluster has 3 nodes. So Longhorn cannot schedule replacement replica when a replica fails.

**Comment by khushboo-rancher** [comment]
`test_running_volume_with_scheduling_failure` has been passing for integration test run on ubuntu-amd64
