### ISSUE TITLE
[ENHANCEMENT] Longhorn UI websocket traffic is way to high

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#2372]
Currently it seems we send the whole volume information for each volume every couple of seconds via the websocket connection.
While the user is on the frontpage of the longhorn UI.
This does not scale well, 

Example the Websocket connection consumes:
5-8MB/s for 151 volumes on a 9 nodes cluster.

As one can see this leads to some heft traffic, since all of this goes via the rancher proxy this is suboptimal.

**Comment by smallteeths** [comment]
The front end may not be able to solve this problem. The front end needs to stay connected to get the latest data. And each page has an icon for the status of the ws connection.

![Jietu20210325-112101](https://user-images.githubusercontent.com/27733391/112414083-6a9b4380-8d5c-11eb-98fa-7e389858ab1c.jpg)

**Comment by c3y1huang** [comment]
Seems like a side-effect from the fix of adding timestamp in https://github.com/longhorn/longhorn/issues/648.

I've deployed 100 pvc, wait until detached, and open the dashboard page with a browser.

The observation with the current master branch code base shows continuing traffic even if there is no resource change.
![Screenshot-2021-03-31-19:17:47](https://user-images.githubusercontent.com/22583541/113148033-faad2180-9263-11eb-93de-1fbcb0a9fe5b.png)

This is after removing the timestamp.
![Screenshot-2021-03-31-20:45:43](https://user-images.githubusercontent.com/22583541/113148572-8fb01a80-9264-11eb-8ffc-021cec543019.png)

@smallteeths could you give a little background context on the reason resource list response data and websocket need to be consistent?

**Comment by smallteeths** [comment]
I'm not so sure if this problem can be modified from a front-end perspective. The volume needs to be kept up to date.  I think the reason for the high traffic is that it keeps pushing data to the front end even when there is no change in the data. I think we can push a null when there is no data change. This way ws can keep the heartbeat and the amount of data is not very large

Issue#648 The problem is that I sent an http request to longhorn and the backend returned the latest data. But the next moment the data pushed by ws is not up to date, so it causes an error on the page.

ws related code :
![Jietu20210401-093235](https://user-images.githubusercontent.com/27733391/113232252-595bb500-92cf-11eb-827a-360b437db207.jpg)

**Comment by innobead** [comment]
@c3y1huang as we discussed, probably we need to update generated Rancher client code which is based on manager API.

**Comment by khushboo-rancher** [comment]
Verified with Longhorn master - `04/07/2021`

Validation - **Pass**

The test is done with 51 volumes in a 3 nodes (worker) cluster.
The avg traffic for v1.1.0 is around 720 kbit/s
<img width="1714" alt="Screen Shot 2021-04-07 at 12 46 38 AM" src="https://user-images.githubusercontent.com/60111667/113767791-ba0a4800-973c-11eb-90b1-d867d791752d.png">
which got improved with master and avg comes around 370 kbit/s
<img width="1728" alt="Screen Shot 2021-04-07 at 12 55 12 AM" src="https://user-images.githubusercontent.com/60111667/113767943-e45c0580-973c-11eb-811d-39dc42854307.png">

@c3y1huang @joshimoo @smallteeths Could you please confirm this is the extent we can optimize it?

**Comment by c3y1huang** [comment]
The latter screenshot looks right. The fix is to ensure websocket does not push full resources data per-second interval when there is no change. Might be easier to check with browser developer tools.
![Screenshot-2021-04-07-10:38:06](https://user-images.githubusercontent.com/22583541/113802683-b357f100-978d-11eb-89c1-68d44eec711a.png)

**Comment by wpwoodjr** [comment]
We are still seeing crippling traffic when on the Longhorn pages.  This shows 11 Mbps:
![image](https://user-images.githubusercontent.com/6633152/117541344-72980580-afe1-11eb-9bcb-39badf8378d0.png)

**Comment by oxr463** [comment]
![image](https://user-images.githubusercontent.com/43783393/118038430-16b0e200-b33d-11eb-936d-50910de24573.png)
