### ISSUE TITLE
[BUG] Attach option available for an already attached RWX volume.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2411]
**Describe the bug**
Attach option available for an already attached RWX volume.
<img width="1755" alt="Screen Shot 2021-03-27 at 2 23 21 AM" src="https://user-images.githubusercontent.com/60111667/112691954-1a2efd80-8ea4-11eb-9637-f8a089021e36.png">

**To Reproduce**
1. Create a RWX volume.
2. Attach the volume to a workload.
3. Check the Longhorn UI, the attach option is available for volume.
4. Clicking it doesn't make any difference but UI sends the request to backend to attach the volume.

```
[longhorn-manager-jtrpl] time="2021-03-26T21:01:51Z" level=debug msg="No need to attach volume pvc-32ca9c71-0f79-4aec-bcc0-f7a20960047b since it's shared via nfs://10.43.188.38/pvc-32ca9c71-0f79-4aec-bcc0-f7a20960047b"
```

**Environment:**
 - Longhorn version: Longhorn -master `03/27/2021`

**Comment by smallteeths** [comment]
I'm not quite sure what our expected behavior should be. For rwx volume should we consider the case of attaching multiple nodes? Or should I disable the attach operation after attaching a node.

The difference between rwx volume and rwo volume in longhorn is that the actions in the data returned to the front end after attaching the rwx volume can still perform attach actions

![Jietu20210329-110844](https://user-images.githubusercontent.com/27733391/112782369-6e420980-907f-11eb-9853-fa438dbc7c96.jpg)

**Comment by khushboo-rancher** [comment]
I think this is because of https://github.com/longhorn/longhorn/issues/2127 may be. @joshimoo Can you check this?

**Comment by joshimoo** [comment]
I am working on always exposing the attach/detach actions as part of the action map, so we can call them irregardless of state of the volume. The backend will then do the appropriate action.

You can hide the attach/detach options unless the volume is in maintenance mode, i.e disableFrontend.
You can wait with this changes, till my volume api changes hit, since there will be changes on the attach/detach since they will now always be exposed as part of the api action map.

**Comment by innobead** [comment]
I think the issues already fixed in https://github.com/longhorn/longhorn-manager/pull/859 by @joshimoo, so I assume we don't need to do anything here, right? (@joshimoo , @smallteeths )

**Comment by joshimoo** [comment]
@smallteeths so the attach/detach options are now always exposed regardless of state and volume type. Can you make the necessary modifications on the UI, so that you rely on the volume state instead of the actions map to determine whether a volume can be attached/detached.

For RWO volumes: 
- `attach` should only be shown while they are detached
- `detach` should only be shown while they are attached

For RWX (Migratable) volumes:
- `attach` should only be shown while they are detached
- `detach` should only be shown while they are attached and only have a single controller (len(controllers) <= 1)

For RWX (non Migratable) volumes:
- `attach` should only be shown while they are detached, and only maintenance mode attachment is allowed
- `detach` should only be shown while they are attached in maintenance mode `"disableFrontend": true`

**Comment by khushboo-rancher** [comment]
Verified with Longhorn v1.1.1-rc1

Validation - **Pass**

The attach/detach button is getting enabled/disabled as per the below rules:

For RWO volumes: 
- `attach` should only be shown while they are detached
- `detach` should only be shown while they are attached

For RWX (Migratable) volumes:
- `attach` should only be shown while they are detached
- `detach` should only be shown while they are attached and only have a single controller (len(controllers) <= 1)

For RWX (non Migratable) volumes:
- `attach` should only be shown while they are detached, and only maintenance mode attachment is allowed
- `detach` should only be shown while they are attached in maintenance mode `"disableFrontend": true`
