### ISSUE TITLE
[FEATURE]  Feedback on volume salvage

### ISSUE THREAD

**Issue by TeoGoddet** [longhorn/longhorn#2428]
**Is your feature request related to a problem? Please describe.**
Longhorn UI is not verbose about volume salvaging. Users have not feedback about failure reason or anything (except if the volume change from the faulted to another state)
**Describe the solution you'd like**
- displaying a popup indicating the result of the operation
- displaying more infos in the event log

**Comment by PhanLe1010** [comment]
@TeoGoddet 

When all replicas of the volume fail unexpectedly. Longhorn automatically salvages the replicas. The `salvage` event is recorded in the volume's `event log`. You can see it inside Longhorn UI
<img width="1052" alt="Screen Shot 2021-04-05 at 3 04 21 PM" src="https://user-images.githubusercontent.com/22139961/113632588-4a069f80-9620-11eb-9961-ff51be1839bf.png">

If the Longhorn successfully `salvage` the volume, the volume will attach and running again otherwise it will be stuck in some error states.   

Does that meet your requirement?

**Comment by TeoGoddet** [comment]
Each time I had faulty replicas (I'm testing with a bad network on purpose)
Longhorn didn't salvaged them automatically and they stay in the faulted state. 

And when I click manually on the salvage button in the UI I did not see anything in the logs.  

shuo-wu made me realize in another issue that I may be experiencing this https://github.com/longhorn/longhorn/issues/2309

So I propose to close it and see if the problem is still there in 1.1.1 and reopen is needed.

**Comment by PhanLe1010** [comment]
Regarding to this comments:
> And when I click manually on the salvage button in the UI I did not see anything in the logs.

You should see the API call logs on the Longhorn manager pods. 
From the UI side, one replica should get out of the error state if the manual savage successful. And the volume should get out of `faulted` state

**Comment by PhanLe1010** [comment]
Close this issue because of lack of activity
Feel free to reopen if you feel needed
