### ISSUE TITLE
[Question] Restore from backup PVC created volume.

### ISSUE THREAD

**Issue by TeoGoddet** [longhorn/longhorn#2429]
**Question**
How can I restore a backup to an pvc/pv created volume ? 
I tried to restore the backup to a volume using the previous name option but fail because original volume still exist.
I tried to restore the backup to a volume not using the previous name option but i cannot then bind the pvc to the new volume.
I'm unusure this possible now and may switrch this to a feature request.
Thanks 
**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes version: v1.20.0
 - Node config
   - OS type and version debian 10
   - CPU per node: 2 to 4
   - Memory per node: 8GB
   - Disk type HDD
   - Network bandwidth and latency between the nodes: <1GB/s
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
Baremetal

Using RWX

**Comment by TeoGoddet** [comment]
Hi ! 
I've been able to restore a faulted pvc created volume from backup.
The process is long : 
```kubectl scale deploy -n <ns> --replicas=0 <deploy_name>```
launch restore of the backup from the ui (with a new volume name)
```kubectl delete -n <ns> pvc <pvc_name>```

recreate PVC (from UI) or 
```curl -X POST "http://longhorn.localhost:8888/v1/volumes/<new-vol-name>?action=pvcCreate" -d '{"pvName":"<new-vol-name>","fsType":"ext4"}'```

scale up again.

you may need to augment the pvc request size in you vcs because the create pvc is usually a bit bigger than the original (seems an issue related to units M vs G)

you need to manually recreate the backup schedule (see #578)

**Comment by shuo-wu** [comment]
1. Can I ask the reason why you want to restore an existing volume? Is it due to the existing volume becoming faulted? Typically, the volume replicas will be salvaged/reused automatically if the volume becomes faulted. If the auto salvage feature doesn't work, you may encounter [this bug](https://github.com/longhorn/longhorn/issues/2309). But I can do manual salvage via UI as a workaround. By resuing/salvaging the existing volumes rather than restore, you can save lots of time as well as bandwidth.
2. The PVC/PV/Longhorn volume name should be unique. Typically one PVC is bound with one PV and one Longhorn volume only. If you really want to do restoration, you need to clean up the existing volume, PV, and PVC. So that you can restore the volume with the same name then.
3. We will store the recurring config in the backups as well in the further version: https://github.com/longhorn/longhorn/issues/2227

**Comment by shuo-wu** [comment]
As for the size mismatching, can you provide the PVC and the volume info?

**Comment by TeoGoddet** [comment]
I had the use case of "revert to an old backup" also in mind, but I now have a better understanding of this and that's not the way it should be done (correct way is described here https://forums.rancher.com/t/how-do-you-launch-a-snapshot-at-longhorn/16130/4)

So the only case left is when salvage does not work, I understand that this should not be the case anymore in the future 

If all replicas are damaged, should people salvage the volume and then revert to a snapshot also in this case ?

I'm very happy that next release will fix a lot of my problems !

The size mismatching may still be an issue to be resolved, maybe in another GH issue ?
I'm unsure what infos you want but here is the recreated PVC : 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2021-04-01T17:29:31Z"
  finalizers:
  - kubernetes.io/pvc-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
        f:volumeName: {}
    manager: longhorn-manager
    operation: Update
    time: "2021-04-01T17:29:31Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/bind-completed: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-01T17:29:38Z"
  name: web-archives-data-pvc
  namespace: agepoly-test
  resourceVersion: "3855273"
  uid: 49b2f9ac-4f23-440f-8459-8399f822b01b
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 19078Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: restore-web-archives
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 19078Mi
  phase: Bound
```
and the original yaml :
``` 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-archives-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
  selector:
    matchLabels:
      owner: agepinfo
      name: data
      app: web-archives
      environment: test

```

**Comment by shuo-wu** [comment]
After salvaging the volume, you need to check if the data is available. If YES, you don't need to do anything. Otherwise, you need to do a snapshot revert or a backup restore.

`20G` means 20000000000 Bytes. Currently, Longhorn won't touch the field `storage` in `pvc.spec`. As long as the Longhorn volume size is the same as the field, the volume is correct.

**Comment by TeoGoddet** [comment]
The create pvc/pv from volume has a feature to choose to use the old pvc/pv spec for the new one, this feature may be broken as it mismatch

**Comment by shuo-wu** [comment]
In the volume PV/PVC creation feature, `Use Previous PVC` just means reusing the previous PVC name. As for other fields like size, they are generated based on the current volume and the related settings. You may need to check if there is mismatching between the original volume and the backup, or between the backup and the restored volume.
