### ISSUE TITLE
 [BUG] Mount RWX volumes doesn't work on k8s nodes supporting only NFS 4.0 - an incorrect mount option was specified

### ISSUE THREAD

**Issue by tmorin** [longhorn/longhorn#2457]
**Describe the bug**

When mounting a RWX Longhorn volume on a host handling only the NFS version 4.0, the mount fails: `mount.nfs: an incorrect mount option was specified`.

Indeed, the option `vers=4.1` is not supported by the k8s host, i.e. the **NFS client**, whereas the option `vers=4.0` is supported.
This issue might be highly related to #2438.

FYI the **NFS server** handles the following NFS versions: 3, 4.0, 4.1, 4.2 (c.f #2438)

**To Reproduce**

Mount a Longhorn volume with the mode ReadWriteMany on a host handling only NFS 4.0.
The pod should fails to load because of: `mount.nfs: an incorrect mount option was specified`.

**Expected behavior**

Longhorn should be able to mount a Longhorn volume RWX on k8s hosts handling only the NFS client 4.0.

**Log**

The log from the pod:
```
  Warning  FailedMount  32s  kubelet  MountVolume.SetUp failed for volume "pvc-f7b43c79-c77c-4a55-b604-a5853e80818a" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /bin/systemd-run
Mounting arguments: [--description=Kubernetes transient mount for /var/lib/kubelet/pods/ec8b21af-af38-4146-8449-71f5dac3adc4/volumes/kubernetes.io~csi/pvc-f7b43c79-c77c-4a55-b604-a5853e80818a/mount --scope -- /bin/mount -t nfs -o vers=4.1,noresvport,soft,sync,intr,timeo=7,retrans=3 10.43.28.79:/pvc-f7b43c79-c77c-4a55-b604-a5853e80818a /var/lib/kubelet/pods/ec8b21af-af38-4146-8449-71f5dac3adc4/volumes/kubernetes.io~csi/pvc-f7b43c79-c77c-4a55-b604-a5853e80818a/mount]
Output: Running scope as unit: run-re1d058193f9048f49724c7b582aa4a19.scope
mount.nfs: an incorrect mount option was specified
```

**Environment:**

 - Longhorn version: 1.1.0
 - Kubernetes version: v1.20.4+k3s1
 - Node config
   - Linux 4.4.213-rockchip64 SMP aarch64
   - CPU per node: 4CPU
   - Memory per node: 4Gi
   - Disk type: emmc + sdcard
   - Network bandwidth and latency between the nodes: local network
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal, 3 nodes

**Comment by joshimoo** [comment]
We do not support NFS v4.0 as a client for the RWX volumes, since v4.1 brought some much needed enhancements including performance as well as session support.
Here is some info on the differences:
- https://events.static.linuxfound.org/sites/events/files/slides/AllMar18_0.pdf
- https://www.iaps.com/nfsv4.1-new-features.html
- https://tools.ietf.org/html/rfc5661

Since nfsv4.1 has been ratified in 2010, I recommend updating your clients.

**Comment by joshimoo** [comment]
Leaving a note here, for the simplified (delete workload on share-manager failure) implementation we could get away without the improvements in v4.1 but for the HA version we definitely require at least v4.1 #2394

Therefore it doesn't make sense to enable v4 now then require v4.1 in a later longhorn update.  This would be more confusing for the users since a previously running system now does no longer work. While by requiring v4.1 immediately the user can address this concern before the system ever goes into a running state.

Also v4 is generally inferior to v4.1 and therefore v4.1 should really be the minimum version since it's available since **2010**
cc @innobead @yasker

**Comment by joshimoo** [comment]
@c3y1huang the linked issue https://github.com/longhorn/longhorn/issues/2438 is a bug in the evaluation of protocol support in the backupstore, see my comment on that issue. It's separate from this issues deliberate choice to not allow nfs v4

**Comment by tmorin** [comment]
Hi @joshimoo 
Thank for the explanations.
I'm going to see how to upgrade the client side for v4.1.
Best regards

**Comment by jedrus2000** [comment]
Maybe it will be useful for ppl finding this issue. I ran into same issue.
In my case it was missing support in kernel for NFS 4.1 and iSCSI - so check out this in your kernel config, and if true - build kernel with it.

Here is some doc about it: https://longhorn.io/docs/1.6.1/deploy/install/#installing-nfsv4-client
