### ISSUE TITLE
[QUESTION] POD can access a replicated volume that is NOT on it's node (host) ?

### ISSUE THREAD

**Issue by iangregsondev** [longhorn/longhorn#2468]
**Question**
 
Could you confirm that this sentence is correct (found in the docs) 

"Note: The recommended way of choosing the default replica count is: if you have more than three nodes for storage, use 3; otherwise use 2. Using a single replica on a single node cluster is also OK, but the HA functionality wouldn’t be available. You can still take snapshots/backups of the volume."

In my case I have 3 nodes, so assuming that the above text, means I should have this set to 2, this is kind of good news if that's the case - as it will potentially allow me to utilize more space.  Quorum is still met with 2 replicas - right?

Maybe I wasn't fully understanding longhorn - seems very powerful :-)

I thought I had to replicate a volume on every single physical worker - so that in case the POD was deployed there then the data was available on that particular node.

So my understanding right now, I assume this is correct, can you confirm?

node1 : has a replica of pvc123

node2: has a replica of the same pvc123

node3: has a POD that uses the pvc123, noting that the pvc123 does NOT have any volume replicated on node3.

So the POD on node3 that depends on the data in the PVC continues to be able to access that data? Even though the volume is NOT physically on node3?

If that's the case, I can't believe I missed that, is there somewhere in the docs that explains that in detail?

Thanks in advance.

**Environment:**
 - Longhorn version: 1.1.0

**Comment by joshimoo** [comment]
You can think of the **replica** as the `volumes-data` the more replicas the more data redundancy you have, each replica contains the full volumes data.

You can think of the **engine** as the `volumes-controller` that exposes the volume and it's responsible for processing all IO requests for the volume and dealing with the replicas.

Longhorn will always start an engine on the same node as your workload, so that your workload can interact with the volume.
The replicas can be randomly scheduled in the cluster and the engine will interact with them.

So if you have a **100 node cluster**, you can have your workload on any of the nodes, even if the replicas are only on **Nodes X,Y,Z**

Since replicas currently contain the full volume data, the amount of replicas can be arbitrarily specified. More then 3 seems overkill though.

**Comment by iangregsondev** [comment]
Great thanks @joshimoo ,

So in my case, as I only have 3 nodes - then the correct value should Replicas: 2 

Right ?

**Comment by joshimoo** [comment]
@iangregsondev depends on how much redundancy you require, see below:
- If you have 1 replica your volume will be faulted when you lose that node/disk
- If you have 2 replicas you can lose 1 of the replica nodes/disks without any impact
- If you have 3 replicas you can lose 2 of the replica nodes/disks without any impact

For important data I use 3 replicas, for data I don't care about I use 1 replica (i.e. logs for example)
Same considerations as with using a raid setup for a traditional disk.

Maybe this helps you decide between 2 or 3 replicas:
- How likely do you think that 2 nodes/disks will fail in the same time window?
- How much of an issue would be the loss of data?
- How costly would a downtime be?

For a test/homelab cluster 2 replicas is fine, since each replica contains the full volumes data, no quorum is needed.

**Comment by iangregsondev** [comment]
Thank you @joshimoo .

Yep, then 2 makes good sense for me, it is an homelab.

Closing - Thanks for all the help.
