### ISSUE TITLE
[BUG] Longhorn engine concurrent upgrade is not correct with RXW volume

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2470]
**Describe the bug**

Concurrent upgrade longhorn engine from v1.0.2 to v1.1.1-rc1. the number of longhorn engine upgrade is not the same as the Concurrent Automatic Engine Upgrade Per Node Limit value.

**To Reproduce**
1. Deploy Longhorn with v1.1.1-rc1 expects longhorn-engine v1.0.2.
2. Download the StatefulSet yaml manifest from [example](https://longhorn.io/docs/1.1.0/references/examples/#statefulset).
2.1. Change the replicas from 2 to 10.
2.2. Change accessMode from `ReadWriteOnce` to `ReadWriteMany`.
2.3. Add nodeSelector to specific node name like worker-0.
3. At Longhorn UI, set the concurrent limit to 2.
4. Watch the longhorn engine images CRD, `kubectl get lhri -n longhorn-system -w`.
5. Edit longhorn-manager DaemonSet, change longhorn-engine version to v1.1.1-rc1.
6. You could observe the reference count of longhorn engine image is not the same as the concurrent limit setting sometimes.

**Expected behavior**

The number of longhorn engine image upgrades should align with the Concurrent Automatic Engine Upgrade Per Node Limit value.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: v1.1.1-rc1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.20.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: SLES SP15
   - CPU per node: 4
   - Memory per node: 8G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 10

**Additional context**

1. I had verified the RWO volume, it works as expected.
2. If I change to value from the concurrent limit setting from 2 -> 3 -> 5, the number of longhorn engine image upgrade volumes would be 3. (I check the `concurrent-automatic-engine-upgrade-per-node-limit`, it 5)

**Comment by innobead** [comment]
cc @PhanLe1010

**Comment by PhanLe1010** [comment]
Thanks @jenting for reporting

This is expected behavior because:
1. RWX volume is an NFS exported volume that is backed by a Longhorn RWO volume
2. When the NFS server attaches the RWX volume to a node-1, the backing RWO volume could be attached to a different node (doesn't have to be node-1)
3. As a result, from the Longhorn perspective, we see 10 Longhorn volumes that are attached to different nodes. This is the reason why you see Longhorn upgrades more than  `concurrent-automatic-engine-upgrade-per-node-limit` volumes at the same time in the reproduce steps.

The goal of `concurrent-automatic-engine-upgrade-per-node-limit` setting is that we want to limit the creation of new engine processes on a node so that there aren't too many new processes are created at the same time. Since 10 volumes are actually on different nodes (even though the exported RWX volumes are on the same node), the observed behavior is ok.

**Comment by jenting** [comment]
Thank you for the explanation @PhanLe1010. Close it.
