### ISSUE TITLE
After the rancher upgrade to 2.5.7, two identical images are offered.

### ISSUE THREAD

**Issue by StefanSa** [longhorn/longhorn#2476]
hi there,
After the rancher upgrade to 2.5.7, two identical images are offered:

`rancher/longhornio-longhorn-engine:v1.1.0` and `rancher/mirrored-longhornio-longhorn-engine:v1.1.0 `

This note text is displayed with the green update arrow.
```
Curent image: v1.1.0
Engine image  v1.1.0 is now availbe !
```

An `upgrade engine` does not help here.
What is to be done here?

---
Version: `v1.1.0` on rancher `v2.5.7`

**Comment by PhanLe1010** [comment]
@StefanSa 

First, having multiple engine images in Longhorn system is fine. Don't need to be worried. 
This means that somehow Longhorn chart was upgraded with the new engine image  `rancher/mirrored-longhornio-longhorn-engine:v1.1.0`. Now because the `rancher/mirrored-longhornio-longhorn-engine:v1.1.0` and `rancher/longhornio-longhorn-engine:v1.1.0` have the same content, Longhorn will ignores the request when you do `engine upgrade` 

Secondly, can you give us some more context about how you produced the problem?
* Did you have Longhorn before upgrading Rancher? If yes, what Rancher UI did you use to install Longhorn? Is it the old Ui or the new `cluster explore` Rancher UI?
* Did you upgrade Longhorn after upgrading Rancher? If yes, which Rancher UI did you use to upgrade Longhorn?
* Can you take some screen shot of the Longhorn upgrade/installation page in Rancher?

**Comment by jenting** [comment]
Ref to https://github.com/rancher/image-mirror/pull/76

**Comment by StefanSa** [comment]
@PhanLe1010 , @jenting 
- Did you have Longhorn before upgrading Rancher? -> No
- Did you upgrade Longhorn after upgrading Rancher? -> Yes, with new `cluster explore` 
- Can you take some screen shot
![upgrade_longhorn](https://user-images.githubusercontent.com/6105075/115386179-5b7fa800-a1d9-11eb-8a32-01bd6b37b4c1.png)

**Comment by PhanLe1010** [comment]
@StefanSa 
Yeah, we are aware of this problem. The problem is that Rancher's new UI has 2 chart releases for Longhorn v1.1.0. One chart with images of the form `rancher/longhornio-longhorn-xxx:v1.1.0` and the other with images of the form `rancher/mirrored-longhornio-longhorn-xxx:v1.1.0`. However, since those images actually have the same git commit, Longhorn doesn't allow users to upgrade the engine image from one to other. Note that this problem only happens to Longhorn v1.1.0 in Rancher's new UI since the Rancher team changed their chart convention recently. 

Since having an extra engine image doesn't affect the functionality of Longhorn. You don't need to worry about it for now.

WhenLonghorn v1.1.1 to be released, you can fix this problem by following the steps:
1. Upgrade Longhorn to v1.1.1 in Rancher new UI
2. Find the volume that you attempted and failed to upgrade from `rancher/longhornio-longhorn-engine:v1.1.0` to `rancher/mirrored-longhornio-longhorn-engine:v1.1.0` . Those volumes will have an option to rollback to the image `rancher/longhornio-longhorn-engine:v1.1.0`. Try to roll them back.
3. Try upgrade the engine image for all volume to `rancher/mirrored-longhornio-longhorn-engine:v1.1.1`

**Comment by StefanSa** [comment]
@PhanLe1010 @shuo-wu 
rancher helm chart only offers v1.1.001, when will v1.1.1 be published?

**Comment by jenting** [comment]
> @PhanLe1010 @shuo-wu
> rancher helm chart only offers v1.1.001, when will v1.1.1 be published?

https://github.com/longhorn/longhorn/issues/2546#issuecomment-828908450

**Comment by StefanSa** [comment]
@jenting, thanks for the hint

**Comment by StefanSa** [comment]
I think we can close the ticket after the successful upgrade to v1.1.1
