### ISSUE TITLE
[QUESTION] Is it possible to move disk to new node and preserve volume replica?

### ISSUE THREAD

**Issue by maxweisspoker** [longhorn/longhorn#2511]
Hello, I am setting up a K8s bare metal cluster which uses network boot to download the filesystem. The filesystem is in-memory and with a few exceptions for certain folders, it is read-only. Therefore, updating it requires rebooting and having the network boot download the newer filesystem. There are no system updates while the machine is running.

So for Kubernetes, this is akin to losing/removing a node on shutdown/reboot, and adding it back as a new node once it is booted. (And part of the boot process will locate and mount hard disks in a deterministic way, so all disk partitions will always be mounted in the same directory location on the node on each boot.)

My goal is to be able to use Longhorn in this setup, and have the ability to preserve hard drive volumes across this type of reboot process.

For example, a node loses power and reboots, putting a Longhorn 3-replica volume in a degraded state with two volumes. Then the node boots and is added to the cluster within a few minutes, and the hard drive and volume are now available again.

So my question is:  Is there a way for Longhorn to identiy the hard drive partition based on its UUID or something and recognize that it's part of the aforementioned 3-replica volume, and then be able re-integrate the disk without having to do a replica rebuild?

In practice, this should mirror moving a hard drive to a new node and mounting it in the same location on that new node. This is why the title of my question is "Is it possible to move disk to new node and preserve volume replica?"  I would like to be able to do this without having the volume be re-built each time, since that needlessly wears down the hard drive.

Is this possible?

**Comment by PhanLe1010** [comment]
After the node comes back online and the disk is mounted at the same path, Longhorn will automatically recognize the disk using the disk UUID stored in `longhorn-disk.cfg` on the disk. Now, there are 2 cases:
1. If the volume was detached at the time that the old node went down, Longhorn will not rebuild the volume's replica on the disk. When the workload pod uses the volume, Longhorn will attach the volume and all replica will be reconnected as nothing ever happened.
2. If the volume was attached at the time that the old node went down, the replica on the failed node will be out of sync with other replicas. Therefore, when the disk comes back online on a new node (or on the same node with different name), Longhorn will still have to scan the replica on the disk and rebuild it to makes sure that it is in sync with other replicas. However, the cost of rebuild might be cheaper in this case compare to rebuilding a replica on a brand new disk because Longhorn will reuse part of the data of the replica on the newly join disk. We say that it might be cheaper because we are having this issue: https://github.com/longhorn/longhorn/issues/1948#issuecomment-791641308

**Comment by shuo-wu** [comment]
BTW, if the disk is not back and the rebuilding on a failed replica cannot be started within a specific time, the failed replica and the related data won't be reused anymore.
You can check this setting for more details: https://longhorn.io/docs/1.1.1/references/settings/#replica-replenishment-wait-interval

**Comment by maxweisspoker** [comment]
Thank you both for the replies and the information. I will look more into this. If I find something relevant or useful to this discussion I will re-open. Thanks again for the help.

**Comment by innobead** [comment]
cc @derekbit
