### ISSUE TITLE
[QUESTION] How much is Semver used here?

### ISSUE THREAD

**Issue by DavidBadura** [longhorn/longhorn#2531]
Hey, first of all, thank you very much for your work! But I would have one concern: 

How much is [Semver](https://semver.org/lang/de/) used here? I saw that features were added in the patch release (v1.1.1), which is not allowed. 
My fear is that BC breaks can occur in feature or even in patch releases that are not expected as a cluster maintainer.

I just wanted to ask how you do it exactly, so that I can adjust to it.

Thanks!

**Comment by joshimoo** [comment]
For patch releases we try to limit feature additions to enhancements that are mostly independent from the rest of the system, so that potential issues would only impact the newly added feature and not the stability of the rest of the system.
(i.e. if you don't uses it there is no concern)

Sometimes we do make exceptions to this rule when we feel like the value of the feature is high enough that we really want it in the next release, while the risk/scope is small enough to minimize risk. During the release process we also run full regression testing (automated + manual tests) to further minimize risks.

The last case is where a feature addition is really important for the stability of the system, as an example we added parallel s3 lookups for the backupstore, depending on view point this could be considered a feature addition or a bug fix :)

cc @innobead @yasker

**Comment by bratao** [comment]
+1 of @DavidBadura sentiment.
I´m so excited about the upcoming features and the evolution pace of longhorn. I´m particularly craving for some speed improvements. However, the amount of new functionality on a x.x.1 release makes me uneasy about running on a production cluster

**Comment by innobead** [comment]
@DavidBadura @bratao Thanks for the feedback. Actually, there is an ongoing plan for the following release cadence. 

Basically, this idea is to align with the concept of Semantic Version to match user expectation and version understanding for better manage their longhorn deployment. For example, a new minor release will be the next latest release including new enhancements/features/bugfixes/etc, but we still have one more patch release with bugfixes included only, then users can determine which release to upgrade.

Please expect the following change.

**Comment by DavidBadura** [comment]
Thank you for the answers. It sounds good! Feel free to close this ticket :-)

Thanks again for the amazing work!
