### ISSUE TITLE
[BUG] Multiple Snapshots per backup schedule

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#2554]
**Describe the bug**
On multiple clusters I see that for a backup schedule there are multiple snapshots per backup schedule. This reduces the retention for snapshot reverts.

**To Reproduce**
1. Set backup schedule to daily.

![image](https://user-images.githubusercontent.com/7300669/116722072-43303a00-a9de-11eb-81f9-0549e5e4ec10.png)

**Expected behavior**
Each day there should only be one snapshot.

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher catalog

**Comment by shuo-wu** [comment]
I guess this issue is similar to https://github.com/longhorn/longhorn/issues/2278.

If possible, can you provide the logs of the pod created by this recurring job? Or you can directly send the support bundle to us if possible.

**Comment by timmy59100** [comment]
Sent you the support bundle per email.

**Comment by shuo-wu** [comment]
I saw the below error log before the 2nd snapshot creation. This means the backup creation call is cancelled due to the short HTTP timeout, which means the cause of this issue is the same as #2278.
```
2021-05-01T00:02:11.809531647Z 2021/05/01 00:02:11 http: proxy error: context canceled
```

Besides, enhancement #2231 will make sure that the snapshots won't be flooded even if there is something wrong with the recurring backup.
