### ISSUE TITLE
Support configuring migratable parameter of the default storage class

### ISSUE THREAD

**Issue by gitlawr** [longhorn/longhorn#2594]
**Is your feature request related to a problem? Please describe.**

To use the [volume live migration feature](https://github.com/longhorn/longhorn/blob/master/enhancements/20210216-volume-live-migration.md#creating-a-migratable-storage-class) we need to set the `migratable` param in the storage class.
The parameter of the default storage class in the Longhorn chart is not configurable at the moment: 
https://github.com/longhorn/longhorn/blob/c2ea9c02228da5702eae33a588d227dfd4be53da/chart/templates/storageclass.yaml

**Describe the solution you'd like**

Support the parameter in the Longhorn chart

**Comment by joshimoo** [comment]
@gitlawr better to create your own storage class with appropriate parameters for the harvester use case instead of relying on the default `longhorn` storage class. We really don't want the `migratable` parameter in the default storage class.

**Comment by gitlawr** [comment]
Thanks for the suggestion. Can you elaborate on the reason? I thought that the default storage class is kinda syntactic sugar and should be no different from a user-created one. And it would be a valid use case that in harvester we want all volumes to be migratable by default.

**Comment by joshimoo** [comment]
The only reason we even ship a default storage class is to make it easier to use longhorn.
But in reality one should always define their own storage classes for each purpose.

For the harvester case, what I recommend is to ship a storage class referencing the longhorn driver as part of harvester with the appropriate setup for harvester as part of harvester.

This way harvester can determine their own requirements and setup independent from longhorns default, that might not suite the specific harvester case, in this case the `migratable` parameter is really purpose built to be used by harvester and we don't want to expose it to the user, since it will lead to bad outcomes without them fully understanding the requirements + necessary flow for that type of setup.
