### ISSUE TITLE
[BUG] UI mutiple selections should be released after performing action

### ISSUE THREAD

**Issue by n0rad** [longhorn/longhorn#2595]
In the UI,  When you select one or multiple volumes and perform an action, the checkboxed are not released.
To me it should be released after an action.

I was caught by it this morning when I wanted to trigger a backup on a volume, then wanted to delete another. I deleted both.

This is not natural to me that the selection remains after performing an action, especially since it's not the case when performing an action with the dropdown.

Moreover the UI is small and display only 8 volumes on the page. The in-page scoll is not helping and so I did not see that the first volume was still selected.

So I propose to :
- release selection of volumes after performing an action
- use browser page scroll instead of in page scroll

**Comment by cclhsu** [comment]
Hi! The purpose of keeping multiple selection is that user can do multiple actions for the same selection.  This is quite common when do the multiple selection.  Hope this answer you question.

**Comment by smallteeths** [comment]
Sorry to be my fault, I have never noticed that the batch creation backup operation on the volume page is different from other operations such as attach and detach. It did not reset the selected volume. In order to be consistent with other operations, I should release the checkbox and update the volume data after performing the operation.

The scroll bar style of the browser is difficult to adjust, and if the scroll bar style of the browser is changed, the entire layout of longhorn-ui will be changed. This suggestion will not be adopted for the time being. If the page display is too small due to the low resolution of the computer, you can adjust page proportion. Use `ctrl -` to adjust the page size to 70% or 80%

thanks @cclhsu @n0rad

**Comment by innobead** [comment]
@smallteeths please remember to backport to 1.1.2 as this labelled `backport-needed`. Thanks.

**Comment by innobead** [comment]
@khushboo-rancher has some concerns and will discuss with @smallteeths .

**Comment by khushboo-rancher** [comment]
Validated with images Longhorn-master-head and v1.1.2-head `05/26/2021`

Validation -**Pass**

After discussing with @smallteeths, The changes seem fine. The selection gets cleared after the action completion.

**Comment by khushboo-rancher** [comment]
@innobead @smallteeths Do we want the same behavior for the backup list page also?

**Comment by innobead** [comment]
> @innobead @smallteeths Do we want the same behavior for the backup list page also?

If this is the same operation, I think we should. @khushboo-rancher please help create an issue for that.

**Comment by khushboo-rancher** [comment]
Created https://github.com/longhorn/longhorn/issues/2652
