### ISSUE TITLE
[DOC] Reference Architecture and Sizing Guidelines

### ISSUE THREAD

**Issue by wjimenez5271** [longhorn/longhorn#2598]
As a user of Longhorn, I need to know the ideal implementation of Longhorn to ensure the best experience. For example, I want to know if I am risking stability by using a node or network type that is undersized for Longhorn. 

Also, need to consider https://github.com/longhorn/longhorn/issues/2246#issue-804376552. 
There may be some unexpected issues when Longhorn creates snapshots/backups on high spec nodes:
#1675
#2029

https://github.com/longhorn/longhorn/issues/2598#issuecomment-1666884745

**Comment by yasker** [comment]
For the volume size limit, let's targeting for supporting up to 2TB single volume.

**Comment by PhanLe1010** [comment]
Related to the slack message https://cloud-native.slack.com/archives/CNVPEL9U3/p1622728334055500

**Comment by PhanLe1010** [comment]
Action items (checked item means we already know):
- [ ] Recommended volume sizes (min, max, best) 
- [ ] Recommended min CPU
- [ ] Recommended min RAM
- [ ] Recommended min Network bandwidth, min latency
- [ ] Recommended Disk min letancy, min IPOS 
- [ ] Recommended OS, Filesystem on Node
- [ ] Recommended backup target (request latency)
- [ ] Recommended cluster setup (Where in the cluster Longhorn should run)

@yasker @joshimoo @shuo-wu @wjimenez5271 Am I missing anything?

**Comment by yasker** [comment]
resource requirement for volume number/total size in cluster or node.

**Comment by yasker** [comment]
@joshimoo What's the biggest volume we've tested right now? 4TB?

**Comment by innobead** [comment]
@PhanLe1010 when working on that, please also move to analysis or implementation pipeline. Thanks!

**Comment by joshimoo** [comment]
@yasker I have never tested that big of a size, I think @meldafrawi / @khushboo-rancher are working on some size tests for backups?

**Comment by khushboo-rancher** [comment]
I've tested with max 1T data while testing https://github.com/longhorn/longhorn/issues/1948. Is the data from https://github.com/longhorn/longhorn/issues/1948#issuecomment-865362997 helpful here?

**Comment by yasker** [comment]
Discussed with @innobead , minimal resource investigation should be also done as a part of sizing guideline, so we will know what's our baseline is.

**Comment by innobead** [comment]
We can wrap up this after 1.2.0 out.

**Comment by innobead** [comment]
Need to wrap up after 1.2.1.

**Comment by innobead** [comment]
Briefly, we should define a framework and based on that figure out the limitation of Longhorn capabilities when running in different supported environment setups (on-prem, cloud, edge) w/ env factors. 

**Conditions**
- On-Prem, Edge, Cloud
- General/Storage node
- Cluster size
- Topology spread constraints

**Requirements**
- Recommended infra requirements (Longhorn disk size and performance, network bandwidth between nodes)
- Recommended host requirements (Kernel, dependent host packages, K8s related)

**Capabilities**
- Max volume size
- Max number of volumes

Based on the matrix of the above conditions and requirements, we can come out with a reference architecture for each and what capabilities Longhorn can support. 

This could not be just an evaluation, but it would turn out there will be some improvement needed to develop accordingly. Besides, also need to look at a new strategy for resource requests for IM pod (DP) instead of just a hard default suggested request.

**Comment by innobead** [comment]
FYI. This is the next priority after object storage integration. cc @longhorn/dev

**Comment by PhanLe1010** [comment]
### Test plan:

We don't have a test plan for this ticket. @longhorn-qa is welcome to read over the report though. Thank you

**Comment by derekbit** [comment]
@PhanLe1010 Can you add a page in the official doc?

**Comment by yangchiu** [comment]
According to the [scalability and sizing guidelines report](https://github.com/longhorn/longhorn/blob/master/scalability/reference-setup-performance-scalability-and-sizing-guidelines/public-cloud/medium-node-spec.md), users can find quantitative references for Longhorn's performance limitations and obtain guidelines on how to scale and size their nodes and Longhorn volumes.
