### ISSUE TITLE
[QUESTION] Open Port 111 (RPC) to the Internet required? (risk of DDoS-Reflection attacs?)

### ISSUE THREAD

**Issue by lsascha** [longhorn/longhorn#2603]
**Question**

I installed Ubuntu Kubernetes nodes and only added the packages
    - open-iscsi
    - nfs-common

for longhorn and RWX volume support like mentioned in the documentation

Now i got a BSI Security E-Mail that port 111 is open to the internet and should be closed because of DDoS-Reflection attacs.

Since as far as i know, Port 111 is required for NFS i can't just close it off i guess?
So is it even really an insecurity in the setup?
Can port 111 be closed off to the internet and NFS still being used since all Nodes are attached to a private Network?

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.21.0
 - Node config
   - OS type and version: Ubuntu 20.04
 - Underlying Infrastructure: Baremetal

**Comment by lsascha** [comment]
Reading more into it, i think the rpcbind service can (safely?) be disabled for the Nodes, since they should only use the NFS-Client. Right?

So maybe we can add to the documentation to disable RPC with
`systemctl disable --now rpcbind.service rpcbind.socket`

after installing NFS with nfs-common package.

But i am not that much into how Longhorn uses NFS and what needs to be able to connect to where. 😬

**Comment by joshimoo** [comment]
For RWX volume support you don't need the rpcbind service at all since we require nfs v4.1+ as a minimum version which doesn't depend on the rpcbind service.

If you want to use an NFS backup target that is not requiring nfs v4.1+ then the rpcbind is needed for nfs v3 connections.
But in this case you should also be able to firewall that service to only work on the internal network unless your nfs server is accessed via the public network (internet)

NOTE: ubuntu tends to enable the rpcbind service when installing nfs-common, but for nfsv4+ rpcbind is not required, so you should be able to disable the service.

**Comment by lsascha** [comment]
Thank you for the quick reply.
I disabled the service on all nodes, and so far i thing everything still works. (using an S3 bucket as backup target)

Still maybe the information can be added to the documentation?
