### ISSUE TITLE
Does this project advise against using Longhorn for databases?

### ISSUE THREAD

**Issue by voarsh2** [longhorn/longhorn#2641]
**Question**

I've not seen any mention of database usage for Longhorn.
I've been doing some initial testing with 2 replicas, a Mariadb cluster (replication) - though I should probably not replicate twice (Maria and Longhorn).

Does this project advise against using Longhorn for databases?

**Additional context**

**Comment by joshimoo** [comment]
If you have replication on the application layer, you don't need replication on the storage layer.
So it's better to use a local volume instead, since you will get better io performance.
The assumption here is that your data is correctly replicated on the application layer, so that you can just pop up a new application replica and it will do a sync.
