### ISSUE TITLE
[QUESTION] Best Practice on Worker Node Failure (in a 3Worker/3ReplicaCount Setting)

### ISSUE THREAD

**Issue by quasarchimaere** [longhorn/longhorn#2651]
**Question**
I found out that the default Replica Count is set to 3. If you only have 3 worker nodes on which the replicas are stored, doesnt this mean that losing one worker node will then default to the loss of every running pod that has a pvc on that worker node? Because losing one worker node will set all the volumes to get degraded (access loss to one replica) and thus they will not be provisioned/attached to any other pod even if the pods would rebuild on another worker?

Whats the best way to solve this issue, or is it not even one and i am missing something?
Options i can think off:
- Add Worker Nodes: probably not going to happen for a while in our current setup
- Reducing the Number of Replicas per volume: decrease to two so that at least one worker node can fail, however what does this mean in terms of high availability of the volumes as a set of only two replicas couldn't find a valid majority if one replica is degraded

Is there a Best Practice setup/guideline for this that you could suggest?

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.20
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): RKE Cluster with 6 Nodes (3 of them dedicated Workers)

**Comment by joshimoo** [comment]
This might also help solidify some concept:
The pod talks with the engine (volume)
-> Engine for each volume is running on the same node as the workload pod

The engine talks with the replicas (volume data)
-> Each replica is a full set of volume data

-------------

Therefore we can see, that we can lose (replica Count - 1) replicas for a volume while still being able to service that volume.
Since each replica is a full copy of the data and each IO is only acknowledged once all active replicas have persisted the write.

So **in your case losing a single replica should not impact the volumes**, once your workload gets rescheduled to a separate node, the volume should be attached there and mounted correctly.

**Comment by quasarchimaere** [comment]
i also just found the answer in your documentation:

If you have a Cluster with more than 3 nodes you can keep the replica count at 3, if you have a cluster with 3 or less you should use 2 as a default
