### ISSUE TITLE
[QUESTION] Making sure Longhorn isn't putting its processes on one node

### ISSUE THREAD

**Issue by voarsh2** [longhorn/longhorn#2657]
**Question**

I restarted a node and found that many of the longhorn pods/processes are all stuffed onto the node that had gone down.
I had hoped there would be tolerations that would reschedule them - but there's only the system default of like 600....

How can I make sure this is mitigated?

FYI:

Having a node turn off has its processes as "unknown" (yellow), quite often the processes are on ONE node, making Longhorn not highly available when it won't bounce back because the processes aren't even spread out......

![image](https://user-images.githubusercontent.com/60437695/120723744-3ebddc00-c4ca-11eb-8570-07a31b2bd552.png)

I had to "increase" the count on many of the none 1 per node processes I even have to go to system, longhorn and "redeploy" in bulk.... Can someone tell me how this can be fixed?
I've tried HA with Longhorn before and haven't run into this issue before, but for some reason I am now....

**Comment by PhanLe1010** [comment]
Hi @voarsh2 

By saying `longhorn pods/processes`, do you mean the `csi-***` deployments in Longhorn system? If so, this is a common problem in Kubernetes since the pods that are scheduled are never rebalanced even if the state of the world changes. There are ways to tackle this problem:
* Automatically. See [this article](https://itnext.io/keep-you-kubernetes-cluster-balanced-the-secret-to-high-availability-17edf60d9cb7) and [kubernetes descheduler](https://github.com/kubernetes-sigs/descheduler)
* Manually by deleting the pods, Kubernetes will reschedule and rebalance them.
