### ISSUE TITLE
[QUESTION] why longhorn restrict install in the specific namespace 

### ISSUE THREAD

**Issue by tgfree7** [longhorn/longhorn#2658]
**Question**
I have a  issue to deploy Longhorn  not in the namespace 'longhorn-system', why can only in the specific namespace ? is there a consideration we don‘t know?

**Comment by PhanLe1010** [comment]
There are some scripts/tools that are currently hard-coded to `longhorn-system` namespace. Moreover, while it is technically not restricted to `longhorn-system` namespace since users can install Helm release into another namespace, we haven't verify/test installing Longhorn in a different namespace yet. Therefore, we cannot recommend user installing Longhorn outside of the `longhorn-system` namespace. 

Btw, why would you want to install Longhorn in a namespace different than `longhorn-system`?

**Comment by tgfree7** [comment]
> There are some scripts/tools that are currently hard-coded to `longhorn-system` namespace. Moreover, while it is technically not restricted to `longhorn-system` namespace since users can install Helm release into another namespace, we haven't verify/test installing Longhorn in a different namespace yet. Therefore, we cannot recommend user installing Longhorn outside of the `longhorn-system` namespace.
> 
> Btw, why would you want to install Longhorn in a namespace different than `longhorn-system`?

We accidentally installed the longhorn in other namesapce, and wonder why in the `longhorn-system`
