### ISSUE TITLE
[BUG] Not all informer registered cacheSync function

### ISSUE THREAD

**Issue by jenting** [longhorn/longhorn#2671]
**Describe the bug**

Currently, the informer register to the cache sync function is
https://github.com/longhorn/longhorn-manager/blob/v1.1.1/datastore/datastore.go#L180-L188
However, we have more informers that need to register to the cache sync function
https://github.com/longhorn/longhorn-manager/blob/v1.1.1/datastore/datastore.go#L126-L174

It'd be better to use reflect to loop the Datastore struct to check which field type matches `type InformerSynced func() bool`.
Then, aggregate these as `cacheSyncs` and pass to `cache.WaitForNamedCacheSync("longhorn datastore", stopCh, cacheSyncs)`.

Furthermore, each controller has the same logic.
https://github.com/longhorn/longhorn-manager/blob/v1.1.1/controller/volume_controller.go#L160
https://github.com/longhorn/longhorn-manager/blob/v1.1.1/controller/volume_controller.go#L118-L121
We could use the same way to aggregate them and pass to `cache.WaitForNamedCacheSync("longhorn datastore", stopCh, cacheSyncs)`.

**Comment by joshimoo** [comment]
I would like a refactor like this, since each controller has a dependency on the DataStore.

- remove the initialization of the informers from [startControllers](https://github.com/longhorn/longhorn-manager/blob/25ccde1b79c62358d9f9cc2ec0c0d8ef8987fe59/controller/controller_manager.go#L73)
- only pass the informer factories to the ds
- only pass the ds to the controllers
- let the datastore create a informer for each resource and export the informers.
- for the controllers only pass the ds and reference the ds exposed informers to add event handlers.
- the controllers can instead now call c.ds.Sync(controllerName, stopCh)

For unit tests all that is needed is a different DS / informerFactories.
Also in the future all resource creation/updates/deletions should go via ds exported functions.
The end result is that there is only a single place where we even need to deal with informer creation and cache syncs.

**Comment by khushboo-rancher** [comment]
Let's wait for today's (10/29/2021) nightly test run to see the results for https://github.com/longhorn/longhorn/issues/3193, https://github.com/longhorn/longhorn/issues/3183, https://github.com/longhorn/longhorn/issues/3182 before closing this.

**Comment by khushboo-rancher** [comment]
The results of e2e tests master look good. https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/478

The functionality of volume, engine, replica, backups is looking good as well. 
Checked some of the cases related to engine/replica crash.
