### ISSUE TITLE
[BUG] can't use longhorn-iscsi-installation.yaml install iscsi.

### ISSUE THREAD

**Issue by lxd5866** [longhorn/longhorn#2739]
#### env
minikube version: v1.21.0
commit: 76d74191d82c47883dc7e1319ef7cebd3e00ee11
minikube kubernetes version :  v1.20.7
minikube images :  Buildroot 2020.02.12
docker version: 20.10.6

####  why
```
 minikube s ssh
                         _             _
            _         _ ( )           ( )
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ zypper
-bash: zypper: command not found
$ apt-get
-bash: apt-get: command not found
$ yum
-bash: yum: command not found
```

#### suggest:
Add a judgment for  Buildroot image

**Comment by cclhsu** [comment]
Minikube currently do not support iscsi module in it build configuration and cannot be installed directly.  There is a recent PR https://github.com/kubernetes/minikube/pull/11458 to enable ISCSI, but it will encounter iscsi cannot support multiple iscsi on same hosts.  Other container technologies such as kind and lxc/lxd, iscsi also are not supported ISCSI due to same issue.  Please use virtual machine to deploy k8S/Longhorn.

**Comment by jenting** [comment]
Close this one since Minikube does not support iscsi module.
Same as other container technologies such as kind.
