### ISSUE TITLE
[QUESTION] How to use Longhorn with delete-heavy workloads?

### ISSUE THREAD

**Issue by michael-sayapin** [longhorn/longhorn#2752]
**Question**

We use Longhorn storage to back our Postgres DB installation. The actual size of the volume is over 400GB is growing, with NO snapshots (no "system hidden" either). Actual data size is 33GB. How do we reclaim the space used by the sparse file? Do we need to provision a PVC size of 35GB to "make" Longhorn seek new holes in sparse data?

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.21.2
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 8
   - Memory per node: 32
   - Disk type: SSD
   - Network bandwidth and latency between the nodes: 7 Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Tencent Cloud ECS

**Comment by c3y1huang** [comment]
Longhorn currently does not support space reclaim. Please see if this [comment](https://github.com/longhorn/longhorn/issues/1555#issuecomment-671097588) and these [threads](https://github.com/longhorn/longhorn/issues/836) helps to answer your question.

**Comment by michael-sayapin** [comment]
Thank you @c3y1huang !

So for this volume we provisioned 500GB size.

Do I understand correctly, that actual size of the volume is going to be:

- provisioned size, i.e. 500GB,
- plus all the retained snapshots,
- plus all the retained backups?

And when the actual *written* data amount reaches 500GB, the driver will start looking for "holes" in the sparse file?

BTW, even if configured to store backups in S3, it seems they are still preserved on disk.

**Comment by c3y1huang** [comment]
> Thank you @c3y1huang !
> 
> So for this volume we provisioned 500GB size.
> 
> Do I understand correctly, that actual size of the volume is going to be:
> 
> * provisioned size, i.e. 500GB,
> * plus all the retained snapshots,
> * plus all the retained backups?

[Here](https://github.com/longhorn/longhorn/issues/2165#issuecomment-759205621) is a good explanation of the actual size. And you can also more further info in Longhorn [doc](https://longhorn.io/docs/1.1.1/volumes-and-nodes/volume-size/).

> 
> And when the actual _written_ data amount reaches 500GB, the driver will start looking for "holes" in the sparse file?

The longhorn starts the volume as a hollow file. It means a file with holes. Then it will start to fill up the "holes" with data and you will see the size starts to increase. And because the filesystem is writing all over the volume, so "holes" will get filled up even if you are just overwriting the same file in the volume with the same size data. And how many "holes" get filled up will also reflect on what you see in the actual size.

> 
> BTW, even if configured to store backups in S3, it seems they are still preserved on disk.

The actual size does not include the backups.

**Comment by aachenmax** [comment]
@michael-sayapin We have experienced exactly the same issues with our Postgres + Longhorn setup. And exactly the same behavior with a HA Redis deployment using data persistence. Volumes slowly filling up, even though the actually used data is just a tiny fraction of the total volume size. How have you dealt with this issue since then?

**Comment by iosifnicolae2** [comment]
I'm having the same problem on v1.2.3 (I've sent the support bundle to longhorn-support-bundle@suse.com, my email is iosif@mailo.dev).

**Comment by shuo-wu** [comment]
Let's track this issue in ticket #836

**Comment by grinono** [comment]
We also have this issue with postgres instance running on longhorn. When full, we see connectivity issues. It's super annoying that we need to monitor and delete the instance every some many days. Did anyone found a solution?

**Comment by derekbit** [comment]
> We also have this issue with postgres instance running on longhorn. When full, we see connectivity issues. It's super annoying that we need to monitor and delete the instance every some many days. Did anyone found a solution?

Hello @grinono,

The issue is in v1.1.1 which is too old.
If you are using a newer version, please create a new ticket with more information. It will help us figure out the root cause.
Thanks.
