### ISSUE TITLE
[BUG] Tests related to backup deletion are failing on v1.1.3 branch

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2831]
**Describe the bug**
https://ci.longhorn.io/job/public/job/v1.1.3/job/v1.1.3-longhorn-tests-ubuntu-amd64/7/#showFailuresLink

**To Reproduce**
1. Run below integration tests
   1. test_backup_lock_deletion_during_restoration
   2. test_backup_lock_deletion_during_backup
   3. test_backup_lock_creation_during_deletion

**Comment by innobead** [comment]
![image](https://user-images.githubusercontent.com/899492/127902514-ab54734f-2c6c-45e6-a1a8-a8a43a24b786.png)

This should be caused by the wrong setting. For patch build, we should use the correct version of individual components instead of master-head like instance-manager, share-manager, backing-image-manager.

@meldafrawi Please help fix the Jenkins job settings. Thanks.

**Comment by khushboo-rancher** [comment]
This issue is observed on master branch as well

**Comment by innobead** [comment]
> This issue is observed on master branch as well

@meldafrawi @khushboo-rancher yes, and this is the same reason. @meldafrawi Please help fix that. (It will possibly happen again if any further change later)

For instance-manager, share-manager, backing-image-manager, we are using them as version-based dependent components, so we can't use master-head directly because it possibly breaks the incompatibility between manager/engine.

For master, you can base https://github.com/longhorn/longhorn-manager/blob/master/deploy/install/02-components/01-manager.yaml#L24-L38.
For 1.1.3, https://github.com/longhorn/longhorn-manager/blob/v1.1.3/deploy/install/02-components/01-manager.yaml#L24-L38. 

But, it will be good we have an automatic way to detect the change and update the Jenkins job accordingly.

**Comment by khushboo-rancher** [comment]
The reported problem is no more reproducible on v1.1.3. Closing this one.
