### ISSUE TITLE
[QUESTION] Safe restarting longhorn-manager

### ISSUE THREAD

**Issue by AlekseyKovy** [longhorn/longhorn#2853]
Hello!
Over time, we began to notice that longhorn's RAM usage was steadily increasing. The longhorn-manager on one node was using most of all the RAM consumed by the longhorn, so we decided to try removing this pod to restart it. After restarting the pod, the RAM usage in the cluster dropped by 600 megabytes, and longhorn-manager started consuming 50 megabytes instead of 800 megabytes.

**QUESTION: Can we create a CronJob  that will restart longhorn-manager? Is it safe to do this or is there another way? Why does restarting the pod reduce the RAM consumption?**

**Environment:**
 - Longhorn version: 1.1.2
 - Kubernetes version: 1.20.4
 - Node config
   - ubuntu 20
   - 4CPU per node
   - 4gb RAM per node
   - SDD

**Comment by shuo-wu** [comment]
Due to the bugs like https://github.com/longhorn/longhorn/issues/2778 or https://github.com/longhorn/longhorn/issues/2818, the longhorn-manager pods may use more and more RAM or CPUs with time elapsed. I already fixed these in the upcoming v1.1.3 or v1.2.0 but I am not sure if there are any other unknown issues that would still lead to the case.

You can do it as a workaround. The existing volumes won't crash and r/w won't be affected. But the risks are, all logs info will get lost and no one can do some operations like snapshot/backup before the new manager pods up.

But we need to figure out the cause and fix it anyway. The workaround is not a long-term solution. Can you provide the support bundle before killing the manager pods when the case happens?
