### ISSUE TITLE
affinity/anti-affinity for replicas

### ISSUE THREAD

**Issue by KuroObi** [longhorn/longhorn#296]
Is there a way to set a affinity or anti-affinity for repica deployment in a longhorn cluster?

In our scenario all database volumes replicas were scheduled onto the same longhorn node.
For this scenario we relied upon the database for data replication and redundancy.
Is there a way or upcoming feature that implements affinity for volumes/replicas like with StatefulSets and Deployments?

**Comment by yasker** [comment]
The replicas of the same volume would be scheduled using the anti-affinity rule, otherwise, it cannot prevent the case of node down.

What do you mean by `volumes replicas were scheduled onto the same longhorn node`? Are you using single replica as you mentioned in the other issues? If so, just use multiple replicas for each volume (recommended 3 at least) would solve the issue naturally.

**Comment by yasker** [comment]
And if there is a bug regarding Longhorn didn't schedule replicas of the same volume to the different node (while it seems possible to use other nodes, e.g. the other nodes weren't full, or disabled for scheduling, etc.), please file an issue to let us know.

**Comment by KuroObi** [comment]
We ware using single replicas per volume since the database dose the replication of the data.
Normally i would deploy multiple replicas of one volume but in this case we have huge amounts of data that wont do to replicate multiple times due to storage limitations.

Since this are some special conditions i would have hoped that there is a way to tell longhorn/k8s to schedule all volume replicas of a  statefulset (for example three database pods) onto different nodes.

**Comment by yasker** [comment]
Hmm, it would need quite some efforts.

The volumes themselves don't know what the workload would be. If we're going to implement this, it's likely the user would need to define a few more options while creating the volume, namely the condition for replica scheduling, probably in the format of one or multiple tags and one or multiple rules. 

I am not convinced that this will be useful except for the users with only one replica. And it's complicated to use and to implement. For example, take a look at how Kubernetes [affinity rules](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) works. I'd like to have more use cases for this feature, rather than only the single replica scenario.

One easier (but not deterministic) way to solve this, is we can try to spread the replicas across all the nodes as evenly as possible. That means we can prioritize the nodes/disks with no volume scheduled or small amounts of storage scheduled before the highly utilized nodes/disks. But that won't guarantee the replicas of volumes for the same workload (e.g. statefulset) won't be scheduled on the same node/disk.
