### ISSUE TITLE
[BUG] Restore from backup sometimes failed if having high frequent recurring backup job w/ retention

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3055]
**Describe the bug**
Restoring from a backup is failing.

**To Reproduce**
1. Deploy Longhorn and set backup target as S3
2. Create volume bak on longhorn
3. Use bak create PV “bak” PVC “myclaim” from longhorn UI
4. Deploy pod “mypod1”
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: mypod1
  volumes:
    - name: mypod1
      persistentVolumeClaim:
        claimName: myclaim
```
5. In mypod1 shell, execute sh -c "echo 'Hello from Kubernetes storage' > /usr/share/nginx/html/index.html"
6. **Create recurring back job, 3 retain, 1 concurrency, every minute**
7. Create manual backup
8. Restore manual backup to volume v1
9. Restored volumes becomes faulted

**Expected behavior**
The restore should never fail

**Log**
[longhorn-support-bundle_31ac3144-3ee9-4f59-86f5-3f9051e009b8_2021-09-22T23-17-01Z.zip](https://github.com/longhorn/longhorn/files/7214356/longhorn-support-bundle_31ac3144-3ee9-4f59-86f5-3f9051e009b8_2021-09-22T23-17-01Z.zip)

**Environment:**
 - Longhorn version: v1.2.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by innobead** [comment]
cc @jenting @shuo-wu

**Comment by jenting** [comment]
I think no.
There is an issue related https://github.com/longhorn/longhorn/issues/3016 which is at version 1.1.x

**Comment by innobead** [comment]
> I think no.
> There is an issue related #3016 which is at version 1.1.2

So you mean it probably not a regression? Please check a bit and have a further update.

**Comment by jenting** [comment]
We've 3 locks in the backup driver. The backup/restore/deletion lock.
The type 2 lock is the deletion lock, it makes sure during backup/restore operation, it can't delete the remote backup, and vice versa. The lock is to protect the consistency of the backupstore. Since it can be used by multiple clusters simultaneously (active and DR volume).

From my understanding now is the recurring job retain=3 and run every min. It would delete the old backup every min and contains only 3 backups.
If the user creates a manual backup and restores the manual backup, during restoration, the recurring job can't delete the backup at the moment until the restoration process is finished.

To improve this, we could do error message parsing on the delete backup/backupvolume API call, and do not enqueue immediately but the Backup/BackupVolume CR could be reconciled in the controller next reconcile time (30 seconds by default).

**Comment by khushboo-rancher** [comment]
This is reproducible on v1.2.0 as well. I tried 5 times and observed this issue twice. Sometimes, only one/two replica fails and volume gets restored with degraded state.

**Comment by innobead** [comment]
@khushboo-rancher I just removed the `kind/regression` first, because it's actually happening in 1.2.0 already. Also, if possible, could you try to verify in 1.1.2 as well to see if this is also possible to reproduce. 

From my view, this is more like an existing behavior instead of any new introduction (Please correct me if I am wrong @jenting @joshimoo ), so at least we need to understand what cases will cause this problem, then identify the areas to fix later.
- What case will cause the faulted volume & what's the workaround
- What case will cause the degraded volume & what's the workaround 
- What is the lock mechanism among the restore, backup, and backup deletion
- How volume restore work

**Comment by innobead** [comment]
Also add some comment from @joshimoo 

> Correct backup/restore cannot be done while a delete operation is in progress. And vice versa the locks is necessary to protect the consistency of the backupstore. Since it can be used by multiple clusters simultanously (i.e active and DR cluster)
For the control flow the lock failures should be treated as intermediate and the backup crd should be requed at a future time.
There is a tech debt epic, for generally improving the error communication mechanism, so we can make it consistent and include a code + message. So that other components can act acurately on the returned errors instead of having to do some error msg parsing.
https://github.com/longhorn/longhorn/issues/1875

**Comment by joshimoo** [comment]
So my expectation for a new restore volume request is that the volume creation will remain pending. In the case where the restore operation has failed due to an existing lock or any other intermediate failures. Currently we don't have a good way to signal these types of failures. Therefore I created this tech debt epic to improve the general error communication + structure. https://github.com/longhorn/longhorn/issues/1875

@jenting Now that we have Backup cr it would be nice during the volumeCreate call to verify the existence of the backup. This way if a restore is requested for a backup that doesn't actually exists we can notify the caller and prevent the volume creation. It's possible I already added something like this in the prior implementation but I would have to check :)

**Comment by jenting** [comment]
Update current what I finding.

1. After discussion with Chris, he did the test with `"echo 'Hello from Kubernetes storage' > /usr/share/nginx/html/index.html"`, and then ssh to the node and run `dd if=/dev/urandom of=/dev/longhorn/bak status=progress`. This `dd` command would format the device so makes the `/usr/share/nginx/html/index.html` gone. So, it's the reason why restore the volume the file `/usr/share/nginx/html/index.html` missing.
2. For type 2 lock acquisition failure is because recurring job retain=3 will delete the older backup every min, and restoring the backup manually. Since the lock is per-volume basis, so during the restoration, the recurring job deletion older backup would not work. So the longhorn-manager Pods floods with error message `failed lock backupstore/volumes/17/22/bak/locks/lock-49c8c5b6feca4a36.lck type 2 acquisition`.
3. For the error message `Failed to initiate the backup restore, will do revert and cleanup then.`. Since longhorn-engine performs restoration per-replica, which means by default we have 3 replicas, each replica will run [restoring simultaneously and separately](https://github.com/longhorn/longhorn-engine/blob/v1.1.2/pkg/sync/backup.go#L239-L250). There might be a possible case that `replica1 restoration -> deletion -> replica2 restoration ->replica3 restoration`. It would cause the replica2 and replicas3 restoration to fail because acquires the restore lock error (type 1 lock).

So I think Chris hits situation 1 and Kushboo hits situation 3.
However, I haven't reproduced situation 3 locally.

**Comment by khushboo-rancher** [comment]
This is reproducible on v1.1.2 as well.

[longhorn-support-bundle_e5fd2315-3415-4f86-8306-d3e2900699cd_2021-09-24T23-23-09Z.zip](https://github.com/longhorn/longhorn/files/7228769/longhorn-support-bundle_e5fd2315-3415-4f86-8306-d3e2900699cd_2021-09-24T23-23-09Z.zip)

**Comment by innobead** [comment]
> This is reproducible on v1.1.2 as well.
> 
> [longhorn-support-bundle_e5fd2315-3415-4f86-8306-d3e2900699cd_2021-09-24T23-23-09Z.zip](https://github.com/longhorn/longhorn/files/7228769/longhorn-support-bundle_e5fd2315-3415-4f86-8306-d3e2900699cd_2021-09-24T23-23-09Z.zip)

Thanks @khushboo-rancher verification!

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/3055?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by jenting** [comment]
> So my expectation for a new restore volume request is that the volume creation will remain pending. In the case where the restore operation has failed due to an existing lock or any other intermediate failures. Currently we don't have a good way to signal these types of failures. Therefore I created this tech debt epic to improve the general error communication + structure. #1875
> 
> @jenting Now that we have Backup cr it would be nice during the volumeCreate call to verify the existence of the backup. This way if a restore is requested for a backup that doesn't actually exists we can notify the caller and prevent the volume creation. It's possible I already added something like this in the prior implementation but I would have to check :)

We've implement the [check](https://github.com/longhorn/longhorn-manager/blob/v1.2.x/manager/volume.go#L203-L206) already.

**Comment by innobead** [comment]
@jenting anything left for this issue? 👇 

> For the error message Failed to initiate the backup restore, will do revert and cleanup then.. Since longhorn-engine performs restoration per-replica, which means by default we have 3 replicas, each replica will run restoring simultaneously and separately. There might be a possible case that replica1 restoration -> deletion -> replica2 restoration ->replica3 restoration. It would cause the replica2 and replicas3 restoration to fail because acquires the restore lock error (type 1 lock).

**Comment by innobead** [comment]
The update from @jenting 

If I remember correctly, the problem/step is

1. The recurring job call RESTful API to delete Backup (the deletion is background delete)
2. User clicks restore, LH manager validates okay by checking the Backup CR is exist (since the deletion is background delete, so the Backup CR exists)
3. The backup_controller deletes the Backup from the remote backup target (this step, the deletion lock acquired)
4. The longhorn engine restore replicas from the remote backup target (this step, the restore lock acquisition failed)
5. Failed replicas occur

That's the reason why should we check the DeletionTimestamp also since the Backup CR deletion is async, check the Backup CR exists or not probably not enough.

**Comment by Lichiehyao** [comment]
**Verified on master-head 20220829**

- longhorn master-head ([cccabbf](https://github.com/longhorn/longhorn/commit/cccabbf89f02dde36de302c46456cd9cd0318dbb))
- longhorn-manager master-head ( [76f0fb4](https://github.com/longhorn/longhorn-manager/commit/76f0fb4badcc8e0f5baf45e3b739767d0971ed6b))

**The test steps**

1. Install Longhorn master-head
2. Create a volume "bak" on longhorn
3. Create volume "bak"'s PV(name:bak) & PVC (name:myclaim) from longhorn UI
4. Deploy pod “mypod1” via cli `kubctl apply -f mypod1.yaml`
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  namespace: default
spec:
  containers:
    - name: testfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: mypod1
  volumes:
    - name: mypod1
      persistentVolumeClaim:
        claimName: myclaim
```

5. Enter mypod1 shell `kubectl exec --stdin --tty mypod1 -- /bin/bash`
6. execute `echo 'Hello from Kubernetes storage' > /usr/share/nginx/html/index.html`
7. Create recurring back job, 3 retain, 1 concurrency, every minute
8. Create a manual backup
9. Restore manual backup to volume-v1
10. Check whether or not the error was printed

**Result Pass**

After restored, we didn’t observe the error symptoms.
[longhorn-support-bundle_a334ca16-9b8c-4e6f-822e-711b32e42777_2022-08-29T06-15-10Z.zip](https://github.com/longhorn/longhorn/files/9442149/longhorn-support-bundle_a334ca16-9b8c-4e6f-822e-711b32e42777_2022-08-29T06-15-10Z.zip)
.
