### ISSUE TITLE
[BUG] Uninstallation fails if backup exists in error state

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3082]
**Describe the bug**
If a cluster has backup crds which are in error state, longhorn uninstallation fails.

**To Reproduce**
1. Deploy Longhorn on a cluster.
2. Have some backups in error state. ( Not sure what caused the error)
```
kubectl get backups -n longhorn-system
NAME                      SNAPSHOTNAME   SNAPSHOTSIZE   SNAPSHOTCREATEDAT   STATE   LASTSYNCEDAT
backup-3490a9c02d90475a                                                     Error   0001-01-01T00:00:00Z
backup-8a766788af8d4259                                                     Error   0001-01-01T00:00:00Z
```
3. Uninstall the Longhorn.
4. Observe the uninstallation job stuck in deleting the backups and fails.

**Expected behavior**
Uninstallation job should delete the backups in error state and proceed for the uninstallation.

**Log**
```
I0928 23:55:18.449201 1 shared_informer.go:223] Waiting for caches to sync for longhorn uninstall
Tue, Sep 28 2021 4:55:19 pm | I0928 23:55:19.349664 1 shared_informer.go:230] Caches are synced for longhorn uninstall
Tue, Sep 28 2021 4:55:19 pm | time="2021-09-28T23:55:19Z" level=info msg=Uninstalling... controller=longhorn-uninstall
Tue, Sep 28 2021 4:55:19 pm | time="2021-09-28T23:55:19Z" level=info msg="Found 2 backups remaining" controller=longhorn-uninstall
Tue, Sep 28 2021 4:55:48 pm | time="2021-09-28T23:55:48Z" level=info msg="Found 2 backups remaining" controller=longhorn-uninstall
Tue, Sep 28 2021 4:56:18 pm | time="2021-09-28T23:56:18Z" level=info msg="Found 2 backups remaining" controller=longhorn-uninstall
Tue, Sep 28 2021 4:56:48 pm | time="2021-09-28T23:56:48Z" level=info msg="Found 2 backups remaining" controller=longhorn-uninstall
```

**Environment:**
 - Longhorn version: v1.2.1-rc2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by jenting** [comment]
I've checked the cluster and dump the support bundle, the root cause of the Backup in `error` state is that:
- it's the volume's first backup and there is a recurring backup of this volume
- during the 1st backup creation and haven't be completed, the backup target be unset
- the backup CR fails into the error state because the backup target be unset

During the uninstallation, we only unset the backup target, we leave the cleanup BackupVolume/Backup CR to backup_volume_controller/backup_controller since we want to make sure there is only one owner which is responsible to clean up the BackupVolume/Backup CR. Otherwise, there might be a chance that the backup target does not unset successfully, and the uninstall job to clean up the BackupVolume/Backup CR which would cause the remote backup to be deleted also.

And since it's the volume's first backup, so the BackupVolume CR hasn't been created yet. So running this [code](https://github.com/longhorn/longhorn-manager/blob/v1.2.0/controller/backup_volume_controller.go#L218) would not clean up the Backup CR since it did not have a corresponding BackupVolume CR yet.

The current workaround way is to manually delete the orphan Backup CRs.

I think we have to revisit the `ownerReferenceDesign` of BackupVolume <-> Backup, but we have to make the BackupVolume CR be created first if it's the volume's 1st backup and make sure the BackupVolume CR won't be deleted during the 1st backup creation in progress.

**Comment by innobead** [comment]
It looks like we need to have a mechanism to clean up the orphan backups, and also there is a workaround for that. Let's tackle this in the following release after 1.2.1.

@jenting Please help update the comment to define how to know the backup is orphan like we discussed. Thanks.

**Comment by innobead** [comment]
@jenting any update for this?

**Comment by jenting** [comment]
> @jenting any update for this?

Did file a PR previously, but Shuo had a [comment](https://github.com/longhorn/longhorn-manager/pull/1089#pullrequestreview-783011332) about that, but I can't find a better way to tackle it.

I'll remove this issue from the current sprint first, and discuss the comment in the team review meeting.

**Comment by derekbit** [comment]
@longhorn/qa Can you help check if the issue is still valid? Thank you.

cc @roger-ryao @chriscchien @yangchiu

**Comment by khushboo-rancher** [comment]
@chriscchien Could you please help with this whenever get a chance?

**Comment by chriscchien** [comment]
Verified **pass** on longhorn `master` and longhorn `v1.5.5-rc2`

Create bakups in `Error` and `Completed` state,  uninstall Longhorn success, ns `longhorn-system` terminated.
