### ISSUE TITLE
[TASK] Add automation test case for IM deletion

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3104]
**What's the task? Please describe.**
The IM deletion of pod having configured file should be added to the integration test.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Create the test skeleton
- [x] Implement the test.
- [x] Verify the test is running fine in the pipeline.

**Additional context**
https://github.com/longhorn/longhorn/issues/3070

**Comment by cchien816** [comment]
Close this task.
Because after merged code, test in v1.2.x was [pass](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/44/testReport/tests/test_ha/test_recovery_from_im_deletion/)
In master head test [fail](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/64/testReport/tests/test_ha/test_recovery_from_im_deletion/) was due to product [issue](https://github.com/longhorn/longhorn/issues/3070)

**Comment by innobead** [comment]
Well done.
