### ISSUE TITLE
[BUG] Restoring backup always point to the latest backup

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3111]
**Describe the bug**

When click on **Restore** from the volume backup list, the volume will be restoring from the latest backup instead of the selected one.
![image](https://user-images.githubusercontent.com/602540/136163623-55db9579-a873-4f22-9965-e8f47fedc56a.png)

**To Reproduce**

A. Prepare backup items:
1. Create a fresh volume(ext4, 3 replicas), mounted to a node or from a pod, in order to write the filesystem.
2. Make 1st backup from the UI
3. Create 1st file* and record the checksum
4. Make 2nd backup
5. Modify 1st file and create 2nd file, and also record checksum
6. Make 3rd backup
7. Make sure the backup items are in place then clean up this volume from the UI
For now, this volume will have 3 backups, with first backup size in 0 byte.
<sup>*</sup>Test files were generated using _dd_ command

B. Steps to reproduce the behavior:
1. Restore volume from the 1st backup
2. Create a workload/deployment mount with this exist pvc
Go into the pod/container and verify the checksum under the mountpoint.
If only look at the size it is from the latest backup item:
![image](https://user-images.githubusercontent.com/602540/136165672-9105d308-8c15-4fed-8bad-cdd14cd50112.png)

**Expected behavior**

Verify if the volume is empty and not the content from 3rd backup.
To verify the behavior, by deleting 3rd backup, now when restoring the 1st backup again it will point to the 2nd backup.

**Log**

Please look at volume name with empty-test and its backups: [longhorn-support-bundle_521c4d5f-6334-401c-87d9-60900f25bed3_2021-10-06T07-55-09Z.zip](https://github.com/longhorn/longhorn/files/7291943/longhorn-support-bundle_521c4d5f-6334-401c-87d9-60900f25bed3_2021-10-06T07-55-09Z.zip)

**Environment:**

 - Longhorn version: v1.1.2, v1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.20.11
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 18.04.5 LTS 5.4.0-1056-aws
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): EC2
 - Number of Longhorn volumes in the cluster: 1 to 3

**Additional context**

An empty backup cfg file for reference:
```json

{
    "Name": "backup-c38c80c901ec4a67",
    "VolumeName": "empty-test",
    "SnapshotName": "bdf7d794-ebc6-4cca-87c1-f8cb291e2f3c",
    "SnapshotCreatedAt": "2021-10-06T04:34:24Z",
    "CreatedTime": "2021-10-06T04:34:27Z",
    "Size": "0",
    "Labels": {
        "KubernetesStatus": "{\"pvName\":\"empty-test\",\"pvStatus\":\"Bound\",\"namespace\":\"default\",\"pvcName\":\"empty-test\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":null,\"lastPodRefAt\":\"\"}",
        "desc": "empty",
        "ver": "0"
    },
    "IsIncremental": false,
    "SingleFile": {
        "FilePath": ""
    }
}
```

**Comment by joshimoo** [comment]
cc @innobead We identified the issue, relevant discussion in slack https://suse.slack.com/archives/C02DR3N5T24/p1633544000314200?thread_ts=1633539761.307400&cid=C02DR3N5T24
@PhanLe1010 is working on a fix and an analysis and postmortem write up.

**Comment by kaxing** [comment]
@yasker I can reproduce v1.1.2 on the same testing cluster. By uninstalling latest version then install v1.1.2 using _kubectl_.

**Comment by PhanLe1010** [comment]
Analysis

### When was the issue introduced:
The issue was introduced with https://github.com/longhorn/longhorn/issues/1279
commit: 1b9e30195f62d6680805b0ff614b9f13d196b727
It means it was in the code base in v1.1.0

### How is v1.1.x impacted by this?
Symptom: 
* Restoring volume from an old backup. Sometimes, the volume is restored from the latest backup
* Restoring volume from an old backup. Crash the engine of the volume while it is restoring. The volume always retries to restore from the latest backup

Root cause: 
From the code perspective, during the restoration (i.e., `v.Status.RestoreRequired=true`), if the `v.Status.LastBackup` is non empty, Volume controller overwrites `e.Spec.RequestedBackupRestore` by the latest backup: [link](https://github.com/longhorn/longhorn-manager/blob/3bba35765633fd2e4e71f4e6d3b74c6d8a8edb46/controller/volume_controller.go#L1766-L1772)

The `v.Status.LastBackup` is [sync and updated by the backup monitor ](https://github.com/longhorn/longhorn-manager/blob/3bba35765633fd2e4e71f4e6d3b74c6d8a8edb46/controller/setting_controller.go#L692-L695) every `backupstore-poll-interval` which is 300 second by default. If the backup monitor set the `v.Status.LastBackup` before the restoring finish, Volume controller will overwrite `e.Spec.RequestedBackupRestore` by the latest backup. This is a race condition.

In the case engine of volume is crashed while the volume is restoring, the Volume controller clear the field `e.Spec.RequestedBackupRestore` [here](https://github.com/longhorn/longhorn-manager/blob/3bba35765633fd2e4e71f4e6d3b74c6d8a8edb46/controller/volume_controller.go#L1180-L1191). The volume is auto attached later. It is stuck in restoring condition until the backup monitor sync `v.Status.LastBackup` and Volume controller set `e.Spec.RequestedBackupRestore` to the latest backup. At this time, volume proceeds to restore the latest backup

### How is v1.2.x impacted by this?
Symptom: 
* Restoring volume from an old backup. The volume is always restored from the latest backup
* Restoring volume from an old backup. Crash the engine of the volume while it is restoring. The volume always retries to restore from the latest backup

Root cause: 

From the code perspective, during the restoration (i.e., `v.Status.RestoreRequired=true`), if the `v.Status.LastBackup` is non empty, Volume controller overwrites `e.Spec.RequestedBackupRestore` by the latest backup: [link](https://github.com/longhorn/longhorn-manager/blob/5021be21e51ce49b1df6ec96a723408210baa31d/controller/volume_controller.go#L2319-L2325)

Unlike in 1.1.x the the backup monitor sometime win the race, in 1.2.x, the volume controller always sets the `v.Status.LastBackup` [here](https://github.com/longhorn/longhorn-manager/blob/5021be21e51ce49b1df6ec96a723408210baa31d/controller/volume_controller.go#L3319-L3320) before going into the setting `e.Spec.RequestedBackupRestore` code path [here](https://github.com/longhorn/longhorn-manager/blob/5021be21e51ce49b1df6ec96a723408210baa31d/controller/volume_controller.go#L3319-L3320) . As a result, Volume controller always overwrites `e.Spec.RequestedBackupRestore` by the latest backup
https://github.com/longhorn/longhorn-manager/pull/1081/files

### Proposer 
We only set `e.Spec.RequestedBackupRestore` to the last backup if the volume is DR volume. For normal restoring volume, set it to `v.Spec.FromBackup` 

### Why did our e2e tests not expose this issue?

Our e2e test is missing this test case that check restoration from an old backup

**Comment by khushboo-rancher** [comment]
Verified with v1.2.2-rc1

Validation - **Pass**

Below are the test cases.

1. Take multiple backups (3), restore 1st backup. Verify the data by attaching to pod.
2. Take multiple backups(3), restore 2nd and 3rd backup. Verify the data.  
3. Create backups in v1.2.1. Upgrade the longhorn image. Repeat 1st and 2nd scenario from above
4. Take multiple backups(3), Delete 2nd backup, restore 1st and 3rd backups. Verify the data
5. Take multiple backups(3), Delete latest backup, restore 1st and 2nd backups. Verify the data
6. While latest restore is in progress, delete the instance-manager-e on the attached node. The restore should restart. Verify the data
7. While 1st restore is in progress, delete the instance-manager-e on the attached node. The restore should restart. Verify the data
8. While latest restore is in progress, delete the instance-manager-r on any node. The rebuild should happen. Verify the data.
9. While 1st restore is in progress, delete the instance-manager-r on any node. The restore should restart. Verify the data.
10. Check the incremental restore of a DR volume.
11. While DR restore is in progress, delete the instance-manager-e.
12. Restore 1st backup using url via storageclass
13. Restore latest backup using url via storageclass
14 Take a backups of an RWX and Restore the 1st and latest backup to RWX volume
15. Take a backups of an RWO and Restore the 1st and latest backup to RWX volume 
16. DR set up with 2 clusters
      1. Cluster1 producer has a volume that has 3 backups.
      2. cluster2 consumer has a DR volume for the 3 backup volume, the first time this should restore the latest backup above. (do crash tests for this DR volume, you can do this on a single node cluster this will also test the surrounding code for salvage features to make sure that they not interfere with the correct restore operations)
      3. after the above restore tests including the crash tests create a new backup on cluster 1 for the existing volume
      4. verify that the DR volume restores that new backup correctly
      5. finally activate the DR volume and create a backup of it's one after writing some new data on it.
      This test should be repeated for a DR volume with the same name as the source volume and once for a DR volume with a new different name from the source volume. This can be done on the same consumer cluster setup.

Validated on master-head - '10/7/2021' - Restore from 1st backup is working fine.
