### ISSUE TITLE
[TASK] Check if the performance of backup and restore different between 1.1.2 and 1.2.2

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3181]
**What's the task? Please describe.**
After changes made during v1.2.0, we want to benchmark the backup restore performance. Compute the time taken to create backup and restore different size of data.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Backup creation time benchmarking
- [x] Restore from backup time benchmarking

**Comment by kaxing** [comment]
Hey @shuo-wu ,

Here is a benchmark result between node/pod and s3 bucket. By leveraging a neat script by [dvassallo/s3-benchmark](https://github.com/dvassallo/s3-benchmark). With following parameters:
`./s3-benchmark --bucket-name for-s3-benchmark --region ap-southeast-1 --payloads-max 12 -payloads-min 12`, test results:
```
--- SETUP --------------------------------------------------------------------------------------------------------------------

Uploading 2 MB objects
 100% |████████████████████████████████████████|  [1s:0s]

--- BENCHMARK ----------------------------------------------------------------------------------------------------------------

Download performance with 2 MB objects (m5.2xlarge)
                           +-------------------------------------------------------------------------------------------------+
                           |            Time to First Byte (ms)             |            Time to Last Byte (ms)              |
+---------+----------------+------------------------------------------------+------------------------------------------------+
| Threads |     Throughput |  avg   min   p25   p50   p75   p90   p99   max |  avg   min   p25   p50   p75   p90   p99   max |
+---------+----------------+------------------------------------------------+------------------------------------------------+
|       8 |      69.9 MB/s |  118   105   107   109   110   113   430   448 |  228   197   200   202   203   207   999  1074 |
|       9 |      83.1 MB/s |  113   102   106   108   109   111   346   408 |  215   194   199   201   203   205   759  1043 |
|      10 |      91.6 MB/s |  113   103   107   108   110   111   399   408 |  217   195   200   202   204   206   944  1049 |
|      11 |      95.6 MB/s |  114   102   106   108   110   113   401   408 |  227   194   199   201   203   209   954  1042 |
|      12 |     108.4 MB/s |  115   104   107   108   109   111   387   408 |  219   196   199   201   203   205   959  1041 |
|      13 |     116.6 MB/s |  114   101   105   107   109   111   399   410 |  221   193   198   201   203   206   971  1044 |
|      14 |     123.3 MB/s |  116   103   107   109   110   112   408   412 |  224   195   200   203   205   207  1012  1063 |
|      15 |     131.7 MB/s |  117   104   107   109   110   113   404   431 |  225   196   200   203   205   208   958  1026 |
|      16 |     133.0 MB/s |  117   102   106   107   109   114   403   408 |  237   195   199   201   204   211   990  1048 |
+---------+----------------+------------------------------------------------+------------------------------------------------+


--- CLEANUP ------------------------------------------------------------------------------------------------------------------

Deleting any objects uploaded from i-0e5ac7e62666b4a1f
 100% |████████████████████████████████████████|  [2m11s:0s]
```

**Comment by shuo-wu** [comment]
The bandwidth is 1Gi hence transferring 10Gi data would take roughly 1min30s ~ 2min. Since the data is generated by `dev/urandom` hence the compression does not contribute to reducing the transferring data size here but just slow down the backup progress. 

Based on the compression investigation in https://github.com/longhorn/longhorn/issues/1409#issuecomment-948693046: 
The total backup time (that includes the compression time) = the data transferring time * 3. 

Hence the expected time for backing up 10Gi random data is around 6min. This matches the above test result.

Conclusion: Longhorn backup works as expected. We can improve the performance by reconsidering the compression in the future.

**Comment by shuo-wu** [comment]
As for the restore, it's still unclear why the restore time varies. It can be affected by the network since the DO does not provide a guaranteed 1Gi bandwidth. Or there may be something wrong with the code. Compared with backup creation that is handled by one replica, restore always means that all replicas of a restore volume will download data from the server simultaneously from the server. Then both bandwidth and backup server type would affect the final result.

Here, there are the important factors we can be careful about anyway:
1. The backup server type should be changed when testing backup and restore.
2. The cluster & the backup server (bandwidth, CPU) for the restore should be the same as that for the backup.
3. The data are all from `/dev/urandom`.
4. For the restore, we can use 1-replica restore volume first. Then check if multiple-replica restore volume would have worse performance.

cc @innobead

**Comment by innobead** [comment]
> As for the restore, it's still unclear why the restore time varies. It can be affected by the network since the DO does not provide a guaranteed 1Gi bandwidth. Or there may be something wrong with the code. Compared with backup creation that is handled by one replica, restore always means that all replicas of a restore volume will download data from the server simultaneously from the server. Then both bandwidth and backup server type would affect the final result.
> 
> Here, there are the important factors we can be careful about anyway:
> 
> 1. The backup server type should be changed when testing backup and restore.
> 2. The cluster & the backup server (bandwidth, CPU) for the restore should be the same as that for the backup.
> 3. The data are all from `/dev/urandom`.
> 4. For the restore, we can use 1-replica restore volume first. Then check if multiple-replica restore volume would have worse performance.
> 
> The test would require more effort. Not sure if we need to do it now. cc @innobead

I think the concern is fair, but the priority can be low and @kaxing or QA can plan in the future.

**Comment by shuo-wu** [comment]
@innobead Sure. And it’s better to rename this ticket then open another ticket for the restore test.

**Comment by innobead** [comment]
> @innobead Sure. And it’s better to rename this ticket then open another ticket for the restore test.

@khushboo-rancher Please help create another one for the benchmark of backup & restore, but actually the part for backup was done already. Thanks.

**Comment by innobead** [comment]
Closing and let's track #3208
