### ISSUE TITLE
[BUG] longhorn volume I/O error, then OS tries to remout fs as read-only

### ISSUE THREAD

**Issue by cocampbe** [longhorn/longhorn#3283]
**Describe the bug**
There is one node in the cluster that has been having issues with longhorn volumes recently. It is the only  node in the cluster that does not have local longhorn storage. The lhv connections are over iscsi. Through out the day, the file system on the volume may have an I/O error. Oracle Linux then tries to keep the file system from getting corrupted by remounting it read-only. When this happens the node goes from a Ready to Not Ready state. It then returns to the ready state and the pods with longhorn volumes will be restarted on the node. 

**To Reproduce**
1. Not really sure. We just started noticing it in the last few weeks.

**Log**
[Fri Nov 19 05:30:34 2021] print_req_error: I/O error, dev sdn, sector 0
[Fri Nov 19 05:30:34 2021] sd 5:0:0:1: [sdn] Synchronizing SCSI cache
[Fri Nov 19 05:30:34 2021] print_req_error: I/O error, dev sdr, sector 0
[Fri Nov 19 05:30:34 2021] sd 9:0:0:1: [sdr] Synchronizing SCSI cache
[Fri Nov 19 05:30:35 2021] print_req_error: I/O error, dev sdq, sector 0
[Fri Nov 19 05:30:35 2021] sd 8:0:0:1: [sdq] Synchronizing SCSI cache
[Fri Nov 19 05:30:35 2021] EXT4-fs error (device sdp): ext4_wait_block_bitmap:532: comm kworker/u513:5: Cannot read block bitmap - block_group = 1, block_bitmap = 1089
[Fri Nov 19 05:30:35 2021] EXT4-fs (sdp): Delayed block allocation failed for inode 17 at logical offset 0 with max blocks 2 with error 5
[Fri Nov 19 05:30:35 2021] EXT4-fs (sdp): This should not happen!! Data will be lost

[Fri Nov 19 05:30:35 2021] Aborting journal on device sdp-8.
[Fri Nov 19 05:30:35 2021] JBD2: Error -5 detected when updating journal superblock for sdp-8.
...
[Fri Nov 19 05:30:40 2021] JBD2: Error -5 detected when updating journal superblock for sdq-8.
[Fri Nov 19 05:30:41 2021] EXT4-fs error (device sdm): ext4_journal_check_start:61: Detected aborted journal
[Fri Nov 19 05:30:41 2021] EXT4-fs (sdm): Remounting filesystem read-only
[Fri Nov 19 05:30:41 2021] bdi-block not registered

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE downstream cluster from rancher server
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 7
 - Node config
   - OS type and version: OL7u9
   - CPU per node: specific node in question has 128
   - Memory per node: specific node in question has 512GB
   - Disk type(e.g. SSD/NVMe): no longhorn volumes on node in question. Nodes hosting volumes are vdisks on SSD.
   - Network bandwidth between the nodes:
   Interval       Transfer     Bandwidth
   0.0-10.0 sec  1.09 GBytes   933 Mbits/sec

 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware and Baremetal
 - Number of Longhorn volumes in the cluster: 29, only 11 in use.

**Additional context**

**Comment by cocampbe** [comment]
[longhorn-support-bundle_701c1dea-2945-4490-bb70-30d9a6eab027_2021-11-19T13-01-40Z.zip](https://github.com/longhorn/longhorn/files/7570386/longhorn-support-bundle_701c1dea-2945-4490-bb70-30d9a6eab027_2021-11-19T13-01-40Z.zip)

**Comment by cocampbe** [comment]
I realize 1.1.0 is older. It looks like there may be improvements with this in later releases. I intend to upgrade to 1.2.2 after I can get rancher upgraded to 2.6.1 or 2.6.2.

**Comment by shuo-wu** [comment]
You mean Longhorn did volume re-attachment and re-mount **after** the pod restart? Was the mount point still valid when the issue happened? Typically this issue is caused by the volume crash whereas the workload is not restarted, which is already recored in [this article](https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/). But based on your statement, it may not fix your case.

v1.1.0 is older. Longhorn does some improvement for the stability part as well as fixing some auto-recovery related issue in v1.2.x. Updating to v1.2.2 is a good choice anyway.

BTW, when providing the support bundle, it's better to point out the problematic volume name and the rough time slot when the issue happened. There are 29 volumes in the clusters and lots of rebuilding/recovery logs in it. I don't know which one I should take.

**Comment by cocampbe** [comment]
> You mean Longhorn did volume re-attachment and re-mount **after** the pod restart? 

No. The is at the OS level, not at the k8s/pod/pvc level. The pod was running. But at the OS level, the disk was giving an I/O error. When that occured, the OS performed a remount of the volume to make it read only. The errors are ext4 journal errors. It's a protection mechanism. 

When that remount occurs, it causes an issue with the pod and likely longhorn. The pod then errors and restarts. It takes a while for the pod to come back up because the lhv still has the nodeID in the spec. 

> BTW, when providing the support bundle, it's better to point out the problematic volume name and the rough time slot when the issue happened. There are 29 volumes in the clusters and lots of rebuilding/recovery logs in it. I don't know which one I should take.

My apologies. I assumed from the log ouptut I put in the ticket, you would see the time was around [Fri Nov 19 05:30:34 2021]. This affected a few volumes, but one you could grep for is pvc-b755886b-7f83-49f2-aef5-e358eb951f91.

**Comment by shuo-wu** [comment]
What I want to ask is what happened before you encountered this remount issue.
e.g., node/network/kubelet is down then back -> the workload pod is restarted & the Longhorn volume is reattached with the pod restart. -> remount issue is triggered.

**Comment by shuo-wu** [comment]
BTW, if there are multiple volumes r/w on the node simultaneously, or there are multiple replicas on a storage node served for r/w, you may encounter a volume crash then fall into this remount error as well. This issue is improved in v1.2.x. That's why I say updating to v1.2.2 is a good choice.

**Comment by cocampbe** [comment]
> What I want to ask is what happened before you encountered this remount issue. e.g., node/network/kubelet is down then back -> the workload pod is restarted & the Longhorn volume is reattached with the pod restart. -> remount issue is triggered.

As far as I can tell, there were no issues on the node. The kubelet container was still running the whole time. But it did report a Not Ready state when the issue occured.

> BTW, if there are multiple volumes r/w on the node simultaneously, or there are multiple replicas on a storage node served for r/w, you may encounter a volume crash then fall into this remount error as well. This issue is improved in v1.2.x. That's why I say updating to v1.2.2 is a good choice.

That is interesting. But I am not sure if it's the source of this issue. The issue only occured on this one specific node. I started looking at any network issues at this point since I knew it was an iscsi connection. But I could not find anything of value in the logs. Since the issue was related to the ext4 journal, I decided to focus attention to the OS.  At that level the OS is just monitoring an iscsi disk and had an i/o error. When the OS decided to remount the ext4 fs presented from the disk, that is when the pods issue came into play. 

Thoughts I have had. One is that this node is on a different subnet than the other nodes. Not the end of the world, but maybe there was some sort of routing issue. Another is that this node has a GPU and I had to set the docker runtime to nvidia. I am not sure what issue that would cause, but it is a difference.

**Comment by shuo-wu** [comment]
The Longhorn node object or the Kubernetes node object will record why the node becomes NotReady. You can take a look when the issue is triggered. And I am thinking if the Longhorn volume is really reattached and remounted **after** the pod restart. 

The network can be a possible cause as well. But I am not sure how much impact setting a separate subnet will be. As well the NVIDIA issue, I have no idea about this part...

**Comment by cocampbe** [comment]
> And I am thinking if the Longhorn volume is really reattached and remounted after the pod restart, or if the pod is restarted after the volume reattachment.

I don't think I am explaining this well. The longhorn volume is presented to a worker node as a regular iscsi disk. That dick is then mounted to the pod on the node. The issue is that the Operating System had an issue with the iscsi disk when an i/o to the dick occured. The underlying file system is ext4, which is set within longhorn. When the i/o occured and had an issue writing to the ext4 journal, the Operating System, likley kernel, tried to remount the iscsi disk as read-only to keep the file system from being trashed. That remount caused the pod to error and restart. The pod did restart, but it took some time for the lhv to be in a ready state. I feel like I am talking about this from a standard linux OS perspective and you are only speaking of it from a k8s perspective. I understand what you are saying, but I am not sure you follow what I am trying to convey.

**Comment by shuo-wu** [comment]
> When the i/o occured and had an issue writing to the ext4 journal, the Operating System, likley kernel, tried to remount the iscsi disk as read-only to keep the file system from being trashed. That remount caused the pod to error and restart. The pod did restart, but it took some time for the lhv to be in a ready state. I feel like I am talking about this from a standard linux OS perspective and you are only speaking of it from a k8s perspective. I understand what you are saying, but I am not sure you follow what I am trying to convey.

OK, got it. The reason why I talked about this issue from a k8s perspective is that the iSCSI disk (exposed by the Longhorn volume) IO error is probably caused by it. Let me clarify this first. Here is the logic:
Kubernetes somehow marks the node as NotReady (node `pdbdwkr07corp` in the support bundle) -> Longhorn marked the engine instance manager (`instance-manager-e-9cdfe05f`) as `unknown` then `error` -> Longhorn tries to clean up this instance manager, which would lead to all volume engines crash -> All related volumes cannot be r/w -> OS encounters the IO errors in the corresponding iSCSI disk -> OS remount the disk as read-only.

In brief, the iSCSI disk IO error is probably caused by Kubernetes  & Longhorn rather than the OS. To avoid this issue, you may need to focus on why Kubernetes/Longhorn will mark the node as NotReady. Besides, after fixing https://github.com/longhorn/longhorn/issues/2650, the volumes or the engine instance managers won't crash if the node is down for a short time.

BTW, I saw that the engine instance manager `instance-manager-e-9cdfe05f` became `unknown`/`error` then got recovered several times. Before the engine instance manager is back and running, the volume on the node cannot be restarted.

**Comment by cocampbe** [comment]
@shuo-wu I understand now. I was thinking that the OS error occured, which caused the longhorn issue, then the node NotReady issue.

**Comment by shuo-wu** [comment]
Typically Longhorn volumes won't cause the node down except for the disk pressure issue.

**Comment by drmalex07** [comment]
This issue seems to be related to [this article on Troubleshooting section of Longhorn documentation](https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/).

Reading the aforementioned article, low disk performance (IOPS) is listed among the possible root causes for the abnormal behavior. Do we have something more specific on this? For example, do we have a ceiling for bandwidth (IO throughput under some specific workload like sequential/random writes) that should be considered as prohibitive for using Longhorn (on top of a disk device) ?

**Comment by derekbit** [comment]
For this issue, we have introduced https://longhorn.io/docs/1.7.2/high-availability/recover-volume/#automatic-volume-remounting for the mitigation.

**Comment by derekbit** [comment]
cc @ChanYiLin
