### ISSUE TITLE
[TASK] Generate multiple CRD versions

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3295]
## What's the task? Please describe
Longhorn will support v1beta1 and v1beta2 (storage version), so need to generate multiple CRD versions in crd.yaml by k8s/generate_code.sh instead of by manual.

- https://github.com/longhorn/longhorn-manager/pull/1126
- https://github.com/longhorn/longhorn/issues/2955

**Comment by derekbit** [comment]
The task is implemented in https://github.com/longhorn/longhorn-manager/pull/1136.

**Comment by jenting** [comment]
We'll update the code to only generate the CRD structural schema on longhorn.io/v1beta2 CRD only, and keep the longhorn.io/v1beta1 schemeless because we should not add any change on the old longhorn.io/v1beta1 anymore.

**Comment by khushboo-rancher** [comment]
@derekbit Do we have any specific test cases for this?

**Comment by derekbit** [comment]
No, we don't have specific test cases for this yet.

**Comment by kaxing** [comment]
Validation - **PASSED**
With latest master branch.

#### On functionality:
- This change is covered by the existing E2E pipeline.
- For mixed resource version scenario(upgrade from before v1.2.3) will be tested separately throughout the release process.

#### On development process:
- By checking out _generate_code.sh_, I can regenerate latest `03-crd.yaml` and deploy it without problem.

---
Additional notes on setting up the environment for _generate_code.sh_:

For unknown reason I had to export the path variable to make it run, in case anyone bump into this I am putting it here: `$ export GOPATH="$(go env GOPATH)"`

Also, for the fresh environment, controller-gen need to be satisfied separately, `go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0`. Otherwise:
```
Generating CRD
./generate_code.sh: line 59: controller-gen: command not found
```

Then, I had to manually clone longhorn-manger repo into the `$GOPATH/src/github.com/longhorn`
```
./generate_code.sh: line 64: /home/kaxing/bin/golang/1.17.7/packages/src/github.com/longhorn/longhorn-manager/deploy/install/01-prerequisite/03-crd.yaml: No such file or directory
```

Lastly:
the generated file goes into: `${GOPATH}/src/${LH_MANAGER_DIR}/deploy/install/01-prerequisite/03-crd.yaml`, in my case:
`/home/kaxing/bin/golang/1.17.7/packages/src/github.com/longhorn/longhorn-manager/deploy/install/01-prerequisite/03-crd.yaml`
