### ISSUE TITLE
[QUESTION] How many storage do I need for longhorn volume - How big can be acutal-size?

### ISSUE THREAD

**Issue by mazycool** [longhorn/longhorn#3307]
## Question
I'm going to setup application which is not stateless. We need around 1TB of storage to keep data.
Two times we hit max storage used and we decide to extend volume. But now we have an issue with underlying FS dedicated only for longhorn - it use to many data.
My question is how big can be actual size with this setup:
![image](https://user-images.githubusercontent.com/16590575/143019255-d6371f8a-6d29-452b-a129-e46344b78cb4.png)

![image](https://user-images.githubusercontent.com/16590575/143019372-3a9d2f1e-7e66-4511-98ee-b27acb78714d.png)

![image](https://user-images.githubusercontent.com/16590575/143019448-d1cc30c7-4596-4c1e-8177-248533f61852.png)

![image](https://user-images.githubusercontent.com/16590575/143019507-b491cf57-3d10-4a35-bcaf-875a5dd3df6f.png)

Automatically Cleanup System Generated Snapshot in enabled

## Environment

 - Longhorn version: 1.1.2
 - Kubernetes version: 1.20.10
 - Node config
   - OS type and version RedHat 8
   - CPU per node: 96
   - Memory per node: 300 GB
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure: Baremetal

**Comment by jenting** [comment]
@kaxing @PhanLe1010 could you please help with this one? I know we have reference architecture testing ongoing.

**Comment by PhanLe1010** [comment]
* The actual size depends on the number of snapshot inside the volume. Your volume has `Size` of 1.17 TB. In theory, each snapshot can hold a full 1.17TB of data (e.g., you write 1.17Tb of data to the volume then take a snapshot A, then rewrite 1.17TB of new data to the volume and take snapshot B. Now bot A and B has 1.17 size). The actual size of the volume is the sum of each snapshot file (e.g., size(snapshot A) + size(snapshot B) = 2.34Tb). See more detail at https://longhorn.io/docs/1.2.2/volumes-and-nodes/volume-size/
* To keep the actual size small, you should limit the number of snapshot in the volume. Creating a recurring snapshot job with retaining count 1 could be a way to keep the number of snapshot small. See https://longhorn.io/docs/1.2.2/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-the-longhorn-ui 
* Lastly, I notice that your volume has 1 replica so it is ok to have size of 1-2TB. If your volume has more than 1 replica, the max size is about 500Gb and the max `actual size` of volume must be smaller than 2TB otherwise Longhorn replication feature will fail. This is a known bug https://github.com/longhorn/longhorn/issues/2765.
