### ISSUE TITLE
[BUG] Drain stuck on K3s setup on node where RWX volume is attached

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3348]
## Describe the bug

Drain stuck in evicting `instance-manager-r-` and `instance-manager-r` on K3s setup on node where RWX volume is attached.

## To Reproduce

1. Create K3s set up v1.20.13+k3s1
2. Create rwx deployed using https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml
3. Upgrade the K3s set up to v1.21.4+k3s1 with drain. Or just drain the node where the RWX volume is attached.
4. The drain stuck, never succeeds.

## Expected behavior

The drain should work.

## Log or Support bundle

[apply-k3s-worker-plan-on-ip-172-31-2-133-with-84592a919e1-nhdls_drain.log](https://github.com/longhorn/longhorn/files/7628423/apply-k3s-worker-plan-on-ip-172-31-2-133-with-84592a919e1-nhdls_drain.log)
[longhorn-support-bundle_25ad5751-a0e7-4d63-9b5d-622fecfde6f4_2021-11-30T19-51-57Z.zip](https://github.com/longhorn/longhorn/files/7628424/longhorn-support-bundle_25ad5751-a0e7-4d63-9b5d-622fecfde6f4_2021-11-30T19-51-57Z.zip)

## Environment

 - Longhorn version: v1.1.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.20.13 / K3s v1.21.4+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04

## Additional context

Workaround: Scale down the RWX pod, the drain succeeds.

**Comment by innobead** [comment]
cc @joshimoo

**Comment by khushboo-rancher** [comment]
Discussed with @PhanLe1010, looks like this is not a regression but was never working.

**Comment by innobead** [comment]
Best efforts to the coming release, but target 1.3.0 or next coming patches of 1.2.x.

**Comment by shuo-wu** [comment]
I realized that you are using v1.1.2 rather than v1.1.3-rc2... The root cause of this is similar to https://github.com/longhorn/longhorn/issues/2933. And the fix is already in v1.1.3: https://github.com/longhorn/longhorn-manager/pull/1138.

Can you verify this issue in v1.1.3-rc2? It works for me.

--- 

In brief, when draining the node the RWX volume is attached on, the share manager pod will be migrated to another node while the volume controller auto remount logic will ask the volume to be reattached to the same node. Then the wrongly reattached volume blocks the drain forever. In v1.1.3, the share manager controller will handle this case by detaching the volume then relaunching it on the correct node.

**Comment by khushboo-rancher** [comment]
I validated this with v1.1.3-rc2, it worked fine.

Sorry for the confusion, our one of path for upgrade testing is `prior release of K3s + prior release of Longhorn --> Upgrade K3s --> Upgrade Longhorn`. So this problem occured.

Closing this issue as this is fixed in v1.1.3-rc2
