### ISSUE TITLE
[TASK] Restore to a brand new cluster that does not contain anything

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3367]
## What's the task? Please describe

Provide the doc that instructs how we can do restore for an empty cluster via Velero

## Additional context

Refer to the discussion in https://cloud-native.slack.com/archives/CNVPEL9U3/p1638530150134100?thread_ts=1638467093.129100&cid=CNVPEL9U3

**Comment by tom-mayer** [comment]
We wanted to have a very generic solution of how to backup/restore a cluster from scratch that uses longhorn as its storage provider. For etcd backup we use Velero.

  1. We backup the cluster state and exclude (note that we are also excluding PVs and PVCs):
    - persistentvolumes
    - persistentvolumeclaims
    - volumes.longhorn.io,
    - backups.longhorn.io
    - backupvolumes.longhorn.io
    - nodes.longhorn.io
    - replicas.longhorn.io
    - engines.longhorn.io
    - backingimagedatasources.longhorn.io
    - backingimagemanagers.longhorn.io,
    - backingimages.longhorn.io
    - sharemanagers.longhorn.io
    - instancemanagers.longhorn.io
    - engineimages.longhorn.io
  2. On the new cluster which is blank, we install Velero via their CLI. We restore the backup we took before with Velero which will make longhorn spin up with the old settings. The longhorn deployment/pods were in the backup, that why it is not necessary to reinstall it. Which was one of our goals. The settings/backupTarget get restored by the restore of the CRDs through Velero.
  3. (All pods that do require longhorn Volumes are now waiting because they don't have their PVCs (which we didn't backup for that exact reason)). When the longhorn ui is ready we click on the "Backup" tab which will load all the backups from the restored backupTarget. We can then batch restore all the Volumes from there
  4. On the Volumes tab when the volumes are ready, we recreate the PVs/PVCs form the UI (Actions -> Create PVC). It is crucial to tick the "Use previous PVC" checkbox in the dialog.  
  5. Claims get auto-attached to the waiting pods
  
This works since we restored etcd together with longhorn all the original namespaces are there and the PVCs will also get recreated via longhorn in their original namespaces, making the pods heal after they are there.

**Comment by khushboo-rancher** [comment]
Verified with master-head `02/16/2022`

Validation - **pass**

Follow the instructions from https://github.com/longhorn/website/pull/440 to restore in the new cluster. It worked as expected.
