### ISSUE TITLE
[FEATURE] Multi Namespace PVC support

### ISSUE THREAD

**Issue by brunnels** [longhorn/longhorn#3397]
Requesting you please add support for shared pvc's across namespaces.  This is available with portworx-volume provisioner and it would be really nice if longhorn also had this feature.

https://docs.portworx.com/portworx-install-with-kubernetes/storage-operations/create-pvcs/create-shared-pvcs/

**Comment by joshimoo** [comment]
@brunnels can you show as part of the portworx documentation where this is specified.
Since a PVC resource is namespaced on the kubernetes side. As well as a PV only beeing able to be bound to by one PVC, creation of multiple artifical PV/PVC would be required where each of the artifical PV refers to the same volume, this can for example be accomplished via multiple NFS PVC that refer to the same NFS server export.

If you just need RWX support, longhorn always has that.

**Comment by brunnels** [comment]
@joshimoo This should be the link to the docs for this feature: https://docs.portworx.com/portworx-install-with-kubernetes/storage-operations/create-pvcs/create-shared-pvcs/

Yeah, namespaced PVC's are the problem and portworx are providing the ability to use the PVC in any namespace.

**Comment by joshimoo** [comment]
@brunnels for me the page does not show anything about cross namespace pvc, instead all I see is documentation about a regular RWX volume that utilizes the old in tree portworx driver instead of the csi driver.

Can you provide a `kubectl get pv` or other demo where you are using a pvc/pv across namespaces via the portworx provisioner?

**Comment by brunnels** [comment]
I will setup again in my test cluster but I was sure I had it working cross namespace. 

In any case this would be a nice feature to have even if I am wrong about portworx having the feature.
