### ISSUE TITLE
[BUG] Can't delete engineimage after upgrade from v1.2.2 to master-head (Dec 15, 2021)

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#3407]
## Describe the bug
Can't delete engineimage after upgrade from v1.2.2 to master-head (Dec 15 2021)

## To Reproduce

1. Install Longhorn v1.2.2
2. Upgrade to master-head (Dec 15 2021)
3. try to delete v1.2.2 engine image
## Expected behavior
Engine image should be deleted

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: master-head (Dec 15 2021)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.20.8+k3s1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 8 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 0

**Comment by meldafrawi** [comment]
This issue also lead to high failure rate of nightly tests: 

e.g. https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/arm64/job/longhorn-upgrade-tests-ubuntu-arm64/

**Comment by PhanLe1010** [comment]
Thanks @jenting @derekbit 
We are guessing the story is: the garbage collector still uses the v1beta1 version of the engineimage CR. So when it tries to remove the finalizer foregroundDeletion, it tries to update the engineimage CR in the v1beta1 format which has status.condition field as a map. Since the stored version is v1beta2 which has status.condition as an array AND since there is no conversion webhook from v1beta1 to v1beta2, garbagecollector failed to remove the finalizer. The end result is the engine CR stuck in deleting state.
One more data point is that when I restart the kube-manager-controller, garbage collector starts using v1beta2 so it is able to delete the engine CR:
```
# rke2 cluster
ps -aux | grep kube-controller-manager
kill <kube-controller-manager-pid>
```

we should move conditions conversion to webhook rather than upgrade path. which should be done in https://github.com/longhorn/longhorn/issues/3265

**Comment by khushboo-rancher** [comment]
As all the tests are failing on nighty upgrade test, we are only running `test_engine_offline_upgrade`. Remember to enable all the upgrade tests after the fix is merge.
cc: @longhorn/qa

**Comment by khushboo-rancher** [comment]
Validation - **Pass**

Validated upgrade manually with Longhorn-master `01/18/2022`, the engine image can be deleted properly.
