### ISSUE TITLE
[QUESTION] does anyone know how to debug locally?

### ISSUE THREAD

**Issue by shumintao** [longhorn/longhorn#3456]
## Question

For example, debug Longhorn-Manager locally

**Comment by kaxing** [comment]
Hi @shumintao Just giving you a quick answer from testing point of view, since I am not sure which function you want to look into.

For local environment, you can consider set up with [k3s](https://k3s.io/) with VMs(VirtualBox, KVM/QEMU, or even HyperKit).

And start with collecting logs:
- `kubectl logs -f daemonset/longhorn-manager -n longhorn-system`

Then look into each pod if error messages are not having enough details:
- `kubectl get pods -l app=longhorn-manager -n longhorn-system`
- `kubectl exec -it longhorn-manager-****** -n longhorn-system -- bash`

Would be good to have more specific idea or which feature you want to debug with, so other devs can give you further details.

**Comment by shumintao** [comment]
> Hi @shumintao Just giving you a quick answer from testing point of view, since I am not sure which function you want to look into.
> 
> For local environment, you can consider set up with [k3s](https://k3s.io/) with VMs(VirtualBox, KVM/QEMU, or even HyperKit).
> 
> And start with collecting logs:
> 
> * `kubectl logs -f daemonset/longhorn-manager -n longhorn-system`
> 
> Then look into each pod if error messages are not having enough details:
> 
> * `kubectl get pods -l app=longhorn-manager -n longhorn-system`
> * `kubectl exec -it longhorn-manager-****** -n longhorn-system -- bash`
> 
> Would be good to have more specific idea or which feature you want to debug with, so other devs can give you further details.

I use dlv to remote deployment

**Comment by jenting** [comment]
In general, we use the longhorn-manager Pods' log and the related Longhorn CR to debug it.
If you'd like to contribute to Longhorn and use dlv to debug longhorn-manager, I think dlv should be workable.

Could you please tell us what's your current problem and what goal you want to achieve?

**Comment by shumintao** [comment]
I just want to understand the architecture logic of Longhorn-Manager and Longhorn-Engine through source code, and how does Replica write data to disk.

**Comment by jenting** [comment]
Awesome, thank you for being interested in Longhorn.
You could check the [concepts](https://longhorn.io/docs/1.2.3/concepts/) as well.

**Comment by jenting** [comment]
Could this question since it's been addressed, feel free to open a new question on the GitHub discussion.

**Comment by teymurov27** [comment]
@opvexe hi, could you accomplished debugging longhorn through delve?
