### ISSUE TITLE
[BUG] StorageClass of pv and pvc of a recovered pv should not always be default.

### ISSUE THREAD

**Issue by PhilipMay** [longhorn/longhorn#3506]
## Describe the bug

- I follow this guide to create an encrypted PV: https://longhorn.io/docs/1.2.3/advanced-resources/volume-encryption/ 
- created a StorageClass `longhorn-crypto-global`
- then I created a PVC (in namespace "xyz") that uses this storage class (`longhorn-crypto-global`) to get an encrypted volume
- then I create a Deployment (in namespace "xyz") that uses the pvc to create a pv
- then I create a backup to S3 using Longhorn UI
- then I delete the namespace "xyz"
- then I restore the backup
- then I create a pvc of the restored pv and check the "encrypt" checkbox
- but looking at the pv and pvc this is the output:

```text
k get pv -A
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS             REASON   AGE
pvc-250db57b-8c2a-4288-b75a-aae34cc241e8   128Mi      RWO            Delete           Bound    traefik/traefik          longhorn-crypto-global            27h
pvc-2f164f3a-3089-475a-addb-dbb59a9e3fd0   100Mi      RWO            Retain           Bound    db/postgres-pvc          longhorn-static                   7s
pvc-f44fc526-c2e8-499b-a6a1-d67363a33f89   5Gi        RWO            Delete           Bound    monitor/storage-loki-0   longhorn-crypto-global            11h

k get pvc -A
NAMESPACE   NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
xyz          postgres-pvc     Bound    pvc-2f164f3a-3089-475a-addb-dbb59a9e3fd0   100Mi      RWO            longhorn-static          12s
monitor     storage-loki-0   Bound    pvc-f44fc526-c2e8-499b-a6a1-d67363a33f89   5Gi        RWO            longhorn-crypto-global   11h
traefik     traefik          Bound    pvc-250db57b-8c2a-4288-b75a-aae34cc241e8   128Mi      RWO            longhorn-crypto-global   27h

```

- you see that the recovered pv and pvc has the storage class longhorn-static but both should have  longhorn-crypto-global.

My guess is that it uses the default storage class.
_EDIT: I checked that. If you use the UI to change the default storage class to `longhorn-crypto-global` then it is set when the pv is recovered from backup. But as I said above - that info should not be taken from the default setting but stored in the backup and taken from there._
The problem is that the storage class of the pvc can not be changed (edited) with `kubectl edit`. 

The StorageClass should be stored with the backup nd restored for pv and pvc.

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: kubeadm
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: none
 - Node config
   - OS type and version: Debian 11.01
   - CPU per node: 8 hyperthreads
   - Memory per node: 32 GB
   - Disk type(e.g. SSD/NVMe): mechanical
   - Network bandwidth between the nodes: none
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 3

**Comment by jenting** [comment]
Longhorn uses the default Longhorn Static StorageClass Name `longhorn-static` when PV/PVC is created.

And yes, we could improve this one with solutions:
- During backup, record the storage class name. And during restore, use the storage class name found in the backup metadata. It's good for a bunch of backups to restore at one time.
- During restoring and creating PV/PVC, let the user choose which StorageClass name to use. This provides more granularity to choose different storage class names per volume.

**Comment by PhilipMay** [comment]
> Longhorn uses the default Longhorn Static StorageClass Name `longhorn-static` when PV/PVC is created.
> 
> And yes, we could improve this one with solutions:
> 
>     * During backup, record the storage class name. And during restore, use the storage class name found in the backup metadata. It's good for a bunch of backups to restore at one time.
> 
>     * During restoring and creating PV/PVC, let the user choose which StorageClass name to use. This provides more granularity to choose different storage class names per volume.

Or do both. During backup, record the storage class name. And during restoring and creating PV/PVC, let the user choose which StorageClass name to use while selecting the recorded as default. That would be the best of both alternatives.

**Comment by MGlants** [comment]
Just restored cluster after big fail. Really need to somehow restore the storage class or specify one(in case of moving to another cluster). I have different recurring tasks which depend on storage-class

**Comment by PhilipMay** [comment]
> Just restored cluster after big fail. Really need to somehow restore the storage class or specify one(in case of moving to another cluster). I have different recurring tasks which depend on storage-class so after restoring my cluster stopped backup persistent volumes. Also, my helm upgrade stopped working after PVC was restored with a different class with the error of unmutable sc field. Maybe somehow allow changing storage class via longhorn manager.

Well @MGlants - I think we both talk about 2 different things. What I talk about is to restore the persistence class reference in the pvc and the pv when LH restores that from backup. And I think you talk about restoring the Persistence Class itself.

IMO this are 2 different topics. IMO you should restore your storage class after cluster failure by "hand". While LH needs to restore backups (pv and pvc) automaticaly...

**Comment by MGlants** [comment]
> > Just restored cluster after big fail. Really need to somehow restore the storage class or specify one(in case of moving to another cluster). I have different recurring tasks which depend on storage-class so after restoring my cluster stopped backup persistent volumes. Also, my helm upgrade stopped working after PVC was restored with a different class with the error of unmutable sc field. Maybe somehow allow changing storage class via longhorn manager.
> 
> Well @MGlants - I think we both talk about 2 different things. What I talk about is to restore the persistence class reference in the pvc and the pv when LH restores that from backup. And I think you talk about restoring the Persistence Class itself.
> 
> IMO this are 2 different topics. IMO you should restore your storage class after cluster failure by "hand". While LH needs to restore backups (pv and pvc) automaticaly...

Nope, I'm talking that cluster was OK, just my longhorn data failed. So I restored via longhorn gui and SC for that PVCs was longhorn-static. It was okay, but my help charts stopped working due to their states

**Comment by janlauber** [comment]
So we got multiple StorageClasses in our Environment. We manage the deployments of the infrastructure and workloads inside the cluster via FluxCD. Now you have to manually change the default longhorn static storageClass Name before every restore to the storageClass name defined in the manifest. This must be done before every restore, because FluxCD (or by default manual editing) the classname of a PVC can't change.
I really hope you can implement the suggestions of @PhilipMay

**Comment by atropos112** [comment]
I have come to an idea (which i thought was clever) to use multiple storageclasses with longhorn, using 1 replica for certain applications, 2 replicas for some and 3 replicas for others depending on use cases. In addition deciding which data should be on hdd and which on ssd's. This to me was a great solution that greatly improved my usage of longhorn, I was kicking myself for not having done this sooner. This kind of granularity (over blanket "go where there is space") I have no doubt would improve everyones setup, but since Backups do not support multi-storageclass setup, I dare to say longhorn doesn't support it either.

Should one use FluxCD or ArgoCD with clearly set out git repository representing their infrastructure, one would likely have storageClasses hard coded on application to application basis. Backups in longhorn do not support this kind of setup, simply put having to change "default storageclass" for every backup recovery cannot be considered supported, this is major as it in effect makes the user pick one of

1. GitOps & Very annoying backup recovery.
2. No GitOps & Straightforward backup recovery.

I don't think a user should be faced with such choice. Is there any plan to resolve this issue in the close future?

**Comment by wiegerthefarmer** [comment]
I'm in a disaster recovery situation and this is extremely annoying. I'm going to have to set the default before every recovery.

**Comment by ChanYiLin** [comment]
Hi @smallteeths
This issue needs UI support and the milestone is 1.5.0, thanks!

So we are adding 1 new field when creating PV/PVC in volume page
- `storageClassName`: string; value: user define, but can be empty

Thanks!

**Comment by khushboo-rancher** [comment]
Leaving a note here - Test the backup created in previous version, getting restored in 1.5.0 in addition to the other test cases.

**Comment by ChanYiLin** [comment]
Hi @khushboo-rancher 
For backups created in previous version, They don't have storageClass info recorded in the config
So when creating PV/PVC from the Volume restored from those backups, they are expected to use default storageClassName in global setting.

**Comment by khushboo-rancher** [comment]
Thanks @ChanYiLin for sharing the expectation. We'll include this case in our testing.

**Comment by roger-ryao** [comment]
**Verified on v1.5.0-rc1 20230608**

- longhorn v1.5.0-rc1 https://github.com/longhorn/longhorn/commit/6b62e767b37792b65f553689514fa3f7f3a24186

**The test steps**
https://github.com/longhorn/longhorn/issues/3506#issuecomment-1550729933

**Result**

1. The backup from 1.4.2 and the backupvolume `status.storageClassName` is `empty` on 1.5.0-rc1.
![Screenshot_20230608_142032](https://github.com/longhorn/longhorn/assets/104337648/d7392e37-bacc-47d7-b2be-925a93675184)

- [x] - Restore the backup to a new volume, create PV/PVC from the new volume without `Storage Class Name` on the UI. The PVC's storageClassName is default `longhorn-static`.
- [x] - Restore the backup to a new volume, create PV/PVC from the new volume with `Storage Class Name` on the UI. The PVC's storageClassName is `longhorn-backing-image-sc`.
![Screenshot_20230608_141926](https://github.com/longhorn/longhorn/assets/104337648/3195dd97-5d1e-4ab6-aafe-1c5d09d37082)

2. The backup from 1.5.0-rc1 **cluster-A** and the backupvolume `status.storageClassName` is `longhorn-backing-image-sc` on **cluster-B**.

- [x]    We didn't create the same StorageClass on **cluster-B**. Restore the backup to a new volume on **cluster-B**, it would show an error message:

```
unable to create volume: unable to create volume pvc-b1592691-a1e6-43c7-8a34-747a244af871: admission webhook "mutator.longhorn.io" denied the request: failed to get backing image bi-download: backingimage.longhorn.io "bi-download" not found

```
- [x]   2. After creating the backingimage, we can restore the backup to a new volume on **cluster-B**
- [ ]   3. Create PV/PVC from the new volume without `Storage Class Name` on the UI. The PVC's storageClassName is `longhorn-backing-image-sc`.  I am uncertain about the necessity of adding validation for this scenario. If the cluster doesn't have the required storageClassName, an error should be displayed.

cc @ChanYiLin

**Comment by ChanYiLin** [comment]
From my point of view, 
I don't think we need to provide such validation to help user check if the storageClass exists

There are two scenarios
###  Backing Image
- 1. Users create a Volume with BackingImage and then do the backup
- 2. Users restore the volume in another clusterB <- at this moment, user need to prepare the BackingImage in cluster B
- 3. Users now then have Volume and BackingImage. Its a static provision of volume. The creation of PV/PVC won't trigger any csi process or access storageClass param.
=> So it is okay to not have storageClass in clusterB

### Encryption 
- 1. Users create a Volume with PVC/StorageClass with the encryption params
- 2. Users do the backup
- 3. Users restore the volume in another clusterB
- 4. Users create the PV/PVC from the volume with the same StorageClass which is not created in clusterB yet.
- 5. Users will fail to mount the volume because the StorageClass and Secret not found. 
=> storageClass not found error will be caught here to remind user to create the secret and the storageClass first in clusterB

 cc @innobead

**Comment by ChanYiLin** [comment]
Hi @roger-ryao 
After discussed with @innobead , we think there is no need to add this validation.
But we will add a note in the document
