### ISSUE TITLE
[BUG] Instance Manager Memory Leak

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#3545]
## Describe the bug
One of the instance manager is using 4 CPU cores and ballooning in memory. Currently it's 19GB memory use and fast rising.

We killed the instance-manager last night but it continues right on.

![grafik](https://user-images.githubusercontent.com/7300669/149901595-fa760798-cc90-40c8-b734-4c347b4e7c17.png)

## Log or Support bundle

The afftected process is in: instance-manager-r-9c410d90
`root         763 18.2 44.4 26153392 18236828 ?   DLl  Jan11 1916:59 /host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.3/longhorn sync-agent --listen 0.0.0.0:10152 --replica 0.0.0.0:10150 --listen-port-range 10153-10162`

Is this specific to a volume? If so how can we determine it? The node is soon OOM.

Thanks for support!

Support Bundle attached.
[longhorn-support-bundle_55903fa6-26ed-4355-a4bf-17d3650572cc_2022-01-18T08-39-31Z.zip](https://github.com/longhorn/longhorn/files/7887493/longhorn-support-bundle_55903fa6-26ed-4355-a4bf-17d3650572cc_2022-01-18T08-39-31Z.zip)

## Environment

 - Longhorn version: 1.23
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster:  5
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 12
   - Memory per node: 32GB
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:  30 active

**Comment by timmy59100** [comment]
We hat to terminate the instance manager again after it reached 26GB memory. Memory is going up again and it uses almost 5 cores and the applications performance is not good.

**Comment by timmy59100** [comment]
It seems the instance manager of volume pvc-444c512d-ca4b-4eff-a991-ec29c3c201c5 is the culprit, it correleates to the process that is taking all the ressources.
But this is our most important volume right now.

**Comment by timmy59100** [comment]
Also looks like right after the snapshot/backup the error started and the volume got corrupt somehow.

**Comment by timmy59100** [comment]
After shuting down all workloads and restarting all longhorn components the volume recovered.
instead of 4000mCPU and unlimited memory. the instance-manager-r-9c410d90 is using 167mCPU and 484Mi memory.

**Comment by PhanLe1010** [comment]
Thanks @timmy59100 for reporting 

We are looking into the support bundle. It seems that there is a problematic failed backup CR (`backup-a2023cc97cd9492a`) that trigger the volume to constantly initiate new backups. There are many logs like this every 2-3 minutes:
```
2022-01-18T08:19:55.933792385Z [pvc-444c512d-ca4b-4eff-a991-ec29c3c201c5-r-28c54628] time="2022-01-18T08:19:55Z" level=info msg="Done initiating backup creation, received backupID: backup-a2023cc97cd9492a"
```

If you try to delete the backup CR by running `kubectl delete backups.longhorn.io backup-a2023cc97cd9492a -n longhorn-system`, the problem might have gone away


cc @jenting  We need to investigate the code path for this failing handing. Looking into the longhorn manager logs, I see there are 800 messages like this 
```
2022-01-18T08:38:58.669297775Z time="2022-01-18T08:38:58Z" level=warning msg="Cannot take snapshot backup" controller=longhorn-backup error="failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.3/longhorn [--url 10.42.7.67:10004 backup create --dest nfs://rs3412rpxs-01-ge4.inacta.local:/volume2/backup_cust_pax/rancher-pax-cluster --backup-name backup-a2023cc97cd9492a --label interval=daily --label KubernetesStatus={\"pvName\":\"pvc-444c512d-ca4b-4eff-a991-ec29c3c201c5\",\"pvStatus\":\"Bound\",\"namespace\":\"postgres-prod\",\"pvcName\":\"data-postgres-0\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":[{\"podName\":\"postgres-0\",\"podStatus\":\"Running\",\"workloadName\":\"postgres\",\"workloadType\":\"StatefulSet\"}],\"lastPodRefAt\":\"\"} --label RecurringJob=backup-7-cd9f4ece-d131a907 backup-7-cd9f4ece-d131a907-c-dafc4da4], output , stderr, time=\"2022-01-18T08:35:58Z\" level=info msg=\"Backing up backup-7-cd9f4ece-d131a907-c-dafc4da4 on tcp://10.42.7.66:10150, to nfs://rs3412rpxs-01-ge4.inacta.local:/volume2/backup_cust_pax/rancher-pax-cluster\"\ntime=\"2022-01-18T08:38:58Z\" level=fatal msg=\"Error running create backup command: failed to create backup to nfs://rs3412rpxs-01-ge4.inacta.local:/volume2/backup_cust_pax/rancher-pax-cluster for volume pvc-444c512d-ca4b-4eff-a991-ec29c3c201c5: rpc error: code = DeadlineExceeded desc = context deadline exceeded\"\n, error exit status 1" node=pax-p-97
```

It seems that the backup init command failed and the backup controller keep retry

**Comment by timmy59100** [comment]
Today we had the same issue again on a different cluster.

**Comment by timmy59100** [comment]
@innobead Is this fixed in the next release? Because we had to disable all backups at the moment.

**Comment by tabnul** [comment]
Same issue here. Every night after the backups ran the instance manager keeps looping with the following message.
It is also using 2 cpu cores constantly, crippling the entire node. Tried with longhorn 1.2.3 and longhorn 1.2.4 RC1

```
[pvc-51b0cc67-cbf7-481b-bea2-d3c307caf6fb-r-5c866c82] time="2022-03-07T04:10:41Z" level=info msg="Done initiating backup creation, received backupID: backup-926d8c31badd4164"
[pvc-51b0cc67-cbf7-481b-bea2-d3c307caf6fb-r-5c866c82] time="2022-03-07T04:13:38Z" level=info msg="Done initiating backup creation, received backupID: backup-926d8c31badd4164"
```

**Comment by jenting** [comment]
Related to #2807

**Comment by jenting** [comment]
Did a discussion with Phan.

The backup_controllers calls the engine's SnapshotBackup API encounters an error (because #2807 which can't finished within [3 mins timeout](https://github.com/longhorn/longhorn-engine/blob/d9b87bed2172b93ab463287d33f988bba67d441c/pkg/replica/client/client.go#L497)), the backup_controller updates the Backup CR `status.state=Error` and `status.error=<error-message>`.
- https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/engineapi/backup_monitor.go#L62
- https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/controller/backup_controller.go#L506-L507
- https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/controller/backup_controller.go#L331

However, we did not update the `status.lastSyncedAt` https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/controller/backup_controller.go#L345-L346 even we mark the `status.state=Error` already. This makes the engine's SnapshotBackup API call would execute again and again https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/controller/backup_controller.go#L317.

---

Proposal 1: modify the longhorn engine to increase the timeout value greater than 3 mins for the engine's SnapshotBackup API call. **The concern is we don't know which value is suitable or enough**.

Proposal 2: modify the backup_controller if the error message of the engine's SnapshotBackup API call is `DeadlineExceeded`, update the Backup CR:
- `status.state=Error`
- `status.error=<error-message>`
- `status.lastSyncedAt`

After the Backup CR reconcile again, it would not run into this [code](https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/controller/backup_controller.go#L317) again. So the _source of truth_ would be the remote backup target. **The concern is that since the engine's SnapshotBackup API call is failed, we would not monitor the backup creation progress because the Backup CR state is [Error](https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/controller/backup_controller.go#L345-L348). The Backup CR would be updated once the backup_volume_controller notice that there is a [change](https://github.com/longhorn/longhorn-manager/blob/02e632c9d93084a87be9dabf04313e3dc714a24f/controller/backup_volume_controller.go#L353-L354) on the remote Backup. Then, we have to update the `status.state=Completed` and clean up the `status.Error=""` once the Backup CR be synced from the remote backup target.**

Proposal 3: address the #2807, but we are still not sure if there is a corner case that 3 mins timeout is still not enough after the #2807 enhancement.

cc @PhanLe1010 @shuo-wu @joshimoo @innobead WDYT?

**Comment by innobead** [comment]
> Proposal 3: address the #2807, but we are still not sure if there is a corner case that 3 mins timeout is still not enough after the #2807 enhancement.
> 
> @PhanLe1010 @shuo-wu @joshimoo @innobead WDYT?

Prefer 3, because I would like us to fix the real cause and make the operation nearly asynchronous.

**Comment by PhanLe1010** [comment]
Agree that if we can make 3 become O(1) operation, it would be the optimal solution. Though, it will take a long time to implement it. In the mean time, the 2nd approach sounds good for the quick workaround

**Comment by meldafrawi** [comment]
@jenting  Can you add reproduce / testing steps ?

**Comment by PhanLe1010** [comment]
Reproduce steps:
1. Install Longhorn 1.2.3 using the `quay.io/jenting/longhorn-engine:master-head-ten-mins-sleep` as the default engine images
2. Create a new volume. Attach. Write 100MB of data.
3. Take backup using Longhorn UI
4. Monitor the RAM of the corresponding engine instance manager for 30 mins. It should be increasing over time and consume most of the available RAM on the node.

Test steps:
1. Repeat the above step with Longhorn 1.2.4 but verify that the engine instance manager doesn't eat all the RAM

**Comment by meldafrawi** [comment]
Validation: **PASSED**
