### ISSUE TITLE
How to set minio as longhorn backup 

### ISSUE THREAD

**Issue by kengan** [longhorn/longhorn#3570]
I have setup minio with   Self-signed Keys and Certificates  which is maked by following command
./certgen -ca -host "10.10.0.3,10.10.0.4,10.10.0.5"
I get two files, one is  public.crt，the otheris private.key,  I can use this minio as rancher backup storage
I want to use the same minio as the longhorn backup storage,
I have create a secrets in k8s namespace longhorn-system about minio
I have try to get pem from crt and key and convert to base64, but I still get error ' failed to append custom certificates'
Can you help me?  Thank  you.

**Comment by shuo-wu** [comment]
Here is the official doc that explains how to set S3-compatible storage like MinIO as Longhorn backupstore:
https://longhorn.io/docs/1.2.3/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-aws-s3-backupstore
https://longhorn.io/docs/1.2.3/snapshots-and-backups/backup-and-restore/set-backup-target/#using-a-self-signed-ssl-certificate-for-s3-communication

Can you check:
1. The backup target format
2. All required fields are set and encoded by bass64 correctly

**Comment by joshimoo** [comment]
@kengan you might want to add the service dns name as a "subjectAltName", in case you use a cluster service for the backupstore. You can have a look at our example cert, by base64 decoding the cert to get the raw pem then throw it into an online  tool or the local openssl.

[example cert](https://github.com/longhorn/longhorn/blob/159f44a0c565283ad4c02feeb4c54e920e4396f8/deploy/backupstores/minio-backupstore.yaml#L10-L11)

Most issues tend to be due to an additional new line during the base64 encoding.
