### ISSUE TITLE
[BUG] Volume fails to scheduled if while creating it couldn't be scheduled.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3626]
## Describe the bug

Volume can't be scheduled if while creation sufficient nodes were not available and later sufficient nodes becomes available.

## To Reproduce

1. Disable all the nodes.
2. Create a volume, scheduling will fail.
3. Enable scheduling on all the nodes.
4. Wait for volume to become scheduled.
5. Volume fails to scheduled.

## Expected behavior

Volume should get scheduled at any point of time when node becomes available.

## Log or Support bundle
[longhorn-support-bundle_69517e70-4622-4d1b-94fa-18b995e2523d_2022-02-14T23-25-26Z.zip](https://github.com/longhorn/longhorn/files/8064644/longhorn-support-bundle_69517e70-4622-4d1b-94fa-18b995e2523d_2022-02-14T23-25-26Z.zip)

Volume name - longhorn-testvol-d12ou6

## Environment

 - Longhorn version: Master-head, v1.2.x
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl

**Comment by shuo-wu** [comment]
Need to consider one more corner case Joshua mentioned in today's PR review session:
1. There is only one schedulable node (node X) in the cluster.
2. Create a volume, then it contains only one scheduled replica. And before the volume attachment, the scheduling condition is true while the robustness is unknown.
3. Forcibly delete node X (then try to attach the volume). Can Longhorn update the volume correctly and in time?

**Comment by PhanLe1010** [comment]
@shuo-wu 

I tried the above steps and see that after deleting a node from rancher the volume still have the `scheduled` condition as `true`
<img width="1920" alt="Screen Shot 2022-02-15 at 3 24 49 PM" src="https://user-images.githubusercontent.com/22139961/154170997-46da95ea-39f5-443d-be37-8db9aee5aef2.png">

I tried to attach the volume to a node but it fail and the volume robustness become faulted. Need to investigate more here

**Comment by PhanLe1010** [comment]
Another new conner case:
* There is an attached volume with 3 healthy replicas. A cluster of 3 worker nodes
* Try to delete a VM using Rancher 
* Rancher create a new replacement node
* The new node is ready for scheduling
* Longhorn doesn't rebuild new replicas on this node (I guess due to the Replica Replenishment Wait Interval is 600s. When the new node join the cluster, it did enqueue the volume. But the volume doesn't schedule a new replica due to Replica Replenishment Wait Interval. When the Replica Replenishment Wait Interval has passed, there is no node event that trigger the volume enqueue)  

Todo:
* May need a separate scheduler that doesn't depend on volume enqueue

**Comment by shuo-wu** [comment]
OK. And after the removal, the corresponding replica node name becomes `N/A` in the UI. How about the replica YAML?

**Comment by PhanLe1010** [comment]
> OK. And after the removal, the corresponding replica node name becomes N/A in the UI. How about the replica YAML?

<details close>
<summary>replica YAML</summary>
<br>

```
apiVersion: longhorn.io/v1beta2
kind: Replica
metadata:
  creationTimestamp: "2022-02-17T00:47:50Z"
  finalizers:
  - longhorn.io
  generation: 2
  labels:
    longhorn.io/backing-image: ""
    longhorndiskuuid: 6028c10a-53af-4242-a60f-303794e74643
    longhornnode: phan-v117-worker-4
    longhornvolume: testvol1
    manager: longhorn-manager
    operation: Update
    time: "2022-02-17T00:47:50Z"
  name: testvol1-r-a87cec74
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta2
    kind: Volume
    name: testvol1
    uid: c29f720f-f52d-420d-965f-fa509a0c407a
  resourceVersion: "6340548"
  uid: 1aa0e8b8-ec20-4788-96b7-1d6505ba5cf8
spec:
  active: true
  backingImage: ""
  baseImage: ""
  dataDirectoryName: testvol1-dbef3eb9
  dataPath: ""
  desireState: stopped
  diskID: 6028c10a-53af-4242-a60f-303794e74643
  diskPath: /var/lib/longhorn/
  engineImage: longhornio/longhorn-engine:master-head
  engineName: testvol1-e-4fb4124c
  failedAt: ""
  hardNodeAffinity: ""
  healthyAt: ""
  logRequested: false
  nodeID: phan-v117-worker-4
  rebuildRetryCount: 0
  revisionCounterDisabled: false
  salvageRequested: false
  volumeName: testvol1
  volumeSize: "21474836480"
status:
  currentImage: ""
  currentState: stopped
  evictionRequested: false
  instanceManagerName: ""
  ip: ""
  logFetched: false
  ownerID: phan-v117-worker-2
  port: 0
  salvageExecuted: false
  started: false
```

</details>

**Comment by shuo-wu** [comment]
> > OK. And after the removal, the corresponding replica node name becomes N/A in the UI. How about the replica YAML?
> 
> replica YAML
> At this point, if we try to attach the volume, we will get `unable to attach volume testvol1 to phan-v117-worker-1: cannot attach volume testvol1 because the engine image longhornio/longhorn-engine:master-head is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to`
> 
> Then, I tried to enable scheduling for one node so that the volume can schedule a new replica. It did schedule a new replica on the just-enabled node. However, when I try to attach the volume, it cannot finish attach. It became faulted:
> 
> volume YAML

After discussing with Phan in Slack, we made a consensus that Longhorn cannot/shouldn't do anything for this case. More accurately, marking the volume as Faulted is fine, and the users need to handle it by themselves. In this case, the reason for the volume being Faulted is that there is no healthy replica while the replica on the removed node will the marked as Failed. If Longhorn ignores the Failed replica here and succeeds the volume attachment, we may have trouble with the following case:
1. 3-replica volume: 2 healthy replicas.
2. 1 replica becomes failed and the 1st reusage is failed as well.
3. Suddenly, another healthy replica is removed. And the volume is detached.
4. There is one new replica created as the replacement.
5. The node that holds the reusage failed replica is removed
For Longhorn, it's hard to distinguish these 2 cases, and this volume should not be attached successfully.

**Comment by joshimoo** [comment]
Related harvester issue: https://github.com/harvester/harvester/issues/1695
As discussed before generally we shouldn't acknowledge volume creation with ok unless the volume is functional. Otherwise we tell kubernetes that the volume exists and functions which will lead to PVC -> PV binding.
This should be done by as part of the VolumeCreate api call.

**Comment by PhanLe1010** [comment]
Another conner case for this issue is:
* There is an attached volume with 3 healthy replicas. A cluster of 3 worker nodes
* Try to delete a node using rancher.
* Rancher create a new replace node
* The new node is ready for scheduling
* Longhorn doesn't rebuild new replica on this node

The issue here is that we cannot move an object to desired state (add a new replica) due to some blockers (Replica Replenishment Wait Interval). However, when the blockers are resolved, there is no change in the cluster to trigger the sync(object) reconciliation.

Some CSI sidecar seems to just add the default 10 mins resync (i.g., [csi-attacher](https://github.com/kubernetes-csi/external-attacher/blob/b042211348754b155a960d4465d9a66f19795ec1/cmd/csi-attacher/main.go#L54), [csi-resizer](https://github.com/kubernetes-csi/external-resizer/blob/ba39c7635f37e58bb822861fe47271f48ce39650/cmd/csi-resizer/main.go#L52)) to deal with this issue

However, Kubernetes still be able to handle this kind of issue with a long [12h resync](https://github.com/kubernetes/kubernetes/blob/37a0b1a3214f490c7dc50b99451a1c69d6d84ee4/staging/src/k8s.io/controller-manager/config/v1alpha1/defaults.go#L31-L33). I think the trick here is that: if there is a blocker Kubernetes requeues the object with rate-limited so it can retry resync it later with a backoff limit. In our case, maybe we can do the same which is requeued the volume CR with rate-limited if doesn't have the desired number of healthy replicas. When the volume CR is in a backoff period, if the user attaches the volume and sync() function for attaching event is failed due to a temporary error (API error), it will take another 5 minutes for us to resync the volume CR. This is not acceptable.

**Comment by shuo-wu** [comment]
The case you mentioned is related to the node/disk down case, which can be resolved by launching a separate node monitor.   Then I don't think we need to add a long backoff limit for volume re-syncing.

**Comment by shuo-wu** [comment]
OK. If the replica replenishment/reusage is unrelated to node conditions, then YES, the node monitor won't help.

You mean we can keep enqueuing degraded volumes with a backoff limit? This sounds good.

**Comment by PhanLe1010** [comment]
Another related conner case raised by @cchien816 https://github.com/longhorn/longhorn/issues/3678

**Comment by PhanLe1010** [comment]
> You mean we can keep enqueuing degraded volumes with a backoff limit? This sounds good.

Yeah, I am think about this approach. But there is a problem: while the volume CR is in a backoff period, the user attaches the volume, Longhorn run sync() function for attaching event. If the sync() is failed due to a temporary error (API error), it will be add back to the queue with 5 minutes backoff period. It will take another 5 minutes for us to resync the volume CR. This is not acceptable.

**Comment by joshimoo** [comment]
I had a quick chat with @PhanLe1010 for knowledge sharing I summarize below:
There are 2 fundamentally different problems/concepts:, for one of them using a rate limiter (flow control) is a great solution for 
the other it's not necessary and introduces unnecessary work, conflates the problem.

**problem 1**: I want to make an appointment and the line is busy so we need to keep dialing this number:
```
--> using a rate limiter + flow control for this problem is a great solution (i.e we need to keep trying this till it works)
--> this is what kubernetes does for the deployment -> replica set
--> this one we currently do for the case when there is an intermittent failure during resource processing (error retry)
```

**problem2: we are on the line and want to schedule an appointment for next wednesday:**
```
--> using a permanent retry loop for this case of problems is unnecessary since we already know, we only need to do something in the future on time X.
--> this one we currently do for like cron jobs / recurring jobs
--> this can be implemented via a monitoring routine or as a simple call to `queue.AddAfter()`
```

If you look at the code for the queue/rate limiter one will see that the rate limiter utilizes the above `AddAfter` call to enqueue the object in the future based on the current rate limiters understanding of the world.

There are 3 different calls possible:
```
queue.Add(key) // immediatly adds the item to the workqueue
queue.AddRateLimited(key) // utilizes the rate limiter, to decide when it can be added
queue.AddAfter(key, duration) // adds the item to a priority queue, for processing in the future on date X
```

**Comment by PhanLe1010** [comment]
The issue mentioned at the comment https://github.com/longhorn/longhorn/issues/3626#issuecomment-1043206989 will be tracked at https://github.com/longhorn/longhorn/issues/3529


Moving this issue forward for testing the original scheduling problem

**Comment by w13915984028** [comment]
Please check if those improvements will also solve https://github.com/longhorn/longhorn/issues/3708, thanks.

**Comment by yangchiu** [comment]
Verified passed on v1.3.0-preview1 by following steps:

1. Disable all the nodes.
2. Create a volume, scheduling will fail.
3. Enable scheduling on all the nodes.
4. Wait for volume to become scheduled.
==> Volume should get scheduled at any point of time when node becomes available.
