### ISSUE TITLE
[BUG] Longhorn webhooks fail to deploy on hardened cluster

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3701]
## Describe the bug

Longhorn admission webhook and Longhorn conversion webhook are unable to come up healthy on an RKE2 cluster with the cis-1.5 profile.

## To Reproduce

1. Create RKE2 cluster using the step listed at https://docs.rke2.io/security/hardening_guide/. eg - RKE2 version - v1.23.4+rke2r1 
2. Deploy Longhorn master-head in the cluster.
3. Longhorn deployment fails.

```
CreateContainerConfigError: container has runAsNonRoot and image will run as root (pod: "longhorn-admission-webhook-bcb579-xhffb_longhorn-system(475c3569-7dae-4427-8dca-d5eedde09c71)", container: wait-longhorn-conversion-webhook)

CreateContainerConfigError: container has runAsNonRoot and image will run as root (pod: "longhorn-conversion-webhook-55dd445b5-z57bg_longhorn-system(bae03ad5-b27a-4159-ab89-3770ce5cd7c4)", container: longhorn-conversion-webhook)
```

## Expected behavior

The webhooks should be deployed properly as other Longhorn workloads are getting deployed.

## Environment

 - Longhorn version: Longhorn-master `03/04/2022`
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.23.4+rke2r1 with cis-1.5 profile

**Comment by kaxing** [comment]
Validation - **PASSED**

Follow the hardening guide and tested with latest manifests longhorn-manager master branch. Deploy without hitting any problem.

- Cluster spec: 1 control/etc node and 3 worker nodes
  - Node distro: CentOS Stream 8 4.18.0-305.3.1.el8.x86_64
  - K8s distro: v1.22.8+rke2r1

```
$ cat /etc/rancher/rke2/config.yaml
selinux: true
protect-kernel-defaults: true
profile: cis-1.6
```
 
Additionally, quick check with rancher-cis-benchmark:2.0.3 using rke2-cis-1.6-profile-hardened profile only had 1 failed item:
<img src=https://user-images.githubusercontent.com/602540/163323884-17c26245-bf9d-44ab-a58c-83ca8fb08a3e.png height=369px />

---
##### Note for testing and setup the security enforcing cluster:
When the distro doesn't come with preinstall iscsi packages, [the auto-install DeamonSet workload](https://github.com/longhorn/longhorn-manager/blob/master/deploy/prerequisite/longhorn-iscsi-installation.yaml
) won't work due to the security policy. Therefore, it is required to manual operation on each host. The suggestion had been added as #3849
