### ISSUE TITLE
[BUG] Failed to upgrade with recurring job: `\"validator.longhorn.io\" denied the request: invalid job`

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3777]
## Describe the bug

Unable to upgrade without step onto the error when there is existing recurring jobs

## To Reproduce

1. install v1.2.4
2. goto setting: setup backup store target and tick `Allow Recurring Job While Volume Is Detached`
3. create a couple recurring jobs for backup or snaphsot
    - set cron schedule to every 1 min
4. wait for a few minutes 
5. upgrade to master-head

## Expected behavior

Upgrade should success

## Log or Support bundle

```
Stream closed EOF for longhorn-system/longhorn-manager-hvzvk (wait-longhorn-admission-webhook)
longhorn-manager W0323 10:26:12.824901       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
longhorn-manager time="2022-03-23T10:26:12Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
longhorn-manager I0323 10:26:12.863264       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
longhorn-manager I0323 10:26:12.878635       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
longhorn-manager time="2022-03-23T10:26:12Z" level=info msg="Start upgrading"
longhorn-manager time="2022-03-23T10:26:12Z" level=info msg="Upgrading from longhorn.io/v1beta1 to longhorn.io/v1beta2"
longhorn-manager time="2022-03-23T10:26:13Z" level=error msg="Upgrade failed: upgrade API version failed: fix up CRs: failed: admission webhook \"validator.longhorn.io\" denied the request: invalid job {Name: Groups:[default] Task:backup Cron:* * * * ? Retain:1 Concurrency:1 Labels:map[]}"
wait-longhorn-admission-webhook waiting
wait-longhorn-admission-webhook waiting
wait-longhorn-admission-webhook waiting
longhorn-manager time="2022-03-23T10:26:13Z" level=info msg="Upgrade leader lost: rj1-pool1-86d5e228-nwdhx"
longhorn-manager time="2022-03-23T10:26:13Z" level=fatal msg="Error starting manager: upgrade API version failed: fix up CRs: failed: admission webhook \"validator.longhorn.io\" denied the request: invalid job {Name: Groups:[default] Task:backup Cron:* * * * ? Retain:1 Concurrency:1 Labels:map[]}"
Stream closed EOF for longhorn-system/longhorn-manager-hvzvk (longhorn-manager)
```

## Environment

 - Longhorn version: v1.2.4 -> master
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.21.9+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Number of Longhorn volumes in the cluster: 3

## Additional context
n/a

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by derekbit** [comment]
In the upgrade path's `v1beta1.FixupCRs()`, `v1beta1` resources are also validated by the admission webhook.

The admission controller does the magic, because the `matchingPolicy` of the admission webhook is `equivalent`.  It means the `v1beta1` resources will be converted to `v1beta2` version, sent to the admission webhook and then validated.

To avoid the conversion while validating/mutating, the `matchingPolicy`  should use `exact`.

Ref: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchpolicy

On the other hand, [`doResourceUpgrade()`](https://github.com/longhorn/longhorn-manager/blob/e89fca5206c67423dafe2c5606f30d737b1af52e/upgrade/upgrade.go#L224) uses v1beta2 APIs, so the error might be encountered during upgrade potentially.

The resources are created or updated in `doResourceUpgrade()`
- InstanceManagers (updated)
- Volumes (updated)
- Replicas (updated)
- Nodes (updated)
- ShareManagers (updated)
- EngineImages (updated)
- BackingImages (updated)
- Engines (updated)
- BackingImageDataSources (created)
- Settings (created and updated)

`Volumes` and `Nodes`'s are validated and muting while doing `Update`. Need to check the  if there is any potential error  while handing the two types of resource.

**Comment by innobead** [comment]
This is good. Also, we need to revisit `v1beta1.FixupCRs()` to ensure the fields of resources are all fixed reasonably to avoid violating the validation rules.

**Comment by derekbit** [comment]
The error caused by`recurring.Spec.Name = =nil` is due to the `recurring.spec.name` missing in [`v1.2.x` crd manifest](https://github.com/longhorn/longhorn-manager/blob/v1.2.x/deploy/install/01-prerequisite/03-crd.yaml#L708).

The incorrect value wil be fixed in `v1beta1.FixupCRs()` and the admission webhook as well.

**Comment by derekbit** [comment]
- Check the creation of the volumes, backingImages, engineimages, recurringjobs and backuptargets in v1.2.4, and then upgrade to 1.3.0.
- Then, uninstall the cluster.

**Comment by kaxing** [comment]
Validation - **PASSED**

Tested recurring jobs created with v1.1.3 and v1.2.4 then upgrade to master-head(v1.3.0-dev<sup>*</sup>), there no more upgrade blocker.
Both snapshot and backup jobs created in previous version can be convert then upgraded to v1beta2 CR.

<sup>* longhornio/longhorn-manager@sha256:121ec7cdf95f3f702f1d0a41436aab1b1150255ae36302304ea20687ebf0bf7a</sup>
