### ISSUE TITLE
[IMPROVEMENT] Periodically clean up volume snapshots

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#3836]
## Is your feature request related to a problem? Please describe

Some users may:
  1. don't care about historical data held by volume snapshots or would like purge system snapshots (different strategies)
  2. be worried about the extra space consumed by volume snapshots;
  3. forgot to clean up volume snapshots, which then may lead to the too-many-snpashot error

Then there is no need to retain any snapshots for the volumes. Having an automatic cleanup mechanism would be convenient.

## Describe the solution you'd like

We can achieve this by adding a new kind of recurring job or enhancing the current snapshot recurring job.

## Describe alternatives you've considered

N/A for now

**Comment by LarsBingBong** [comment]
So this didn't come into v1.4.0? So it's going to hit v1.4.1 and v1.3.3 of Longhorn?

Thank you

**Comment by innobead** [comment]
> So this didn't come into v1.4.0? So it's going to hit v1.4.1 and v1.3.3 of Longhorn?
> 
> Thank you

Yes, this is the plan if no surprise.

**Comment by chriscchien** [comment]
Hi, I am not sure if we should update below test step because the last 1 system snapshot can not be deleted, from UI, command or recurring job  type snapshot-cleanup https://github.com/longhorn/longhorn/blob/e1ea3d7515e4302865944b3434591f9703e24ebe/enhancements/20230103-recurring-snapshot-cleanup.md?plain=1#L118

**Comment by c3y1huang** [comment]
> Hi, I am not sure if we should update below test step because the last 1 system snapshot can not be deleted, from UI, command or recurring job type snapshot-cleanup
> 

Talked to @chriscchien , and this is the expected behavior. Ref: https://longhorn.io/docs/1.4.0/concepts/#243-deleting-snapshots
> But Longhorn cannot do that for the latest snapshot since there is no more recent snapshot to be conflated with the deleted snapshot. The next “snapshot” of the latest snapshot is the live volume (volume-head), which is being read/written by the user at the moment, so the conflation process cannot happen.
> 
> Instead, the latest snapshot will be marked as removed, and it will be cleaned up next time when possible.

**Comment by chriscchien** [comment]
Verified on Longhorn master `e1ea3d` with test [steps](https://github.com/longhorn/longhorn/blob/e1ea3d7515e4302865944b3434591f9703e24ebe/enhancements/20230103-recurring-snapshot-cleanup.md)
Result **Pass**

Tested below cases with 1. volume and recurring job were in the same group and 2. they were not in the same group but assigned recurring job to volume.
-  Recurring job with type `snapshot-delete` will periodically delete snapshots if snapshot number greater then `spec.retain` in recurring job.
- Recurring job with type `snapshot-clean` will periodically delete all system snapshots and won't delete snapshot created by user (`userCreated: true`)

**Comment by dberardo-com** [comment]
so @chriscchien  based on your description i understand that:

* snapshot-delete --> this is needed because the retain parameter on the snapshot creation jobs was basically not doing anything in previous versions, right? and how about in v1.5+ is the retain parameter enough ? it seems to me that the snapshot-delete job needs only to be used once after upgrading, and then it can be disabled overall, what do you think ?
* snapshot-clean --> i dont know what systems snapshots are about ... would you suggest a retain value of 1 for this job, or should it be higher ? and how about frequency ?
cheers
