### ISSUE TITLE
[TASK] Bump K8s min version support, CSI sidecar versions, dependent lib version

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#3891]
## What's the task? Please describe

For each feature release, we should revisit if need to bump the minimum support version of K8s and K8s dependent libraries based on different reasons like K8s support version cycle, the minimum versions of K8s used by CSI sidecar components planned to deliver/support (like recent snapshotter), etc.  

## Describe the items of the task (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [x] Bump to the recent versions of K8s dependent libraries if needed
- [x] ~~Update the min version support of K8s if needed~~
- [x] Update CSI sidecar versions if needed

## Additional context

Add any other context or screenshots about the task request here.

**Comment by joshimoo** [comment]
This is a related issue for this task: https://github.com/longhorn/longhorn/issues/3720

**Comment by innobead** [comment]
@PhanLe1010 will help with this one w/ @joshimoo help.

**Comment by PhanLe1010** [comment]
## Steps to bum K8s, client-go, CSI sidecars, Golang version

1. Check the [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) to identify the deprecated/removed API versions that are used by Longhorn. Using the info on this document, we should be able to determine the minimum supported Kubernetes version by following the steps:
    1. Find the latest Kubernetes version Longhorn is targeting to support. Let's name it `k8s-latest`. E.g, Kubernetes `v1.25.0`
    1. Find all the removed API versions in `k8s-latest` that is being used by Longhorn. E.g., `batch/v1beta1` is removed in Kubernetes `v1.25.0` 
    1.  Find the newer versions for the above removed API versions in `k8s_latest`. E.g., `batch/v1beta1` is the newer version for `batch/v1beta1` in Kubernetes `v1.25.0` 
    1. The minimum Kubernetes version that Longhorn can support is the Kuberenetes version that supports all of the newer API versions in the above step. Let's call this version `k8s-min-supported`. E.g., `batch/v1` API version, available since v1.21 thus the minimum Kubernetes version that Longhorn can support is >= v1.21
1. Upgrade the K8s, client-go dependency library to `k8s-min-supported`
1. Findout the Golang version that is used to build `k8s-min-supported`. Upgrade Golang version to this version
1. CSI sidecars: TODO

**Comment by PhanLe1010** [comment]
Test steps:

Test uninstall 

PR for longhorn yaml

Doc

Test PSP on cluster that enable PSP


Test the CSI snapshot intensively snapshot

**Comment by PhanLe1010** [comment]
TODO: 
* Doc:
  * Support K8s in range [v1.18, v1.24] inclusively

**Comment by innobead** [comment]
I think probably we can just leverage e2e to see if any outstanding issues later.

@PhanLe1010 @yangchiu WDYT?

**Comment by PhanLe1010** [comment]
@innobead Could you help to release a new version for `longhorn-manager` so I can finish the [TODO work](https://github.com/longhorn/longhorn/issues/3891#issuecomment-1133416269)?

**Comment by innobead** [comment]
> @innobead Could you help to release a new version for `longhorn-manager` so I can finish the [TODO work](https://github.com/longhorn/longhorn/issues/3891#issuecomment-1133416269)?

v1_20220523 has been released.

**Comment by yangchiu** [comment]
For each of the Kubernetes version: [1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24], do:

* Test new install Longhorn master-head, create some volumes (RWO/RWX), workloads, backups job, snapshot jobs, test basic Longhorn functionality
  * 1.18: verified passed on v1.18.20+k3s1. (Tested in local environment since the kubectl has different output format which would make e2e test pipeline stuck)
  * [1.19](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1327/): verified passed on v1.19.16+k3s1
  * [1.20](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1329/): verified passed on v1.20.13+k3s1
  * [1.21](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1331/): verified passed on v1.21.7+k3s1
  * [1.22](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1333/): verified passed on v1.22.9+k3s1
  * [1.23](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1342/): verified passed on v1.23.1+k3s2
  * [1.24](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1335/): verified passed on v1.24.0-rc1+k3s1

* Test upgrade from older version
  * 1.18: verified passed on v1.18.20+k3s1. (Tested in local environment since the kubectl has different output format which would make e2e test pipeline stuck)
  * [1.19](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1328/): verified passed on v1.19.16+k3s1
  * [1.20](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1330/): verified passed on v1.20.13+k3s1
  * [1.21](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1332/): verified passed on v1.21.7+k3s1
  * [1.22](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1334/): verified passed on v1.22.9+k3s1
  * [1.23](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1343/): verified passed on v1.23.1+k3s2
  * [1.24](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1336/): verified passed on v1.24.0-rc1+k3s1

* Test monitoring metrics: TODO
* Test uninstallation: TODO
* Test chart installation and uninstallation: TODO
