### ISSUE TITLE
[IMPROVEMENT] Upgrade with limited resources

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#3897]
## Is your improvement request related to a feature? Please describe

Currently, Longhorn reserves 24% of the CPU resource for the engine and replica managers running on the node.

During the upgrade, since we might need to run another set of engine and replica managers per node, the request for the CPU resources will be temporarily increased to 48% of the total CPU, which might be unable to meet by the node. It will result in the upgrade being stuck in the instance manager upgrade phase.

## Describe the solution you'd like

Find a way to eliminate the possibility of being unable to upgrade due to a lack of requested CPU/memory resources.

## Describe alternatives you've considered

* Reduce the default reserved CPU percentage
* Warn user about remaining requested CPU before the upgrade, either in doc or in the upgrade mechanism.

## Additional context

None

**Comment by iosifnicolae2** [comment]
Also, it would be a good idea to improve the process of upgrading instance managers.
Here is our use-case:
1. We upgrade Longhorn to the latest version.
2. We're getting an alert because we don't have enough CPU resources (we have two versions of instance-managers in our cluster).
3. We go to Longhorn > Settings > Instance Manager Image and check **what volumes need to be detached in order to make the old instance-manager version not used by any volume**.
4. Trigger a `Redeploy` for all the Statefulsets/Deployments that are using the above volumes.
**The problem**
   - when we **trigger a redeploy**, the volumes do not detach and this will block the upgrade of instance-manager...
   - if we **scale the Statefulset/Deployment down to 0** then wait a bit and then scale it back to normal, the volume will use the latest instance-manager version

### Question
Why the volumes **are not detached when redeploying** Statefulsets/Deployments? Is it because of Longhorn or Kubernetes? @PhanLe1010 wdyt?

### Ideal solution
After we uprgade to the latest Longhorn version, we would like to **trigger a re-deployment to all Statefulsets & Deployments** so we can have a **single instance-manager version** for our entire Kubernetes cluster.

**Comment by innobead** [comment]
This will be handled in #5208
