### ISSUE TITLE
[IMPROVEMENT] Longhorn doesn't reuse failed replica on a disk with full allocated space

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#3921]
## Describe the bug

Longhorn doesn't reuse failed replicas on a disk with full allocated space

## To Reproduce

1. Create a Longhorn cluster with 3 nodes
2. Create 3 volumes such that the total size of 3 volumes is equal to the maximum allocable space
3. Attach the volumes, write some data to them
4. Reduce the `Storage Over Provisioning Percentage` setting a bit so that all nodes are un-schedulable due to allocated space being bigger than max allocated space
5. Crash replica instance manager on node-1
6. All replicas on node-1 failed. Longhorn doesn't reuse any failed replicas on node-1. Node-1 stuck there forever

## Expected behavior

Longhorn should reuse failed replica on node-1.

## Environment

 - Longhorn version: Longhorn <= v1.2.4

## Workaround

Temporary increase the storage overprovision setting so that nodes become schedulable and Longhorn reuse replicas on node-1

**Comment by PhanLe1010** [comment]
Update:

Now, I am not sure if this is a bug as the reproducing steps are problematic by themselves.

**Comment by shuo-wu** [comment]
May need to revisit this part for reusing the failed replica in unscheduable disks issue:
https://github.com/longhorn/longhorn-manager/blob/665eff6d4365aa2a6272f4354a587c30de30b05c/scheduler/replica_scheduler.go#L528-L548

**Comment by innobead** [comment]
@PhanLe1010 Also need to backport to 1.2.x. Thanks.

**Comment by cchien816** [comment]
Verified on longhorn-manager `dc17cf`
Result Pass

Steps:
- Create a Longhorn cluster with 3 nodes
- Create 3 volumes such that the total size of 3 volumes is equal to the maximum allocable space
- Attach the volumes, write some data to them
- Reduce the Storage Over Provisioning Percentage setting a bit so that all nodes are un-schedulable due to allocated space being bigger than max allocated space
- Crash replica instance manager on node-1
- All replicas on node-1 failed. 
- After a while all failed replicas on node-1 become in running status

Additional:

- Can reproduced on v1.3.0
