### ISSUE TITLE
Recommended method for rebooting nodes

### ISSUE THREAD

**Issue by paulmorabito** [longhorn/longhorn#393]
Hi,

I have a rancher (2.1.6) K8s cluster in HA mode but only with two nodes. I'm using the latest longhorn for volumes for some of my containers. One of my nodes previously crashed and upon reboot, I couldn't remount the volume in the container. I have 3 replica sets and configured longhorn to store data on both nodes.

I'd like to reboot one of my nodes for maintenance. What is the recommended way of doing this so that I don't damage the longhorn volumes? I was considering firstly pausing orchestration on all non-system/longhorn pods/deployments/services, draining the node, rebooting and then restarting orchestration. 

Would this be OK? If not, can you recommend another method?

**Comment by yasker** [comment]
Since you only have two nodes, set the default replica count to 2 is enough. Because you can only lost one node before losing the HA for the volume.

In the latest Longhorn (v0.3.3), if you reboot a node, as long as there is a replica on the other node, the volume should be attached automatically and continue to work with the container. If it's not the case, you can file a bug.

In v0.3.3, assuming you have only 2 nodes and want to reboot one of them (refer as **maintenance node**, vs **active node** which won't be rebooted), here is the recommended reboot sequence:
1. Make sure all volumes are healthy.
2. Go to the `Nodes` page. Disable the scheduling for **maintenance node**. This will stop Longhorn from rebuilding any new replicas on the node.
3. IMPORTANT: Make sure all the volumes have **at least one replica on the active node**. Otherwise you will lose data in this process.
    3.1 If it's not the case, there should be **at least two** replicas for the volume on the **maintenance node**. Then you can safely delete **one** replica for the volume.  Now volume would be in `degraded` state, and Longhorn should rebuild the replica on the **active node** shortly. Wait until the volume become `healthy` again, check to make sure the pod using the volume is still healthy, then continue with the next volume.
4. Reduce the replica count for all volumes to `min(3, n-1)`(n is the total number of the nodes, so this in your case, the result is `1`). This will stop Longhorn from rebuilding any new replicas if there is at least `min(3, n-1)` replicas available. Notice this will reduce the volume's robustness for the period.
4. Double check all the volumes have **at least one replica on the active node**.
5. For any volumes attached to **maintenance node**, it's better if you can detach them by stopping the workload using it in Kubernetes. You can identify the workload by looking at the volume name and compare it to `kubectl get pv`, then find PVC from there, and find the workload associated with the PVC.
6. Go to the `Nodes` page. Select the **maintenance node** (scheduling for the node should has been disabled), click `Replicas`. Delete the **running replicas** in the list one by one. After each replica deletion, make sure the related attached volume is still healthy.
7. Perform the maintenance on the node, e.g. reboot the node.
8. After reboot, start the workload again.
9. Enable the scheduling for the **maintenance node**.
10. Increase the replica count one by one for the volumes to `max(3, n)` (in your case, `2`) to restore the volume robustness. Watch Longhorn starts to rebuild replicas on the **maintenance node**. Wait until the volume become healthy, then continue with the next one.

Let me know if you have any question.

We will introduce a way to [identify the Kubernetes workload using the volume directly in Longhorn UI in v0.5.0](https://github.com/rancher/longhorn/issues/82), and [automated process for maintenance in v0.6.0](https://github.com/rancher/longhorn/issues/307).

**Comment by paulmorabito** [comment]
Hi,

Thanks for the detailed reply. This (largely) worked. The only stage that
didn't was step 7. If I clicked delete, nothing actually happened.

Finally, what should happen in the case of a more catastrophic failure -
for example, a node dies unexpectedly or a power outage outs all nodes? for
the first, if the volume is replicated across nodes, this would be OK? For
the second, would restarting everything restore it sufficiently?

Thanks,

**Comment by yasker** [comment]
@paulmorabito 

You meant in step 7, you cannot delete the replicas on the node? That's weird... Can you delete the same replica in the volume detail page?

For more catastrophic failures:
1. If one node failed, there won't impact the volume (except for the ones attached to that node) since we have multiple replicas across different nodes.
2. If power outage happens to all the nodes at the same time, when power is back, Longhorn will automatically attach the volumes back to the nodes. If power outage of the nodes happens at a slightly different time, you may end up with some volume in `Faulted` state. You can recover from that state using `Salvage` option of the volume. Longhorn will try it best to decide which replica contains the most recent data and use it for the volume.

**Comment by paulmorabito** [comment]
I didn't try deleting in volume download page. It may have been that I was
accessing the browser via VNC and possibly this impacted the responsiveness
of the UI but I don't think so.

Thanks for the response to the rest.
