### ISSUE TITLE
[IMPROVEMENT] Improve the error message from API

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3956]
## Is your improvement request related to a feature? Please describe

When one adds a new disk and then immediately removes the disk, the API will return the error message because the disks' spec and status are not synced yet.

![image](https://user-images.githubusercontent.com/12527233/167568868-17014023-174c-4625-b5e5-ea8612ea906d.png)

The message is not friendly to users and cannot let them understand what happened in the backend.
We can add more information in the error message.

## Additional context

https://github.com/longhorn/longhorn-tests/pull/960#issuecomment-1121931717

**Comment by cchien816** [comment]
Close this issue.

After change disk API error message from `cannot finish API request due to too many error retries` to `being syncing and please retry later` in both backend and longhorn-test repo,  
1. User will get more precise error message from UI and
2. e2e [error](https://github.com/longhorn/longhorn/issues/3951) not happen in recently build
