### ISSUE TITLE
[FEATURE] Restore BackingImage for BackupVolume in a new cluster

### ISSUE THREAD

**Issue by FrankYang0529** [longhorn/longhorn#4165]
## Is your feature request related to a problem? Please describe

A normal `Backup` for `Volume` can be restored in another cluster. However, a `Volume` based on a `BackingImage` **_can't_** be restored because we don't help users backup `BackingImage` in the backup target.

## Describe the solution you'd like

Store `BackingImage` to the backup target if a `BackupVolume` is based on it. Restore `BackingImage` without manual uploading backing images in a new cluster.

## Additional context
https://github.com/harvester/harvester/issues/2237

**Comment by yasker** [comment]
Based on the user feedback, we might want to enhance this to be able to do delta backup/restore, so it would be easier to distribute golden images for volumes.

**Comment by FrankYang0529** [comment]
I did some research about delta backup. There are two use cases, and I would like to know whether we want to implement the feature.

**Case 1: Users upload an image twice with different names**
In volume delta backup, we store volumes in different folders, so each volume only compares to itself. However, in BackingImage, we don't have this kind of relationship. To save storage space, we need to compare the new image with all existing images.

**Case 2: Users upload an image, use it to create a volume, and export the volume as a new image**
In this case, we can check the volume StorageClass to find the relationship between old and new images. However, in my experiment, it looks like we can't save much space. I uploaded a 609M BackingImage, created a 3G Volume, and exported the volume as an image. I set a block as 256 bytes, and we can only save 198,912 bytes.

```bash
> go run main.go origin.img first-exported.img
File 1 size:  637665280
File 2 size:  3221225472
Same bytes:  198912
```

Added a file with content `123` to the volume and exported an image again. We can save 1,455,144,192 bytes between two exported images.

```bash
> go run main.go first-exported.img second-exported.img
File 1 size:  3221225472
File 2 size:  3221225472
Same bytes:  1455144192
```

Based on the experiment result, we can only save space if we export a volume multiple times. However, if we store different BackingImages in different folders, it's hard to get this benefit, because exported BackingImages only link to the uploaded BackingImage. Exported BackingImages from the same volume don't link to each other.
```mermaid
graph TD;
    UploadedImage-->Volume;
    Volume-->FirstExportedImage;
    Volume-->SecondExportedImage;
```

Experiment code: https://go.dev/play/p/qVJrEY0ra6_x

**Comment by FrankYang0529** [comment]
Another design is that we can save all BackingImages in a folder and save blocks in different checksum paths like what we implemented for volume backup. In this design, we just compare block checksum paths. If it exists, we skip. If it doesn't exist, we upload the block. However, we may have the hash collision risk. If two different blocks have the same hash, it may influence many BackingImages.

**Comment by dseralathan** [comment]
Backup target is set to a NFS on both clusters .
I have created a "VMBackup" from cluster  1  and power off VM  and try to restore to the  cluster 2.
On cluster 2 the there is no backup available to restore .  any idea how we can get the backup sync from cluster1 to 2

**Comment by yasker** [comment]
@FrankYang0529 A bit more explanation about the feature.

## User Story

The user would want to have a way to deploy updated golden images to the edge locations, without requiring the edge locations to download potentially hundreds of GB of data every time when the golden image is updated.

For example:
1. The central admin decides to deploy a new VM workload to the downstream clusters.
2. The image for the workload was built. Let's call it Image_v1.
3. The central admin asks the downstream cluster admins to download the image and run the workload based on Image_v1. Image_v1 itself won't be changed. All the workloads are running on a COW layer on top of Image_v1
4. After a few weeks, the VM needs to be updated due to e.g. service patch or CVE.
5. The central admin pulls in Image_v1, updates it by starting the VM, and changes the file inside, creating Image_v2.
6. The central admin notifies the downstream cluster admins to update the workload. 
7. Downstream cluster admins download the Image_v2 (delta or not), then start using it for the new workloads, as well as migrating the old workloads to it.
8. And continue.

## Considerations
We might need to do more than just trying to efficiently backup the base image in this case. Thinking about if we can use CSI Snapshot mechanism to refactor the backing image mechanism next year. Just treat the normal volume as the backing images, and allow one volume to be a COW layer on top of the snapshot of another volume.

**Comment by yasker** [comment]
> Another design is that we can save all BackingImages in a folder and save blocks in different checksum paths like what we implemented for volume backup. In this design, we just compare block checksum paths. If it exists, we skip. If it doesn't exist, we upload the block. However, we may have the hash collision risk. If two different blocks have the same hash, it may influence many BackingImages.

No need to worry about the hash collision. If we have hash collision for the SHA512(or SHA256? I forgot which one), for the same block size, it has the same content (at least to the best of knowledge of mathematics calculation nowadays) .

**Comment by yasker** [comment]
> Backup target is set to a NFS on both clusters . I have created a "VMBackup" from cluster 1 and power off VM and try to restore to the cluster 2. On cluster 2 the there is no backup available to restore . any idea how we can get the backup sync from cluster1 to 2

You might want to check https://github.com/harvester/harvester/issues/2237 instead.

**Comment by innobead** [comment]
To sum up the requirements, there are 3 features required for the story of backing image backup & restore
- Support backing image backup & restore via CSI Snapshot (https://github.com/longhorn/longhorn/issues/5005)
- Support backing image backup & restore with delta data transfer (https://github.com/longhorn/longhorn/issues/5005)
- Support volume backup & restore if the volume is backed by a backing image (this issue)

**Comment by ChanYiLin** [comment]
Hi @innobead , I just created another issue for supporting BackingImage backup & restore with delta data transfer.
[FEATURE] Support backing image backup & restore with delta data transfer https://github.com/longhorn/longhorn/issues/5821

**Comment by innobead** [comment]
Good thanks @ChanYiLin :+1:

**Comment by ChanYiLin** [comment]
Sub-tasks
- [ ] Refactor backupstore lib to coalesce the common util functions and types in backupvolume and backupbackingimage

**Comment by roger-ryao** [comment]
**Verified on master-head 20240105**

- longhorn master-head https://github.com/longhorn/longhorn/commit/f5dd46a7496b54973f3d0621c5e96de84ea24ec1
- backing-image-manager master-head https://github.com/longhorn/backing-image-manager/commit/28b787c0ddfc95fb6af5573294e6366cdd0f87f2
- longhorn-engine master-head https://github.com/longhorn/longhorn-engine/commit/f86f4a84a19d846c20369694e01995b0f950e5fe
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/94a659f93cb22fddb41bca26f47b20880c834fcf

**The test steps**
https://github.com/longhorn/longhorn/issues/4165#issuecomment-1874946877


**Result**

- [x] require/doc : https://github.com/longhorn/website/pull/833/
- [x] require/ui : https://github.com/longhorn/longhorn/issues/7541 will be added in v1.7.0
- [x] Basic Operation : passed
- [ ] Backing up and restoring BackingImage automatically when backing up and restoring Volume
  - According to ticket's expectation, Users shouldn't need to restore the backing image first before restoring the volume.     It seems that restoring a volume requires me to manually restore the backing first. Otherwise, the UI shows an error:
``` console
Failed to create volume: unable to create volume vol-0: admission webhook "[mutator.longhorn.io]
(http://mutator.longhorn.io/)" denied the request: failed to get backing image parrot: [backingimage.longhorn.io](http://backingimage.longhorn.io/) "parrot" not found.

```     
[supportbundle_c38072a6-0547-4676-b9c3-20ff75dd28e9_2024-01-05T08-08-43Z.zip](https://github.com/longhorn/longhorn/files/13839577/supportbundle_c38072a6-0547-4676-b9c3-20ff75dd28e9_2024-01-05T08-08-43Z.zip)

![Screenshot_20240105_155032](https://github.com/longhorn/longhorn/assets/104337648/f255f16a-00f3-457a-8ceb-e3c409a7fbd6)

**Comment by ChanYiLin** [comment]
Hi, for the issues mentioned above about the admission webhook

From UI side, `Restore Latest Backup`  should provide the BackingImage name.
It currently doesn't support fill in the the BackingImage name, instead, it only supports choosing existing BackingImage in the cluster. It is incorrect.

With the Backup/Restore BackingImage feature, user should be able to fill in the BackingImage which  is not in the cluster but in the backupstore.

![Screenshot from 2024-01-05 16-44-14](https://github.com/longhorn/longhorn/assets/7100904/4bbcebeb-2877-4794-80c1-92bf81ecae19)

If it doesn't provide the BackingImage name
Than our Webhook Mutator will get the BackingImage from the BackupVolume and assigned to `volume.spec.backingImage`
And it will fail immediately at Validator because BackingImage is not found in the system.

By providing the BackingImage in UI as payload, our api will restore the BackingImage automatiaclly. [Here](https://github.com/longhorn/longhorn-manager/blob/master/manager/volume.go#L154)
But in this case, the BackingImage will be assigned in Mutator and it is too late to restore the BackingImage

I will create a UI issue for this.
For this issue, I think it is good to go.
cc @roger-ryao @innobead

**Comment by ChanYiLin** [comment]
UI issue: https://github.com/longhorn/longhorn/issues/7560

**Comment by roger-ryao** [comment]
**Verified on master-head 20240108**

- longhorn master-head https://github.com/longhorn/longhorn/commit/f5dd46a7496b54973f3d0621c5e96de84ea24ec1
- backing-image-manager master-head https://github.com/longhorn/backing-image-manager/commit/28b787c0ddfc95fb6af5573294e6366cdd0f87f2
- longhorn-engine master-head https://github.com/longhorn/longhorn-engine/commit/b41e8109a378a4ac5fbf076a4549f39ea348c1f3
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a601b9b14da2ef3bb72f225dc3bc6b94515f0d33

**The test steps**
https://github.com/longhorn/longhorn/issues/4165#issuecomment-1874946877


**Result Passed**


- [x] require/doc : https://github.com/longhorn/website/pull/833/
- [x] require/ui : https://github.com/longhorn/longhorn/issues/7541 will be added in v1.7.0
- [x] Basic Operation : passed
- [x] Backing up and restoring BackingImage automatically when backing up and restoring Volume
  -  the UI issue : https://github.com/longhorn/longhorn/issues/7560
