### ISSUE TITLE
[TASK] Verify spinning disk/HDD via the current e2e regression

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4182]
## What's the task? Please describe

We have improved the performance of the spinning disk in 1.2.0 (https://github.com/longhorn/longhorn/issues/2206), but we haven't added spinning disks as longhorn disks as part of our existing e2e regression to see if there will be some outstanding issues. 

To certificate/claim if Longhorn is able to support spinning disks, we need to improve our testing.

## Describe the items of the task (DoD, definition of done) you'd like

- [x] Add another pipeline by using spinning disks (HDD) as longhorn disks to run all e2e regression. (the K8s cluster still needs to run on SSD like the root file system)
- [x] Have a test report of 1.3.0 & 1.2.4 (recently released versions)

## Additional context

N/A

cc @longhorn/qa

**Comment by innobead** [comment]
@yangchiu we also need to have a test result here for 1.3.0. 
> ## Describe the items of the task (DoD, definition of done) you'd like
> * [ ]  Add another pipeline by using spinning disks (HDD) as longhorn disks to run all e2e regression. (the K8s cluster still needs to run on SSD like the root file system)
> * [ ]  Have a test report of 1.3.0

**Comment by yangchiu** [comment]
[Full regression test result using HDD](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1603/)

Following are failed test cases:
```
test_backing_image.test_exporting_backing_image_from_volume
test_basic.test_allow_volume_creation_with_degraded_availability_restore[s3]
test_cloning.test_cloning_with_detached_source_volume
test_cloning.test_cloning_interrupted
test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot
test_ha.test_ha_salvage
test_ha.test_rebuild_failure_with_intensive_data
test_ha.test_rebuild_replica_and_from_replica_on_the_same_node
test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion[s3]
test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion[nfs]
test_scheduling.test_replica_rebuild_per_volume_limit
test_scheduling.test_data_locality_basic
```

Among the failed test cases, the following are flaky test cases:
```
test_backing_image.test_exporting_backing_image_from_volume
test_basic.test_allow_volume_creation_with_degraded_availability_restore
test_cloning.test_cloning_with_detached_source_volume
test_cloning.test_cloning_interrupted
test_ha.test_ha_salvage
```

[The following are test cases only failed when using HDD](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1615/):
```
test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot
test_ha.test_rebuild_failure_with_intensive_data
test_ha.test_rebuild_replica_and_from_replica_on_the_same_node
test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion[s3]
test_scheduling.test_replica_rebuild_per_volume_limit
test_scheduling.test_data_locality_basic
```
They all failed due to timeouts.

**Comment by innobead** [comment]
@yangchiu Thanks. This is good. Is it/timeout related to test case implementation or the function broken?

**Comment by yangchiu** [comment]
The original timeout is RETRY_COUNTS * RETRY_INTERVAL = 300 * 0.5 = 150 sec

After modified the constants to have a longer timeout, most of the failed test cases would pass:
[Test with 4x timeout (600 sec)](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1621/): 2 failures
[Test with 8x timeout (1200 sec)](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1623/): only 1 failure: `test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot`
Test with even longer timeout, `test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot` would still fail.

==> most of the failed test cases are due to timeouts except `test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot` (https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1623/testReport/tests/test_csi_snapshotter/test_csi_snapshot_snap_create_volume_from_snapshot/). Further investigation is needed.

**Comment by yangchiu** [comment]
https://github.com/longhorn/longhorn/issues/4227 opened to track test_csi_snapshot_snap_create_volume_from_snapshot failed issue.

**Comment by innobead** [comment]
> The original timeout is RETRY_COUNTS * RETRY_INTERVAL = 300 * 0.5 = 150 sec
> 
> After modified the constants to have a longer timeout, most of the failed test cases would pass: [Test with 4x timeout (600 sec)](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1621/): 2 failures [Test with 8x timeout (1200 sec)](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1623/): only 1 failure: `test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot` Test with even longer timeout, `test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot` would still fail.
> 
> ==> most of the failed test cases are due to timeouts except `test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot` ([ci.longhorn.io/job/private/job/longhorn-tests-regression/1623/testReport/tests/test_csi_snapshotter/test_csi_snapshot_snap_create_volume_from_snapshot](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1623/testReport/tests/test_csi_snapshotter/test_csi_snapshot_snap_create_volume_from_snapshot/)). Further investigation is needed.

Probably we can make this retry as a parameter to adjust accordingly when running for HDD? Create a ticket for that improvement. WDYT?

**Comment by yangchiu** [comment]
> Probably we can make this retry as a parameter to adjust accordingly when running for HDD? Create a ticket for that improvement. WDYT?
> 
> We will need to run this kind of regression on-demand in the future as well.

Yes, it's much more reasonable. Opened https://github.com/longhorn/longhorn/issues/4228 to track this.

**Comment by innobead** [comment]
@yangchiu as discussed, we also need to run the test for 1.2.4 to see if the result is the same as 1.3.0.

**Comment by yangchiu** [comment]
**Test results of v1.2.4:**

**(1) without adjusting TIMEOUT**: [8 faltures](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1644/)

After excluding flaky test cases, failed test cases are:

```
test_ha.test_rebuild_failure_with_intensive_data
test_ha.test_rebuild_replica_and_from_replica_on_the_same_node
test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion
test_scheduling.test_replica_rebuild_per_volume_limit
test_scheduling.test_data_locality_basic
```

They are same as v1.3.0 (There's no `test_csi_snapshotter.test_csi_snapshot_snap_create_volume_from_snapshot` test case in v1.2.4)

**(2) Rerun the failed test cases with 16x longer TIMEOUT, all the test cases can pass**: [no failures](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1650/)

**Comment by yangchiu** [comment]
**Test results of v1.3.0 using sc1 cold hdd Max throughput 250 MiB/s:**

**(1) without adjusting TIMEOUT**: [19 failures](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/32/)

```
test_backing_image.test_exporting_backing_image_from_volume
test_basic.test_expansion_with_scheduling_failure
test_basic.test_multiple_volumes_creation_with_degraded_availability 
test_basic.test_allow_volume_creation_with_degraded_availability_restore 
test_cloning.test_cloning_basic
test_cloning.test_cloning_with_backing_image
test_csi.test_allow_volume_creation_with_degraded_availability_csi
test_ha.test_rebuild_failure_with_intensive_data
test_ha.test_rebuild_replica_and_from_replica_on_the_same_node
test_ha.test_rebuild_with_inc_restoration
test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion
test_ha.test_single_replica_failed_during_engine_start
test_ha.test_engine_crash_for_dr_volume
test_node.test_node_eviction_soft_anti_affinity
test_node.test_node_eviction_multiple_volume
test_rwx.test_rwx_parallel_writing
test_scheduling.test_replica_rebuild_per_volume_limit
test_scheduling.test_data_locality_basic
test_cloning.test_cloning_interrupted
```

(**2) Rerun the failed test cases with 16x longer TIMEOUT multiple times, only the following 2 test cases are always failed**:

https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/47/
https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/48/
https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/49/
https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/52/
https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/53/

```
test_basic.test_multiple_volumes_creation_with_degraded_availability
test_cloning.test_cloning_with_backing_image 
```

**Comment by yangchiu** [comment]
**Test results of v1.2.4 using sc1 cold hdd (Max throughput 250 MiB/s)**

**(1) Without adjusting TIMEOUT:** [18 failures](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/61/)

**(2) After rerun the failed test cases with longer TIMEOUT multiple times, only the following [3 test cases](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/72/) are always failed:**

```
test_cloning.test_cloning_interrupted
test_ha.test_rebuild_with_inc_restoration
test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion
```

`test_ha.test_rebuild_with_inc_restoration` and `test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion` are failed due to Longhorn API timeout which is not controlled by longhorn-tests:

`longhorn.ApiError: (ApiError(...), '500 : fail to create snapshot: error creating snapshot \'\': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn [--url 10.42.2.10:10000 snapshot create ], output , stderr, , error <nil>\n{\'code\': 500, \'detail\': \'\', \'message\': "fail to create snapshot: error creating snapshot \'\': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn [--url 10.42.2.10:10000 snapshot create ], output , stderr, , error <nil>", \'status\': 500}')`

Could already be fixed in master or v1.3.0 since master or v1.3.0 doesn't have this error.

`test_cloning.test_cloning_interrupted` could be a flaky test case with a very high failed rate. I'll rerun the test case to check the result.

**Comment by yangchiu** [comment]
**Test results of v1.3.0 using volume type st1 (Max throughput 500 MiB/s):**

**(1) Without adjusting TIMEOUT:** [9 faltures](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1653/)

```
test_backing_image.test_exporting_backing_image_from_volume
test_basic.test_allow_volume_creation_with_degraded_availability_restore
test_cloning.test_cloning_interrupted
test_csi.test_allow_volume_creation_with_degraded_availability_csi
test_ha.test_rebuild_failure_with_intensive_data
test_ha.test_rebuild_replica_and_from_replica_on_the_same_node
test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion
test_scheduling.test_replica_rebuild_per_volume_limit
test_scheduling.test_data_locality_basic
```

**(2) Rerun the failed test cases with 16x longer TIMEOUT, all the test cases can pass:** [1 failures](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1657/) except `test_cloning.test_cloning_interrupted` which is a flaky test case still need to be fixed.

**Comment by yangchiu** [comment]
Test results of v1.3.0 using volume type st1 Throughput Optimized HDD (Max throughput 500 MiB/s): https://github.com/longhorn/longhorn/issues/4182#issuecomment-1188672177
Test results of v1.3.0 using sc1 Cold HDD (Max throughput 250 MiB/s): https://github.com/longhorn/longhorn/issues/4182#issuecomment-1186644095

Test results of v1.2.4 using volume type st1 Throughput Optimized HDD (Max throughput 500 MiB/s): https://github.com/longhorn/longhorn/issues/4182#issuecomment-1186639361
Test results of v1.2.4 using sc1 Cold HDD (Max throughput 250 MiB/s): https://github.com/longhorn/longhorn/issues/4182#issuecomment-1188563337

**Comment by innobead** [comment]
Thanks @yangchiu 🙂 !

**Comment by rebeccazzzz** [comment]
As discussed with @innobead, we need to add the documentation for this issue as well.

**Comment by innobead** [comment]
The doc is updated for 1.2.4 and 1.3.0 best practices.
