### ISSUE TITLE
[IMPROVEMENT] Schedule volumes based on available disk space

### ISSUE THREAD

**Issue by iosifnicolae2** [longhorn/longhorn#4185]
## Is your improvement request related to a feature? Please describe

Today is the second time when the production was down because we did not have enough disk space for volumes.
When we've tried to move replicas between disks, the replica is not moved on a disk with the maximum available space..

## Describe the solution you'd like

Longhorn should take into consideration the available disk space when deciding where to schedule the replica.

## Describe alternatives you've considered

We're trying to use anti-affinity rules, but this only works for nodes, not disks..

**Comment by shuo-wu** [comment]
When scheduling a new replica or reusing a failed replica, Longhorn needs to consider the current available space of the disks.
For the failed replica reusage, there is another ticket tracking it: https://github.com/longhorn/longhorn/issues/3921

**Comment by yangchiu** [comment]
Verified on master-head (longhorn-manager dc17cf4) by the following steps:

(1) Create longhorn cluster with default disk on each node.
(2) Pick a random node A, attach an extra storage which has larger size than the default disk.
(3) Add this extra storage as an additional disk to the node A.
(4) Create and attach a longhorn volume, for the node A, the volume replica is scheduled to the additional disk instead of the default disk. 

and by running [the automated test case](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1700/).
