### ISSUE TITLE
[BACKPORT][v1.3.1][IMPROVEMENT] Longhorn doesn't reuse failed replica on a disk with full allocated space

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4243]
ref: https://github.com/longhorn/longhorn/issues/3921

**Comment by cchien816** [comment]
**Verified on longhorn v1.3.x dbd99b
Result Pass**

Steps:

- Create a Longhorn cluster with 3 nodes
- Create 3 volumes such that the total size of 3 volumes is equal to the maximum allocable space
- Attach the volumes, write some data to them
- Reduce the Storage Over Provisioning Percentage setting a bit so that all nodes are un-schedulable due to allocated space being bigger than max allocated space
- Crash replica instance manager on node-1
- All replicas on node-1 failed.
- After a while all failed replicas on node-1 become in running status

Additional:

- Can reproduced on v1.3.0
