### ISSUE TITLE
[BACKPORT][v1.3.x][IMPROVEMENT] Schedule volumes based on available disk space

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4261]
https://github.com/longhorn/longhorn/issues/4185

**Comment by yangchiu** [comment]
Verified on v1.3.x-head (longhorn-manager a4b5f37) by the following steps:

(1) Create longhorn cluster with default disk on each node.
(2) Pick a random node A, attach an extra storage which has larger size than the default disk.
(3) Add this extra storage as an additional disk to the node A.
(4) Create and attach a longhorn volume, for the node A, the volume replica is scheduled to the additional disk instead of the default disk.

and by running [the automated test case](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1702/).
