### ISSUE TITLE
[IMPROVEMENT] Introduce timeout mechanism for the sparse file syncing service

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4305]
## Is your improvement request related to a feature? Please describe

Currently, the file syncing service in https://github.com/longhorn/sparse-tools/blob/master/sparse/rest/handlers.go does not contain a timeout mechanism. This means that the replica rebuilding or backing image syncing (receiver side) may get stuck if the sender somehow crashes.

## Describe the solution you'd like

Add a timeout mechanism for the service.

## Additional context

This is different from https://github.com/longhorn/longhorn/issues/4054

**Comment by innobead** [comment]
cc @derekbit as well, it's about sync file resilience which is also been used in replica rebuilding/cloning.

**Comment by ChanYiLin** [comment]
Hi @shuo-wu 
From my understanding, both in the replica rebuilding or backing image syncing scenario:
- `receiver` will launch the server and wait.
- `sender` will be the client and send the file to the `receiver`. After sending the file, `sender` will call `client.close()`  to close `receiver` server so `receiver` can move on.

If we are considering the case of `sender` crash and make `receiver` stuck, shouldn't we set timeout in `receiver` ?
However, this doesn't make sense since we don't know the whole transferring time.

So the only way is to have another component to detect `sender` crash and send close to `receiver`?

WDYT?

cc @derekbit

**Comment by derekbit** [comment]
The client should be aware of the disconnection. I think we don't need an extra timeout for it, because the timeout might kill the slow replica rebuilding task accidentally.

**Comment by ChanYiLin** [comment]
For backing image syncing scenario, here is some details

https://github.com/longhorn/backing-image-manager/blob/503d3609ca7e099ba155901dbe7edd66f3005bfe/pkg/manager/service.go#L307-L368

Assume 
```
controller
       | 1. sync (sync file from B to A)
      V
managerA -- 3. Send(send file to A) -->  managerB
      | 2. start server                                              |  4. syncContent()
     V                                                                      V
[Sparse server]  <-  send file content -  [Sparse Client]
```

If ManagerB(Sender) crashes,

In ManagerA(receiver):
As in the code, we actually wait for 24 hours to check if file is ready in the end, or it will timeout [L338](https://github.com/longhorn/backing-image-manager/blob/master/pkg/manager/service.go#L338)
However, even if it timeout, it only try to release the port, but since no one call `close()` to the server so it can't release port.
We will have error message, but the `receiver` server is still stuck, and the file will be in-progress forever
```
log.WithError(err).Errorf("Backing Image Manager: failed to release port %v after syncing backing image", port)
```

**Comment by ChanYiLin** [comment]
> The client should be aware of the disconnection. I think we don't need an extra timeout for it, because the timeout might kill the slow replica rebuilding task accidentally.

Also, client send file to server by extents to extents, not just in one POST call -> [here](https://github.com/longhorn/sparse-tools/blob/master/sparse/client.go#L194)
and we already set timeout in the client side, so if the http timeouts or fails, it is handled

**Comment by shuo-wu** [comment]
IIRC we already have a long timeout for the rebuilding part (72h or 48h?). 

For the backing image syncing part, YES there is a 24h timeout to avoid the backing image getting stuck infinitely. But it's not enough. Hence the key point here is to make the **receiver/server side quickly** detect if the sender is offline. Can we add a ticker on the server side that fails the server itself when there is no data request for a period? 
On the other hand, HTTP will help handle the sender if the server/receiver crashes.

**Comment by ChanYiLin** [comment]
> IIRC we already have a long timeout for the rebuilding part (72h or 48h?).
> 
> For the backing image syncing part, YES there is a 24h timeout to avoid the backing image getting stuck infinitely. But it's not enough. Hence the key point here is to make the **receiver/server side quickly** detect if the sender is offline. Can we add a ticker on the server side that fails the server itself when there is no data request for a period? On the other hand, HTTP will help handle the sender if the server/receiver crashes.

Yes, so maybe we need to handle case by case 
The scope is not in this file https://github.com/longhorn/sparse-tools/blob/master/sparse/rest/handlers.go, but in every receiver server.
We need to add ticker in every receiver server to detect that if `sender` is offline.
For example: [here](https://github.com/longhorn/backing-image-manager/blob/master/pkg/sync/sync_file.go#L532-L554)

**Comment by innobead** [comment]
@ChanYiLin let's backport this to 1.4.x.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-engine 2d191ac) following [the test steps](https://github.com/longhorn/longhorn/issues/4305#issuecomment-1469722629).
