### ISSUE TITLE
[BUG] Error/warning during uninstallation of Longhorn v1.3.1 via manifest

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#4405]
## Describe the bug

During uninstallation of Longhorn v1.3.1, some error and warning can be seen in the logs.

## To Reproduce

1. Install Longhorn v1.3.1
2. Create some volume and attach to pod.
3. Uninstall Longhorn
4. See the below error in the uninstaller logs
```
W0811 17:47:21.868685 1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:default:longhorn-uninstall-service-account" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
--
Thu, Aug 11 2022 10:47:21 am | E0811 17:47:21.870257 1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: volumeattachments.storage.k8s.io is forbidden: User "system:serviceaccount:default:longhorn-uninstall-service-account" cannot list resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope
```

## Expected behavior

No error should be logged when during uninstallation.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl

**Comment by khushboo-rancher** [comment]
@innobead What would be the milestone for this?

**Comment by innobead** [comment]
> @innobead What would be the milestone for this?

Target for 1.4.0, and backport to 1.3.2. Good catch!

**Comment by PhanLe1010** [comment]
There are 3 ways to install Longhorn (Rancher UI, Helm, kubectl), [link](https://longhorn.io/docs/1.3.0/deploy/install/)

This problem only happens when users installs Longhorn v1.3.1 using kubectl and uninstall Longhorn v1.3.1 by deploying the yaml https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/uninstall/uninstallas mentioned in the [doc](https://longhorn.io/docs/1.3.1/deploy/uninstall/#uninstalling-longhorn-using-kubectl) 

**Root cause**
* The resource `"volumeattachments"` is missing from the uninstaller's service account

*Workaround*
* Download the yaml file https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/uninstall/uninstall
* Manually adds the `"volumeattachments"` resource to the APIgroups `"storage.k8s.io"` in the yaml file:
  ```
    - apiGroups: ["storage.k8s.io"]
      resources: ["csidrivers", "storageclasses", "volumeattachments"]
  ```
* Follow the steps in the doc but replace the yaml https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/uninstall/uninstall by this yaml

**Comment by Lichiehyao** [comment]
Verified on master-head 20220816

- longhorn master-head ([20ba35f](https://github.com/longhorn/longhorn/commit/20ba35f9a2802ff5e33ed50060077fa00176e491)) 
- longhorn-manager master-head ( [d7d200b](https://github.com/longhorn/longhorn-manager/commit/d7d200b867b5b3229d140432b975664157b2a5c0))

Result Pass

1. The issue can be reproduced on v1.3.1
2. Follow test steps in the [comment](https://github.com/longhorn/longhorn/issues/4004#issue-1241048070) and use  longhorn:master-head longhorn-manager:master-head in https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml 
3. After uninstalled Longhorn, we didn’t find out the error log in the uninstaller logs
