### ISSUE TITLE
[TASK] Integrate codecov to manage unit testing coverage

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4425]
## What's the task? Please describe

Let's leverage https://about.codecov.io/ for the unit tests coverage for major longhorn components including manager, instance-manager, engine, share-manager, and backing image manager. 

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] Integrate coverage report to codecov for each merge. 

## Additional context

[Add any other context or screenshots about the task request here.](https://docs.codecov.com/docs/github-tutorial)

**Comment by yangchiu** [comment]
@innobead wait for https://github.com/longhorn/backing-image-manager/pull/66 being merged

**Comment by innobead** [comment]
Merged. Just close it if all work. Thanks @yangchiu .

**Comment by yangchiu** [comment]
longhorn-manager, longhorn-engine, longhorn-share-manager, longhorn-instance-manager and backing-image-manger are all integrated with codecov now.
The codecov overview page of longhorn-share-manager is empty. It's because there is no any test file in longhorn-share-manager repo, and the `go test` ended up output an empty test report file.

**Comment by innobead** [comment]
cc @longhorn/dev
