### ISSUE TITLE
[BUG] Unnecessary instancemanager makes issues since v1.3.1

### ISSUE THREAD

**Issue by DrZoidberg09** [longhorn/longhorn#4467]
## Describe the bug

After installing v1.3.1 a 7th instance-manager engine gets deployed. v1.3.0 and before only spin up 6 engines (I have 3 worker nodes in my cluster). Consequently, 2 replicas of the instance-manager permanently fail to start.

## To Reproduce

1. Have a Kubernetes Cluster with 3 control planes and 3 worker nodes on v1.23.9
2. Have Rancher 2.6.6
3. Install Longhorn v1.3.1 through rancher

## Expected behavior

It should only spin up 6 instances as in v1.3.0 and before

## Log or Support bundle

Please let me know if certain logs help

**Comment by derekbit** [comment]
Can you provide the support bundle?

**Comment by DrZoidberg09** [comment]
[longhorn-support-bundle_2d71ad25-a9d0-46e9-a06a-ee5e307fbffa_2022-08-23T08-35-38Z.zip](https://github.com/longhorn/longhorn/files/9400840/longhorn-support-bundle_2d71ad25-a9d0-46e9-a06a-ee5e307fbffa_2022-08-23T08-35-38Z.zip)

**Comment by derekbit** [comment]
The two instance-managers, `instance-manager-r-b675cbd9` and `instance-manager-r-01a9f66f` are stuck at `starting` state.

The events show 
```
  reason: OutOfcpu
  message: 'Node didn''t have enough resource: cpu, requested: 480, used: 3601, capacity:
    4000'
```

**Comment by DrZoidberg09** [comment]
Two questions still remain: 
Why does it request such a high number of CPUs? Is there any need for 480 CPUs? And why does 1.3.1 spin up one more instance-manager than any other version before?

**Comment by derekbit** [comment]
For the second question, because someof the volumes' replicas are still runnig the instance-managers. You can please refer to https://longhorn.io/kb/troubleshooting-some-old-instance-manager-pods-are-still-running-after-upgrade/

![image](https://user-images.githubusercontent.com/12527233/186124112-2759300c-f9a7-4dad-b78b-19fa809038a5.png)

**Comment by DrZoidberg09** [comment]
Thanks! After cleaning up the engines, it now works fine. 
However, the high amount of requested CPUs seems strange to me (however, I am far for being an expert here :) )

**Comment by derekbit** [comment]
@DrZoidberg09 
The requested CPU 480 is because of the settings `guaranteed-engine-manager-cpu` and `guaranteed-replica-manager-cpu`. By default, the two values are 12 percent. If your are interested the settings, please refer to https://longhorn.io/docs/1.3.0/references/settings/#guaranteed-engine-manager-cpu.
