### ISSUE TITLE
[TASK] Remove redundant deploy manifest from manager repo

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4476]
## What's the task? Please describe

Right now, we keep manifests in two places: longhorn/longhorn and longhorn/longhorn-manager, but it usually will cause some extra efforts to ensure they are in sync. If they are out of sync, it's easy to cause uncertain issues.

Also, our current testing provision is based on longhorn-manager, so after this change, it should rely on longhorn/longhorn instead which will be the deployment source of truth.

## Describe the items of the task (DoD, definition of done) you'd like

- [ ] As title, also need to ensure automation tests run w/o issues.

## Additional context

https://github.com/longhorn/longhorn-manager/pull/1464#discussion_r953510547

cc @longhorn/qa @longhorn/dev

**Comment by PhanLe1010** [comment]
🚀

**Comment by yangchiu** [comment]
need to backport to v1.3.x, v1.2.x, v1.1.x

**Comment by yangchiu** [comment]
Already backport to v1.3.x and v1.2.x.

Unable to apply this change to v1.1.x, because longhorn/longhorn doesn't have v1.1.x branch. If forcibly apply this change to v1.1.x, it can only test release version like v1.1.3, and the current behavior of testing the latest version of v1.1.x like v1.1.x-head will be broken.

So pipeline v1.1.x would still have longhorn-manager dependencies.

**Comment by innobead** [comment]
That's okay for 1.1 which has been deprecated as well.
