### ISSUE TITLE
[TEST] Add automation test case for orphaned backup cleanup

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4481]
## What's the test to develop? Please describe

Add test case for https://github.com/longhorn/longhorn/issues/3898.

## Describe the items of the test development (DoD, definition of done) you'd like

- [x] Add test skeleton.
- [x] Implement automation test case

## Additional context
https://github.com/longhorn/longhorn/issues/3898#issuecomment-1226705441

**Comment by c3y1huang** [comment]
cc @mantissahz @chrisc1981

**Comment by innobead** [comment]
@mantissahz Please help at least add the test skeleton to the longhorn-test repo? then QA can help with the implementation in the future.

**Comment by khushboo-rancher** [comment]
@chriscchien Can you check if this is passing on our nightly run, you can close this?

**Comment by chriscchien** [comment]
Close this ticket because test case `test_backup_failed_enable_auto_cleanup` and `test_backup_failed_disable_auto_cleanup` had consistent test result on pipeline :
- [master-head](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/252/testReport/tests/test_basic/)
- [v1.3.x](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/144/testReport/tests/test_basic/)
- [v1.2.x](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/227/testReport/tests/test_basic/)
