### ISSUE TITLE
manager: Allow remove a node if the role of node changed from worker to non-worker

### ISSUE THREAD

**Issue by paulmorabito** [longhorn/longhorn#453]
Hi,

I'm running Rancher 2.2.0 and Kuvernetes 1.13.4.

I updated my cluster - added one node (with all three roles) and changed an existing node to remove the worker role. This was one of my nodes running longhorn and I mistakenly didn't stop scheduling or remove it from longhorn before updating the cluster.

Is there anything I can do to remove the node from longhorn? It's marked as down in the UI but I can't choose remove node as it's greyed out.

Thanks,

**Comment by paulmorabito** [comment]
I've partially resolved this here.

I re-enabled the node as a worker and disabled scheduling. I can't remove it from longhorn but it is otherwise inactive so I don't mind.

There is only one issue. One longhorn volume still has a replica on the disabled node. I can't remove the replica and also I can't delete it. It just hangs.

Any ideas?

**Comment by yasker** [comment]
@paulmorabito Longhorn can remove node when:
1. The node scheduling is disabled
2. There is no replica on that node.

Since there is one replica on that node, you won't able to delete it. And in order to delete that replica, Longhorn manager needs to be run (at least temporarily) on that node and perform the cleanup.

Are you able to remove the replica on the node while the node is still acting as a worker? Longhorn manager needs to run on that node while performing the cleanup. If not, please send me a support bundle and let me see what I can help.

**Comment by paulmorabito** [comment]
I re-enabled the node as a worker, deleted the remaining volume and
disabled it as a worker again. The node is now listed as down in longhorn
(it has controlpane and etcd roles only). I can select remove, however the
error I get is:

"Unable to delete node: Could not delete node 192.168.1.113 with node ready
condition is False, reason is ManagerPodMissing, node schedulable false,
and 0 replica, 0 engine running on it"

so I guess, I need the manager to be active on the node for it to be
deleted? It's ok either way at this point, not an issue.

Thanks for your help.

**Comment by yasker** [comment]
@paulmorabito This is a bug. Normally we allow removing of the node if the node has been removed from the cluster. But we didn't take node role changing into non-worker into consideration so it's not allowed.

We will fix this in the next release.

**Comment by meldafrawi** [comment]
Longhorn Version: 0.5.0-rc2

Can remove node when Role changed from`worker` to `non-worker`.

**Comment by yasker** [comment]
Due to https://github.com/longhorn/longhorn/issues/574, we need to fix this issue in a different way.

I cannot find a universal method to determine the Kubernetes node's role. For example, GKE sets no node role in the node label.

We probably have to rely on if the manager pod exists on the pod or not instead (`NodeConditionReasonManagerPodMissing`).

**Comment by meldafrawi** [comment]
Validation: **PASSED**

Steps to test: (using RKE)
  - Change a worker node's role from `worker` to `non-worker` (etcd / controleplane).
  >> Expected result: on `Nodes` page, from right drop down menu, `Remove  Node` option should be available.
