### ISSUE TITLE
kubernetes v1.13.5 driver name io.rancher.longhorn not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by vincent927** [longhorn/longhorn#455]
When I upgraded from 1.16 to 1.13.5 ， it was wrong .

```
driver name io.rancher.longhorn not found in the list of registered CSI drivers
```

**Comment by yasker** [comment]
Which version of Kubernetes you're using before? 

If it was 1.11 or less, you need to delete the driver deployer pod to allow redeploy of Longhorn CSI drivers, since the registration mechanism changed starting Kubernetes 1.12.

You can refer to https://github.com/rancher/longhorn/issues/425#issuecomment-468864486 and later comments.

For Longhorn v0.4.0 or before, you need to follow https://github.com/rancher/longhorn/issues/425#issuecomment-468893915 instead. We've fixed the deployer for changing kubernetes version in v0.4.1.
