### ISSUE TITLE
Add arm64v8 support

### ISSUE THREAD

**Issue by giminni** [longhorn/longhorn#458]
Please add arm64v8 support. Thx

**Comment by giminni** [comment]
@yasker K3s suport armhf, arm64 and amd64 is there a change to compile by myself longhorn-manager, controller and ui?

**Comment by yasker** [comment]
We haven't looked into arm64v8 support yet...

On the other hand, you should able to only deploy manager on certain nodes by modify the manager deployment yaml file. Though the engine image daemonset will likely fail since the image supports amd64 only. We're looking at some ways to customize a few workloads generated by Longhorn manager, including engine image daemonset (https://github.com/longhorn/longhorn/issues/584).

**Comment by giminni** [comment]
Thanks @yasker 

BTW I asked the K3s team if there could be a seamless integration between longhorn and k3s for all the supported architectures. (https://github.com/rancher/k3s/issues/567)

**Comment by AlexMikhalev** [comment]
Subscribed. I would love to see longhorn on RPi so I can create RPi based storage cluster.

**Comment by agustinvinao** [comment]
would be great to have this working on arm64, armhf.

**Comment by markmaas** [comment]
Perhaps when Apple comes with their ARM processors, we will see more software be available on ARM as well ;-)

**Comment by joshimoo** [comment]
Linking to full arm feature request: longhorn/longhorn#6

**Comment by yasker** [comment]
Close this issue since ARM64 support has been added in #6.

**Comment by AlexMikhalev** [comment]
@yasker thank you.
