### ISSUE TITLE
[IMPROVEMENT] Review/consolidate  the sectorSize in replica server, replica volume, and engine

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4599]
## Is your improvement request related to a feature? Please describe

Right now [the default sectorSize of replica volume](https://github.com/longhorn/longhorn-engine/blob/330a008f54ff90cf16d604925e1e915980d640b4/pkg/replica/replica.go#L33) is 4096 bytes while [the default sectorSize of replica server](https://github.com/longhorn/longhorn-engine/blob/330a008f54ff90cf16d604925e1e915980d640b4/app/cmd/replica.go#L85) is 512 bytes. The engine controller sectorSize is currently the same with replica server sectorSize. There is a also [default sector size of 512 in backing image](https://github.com/longhorn/longhorn-engine/blob/330a008f54ff90cf16d604925e1e915980d640b4/pkg/backingfile/backingfile.go#L19). We should reconsider and consolidate these values. It seems that the sectorSize of controller and replica server is not used anywhere so should be deprecated it?

**Comment by innobead** [comment]
cc @shuo-wu @joshimoo

**Comment by derekbit** [comment]
We will change the block size of the iSCSI LUN to 4096 to avoid the data corruption caused by the read-modify-write's race condition.

There are some tasks we need to do
- Add the new field `engine.spec.blocksize`.
   By default it is 512 for all existing volumes. For a new volume, it will get 4096. Then we can launch the engine with the correct physical block size.

- For the existing volume containing a filesystem with non-4096 blocksize, it is still facing the risk of data corruption. We need to provide a script and document for helping find the volumes at stake and migrat the volumes to new ones.

**Comment by derekbit** [comment]
**Use the solution [Using specific block size in Longhorn volume’s filesystem](https://github.com/longhorn/longhorn/issues/4594), instead.**

For the newly created LH filesystem-mode volume, the filesystem data/metadata block size will be 4096 rather than 512. Then we can avoid the two io performance drop
- IO performance drop on a volume with filesystem block size less than 4096 because of the [patch](https://github.com/longhorn/longhorn-engine/pull/745)  during replica rebuilding
- Frequent read-modify-write operation if the filesystem block size is less than 4096 ([code](https://github.com/longhorn/longhorn-engine/blob/master/pkg/replica/diff_disk.go#L62)).

We still use 512 as the iSCSI LUN block size in order to
- Guarantee the backward compatibility for existing filesystem-mode and block-mode volumes
- Does not introduce any impact to newly created block-mode volumes.

---

In this ticket, we will continue reorganizing the volume, replica and backingimage sector size in longhorn-engine and make the codes more understanable.

**Comment by PhanLe1010** [comment]
@derekbit Could you please update the template https://github.com/longhorn/longhorn/issues/4599#issuecomment-1260373378 to reflect the final selected PRs for this issue? Thank you very much

**Comment by derekbit** [comment]
> @derekbit Could you please update the template [#4599 (comment)](https://github.com/longhorn/longhorn/issues/4599#issuecomment-1260373378) to reflect the final selected PRs for this issue? Thank you very much

Ah, thank you for the reminder.

**Comment by yangchiu** [comment]
@derekbit Could you elaborate more about how to verify this ticket or what we/users expect to see after this PR? Thank you!

**Comment by derekbit** [comment]
@yangchiu 
Updated the method https://github.com/longhorn/longhorn/issues/4599#issuecomment-1260373378

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-engine 691122a) by following https://github.com/longhorn/longhorn/issues/4599#issuecomment-1260373378.

For both ex4 and xfs filesystem, the sector size and block size are expected 512 bytes and 4KB.
