### ISSUE TITLE
[IMPROVEMENT] Add ability to disable storage class management, creation, deployment (usability, appliance, harvester)

### ISSUE THREAD

**Issue by joshimoo** [longhorn/longhorn#4686]
## Is your improvement request related to a feature? Please describe

From a usability perspective for people distributing longhorn internally for example harvester.
It might be nice to just add a setting to longhorn to disable managment/creation/etc of the `longhorn` storage class.

This is useful for https://github.com/harvester/harvester/issues/2692 to not have the 2 different classes.
But also if a user wants to provide their own dedicated storage classes to their end users.

## Describe the solution you'd like

Add a setting to disable the config map --> longhorn storage class controller parts.
This setting should be setable during deployment, for example helm, catalog, etc.

## Describe alternatives you've considered

Harvester could hide the storage class from their UI, but it's really unnecessary since this is such a small change for us that would also benefit any users that utilize longhorn as an appliance.

## Additional context
- https://github.com/harvester/harvester/issues/2692

**Comment by ejweber** [comment]
This is my proposed solution:

1. Create a new Helm variable that omits the longhorn-storageclass ConfigMap on Helm install or upgrade if enabled. (https://github.com/longhorn/longhorn/pull/7910)
2. Modify longhorn-manager so that it deletes the default StorageClass if the ConfigMap is deleted. (It obviously already doesn't create the default StorageClass if the ConfigMap doesn't exist.) We don't want to set a finalizer on the user-created ConfigMap, so the implementation tries to avoid the need for one. (https://github.com/longhorn/longhorn-manager/pull/2579)
3. Set the helm variable to false in the Harvester `values.yaml` (for the Harvester use case). (https://github.com/harvester/harvester/blob/master/deploy/charts/harvester/values.yaml#L387-L426)

I think the biggest question is, do we want the StorageClass to go away when the ConfigMap does? Or do we just want to leave it alone and not create/update it. In other words, do we want number 2 of the above?

**Comment by ejweber** [comment]
After discussing this with @PhanLe1010 and @james-munson, there are two concerns:

1. I was working under the assumption that the StorageClass was only referenced during volume creation. If that were the case, removing it automatically would have very low impact on users (who presumably intended for it to happen.) However, the StorageClass is also referenced during volume expansion. (See https://github.com/longhorn/longhorn/issues/6446 and https://github.com/kubernetes/kubernetes/blob/5bf23121cc45888e78992f5e29183ad03dbfa0ae/plugin/pkg/admission/storage/persistentvolume/resize/admission.go#L107-L110). This makes automatically removing the StorageClass potentially a bit more annoying.
2. There is some pushback against the usefulness of the feature at all. Since Harvester uses its own `longhorn-harvester` StorageClass, it's not clear what negative impact there is to also having the `longhorn` StorageClass hanging around.

Current recommendations:

1. Get rid of the auto-deletion behavior in https://github.com/longhorn/longhorn-manager/pull/2579. If the user wants us to never create the default StorageClass, they can use the new Helm variable and/or remove the ConfigMap from `deploy/longhorn.yaml`. If the StorageClass already exists, the user can manually delete it after taking the previous step. (Harvester could do this too in upgrade if it wanted to.)
2. Gather feedback from Harvester and Longhorn devs on whether this is actually useful.

**Comment by ejweber** [comment]
After discussing it internally with the Harvester team, they see no particular reason to implement this feature. It won't be hard to implement in the future if necessary, but for now, I suggest we close this one as "not planned". It seems it will just be additional Helm variable bloat that might only confuse users.

Do you have any objections @innobead?

**Comment by innobead** [comment]
Sounds good to me. The context has been changed, and Harvester ships with its own storage class too. This request is not valid anymore.
