### ISSUE TITLE
[TASK] Add issues created by non-project users to community project

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4701]
## What's the task? Please describe

If any issues created by non-project users or actually from community users, add issues directly to the Community Issue Review project. 

Why? this can save some manual operation for the Community Issue Coordinator or if they forget to add issues to the project, it's possible to miss the opportunity to follow up on the issue status.

## Describe the items of the task (DoD, definition of done) you'd like

- [x] By GitHub action to add issues to the project as mentioned above

## Additional context

N/A

cc @longhorn/dev

**Comment by yangchiu** [comment]
@innobead The default `GITHUB_TOKEN` probably doesn't have enough permission of the read access of organization members and the read/write access of projects to get this task done.
When you have time could you help to create a customized token for longhorn repository? 

(1) Create a new token by following https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

(2) Set the following permissions:
`workflow`
`read:org`
`project `
![permission-1](https://user-images.githubusercontent.com/5709208/196136175-a703fdbe-cd12-44f7-b233-64ec12e85943.png)
![permission-2](https://user-images.githubusercontent.com/5709208/196136208-f543a3b6-cc5d-4e4c-aa78-b388b656f1e7.png)

(3) Add the token to longhorn/Settings/Secrets/Actions secrets

Thank you!!

**Comment by yangchiu** [comment]
@innobead After testing, we also need `write:org` permission otherwise it would encounter error like:

`gh: yangchiu does not have the correct permissions to execute AddProjectNextItem query. It requires the following scopes: ['write:org', 'repo'], but the token has only been granted the: ['project', 'read:org', 'repo', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.`

It would be appreciated if our `CUSTOM_GITHUB_TOKEN` can be updated to have `write:org` permission too:
![permission3](https://user-images.githubusercontent.com/5709208/196358438-dd46412b-4f7f-46a8-ac49-8c0e5cbc37aa.png)

Thank you and sorry for the misleading!

**Comment by innobead** [comment]
@yangchiu merged, please follow up if this works w/o issues.

**Comment by yangchiu** [comment]
The same code worked on 10/18 doesn't work today. Probably due to the deprecation message: `gh: The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.`, need to find different way and re-implement this action again.

10/18: https://github.com/yyz-field/test/actions/runs/3271198176/jobs/5380690741
today: https://github.com/yyz-field/test/actions/runs/3381968619/jobs/5616394869
