### ISSUE TITLE
[BUG] Cannot re-run helm uninstallation if the first one failed and cannot fetch logs of failed uninstallation pod

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#4711]
## Describe the bug

Cannot re-run helm uninstallation if the first one failed and cannot fetch logs of failed uninstallation pod

## To Reproduce

1. Clone the chart repo and remove the `--force` flag [here](https://github.com/longhorn/longhorn/blob/97cb124f247e736a77c4e73e319cc4b5c2f1bb46/chart/templates/uninstall-job.yaml#L27) as a way to artificially fail the uninstalltion job
2. Install the Helm chart
3. Create some volumes and attach them
4. Do helm uninstall
5. The uninstallation job will fail because there are attached volumes and `--force` flag is not set
6. Now detach the volumes
7. Re-run helm uninstalltion again. This command always fail since the previous uninstallation job already exist 
8. Also we cannot check the log of the uninstallation pod because it is already cleanup so we are kind of lost not knowing what was the failed reason.

## Expected behavior

Users can re-run helm uninstallation and can see logs of failed uninstallation pod

## Environment

 - Longhorn version: <= 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm/Rancher UI

**Comment by PhanLe1010** [comment]
**Test steps:**

1. Clone the chart repo and remove the `--force` flag [here](https://github.com/longhorn/longhorn/blob/97cb124f247e736a77c4e73e319cc4b5c2f1bb46/chart/templates/uninstall-job.yaml#L27) as a way to artificially fail the uninstallation job
1. Install the Helm chart
1. Create some volumes and attach them
1. Do helm uninstall
1. The uninstallation job will fail because there are attached volumes and `--force` flag is not set
1. Verify that we can check the log of the failed uninstallation pod inside `longhorn-system` namespace
1. Now detach the volumes
1. Re-run `helm uninstall` again. Very that the uninstallation succeeded

**Comment by Lichiehyao** [comment]
**Verified on master-head 20221027**

- longhorn master-head ([777bc5b](https://github.com/longhorn/longhorn/commit/777bc5b0c025ea2e8bf497bf22fc9d701db50bf9)) 
- longhorn-manager master-head ([76468fa](https://github.com/longhorn/longhorn-manager/commit/76468fa5013b70c5715977e6ba2dc35c3f024974)) 


**The test steps**

Test steps:

1. Clone the chart repo  `git clone https://github.com/longhorn/longhorn.git`
2. remove the `--force` flag [here](https://github.com/longhorn/longhorn/blob/97cb124f247e736a77c4e73e319cc4b5c2f1bb46/chart/templates/uninstall-job.yaml#L27) as a way to artificially fail the uninstallation job 
( longhorn/chart/templates/uninstall-job.yaml )
3. Install the Helm chart 
```
cd longhorn/chart
helm install longhorn . --namespace longhorn-system --create-namespace
```
4. Create one volume and attach to node-1
5. Do helm uninstall `helm uninstall longhorn -n longhorn-system`
6. The uninstallation job will fail because there are attached volumes and --force flag is not set
![Screenshot_20221027_105232](https://user-images.githubusercontent.com/104337648/198179757-4410bd63-8380-4f57-b474-b190a3d7ca53.png)
7. Verify that we can check the log of the failed uninstallation pod inside longhorn-system namespace
`kubectl -n longhorn-system logs longhorn-uninstall-z7hf5`
![Screenshot_20221027_105538](https://user-images.githubusercontent.com/104337648/198180194-f53fd9fc-978c-4b05-b310-8ea4516e499b.png)
8. Now detach the volumes
9. set `deleting-confirmation-flag` to `true`
`kubectl -n longhorn-system edit settings.longhorn.io deleting-confirmation-flag`
10. Re-run helm uninstall again. Very that the uninstallation succeeded
`helm uninstall longhorn -n longhorn-system`

**Result Passed**

**Comment by Lichiehyao** [comment]
Hi @PhanLe1010 :
    After I verified this issue, we need to confirm one thing in our design. 
    
**The test steps**
    1. Clone the chart repo  `git clone https://github.com/longhorn/longhorn.git`
    2. Install the Helm chart
```
cd longhorn/chart
helm install longhorn . --namespace longhorn-system --create-namespace
```

3. Do helm uninstall `helm uninstall longhorn -n longhorn-system`
4. The uninstallation job will fail 
5. set `deleting-confirmation-flag` to `true`
`kubectl -n longhorn-system edit settings.longhorn.io deleting-confirmation-flag`
6. Re-run helm uninstall again. Very that the uninstallation succeeded
`helm uninstall longhorn -n longhorn-system`

**Result Passed**
1. I didn't create any volume on the Longhorn, the uninstallation job also failed
2. Before uninstall Longhorn, we must  set `deleting-confirmation-flag` to `true` 

Is it the expected behavior on the master-head?

**Comment by PhanLe1010** [comment]
> I didn't create any volume on the Longhorn, the uninstallation job also failed
Before uninstalling Longhorn, we must set deleting-confirmation-flag to true

Yes, it is expected that `Before uninstalling Longhorn, we must set deleting-confirmation-flag to true`  Thank you for re-verifying

**Comment by yangchiu** [comment]
@PhanLe1010 Should https://github.com/longhorn/longhorn/blob/master/uninstall/uninstall.yaml be modified like https://github.com/longhorn/longhorn/pull/4712 too? Otherwise if using `kubectl` to uninstall longhorn, it would be unable to fetch logs of failed uninstallation pod too?

**Comment by PhanLe1010** [comment]
Great catch. I will update it

**Comment by PhanLe1010** [comment]
Pushed PR https://github.com/longhorn/longhorn/pull/4810

**Comment by innobead** [comment]
@yangchiu Please help verify https://github.com/longhorn/longhorn/issues/4711#issuecomment-1294398011, then close if it works correctly. Thanks.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn cc043c4) by the following test steps:

(1) install longhorn master-head
(2) try to uninstall longhorn by `kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/master/uninstall/uninstall.yaml`
(3) view logs by `kubectl logs job/longhorn-uninstall -n longhorn-system`, the expected error message can be seen, indicates the `Deleting Confirmation Flag` flag has to be set to true.
(4) set `Deleting Confirmation Flag` flag to true, and delete/create uninstallation job again, longhorn can be uninstalled without problems.
