### ISSUE TITLE
Volumes get bigger and bigger

### ISSUE THREAD

**Issue by KuroObi** [longhorn/longhorn#478]
We observed that volumes get bigger than there maximal size. We are running a Prometheus and Elasticsearch database where a lot of data gets generated and deleted.
Is there a way to slim down the replicas to reduce the overall used storage on nodes with the replicas.

**Comment by yasker** [comment]
@KuroObi After backing up the snapshots, you can delete them to remove unnecessary history data, which will shrink the volume size.

Notice the snapshot deletion may take a relatively long time (since we need to coalesce the data) and result in a higher than normal load on the system, so it's better to do it one by one.

If you have recurring backup/snapshot set, the snapshot deletion would be performed automatically to retain only the specified number of snapshots.

**Comment by KuroObi** [comment]
We had to remove the old volume but the new one is nearing its limit.
I'll let  you know when the  replica get to there limit.

**Comment by yasker** [comment]
@KuroObi Does delete snapshots work for you?

**Comment by KuroObi** [comment]
@yasker  with the old volume we couldn't delete the snapshots due to the fact that we lost one of our replicas and it took to long to restore it so we deleted it and recreated the volume from scratch.
But the new replicas approaching the limit, i should know more on monday.

**Comment by KuroObi** [comment]
I was able to recreate the issue:
![longhorn_vol_size_20190423](https://user-images.githubusercontent.com/2558064/56562037-cf662600-65a8-11e9-95fa-e551c3ef08a1.png)

The only snapshot that i can see is a system snapshot that I can't delete.

**Comment by yasker** [comment]
@KuroObi If you move your mouse over the snapshot and head, you should see the real `size` of each.  The actual size is what added up by those number.

The volume head is also treated as a snapshot in the Longhorn. So it's still OK for the actual size to be bigger than the nominal size.

If you want to downsize the volume, you can create a new snapshot, then delete the first volume. 

It works like this:
1. Every time when you delete a snapshot, it's content would be calculated and coalesced into its child, so the child snapshot would still contain the correct data.
2. Since we cannot modify the volume head, which is being read/write by the user, Longhorn cannot delete the last snapshot in the chain for real. But you can have a new empty volume head by creating a new snapshot.
3. Once you have two snapshots and delete the older one of them, it would be possible for Longhorn to coalesce the data.

So after that, you should see the actual size is smaller than the size.

Btw, you can set recurring backups with your volume and set retain to a certain number, which will automatically clean up the snapshot and backups for you.

**Comment by KuroObi** [comment]
@yasker That worked, thank you very much.
Is there going to be a feature in the future that is going to tell longhorn to downsize the volumes automatically?

**Comment by yasker** [comment]
@KuroObi Currently you can schedule a recurring snapshot or backup, so the snapshot would be automatically created and cleaned up if the number of snapshots exceeds the specified retain number.

It's highly recommended to schedule a few recurring backups, as the fall back protection for your data.

**Comment by courcelm** [comment]
I'm also having this issue with Elasticsearch. It seems that system hidden snapshots are not deleted. What is the retain number for those?
This is problematic, my 30Gi volume is now 123Gi and this eventually causes disk pressure.

**Comment by yasker** [comment]
@courcelm system hidden snapshots should be automatically deleted once you delete any snapshots. Does https://github.com/rancher/longhorn/issues/478#issuecomment-485930147 help in your case?

**Comment by courcelm** [comment]
The UI does mention that hidden snapshots are deleted.

Following your above comment, I created a new snapshot (I had none previously). Then I deleted it. I got a 504 error from the UI. It seems deleted after a page refresh. However, my actual size is still 124 Gi instead of lower than 30 Gi.

**Comment by courcelm** [comment]
I got this in my replica log:

time="2019-05-29T18:38:35Z" level=info msg="Marking disk 37415192-abe0-4505-9bd6-311df5c82dd1 as removed"
10.42.7.98 - - [29/May/2019:18:38:35 +0000] "POST /v1/replicas/1?action=markdiskasremoved HTTP/1.1" 200 10019 "" "Go-http-client/1.1"
time="2019-05-29T18:38:35Z" level=info msg="Prepare removing disk: 37415192-abe0-4505-9bd6-311df5c82dd1"
time="2019-05-29T18:38:35Z" level=info msg="Currently snapshot volume-snap-37415192-abe0-4505-9bd6-311df5c82dd1.img doesn't meet criteria to be removed, skip it for now"
10.42.7.98 - - [29/May/2019:18:38:35 +0000] "POST /v1/replicas/1?action=prepareremovedisk HTTP/1.1" 200 216 "" "Go-http-client/1.1"
time="2019-05-29T18:38:35Z" level=info msg="Prepare removing disk: 71cde0d7-ccea-451d-bc25-09c68f08109c"
time="2019-05-29T18:38:35Z" level=info msg="Disk volume-snap-71cde0d7-ccea-451d-bc25-09c68f08109c.img cannot be found, may has already been removed"
10.42.7.98 - - [29/May/2019:18:38:35 +0000] "POST /v1/replicas/1?action=prepareremovedisk HTTP/1.1" 200 218 "" "Go-http-client/1.1"

**Comment by yasker** [comment]
@courcelm Can you show me a screenshot of your snapshots? Each of them (including volume head) should have an actual size assigned to them when you hover your mouse over the snapshot name.

**Comment by courcelm** [comment]
Here it is:

![Screenshot from 2019-05-29 15-29-11](https://user-images.githubusercontent.com/1862936/58585402-99126b00-8226-11e9-9a79-b8dd26d55ec2.png)

![Screenshot from 2019-05-29 15-30-14](https://user-images.githubusercontent.com/1862936/58585431-b34c4900-8226-11e9-9b0d-61d48b01ab02.png)

+ 25 hidden snapshots

**Comment by yasker** [comment]
@courcelm Can you send me a support bundle? You can find the generation link at the bottom of UI, and try it in the dashboard page (there was a bug on the volume detail page).

You can find my email in my profile.
