### ISSUE TITLE
[BUG] Volume metafile getting deleted or empty results in a detach-attach loop

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#4846]
## Describe the bug (🐛 if you encounter this issue)
From the reporter:

> it happened during runtime no node shutdown no upgrade nothing

> Now we ran into this issue, one time during node reboot and once during longhorn upgrade (1.22 -> 1.3.1), in one environment volume.meta file itself is missing and in another environment volume.meta file is empty.

More context is needed later.

## To Reproduce

N/A

## Expected behavior
The volume metafile always records the valid info

## Log or Support bundle
N/A

## Environment

 - Longhorn version: v1.2.2 or v1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by shuo-wu** [comment]
cc @innobead @joshimoo

**Comment by innobead** [comment]
cc @longhorn/qa 

For longhorn's current design, we quite rely on saving some files persistent on the host, so it's inevitable to have some error handling and self-healing/recovering when the persistent data on the host has some problems like getting deleted or empty like in this case. 

For QA, need to have more negative testing to cover this kind of external interrupt to test Longhorn resilience.

**Comment by chriscchien** [comment]
Verified in longhorn master `207e74` with test [steps](https://github.com/longhorn/longhorn/issues/4846#issuecomment-1333253133)
Result [Pass](url)

After create pod with longhorn volume then delete the pod let volume in detach state:
1. If  `volume.meta` were removed or emptied in replica file path, replicas will recovery soon after pod recreated. Volume will attach to node and data still kept consistent if volume have replica with correct meta file
2. But if `volume-head-001.img.meta` were also removed/emptied in some replicas, after pod recreated, volume will keep in Degraded status, replicas which had file `volume-head-001.img.meta` modified, will keep in fail status. Because `volume-head-001.img.meta` is not this ticket's scope, maybe we can consider handle those situation in the future.
