### ISSUE TITLE
[DOC] Provide the user guide for Kubernetes upgrade

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#494]
User will need to upgrade Kubernetes from time to time, we need to cover Kubernetes major version upgrade in our tests, and provide guidance for the user to prepare for the Kubernetes upgrade.

**Comment by PhanLe1010** [comment]
We observed Rancher upgrades worker nodes in batch and Kubernetes restarts the pods on the worker nodes that are being upgraded. This means that Longhorn instance managers (engine/replica) on upgrading nodes will be killed. Longhorn will mark replicas on those nodes as error and starts rebuilding those replicas. For the Longhorn engine on those nodes, they will be marked as error and Longhorn automatically detaches then reattaches the volumes.

With the current implementation, we cannot avoid replica rebuilding unless users are willing to **stop all workloads and detach all volumes before upgrading Kubernetes.** If the volumes are still attaching and the instance managers got killed, the replicas on those instance managers will be out of sync and will become error.

Some action items:
1. Write documents about this behavior
1. Investigate a way to allow users to do Kubernetes upgrade without having to stop all workload

**Comment by yasker** [comment]
If user follows the drain process before upgrade, then there should be no service interruption.

**Comment by yasker** [comment]
We need to raise the priority of this. We need to prepare the best practice for the Kubernetes upgrade with Longhorn.

One issue we've seen from the users is IT department asked them to upgrade Kubernetes from time to time due to CVEs, and we cannot afford Longhorn get stuck or malfunction during every upgrade.

**Comment by cclhsu** [comment]
Currently, I am doing research/hand-on testing to include following for the guide.

- The guide to include using Rancher to Upgrade RKE, RKE2, and K3S with Longhorn.
- The guide to include using upgrade strategy to upgrade RKE and system upgrade controller to upgrade RKE2 and K3S
-  List of known issues and best practice in different stage

**Comment by mfbrj** [comment]
> If user follows the drain process before upgrade, then there should be no service interruption.

What are the recommended settings to drain nodes?

![image](https://user-images.githubusercontent.com/835834/128275223-f178dcdd-e353-4908-8f2f-792964926cb7.png)

**Comment by khushboo-rancher** [comment]
@mfbrj The setting in the screenshot holds good. Depends upon how many workloads are running on the node you might want to adjust the timeout `Give up after` setting.

It's better to drain a node with volumes detached, as there will be lot of replica rebuilding if you don't scale down the workload pods before upgrading.

**Note**: you might see the instance-manager getting blocked intermittently due to PDB, but they will get drained out eventually at the last.

Drain command for your reference
`kubectl drain <node-ip> --delete-local-data=false --force=false --grace-period=-1 --ignore-daemonsets=true --timeout=120s`

**Comment by mfbrj** [comment]
Thanks for you answer, @khushboo-rancher 

> It's better to drain a node with volumes detached, as there will be lot of replica rebuilding if you don't scale down the workload pods before upgrading.

Scale down workloads before a upgrade throw away the high availability that a kubernetes environment should delivery. 

> **Note**: you might see the instance-manager getting blocked intermittently due to PDB, but they will get drained out eventually at the last.

A single replica rebuild of 60 GB takes 8 min at my environment. 

1. After the 120s timeout the PDB is bypassed?
2. Does this timeout have anything to do with the replica rebuild time? In other words, after 120 seconds, Rancher will proceed the upgrade anyway?
3. Or the timeout is about the time that Longhorn should take to detache all workloads of the current upgraded node?
4. Longhorn will prevent Rancher/RKE to continue the upgrade if there is only one healthy replica of a volume?

**I prefer the upgrade to last 24 hours rather than losing all replicas of a single volume.**

**Comment by khushboo-rancher** [comment]
>1. After the 120s timeout the PDB is bypassed?

No, the instance-manager is designed to get drained at the last after all the other pods on the node is drained. It's not related to 120s timeout.
>2. Does this timeout have anything to do with the replica rebuild time? In other words, after 120 seconds, Rancher will proceed the upgrade anyway?

Replica rebuilding has nothing to do with timeout.
> 3. Or the timeout is about the time that Longhorn should take to detache all workloads of the current upgraded node?

This timeout is drain timeout, Kubenetes will wait 120s for drain to complete.

> 4. Longhorn will prevent Rancher/RKE to continue the upgrade if there is only one healthy replica of a volume?

By default, Longhorn will block kubectl drain action on a node if the node contains the last healthy replica of a volume. You can change the setting in the Longhorn GUI setting page.

**Comment by jenting** [comment]
Link to closed doc PR https://github.com/longhorn/website/pull/335

**Comment by innobead** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/494?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/3304#issuecomment-982896479

**Comment by innobead** [comment]
When having https://github.com/longhorn/longhorn/issues/5549 and https://github.com/longhorn/longhorn/issues/3304, the upgrade practice will be clear and ready. 

Currently, we have https://longhorn.io/docs/1.4.1/volumes-and-nodes/maintenance/, so that should be updated. Also, need to have a specific Kubernetes upgrade doc to describe different cases like one/multiple node clusters, vanilla upgrade, or using other 3rd-party tools like Rancher SUC or Rancher.

**Comment by innobead** [comment]
https://longhorn.io/docs/1.5.0/volumes-and-nodes/maintenance/ provided.
