### ISSUE TITLE
[IMPROVEMENT] Set default `engine-replica-timeout` vaule for engine controller start command

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5031]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Set default `engine-replica-timeout` vaule for engine controller start command

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn-engine/blob/4bdb80d656dd32c563655986fadb63079a0b29e6/pkg/controller/init_frontend.go#L39-L46

**Comment by chriscchien** [comment]
Verified in longhorn master `4f35fd`
Result **Pass**

1. In instance-manager-e log,  can not see log related to `"Using default engine-replica timeout %v instead since the given value %v is not allowable"`. Because after https://github.com/longhorn/longhorn-engine/pull/782 merged, timeout have default value [set](https://github.com/longhorn/longhorn-engine/blob/502488e32b69573b8c2a6eddeca2815127068663/app/cmd/controller.go#L127), so the warning message in func `DetermineEngineReplicaTimeout` not triggered.
2. engine related test case passed in master-head [pipeline](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/338/testReport/tests/test_engine_upgrade/)
