### ISSUE TITLE
[IMPROVEMENT] Inconsistent name convention across volume backup restore and system backup restore

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5066]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

User can restore a volume backup with ` restore-1volume-1backup-2` but can't restore system backup with the same name.
We can follow same naming convention across the product.

<img width="1440" alt="Screenshot 2022-12-14 at 12 45 10 AM (2)" src="https://user-images.githubusercontent.com/60111667/207550072-f81438a0-cacb-4793-b608-38b72c8a537e.png">

**Comment by c3y1huang** [comment]
Hi @khushboo-rancher , I am not able to reproduce this.
![Screenshot-2022-12-15-10:41:57](https://user-images.githubusercontent.com/22583541/207761574-129cc651-dac1-4611-b460-5ed0d1c9ef93.png)

I've also asked @chriscchien to try and seems not reproducible.

Can you provide the support bundle?

**Comment by khushboo-rancher** [comment]
I have the support bundle but I've done lots of other operations on the cluster.

[supportbundle_53cae9b1-ec77-40ba-aa16-a9171b760e3e_2022-12-15T02-57-59Z.zip](https://github.com/longhorn/longhorn/files/10233355/supportbundle_53cae9b1-ec77-40ba-aa16-a9171b760e3e_2022-12-15T02-57-59Z.zip)

Time around - 2022-12-14 08:00 AM in UTC

**Comment by c3y1huang** [comment]
I can't tell from the support bundle. 

We do not set a naming convention for SystemBackup/Restore. For now, I am not able to reproduce.

**Comment by khushboo-rancher** [comment]
I encountered this again with v1.4.0-rc-2
```
[longhorn-manager-6vgg7 longhorn-manager] time="2022-12-22T20:20:31Z" level=warning msg="HTTP handling error failed to create SystemRestore restore-1`: SystemRestore.longhorn.io \"restore-1`\" is invalid: metadata.name: Invalid value: \"restore-1`\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
```

**Comment by c3y1huang** [comment]
@khushboo-rancher , is there a typo in `restore-1\``?

**Comment by weizhe0422** [comment]
Following the steps below to test on `master-head` and `1.4.x-head`, I can reproduce the error message mentioned in this [comment](https://github.com/longhorn/longhorn/issues/5066#issuecomment-1363547881) because there is a space in the string prefix.

1. Install Longhorn and set up backup target path
2. Create or restore a system backup with name ` restore-1volume-1backup-2`
![image](https://user-images.githubusercontent.com/17548901/209612903-3eb0c306-86c1-4da0-80f1-5d3a90f0e903.png)
![image](https://user-images.githubusercontent.com/17548901/209612955-b6c40658-1c58-422d-b784-2580f50e6c39.png)

**Comment by innobead** [comment]
Ok, this is some inconsistent at UI, when restoring a volume, UI will do the trim to remove the prefix empstry characters, so the payload sent is actually w/o invalid empty character anymore. 

https://github.com/longhorn/longhorn-ui/blob/20dbdf331fd0efe299523341058a7c90f62d6f1f/src/routes/backup/RestoreBackup.js#L46-L48
![image](https://user-images.githubusercontent.com/899492/209616793-57fdea0e-d396-4831-a89f-bca2e222034a.png)

For backend, we don't have any pre-cleanup for users, so if users create `SystemRestore` CR directly, they will still encounter this kind of issues. Personally, I think we don't need to do any specific behavior for that, because that kind of errors can teach users how to use Longhorn or K8s.

**Comment by roger-ryao** [comment]
**Verified on master-head 20221227**

- longhorn master-head ([62998ad](https://github.com/longhorn/longhorn/commit/62998adab26c67b4739cf336ff19f636e80d0459)) 
- longhorn-ui master-head ([f9ed1f7](https://github.com/longhorn/longhorn-ui/commit/f9ed1f7752e0b631ff7a2cd544ee8d0a346f7e0b))

**Verified on v1.4.x-head 20221227**

- longhorn v1.4.x-head ([c32192c](https://github.com/longhorn/longhorn/commit/c32192c4d204f03f3b7832f99373fbad7e7ac012)) 
- longhorn-ui v1.4.x-head ([3109b51](https://github.com/longhorn/longhorn-ui/commit/3109b51d093a26aaf6b51f0f23f6b519b32f7bc5))

**The test steps**

1. Create the system backup with the prefix empty characters name 
2. Restore System backup with the prefix empty characters name
 e.g. ` restore-1volume-1backup-2`


**Result Passed**
