### ISSUE TITLE
[BUG] Node & Disk tags are not restored in system backup restore

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5118]
## Describe the bug (🐛 if you encounter this issue)

The node and disk tags for Longhorn nodes should also get restored when user does a system backup restore.

## To Reproduce

1. Go to Longhorn UI, Add some node tags and disk tags.
2. Create a system backup.
3. Delete the node and disk tags.
4. Restore the system backup.
5. Node/disk tags are not restored.

## Expected behavior

The node and disk tags should also get restored.

## Environment

 - Longhorn version: v1.4.x-head

**Comment by innobead** [comment]
@khushboo-rancher @c3y1huang 

Should we restore nodes and their disk settings? I think they will be dynamically created by auto detection via the node controller.

If no need, because some resources relying on them like storage class, so we should have a note in the doc to remind this part as a prerequisite.

**Comment by innobead** [comment]
After discussing with @c3y1huang , Longhorn nodes will not be restored, because they will be automatically created based on the target cluster. This kind of prerequisite should be mentioned in the doc. 

@khushboo-rancher good check :+1:
