### ISSUE TITLE
[BUG] Instance manager pod does not respect of node taint?

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5161]
### Discussed in https://github.com/longhorn/longhorn/discussions/5160

<div type='discussions-op-text'>

<sup>Originally posted by **jwenjian** December 28, 2022</sup>
I am confused about the instance manager pod behavior of node taint, hope anyone can help :)

I have a single node cluster with longhorn installed, then I add a new taint to the node, e.g. `k=v:NoSchedule`,then I delete the instance manager pod, based on my understanding, the new instance manager pod cannot be scheduled since it has no corresponding toleration.

But the new pod is scheduled and running normally, just like before.

I tried to delete the longhorn ui pod, the new UI pod is in pending status and cannot be scheduled to the node, which is expected.

Is there any other *dark tech* for the instance manager pods?

BTW, when I describe the instance manager pod, I just found 2 tolerations, none of them is for the new taint:

```
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason   Age   From     Message
  ----    ------   ----  ----     -------
  Normal  Pulled   54m   kubelet  Container image "longhornio/longhorn-instance-manager:v1_20211210" already present on machine
  Normal  Created  54m   kubelet  Created container replica-manager
  Normal  Started  54m   kubelet  Started container replica-manager

```
</div>

**Comment by innobead** [comment]
cc @longhorn/qa

**Comment by ejweber** [comment]
I agree with @innobead's assessment in #5160. Brainstorming this afternoon, I came up with some changes we _could_ potentially make.

1. Append a `kubernetes.io/hostname: <im.spec.NodeID>` label to the [nodeSelector we already use ](https://github.com/longhorn/longhorn-manager/blob/124952b219a391cbdf6a15984e5b69d234843215/controller/instance_manager_controller.go#L987-L990), remove the NodeName field [@innobead pointed out](https://github.com/longhorn/longhorn-manager/blob/124952b219a391cbdf6a15984e5b69d234843215/controller/instance_manager_controller.go#L1081), and rely on the nodeSelector to cause instance-manager pods to be scheduled on the intended node. (This could also be done with a nodeAffinity, but it seems confusing to mix nodeSelector and nodeAffinity.) Pods won't be scheduled if there is a preventing taint.
2. Add a podAffinity constraining the instance-manager pod to the same node as the longhorn-manager pod, remove the aforementioned NodeName field, and rely on the podAffinity to cause instance-manager pods to be scheduled on the intended node. Pods won't be scheduled if there is a preventing taint.
3. Add a check similar to the one @shuo-wu [already did](https://github.com/longhorn/longhorn-manager/blob/124952b219a391cbdf6a15984e5b69d234843215/controller/instance_manager_controller.go#L432-L436) for unscheduleable nodes (this one for taints with the NoSchedule effect) so that we never try to create instance-manager pods in the first place. I don't like this approach, as it largely duplicates the existing functionality of the Kubernetes scheduler. Note that @shuo-wu's check applies to nodes with spec.unschedulable=true (nodes that are cordoned), not nodes with taints.
4. Do nothing. Is there a valid reason to want to run a longhorn-manager pod on a node, but not instance-manager pods?

The backing image manager and backing image data source controllers also directly write the NodeName field in a similar way. If we choose to change this behavior in the instance manager controller, we should probably do it there as well.

My gut reaction is that there isn't a compelling reason to make a change here. The existing behavior is confusing, but I don't understand why we'd want to run longhorn-manager without instance-manager.

If we do want to make a change, I lean towards the second option.

Please let me know your thoughts, @innobead or @shuo-wu if you get a moment.

**Comment by shuo-wu** [comment]
> Add a check similar to the one @shuo-wu [already did](https://github.com/longhorn/longhorn-manager/blob/124952b219a391cbdf6a15984e5b69d234843215/controller/instance_manager_controller.go#L432-L436) for unscheduleable nodes

YES, we encountered a similar issue before and I didn't think of the node selector labeling way. This is more like a workaround. It's great to have a better solution.

But statement #4 is valid as well. Or in other words, the instance manager pod and the backing image manager pod should have the same node affinity with the longhorn manager pod on each Longhorn worker node.

**Comment by ejweber** [comment]
We discussed this in the community issue review meeting. Our current plan is to:

1. Confirm whether or not we will run replica processes on the node when it is tainted. We probably will, but we have a feature that disables scheduling when the node is cordoned, so it is not a sure thing.
2. Reach out to the user who initiated the question and ask if the current behavior is actually problematic, or if they are just curious.
3. If we don't hear back from the user or they don't provide a justification for a change, we will do nothing.

**Comment by ejweber** [comment]
We DO currently run replicas on nodes that are tainted:

```
eweber@laptop:~/longhorn> k describe node eweber-v124-worker-1ae51dbb-4pngn | grep Taints
Taints:             test=test:NoSchedule

eweber@laptop:~/longhorn> k apply -f examples/
block_volume.yaml              csi/                           deployment.yaml                pod_with_pvc.yaml              rwx/                           simple_pvc.yaml                statefulset.yaml               
crypto/                        data_migration.yaml            network-policy/                restore_to_file.yaml.template  simple_pod.yaml                snapshot/                      storageclass.yaml              
eweber@laptop:~/longhorn> k apply -f examples/pod_with_pvc.yaml 
persistentvolumeclaim/longhorn-volv-pvc created
pod/volume-test created

eweber@laptop:~/longhorn> kl get replica
NAME                                                  STATE     NODE                                DISK                                   INSTANCEMANAGER                                     IMAGE                                    AGE
pvc-bcbbb2ad-749f-465f-ac68-393980982b20-r-1cdb9b9d   running   eweber-v124-worker-1ae51dbb-4pngn   9699a051-aff8-457d-a6f4-4c067615e7ed   instance-manager-bd54850e35239b37069374780ca0f9a3   longhornio/longhorn-engine:master-head   11s
pvc-bcbbb2ad-749f-465f-ac68-393980982b20-r-2951a59c   running   eweber-v124-worker-1ae51dbb-ppvzp   711d4bcb-85ab-4cfc-ad06-fcf12de42916   instance-manager-faf47d6949e508720ae71ed3ee10e466   longhornio/longhorn-engine:master-head   11s
pvc-bcbbb2ad-749f-465f-ac68-393980982b20-r-c24b688f   running   eweber-v124-worker-1ae51dbb-pbxr9   4a758df2-1b96-4c11-a664-4f211f542923   instance-manager-4639bda14281d41f3af00d64bc364bb9   longhornio/longhorn-engine:master-head   11s
```

I have reached out in #5160 in preparation for closing this issue.

**Comment by innobead** [comment]
Good update. I agree with the conclusion below, primarily instance-manager is actually managed by longhorn-manager, so they should be atomic existence. 

> Longhorn-manager will continue to try to run an instance-manager pod on any node where it itself is running.
If longhorn-manager is forced off a node, instance-manager can be deleted and will not run again.

**Comment by ejweber** [comment]
Closing this issue after further discussion in #5160.
