### ISSUE TITLE
[FEATURE] Support SPDK lvol shallow copy for newly replica creation

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#5217]
Shallow copy of a logical volume over an arbitrary bdev

What we have to implement is a JSON-RPC to copy a logical volume over an arbitrary bdev (that in our case will represent a remote volume exported via NVMe-oF and locally attached) _while the top layer is also being modified_ (see next section).

- [x] RPC creation
- [x] lvol shallow copy
- [x] blob copy
- [x] unit test
- [x] RPC documentation
- [x] Refactoring for blob and bdev layers separation
- [x] end2end test

cc @longhorn/dev-data-plane

**Comment by DamiaSan** [comment]
After discussions with Mike Gerts and Ben Walker of SPDK, a refactoring is needed to keep sepration between blob and bdev layers

**Comment by innobead** [comment]
This is only for rebuilding a whole new replica since it iterates to copy each snapshot to the new exposed replica (lvol), then snapshot it accordingly. 

Need to extend this to support how to rebuild from a failed replica in place to reuse the existing data if some data blocks are able to reuse.  ref: https://github.com/longhorn/longhorn/issues/5573

**Comment by DamiaSan** [comment]
Just to clarify, shallow copy simply copy a lvol, where with lvol we mean a single layer, i.e. a snapshot or a clone (the live data). So it doesn't iterate, it will be the `longhorn-spdk-engine` that will iterate to copy (using shallow copy) each snapshot to the new exposed replica

**Comment by DamiaSan** [comment]
https://github.com/longhorn/spdk/pull/5
