### ISSUE TITLE
[BUG] Building v1.3.x images failed

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#5365]
## Describe the bug (🐛 if you encounter this issue)

Building v1.3.x images failed because the repository is gone.

## Expected behavior

Build v1.3.x images successfully.

## Log or Support bundle

https://drone-pr.longhorn.io/longhorn/longhorn-instance-manager/362/1/3

## Related issue:
https://github.com/longhorn/longhorn/issues/4191

**Comment by mantissahz** [comment]
https://download.opensuse.org/repositories/devel:/tools:/scm/
`15.3` is removed

**Comment by innobead** [comment]
IIRC @yangchiu fixed this before, so probably this repo just missed.

**Comment by yangchiu** [comment]
15.3 was removed because it's end of life according to https://suse.slack.com/archives/C02D1374S3V/p1675818735801259

To figure out what packages we need in devel:tools:scm, I tried to remove this repo from both Dockerfile and Dockerfile.dapper, but `dapper ci` can succeed without any error after the removal.

So remove devel:tools:scm first and see if there's any errors in the daily regression

**Comment by innobead** [comment]
@yangchiu thanks for the quick analysis and fix!

**Comment by innobead** [comment]
@mantissahz Please close this if all images working fine. Thanks.

**Comment by mantissahz** [comment]
According to daily build https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/287/, the images should work fine.

**Comment by c3y1huang** [comment]
Should the changes also go into the master branch?

**Comment by innobead** [comment]
> Should the changes also go into the master branch?

Yes, @yangchiu is on that.
