### ISSUE TITLE
[BUG] Unable to upgrade longhorn from v1.3.2 to master-head

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5368]
## Describe the bug (🐛 if you encounter this issue)

When upgrade longhorn from v1.3.2 to master-head, `longhorn-manager` stuck in `CrashLoopBackOff` state with errors:
```
time="2023-02-08T05:40:02Z" level=fatal msg="Error starting manager: upgrade resources failed: upgrade from v1.3.x to v1.4.0: upgrade volume failed: failed to update volume pvc-628e4b5d-d31b-4e92-b87e-27d03ac245b7: Volume.longhorn.io \"pvc-628e4b5d-d31b-4e92-b87e-27d03ac245b7\" is invalid: spec.backupCompressionMethod: Unsupported value: \"\": supported values: \"none\", \"lz4\", \"gzip\""
```

## To Reproduce

1. install longhorn v1.3.2
2. create a pod to use longhorn volume
3. upgrade to longhorn master:head
4. longhorn-manager stuck in CrashLoopBackOff

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
In the current implementation, we will update resources as per each longhorn version by ascending version order after updating to the latest API resource (now it's v1beta2); however, this caused this issue to happen (newly added fields will fail the previous upgrade path). 

In this case, the `backupCompressionMethod` field is added to the v1beta2 volume spec in the master/1.5.0 code base, so the upgrade from 1.3.x/1.4.x will fail when updating the volume resources without updating `backupCompressionMethod`.

What we should do is `Updating resources to the API server at the end instead of in each upgrade path`.

**Comment by yangchiu** [comment]
After the [fix](https://github.com/longhorn/longhorn-manager/pull/1698) merged, the upgrade test jenkins pipelines on `master` branch back to normal and everything works fine now.

**Comment by innobead** [comment]
@derekbit I feel we should backport this to 1.4.x? Is this related to https://github.com/longhorn/longhorn/issues/5485?
