### ISSUE TITLE
[BUG] `test_snapshot_hash_detect_corruption_in_global_enabled_mode` failed due to not proper cron job value 

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5394]
## Describe the bug (🐛 if you encounter this issue)

From master branch build #[399](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/399/testReport/junit/tests/test_snapshot/test_snapshot_hash_detect_corruption_in_global_enabled_mode/)

In master head, cron job value in https://github.com/longhorn/longhorn-tests/blob/1917cf1a34b4a649dc0032512a14cf4242d12a23/manager/integration/tests/test_snapshot.py#L289 not suitable for
 product, when cron job started, test script still prepare snapshots which make function `wait_for_rebuild_start` failed

## To Reproduce

1. Run `test_snapshot_hash_detect_corruption_in_global_enabled_mode` on master branch pipeline
2. Will see fail at `wait_for_rebuild_start`

## Expected behavior

Have consistent test result in all branches result

## Log or Support bundle

N/A

## Environment

 - Longhorn version: master-head `bb1bd7`

## Additional context

N/A

**Comment by innobead** [comment]
cc @derekbit 

@chriscchien is this also happening in 1.4.x? 

cc @longhorn/qa

**Comment by derekbit** [comment]
@chriscchien @roger-ryao 
The newly introduced https://github.com/longhorn/longhorn-tests/commit/d012b0a3531b0ac5e8b87350e81c3aee1e282099  patch results in the failure?

**Comment by chriscchien** [comment]
> cc @derekbit 
> 
> 
> 
> @chriscchien is this also happening in 1.4.x? 
> 
> 
> 
> cc @longhorn/qa 

In recent v1.4.x test result I did not find failure of this test case

**Comment by derekbit** [comment]
> > cc @derekbit
> > @chriscchien is this also happening in 1.4.x?
> > cc @longhorn/qa
> 
> In recent v1.4.x test result I did not find failure of this test case

Got it. Weird. I don't remember any new change in the related functionalities.
But it seems to we need to check if the snapshot is created first.

**Comment by yangchiu** [comment]
> > > cc @derekbit
> > > @chriscchien is this also happening in 1.4.x?
> > > cc @longhorn/qa
> > 
> > 
> > In recent v1.4.x test result I did not find failure of this test case
> 
> Got it. Weird. I don't remember any new change in the related functionalities. But it seems to we need to check if the snapshot is created first.

Just to clarify, both `test_snapshot_hash_detect_corruption_in_global_enabled_mode` and `test_snapshot_hash_detect_corruption_in_global_fast_check_mode` could fail in both `master` and `v1.4.x`.

**Comment by yangchiu** [comment]
This issue is related to [waiting for rebuilding for the corrupted replica timeout](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_snapshot.py#L339).

When this issue happened, there are already **3** snapshots being created, which can be verified on Longhorn UI, but the corrupted replica just isn't get to be rebuilt. Navigate to the setting page and modify the cronjob to a more frequent one like `*/5 * * * *` and wait for a while, a replica rebuilding can be observed.

In the current test case implementation, it's possible that the cronjob in https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_snapshot.py#L289 is set to a malformatted one like: `59/5 6 * * *`. This cronjob will only be executed once per day on 6:59 AM, if the test case missed this chance to trigger the integrity check, it will timeout and fail for sure.

Moreover, the wait timeout in https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_snapshot.py#L338 seems not reliable to catch the replica rebuilding event. It's possible to have to wait longer than this value to see the replica rebuilding.

I tried to set the cronjob to `*/3 * * * *` (every 3 mins) and the wait rebuild timeout to 6 mins, and ran `test_snapshot_hash_detect_corruption_in_global_enabled_mode` and `test_snapshot_hash_detect_corruption_in_global_fast_check_mode` for 30 times, doesn't observe the `wait_for_rebuild_start` timeout anymore, but this modification will cause other test case fail since all the snapshot_hash test cases share the same cronjob setup function but have different expects to the timing of integrity check.
