### ISSUE TITLE
[FEATURE] Identify failed replica of RAID1 bdev for replica rebuilding  

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5422]
## Is your feature request related to a problem? Please describe (👍 if you like this request)

Need to have an error handling mechanism in RAID1 bdev to understand failed downstream replicas, then have a way to report the error to trigger replica rebuilding. 

## Describe the solution you'd like

RAID1 bdev should monitor the status of each replica, then have an exposed interface (RPC) to let longhorn-spdk-engine to trigger replica rebuilding or the monitoring could be driven by longhorn-spdk-engine. 

## Additional context

cc @longhorn/dev-data-plane

**Comment by DamiaSan** [comment]
SPDK RPC bdev_raid_get_bdevs already shows informations about current base bdevs in the RAID1, we have to make some test to see how it handle node failure and so base bdevs departure

**Comment by DamiaSan** [comment]
There is a development under review for degraded mode support:
https://review.spdk.io/gerrit/c/spdk/spdk/+/15266

**Comment by innobead** [comment]
> under review for degraded mode support:

@DamiaSan Sounds good. Then, we should see if we could leverage it directly to the downstream first or base it on it to have a downstream revision.

**Comment by DamiaSan** [comment]
@shuo-wu @derekbit Actually, how is the rebuild operation triggered?

**Comment by shuo-wu** [comment]
There are 2 use cases for the replica identification, or let's say replica consistency validation:
1. Each time before a regular RAID start, Longhorn or spdk_tgt needs to guarantee that all base bdevs hold the same data (probably as well as the same snapshot chain)
2. As mentioned in [this comment](https://github.com/longhorn/longhorn/pull/7031#issuecomment-1822636145), Longhorn needs to check the consistency for all replicas after the engine/RAID crash since we don't know if the in-fly writes succeed in replicas.

---

Currently, I don't have a good idea about the Longhorn SPDK replica consistency validation. But I will list the mechanism for v1 volume as a reference:
1. During engine launching, we will check if the snapshot file **change time** matches the metafile record. If YES, then it means the snapshot file is not changed since the recorded **checksum** is valid. By comparing the snapshot checksum for all replicas, we will know if they hold identical snapshots.
2. For the volume-head among the replicas, a v1 volume will check and compare **the revision counter**. The revision counter means the counter of block write received by a replica. If this value among 2 replicas is identical, it means the volume-heads of 2 replicas hold the same data. (But to be honest, the revision counter update and the corresponding write cannot be considered as one atomic operations. For example, if the replica crashes after the revision counter update but before the data write, there is still an inconsistency)
When either of the above checks fails, the engine will mark the outlier replica as `ERR` then start to rebuild it.

---

@DamiaSan we need to investigate 2 parts:
1. How can we detect the inconsistency? Do we need/Can we use the revision counter + ctime & checksum mechanism for SPDK? Considering the race issue of the revision counter, can we have a better way? Besides, will introducing these mechanisms degrade the IO performance?
2. Which one is responsible for the revision counter/checksum/other metainfo calculation or recording? Longhorn SPDK server or spdk_tgt? If it's spdk_tgt, will the idea be accepted by upstream?

**Comment by DamiaSan** [comment]
Following [discussion](https://spdk-team.slack.com/archives/CJE4C98G1/p1701349496198019) on SPDK Slack channel

**Comment by DamiaSan** [comment]
Many of these issues have been addressed in the LEP https://github.com/longhorn/longhorn/pull/7031.
@shuo-wu @derekbit @innobead

**Comment by DamiaSan** [comment]
We have the epic #9491 , I think we can close this issue.
WDYT @derekbit @innobead ?

**Comment by innobead** [comment]
> We have the epic #9491 , I think we can close this issue. WDYT @derekbit @innobead ?

Yes, as the checksum-related operations will be covered.
