### ISSUE TITLE
[BUG][v1.4.x] test case test_backup_lock_deletion_during_restoration failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5458]
## Describe the bug (🐛 if you encounter this issue)

Test case `test_basic.py::test_backup_lock_deletion_during_restoration` has high possibility to fail in v1.4.x: https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/86/

This test case will restore a volume from a backup, and delete the backup during restoration, and expect the restoration can still complete without error. But in v1.4.x sometimes there are `remote backup not found` errors in restoreStatus and cause this test case failed:
```
'restoreStatus': [{
		'backupURL': 'nfs://longhorn-test-nfs-svc.default:/opt/backupstore?backup=backup-5cbed6b3174043ce&volume=longhorn-testvol-6qv9m5-std',
		'error': 'remote backup not found',
		'filename': 'volume-snap-d4e0b2a6-25b3-40ca-851e-b8ecf0b76268.img',
		'isRestoring': True,
		'lastRestored': '',
		'progress': 100,
		'replica': 'longhorn-testvol-6qv9m5-restore-r-ad1ccb30',
		'state': 'in_progress'
	}, {
		'backupURL': 'nfs://longhorn-test-nfs-svc.default:/opt/backupstore?backup=backup-5cbed6b3174043ce&volume=longhorn-testvol-6qv9m5-std',
		'error': 'remote backup not found',
		'filename': 'volume-snap-d4e0b2a6-25b3-40ca-851e-b8ecf0b76268.img',
		'isRestoring': True,
		'lastRestored': '',
		'progress': 100,
		'replica': 'longhorn-testvol-6qv9m5-restore-r-0ea1a7d0',
		'state': 'in_progress'
	}, {
		'backupURL': 'nfs://longhorn-test-nfs-svc.default:/opt/backupstore?backup=backup-5cbed6b3174043ce&volume=longhorn-testvol-6qv9m5-std',
		'error': 'remote backup not found',
		'filename': 'volume-snap-d4e0b2a6-25b3-40ca-851e-b8ecf0b76268.img',
		'isRestoring': False,
		'lastRestored': 'backup-5cbed6b3174043ce',
		'progress': 100,
		'replica': 'tcp://10.42.3.13:10015',
		'state': 'complete'
	}]
```

- `master` branch doesn't have this issue. This test case always passes in the recent 30 `master` builds
- in `v1.4.x`, `nfs` has higher failure rate than `s3`, like in https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/86/, the failure rate for `nfs` is 8/10, but the failure rate for `s3` is only 2/10

## To Reproduce

Run test case `test_basic.py::test_backup_lock_deletion_during_restoration`

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
@yangchiu Can you help check if v1.4.0 has the same issue? I'd like to narrow down the issue. Thank you.

**Comment by yangchiu** [comment]
> @yangchiu Can you help check if v1.4.0 has the same issue? I'd like to narrow down the issue. Thank you.

Yes, I got the same result in v1.4.0: https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-amd64/89/

**Comment by derekbit** [comment]
The issue is caused by the PR https://github.com/longhorn/longhorn-manager/commit/1f22bf19aa9de7d37a02c1a2b557d4bd146ce65e.

During the restoration process of a volume that contains multiple replicas, an attempt to delete a backup was rejected because the lock cannot be acquired. The behavior is expected and works well in this test.

A periodic check is performed by the engine monitor to determine whether a backup needs to be restored ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_controller.go#L1006)).
- The restore task was issued and started in the first reconciliation.
- After that, second reconciliation issues the restore task again, since the previous restore task was still in progress (`engine.Status.LastRestoredBackup` is `""`) and there were replicas that were not being restored ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_controller.go#LL1221C9-L1221C9)). 
- The backup was successfully deleted, because the restore issued in the _first_ reconciliation finished. The restore issued in the _second_ reconciliation failed because the backup is deleted and not found, and then the `restoreStatus.error` is set to `remote backup not found` ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_controller.go#L1379)).
- The replicas were marked as failed because of the `restoreStatus.error`.
- The restore died in the `wait_for_volume_restoration_completed(client, restore_volume_name)` check in the end.

**Comment by derekbit** [comment]
If the backup is being used for volume restoration, the backup deletion is not allowed.
We need to update the test case as well.

**Comment by innobead** [comment]
> If the backup is being used for volume restoration, the backup deletion is not allowed. We need to update the test case #1867 as well. The expected behavior will become
> 
> ```
> Create a volume and write 100 mb data to it.
> Take a backup.
> Restore the backup and immediately delete the backup.
> The restoring volume continues and the backup is not be deleted when running restoration.
> After restoration, the backup is deleted.
> ```

Of course, this can not be avoided if the backup target is used by another cluster at the same time. This should be tackled by the lock handling instead.

**Comment by innobead** [comment]
cc @mantissahz

**Comment by yangchiu** [comment]
This test case doesn't fail in the latest 3 `v1.4.x-longhorn-tests-sles-amd64`, `v1.4.x-longhorn-tests-sles-arm64`, `v1.4.x-longhorn-upgrade-tests-sles-amd64`, `v1.4.x-longhorn-upgrade-tests-sles-arm64` test builds.
