### ISSUE TITLE
[BUG][v1.4.1-rc1] Node disconnection test failed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5476]
## Describe the bug (🐛 if you encounter this issue)

In [Node disconnection test](https://longhorn.github.io/longhorn-tests/manual/pre-release/node/node-disconnection/) case 1, the desired behavior is: 
```
If there is data writing during the disconnection, 
due to the engine process not able to talk with other replicas, 
the engine process will mark all other replicas as ERROR.
```
The volume will remain `detached`, and all replicas remain in `error` state after node network connection back.

But in `v1.4.1-rc1`, network disconnection will not cause the replica on the attached node becoming `error` state, instead it remains `healthy`, and after node network connection back, replicas on other nodes can be rebuilt from this `healthy` replica, and finally all the replicas are in `healthy` state, which is not the expected behavior.

Need to confirm whether the behavior changing is expected.

## To Reproduce

manually execute [Node disconnection test](https://longhorn.github.io/longhorn-tests/manual/pre-release/node/node-disconnection/) case 1

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment]
@yangchiu how long the discussion was? 

cc @derekbit

**Comment by yangchiu** [comment]
> @yangchiu how long the disconnection was?
> 
> Case one is for 100 seconds for the disconnection, then what we would expect should be replicas marked as error already
> 
> cc @derekbit @shuo-wu @c3y1huang

100 seconds.

Following the same test steps, v1.4.0 doesn't have this problem. The behavior is same as the description in the test case.

**Comment by derekbit** [comment]
The behavior change is due to the commit https://github.com/longhorn/longhorn-manager/pull/1691.

In master-head/v1.4.1-rc1, disable auto-salvage in the following scenarios.

**Scenario 1: one of the replicas is on the attached node.**
- Attached node is disconnected
- The replica is on the attached node becomes `unknown`. _The connection between the engine and the replica still works, so the `unknown` state should be expected._
- The replica becomes `running` after the network connection is back. Then, other replicas are rebuilt from the replica on the attached node.
- In the end, all replicas are `running`.

**Scenario 2: none of the replicas is on the attached node.**
- Attached node is disconnected
- All replicas become `stopped` after the network connection is back.

@yangchiu Can you help check the behaviors again? Thank you.

**Comment by innobead** [comment]
If confirming the above test cases, then we need to update the test doc. cc @longhorn/qa

**Comment by yangchiu** [comment]
Yes, current behavior follows https://github.com/longhorn/longhorn/issues/5476#issuecomment-1453010590, and the test case needs to be updated.

**Comment by innobead** [comment]
@yangchiu It seems behavior change, so just close this if all is good, and also update the test cases accordingly. Thank.

cc @longhorn/qa

**Comment by yangchiu** [comment]
Manual test updated in https://github.com/longhorn/longhorn-tests/pull/1278, we can close this one.
