### ISSUE TITLE
[BUG] RWX volume attachment failed if tried more enough times

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#5537]
## Describe the bug (🐛 if you encounter this issue)

Related to https://github.com/longhorn/longhorn/issues/5456

According to users comments: https://github.com/longhorn/longhorn/issues/5456#issuecomment-1463344939, https://github.com/longhorn/longhorn/issues/5456#issuecomment-1463482400.

All he did is just:
(1) Create RWX volume and use it in each CI build
(2) Generate more enough builds and run for more enough days
Eventually he would observe [a RWX volume in faulted state and all replicas are failed](https://github.com/longhorn/longhorn/issues/5456#issuecomment-1461405399)

Currently we don't have existing test case of keeping creating multiple RWX volumes to simulate this scenario, so try to slightly modify the current test case to see if we can reproduce this. 

Modified `test_rwx_with_statefulset_multi_pods` to make it repeat itself for 10 times (so it would create **10** statefulsets with RWX volumes in the same round)
Something like: https://github.com/longhorn/longhorn-tests/commit/31245552d2a61353b682be174aed291922d8307d

And run this single test case in jenkins pipeline for more enough times (from https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3172/ to https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3195/, so there are **10** statefulsets * **24** builds = **240** statefulsets created in total), eventually we can observe statefulet failed to start: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3191/, and there is a faulted RWX volume in the same state as https://github.com/longhorn/longhorn/issues/5456#issuecomment-1461405399 if you check longhorn ui.

The detailed logs can be found in https://github.com/longhorn/longhorn/issues/5456#issuecomment-1464736712

## To Reproduce

Use test image `yangchiu/test-rwx-10` and run test case `test_rwx.py::test_rwx_with_statefulset_multi_pods`

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment]
Volume `vc-197a0290-5c20-40ee-97d6-d40b0fc54988`

- Node ip-10-0-1-27
  1. Volume got new owner ip-10-0-1-27 (`2023-03-11T00:50:44.685251886Z`)
  2. Share manager got new owner ip-10-0-1-27
  3. Created pod for share manager
  4. _cannot check IsNodeDownOrDeleted() when syncShareManagerPod_ --> `pod.Spec.NodeName` is `""`
  5. Creating instance pvc-197a0290-5c20-40ee-97d6-d40b0fc54988-r-0da8fd3f
  6. Deleting instance pvc-197a0290-5c20-40ee-97d6-d40b0fc54988-r-0da8fd3f
  7. ....

- Node ip-10-0-1-10
  - Volume got new owner ip-10-0-1-10 (`2023-03-11T00:50:47.661659692Z`)
  - ...

https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go#L606

The root cause of the issue is the failure to perform the `IsNodeDownOrDeleted` check before the `spec.NodeName` of the share manager pod is set. Then, the volume is requested to detach and transferred to another node, and the in-progress deletion of the replicas due to the previous failure lead to the faulty volume.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 3cc3cb7) by running test case `test_rwx.py::test_rwx_with_statefulset_multi_pods` of customized test image `yangchiu/test-rwx-10` for **24** times (created **240** statefulsets with RWX volumes). The test case passed in every build.
