### ISSUE TITLE
[IMPROVEMENT] Have explicitly message when trying to attach a volume which it's engine and replica were on deleted node 

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5545]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

From https://github.com/longhorn/longhorn-tests/pull/1279#discussion_r1133411257

Steps
1. Deploy Longhorn
2. Create a volume with 1 replica
3. Attach volume to node, make sure replica and volume were on the same node
4. Delete node volume attached to
5. Detach volume
6. Attach volume to another node will see below message
```
unable to attach volume <volume name> to <node name>: cannot attach volume <volume name> because the engine image longhornio/longhorn-engine:v1.4.1-rc2 is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to
```  
which is misleading because it should be the only replica is failed on the deleted node, so there is no available replica instead.

## Describe the solution you'd like

Have explicitly message  to reflect real situation

## Additional context

N/A

**Comment by ChanYiLin** [comment]
Hi
If I understand correctly,
after deleting the node `kubectl delete node.longhorn.io`, the volume should be `faulted` and cannot be detached and attached.
This is under progress in this issue: https://github.com/longhorn/longhorn/issues/5542

So is this issue still reproducible and requires fixing? Thanks!

cc @derekbit @weizhe0422 @chriscchien @innobead

**Comment by weizhe0422** [comment]
If the volume has only one replica on multiple nodes, I think the volume becomes `Degraded` when the node is removed or shut down, but the volume can still be detached and attached to another schedulable node.

**Comment by ChanYiLin** [comment]
Hi @innobead 
This issue is from https://github.com/longhorn/longhorn-tests/pull/1279#discussion_r1133573553
> this is expected because the replica was on the deleted node. However, the message looks misleading, because it should be the only replica is failed on the deleted node, so there is no available replica instead.
[/datastore/longhorn.go#L1489-L1494](https://github.com/longhorn/longhorn-manager/blob/423513ad5838695c0b481a1c5309a0ecb73abbe9/datastore/longhorn.go#L1489-L1494)

	for _, r := range replicas {
		isReady, err := s.CheckEngineImageReadiness(image, r.Spec.NodeID)
		if err != nil || isReady {
			return isReady, err
		}
	}


I understand the message is quite misleading from user's perspective
But the message reflect the right situation for the function `CheckEngineImageReadyOnAtLeastOneVolumeReplica()` 
```
unable to attach volume <volume name> to <node name>: cannot attach volume <volume name> because the engine image longhornio/longhorn-engine:v1.4.1-rc2 is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to
```

The message might also appear if all the nodes of the replicas have wrong engine-image 
So from my point of view `"is not deployed on at least one of the the replicas' nodes"` has already specified the situation
No matter it is because wrong engine or node is gone.

**Comment by innobead** [comment]
Agreed. 

The original message seems general for different cases, so it's no need to have a specific message for this case.
