### ISSUE TITLE
[BUG] [v1.3.3-rc2] After upgrade the volume engine to 1.3.3-rc2, volume status change to Faulted

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#5646]
## Describe the bug (🐛 if you encounter this issue)

In [#1279 DR volume live upgrade and rebuild](https://longhorn.github.io/longhorn-tests/manual/pre-release/backup-and-restore/dr-volume-live-upgrade-and-rebuild/) , step17:

Do live upgrade for the original volume and the 2nd DR volumes.

After ugrade the original volume engine from 1.3.2 to 1.3.3-rc2 , volume status change to Faulted

## To Reproduce

1. Install Longhorn v1.3.2
2. Create the volume and attach to node
3. Upgrade Longhorn system to 1.3.3-rc2
4. Upgrade volume engine image to v1.3.3-rc2
5. See erro
![Screenshot_20230323_144742](https://user-images.githubusercontent.com/104337648/227125005-7b456181-04e1-4046-9a77-601f61d581de.png)

## Log or Support bundle

[longhorn-support-bundle_d758dafe-1638-4db4-b1eb-0b9596f08f3f_2023-03-23T06-46-57Z.zip](https://github.com/longhorn/longhorn/files/11047788/longhorn-support-bundle_d758dafe-1638-4db4-b1eb-0b9596f08f3f_2023-03-23T06-46-57Z.zip)

**Comment by roger-ryao** [comment]
Hi @PhanLe1010 & @innobead 
     I was unable to reproduce it on the new cluster, and I suspect that it may be due to an issue with my environment.

**Comment by innobead** [comment]
Thanks, @roger-ryao . Still let @PhanLe1010 take a look the original support bundle to see if any problem.

**Comment by PhanLe1010** [comment]
Root cause analyst: 

Short answer: It was caused by the mistake in this commit https://github.com/longhorn/longhorn-manager/commit/580208f27772b8c6f74d43f46eaf3651b5e07dc9

More details:

1. volume.SPec.EngineImage changed to newEI. Volume enters [upgrade process](https://github.com/longhorn/longhorn-manager/blob/0e366f8867fcad3a5681919aa4399f93e54033c4/controller/volume_controller.go#L2417). 
2. Volume controller [create inactive migrating replicas](https://github.com/longhorn/longhorn-manager/blob/0e366f8867fcad3a5681919aa4399f93e54033c4/controller/volume_controller.go#L2534) and [set engine.Spec.EngineImage to newEI](https://github.com/longhorn/longhorn-manager/blob/0e366f8867fcad3a5681919aa4399f93e54033c4/controller/volume_controller.go#L2573)
3. Engine controller start the live upgrade with new replicas then set engine.Status.CurrentEngineImage to newEI
4. Volume controller set old replicas to inactive but failed to set new replicas to active because of [the `!r.DeletionTimestamp.IsZero()` mistake ](https://github.com/longhorn/longhorn-manager/blob/580208f27772b8c6f74d43f46eaf3651b5e07dc9/controller/volume_controller.go#L2582)
5. Now all replicas are inactive 
6. Volume controller [set v.Status.CurrentEngine Image to newEI](https://github.com/longhorn/longhorn-manager/blob/580208f27772b8c6f74d43f46eaf3651b5e07dc9/controller/volume_controller.go#L2591) -> signling that the upgrading is finished 
7. Then cleanupCorruptedOrStaleReplicas [cleanup all replicas (because they are all inactive)](https://github.com/longhorn/longhorn-manager/blob/580208f27772b8c6f74d43f46eaf3651b5e07dc9/controller/volume_controller.go#L829-L834)
8. Volume become faulted because all replicas are deleted

**Comment by PhanLe1010** [comment]
Since we merged the fix PR: https://github.com/longhorn/longhorn-manager/pull/1801, this issue cannot happen anymore. Moving the ticket to ready for testing

**Comment by roger-ryao** [comment]
**Verified on v1.3.3-rc2 20230327**

**The test steps**

https://github.com/longhorn/longhorn/issues/5646#issue-1636951477

**Result Passed**
