### ISSUE TITLE
Since update to 0.5 AWS EU-Requests-Tier1 increased

### ISSUE THREAD

**Issue by vistalba** [longhorn/longhorn#573]
Since update to v0.5.0 I see a increase of the request (EU-Requests-Tier1) in my S3 AWS Cost explorer by factor 10.

---
Version: `v0.5.0`

**Comment by yasker** [comment]
Oh, it's likely due to the new backup related features. We currently polling backup target every 5 minutes (by default) to update the latest backup. 

You can set the settings BackupStorePollInterval to a large number to delay the polling. Though if you're on disaster recovery setup for multicluster, this won't be favorable. We can add a way to disable the auto polling e.g `using value 0` to disable the feature for single cluster users. 

Sorry for the incurred additional cost, we will make sure next time we change things may impact the S3 bill, we will put it in our release note.

**Comment by vistalba** [comment]
I alreay set this value to 3600. 

It wasn't a real problem for my bill. It just increased from 0.01 cent/day to 0.1 cent/day. It's just a test cluster with 7 volumes so it doesn't really matter but for people with a lot of backups this may be relevant. 

I don't understand the point with "disaster revocery setup".
I already tested in version v0.4.1 a recovery from S3 on a new clean rancher-cluster with a new longhorn install. It worked fine for all the 7 volumes I have. Without this "BackupStorePollInverval". I did all the steps manually.

1. Start rancher docker
2. login
3. install driver
4. create cluster and some VMs (3 nodes)
5. after it was ready I deplyoed longhorn from apps
6. after it was deployed I opend the longhorn GUI -> settings
7. configured the S3 storage like before
8. go to "Backup" in longhorn GUI
9. Select image to restore and define the name of the volume (I set the same as before on the old cluster)
10. attach the volume to a node to start restore
11. after restore deployed the deployment on rancher/k8s

**Comment by yasker** [comment]
@vistalba Yeah, the disaster recovery feature is an upgraded version of the current process. The restoration is copying the data from the backup store, which can take a long time. It's undesirable if the volume is very big and needs quite some time (e.g. hours) to be copied over.

The disaster recovery feature is designed so the volume in the backup cluster will constantly poll the backup store, and if any new backup for the volume appears, the volume in the backup cluster will automatically start the restoration process, and it would be incremental so it only copies the data that changed. In this way, once you have an accident, you just need to `activate` the volume in the backup cluster, the time spent on restoring the volume should be much less or none (depends on if there is any data hasn't be restored yet), so you can start your workload much faster. This is designed to achieve a better RTO by reducing the volume restoration time.

**Comment by vistalba** [comment]
@yasker thanks for explaination. Nice feature.

So I think it is useful if this feature isn't used (e.g. there is no backup cluster in place) it can be disabled. 
Maybe it is also a good idea to better explain what the setting is doing. My backup-plan creates one backup per day - if I understand you right - there is no sense to poll the store more often. So maybe there is a way to calculate a good/the best value from the sheduled backups. (something like the shortest timespan between two backups of the same volume and the timeplan over all volumes).

e.g.:
If all backups are done within 01:00am and 05:00am just once a day. Poll just once in 24h maybe at 05:30am

If all backups are done all around the clock every hour. Poll just every 3600 seconds.

**Comment by yasker** [comment]
@vistalba In your case, this setting should be disabled. The setting BackupStorePollingInterval is useful in the backup cluster. If it's in the same cluster, any backup and list backup operation has a side effect to update the related `Last Backup` field, so you don't need to poll the store if you're making backups from the same cluster.

**Comment by yasker** [comment]
We will add a disable option to the BackupStorePollingInterval. If it's 0, it's disabled.

**Comment by meldafrawi** [comment]
Steps to test:
- Create 2 K8S clusters (A & B), install longhorn, and create longhorn `StorageClass`
- Create an AWS S3 bucket, and configure backup target to use it for both clusters.
- On Cluster B Settings page:  set `Backupstore Poll Interval` to **0**
- On Cluster A: Create Longhorn volume `XA`, attach it to a node, and create a backup.
- On Cluster B, backup page, click `Create Disaster Recovery Volume` and create a DR volume `XA_DR` 

**Expected result:**  `XA_DR`'s `Last Backup At` value on `Volume` page will not be updated since `Backupstore Poll Interval` is disabled on Cluster B,

- On Cluster B Settings page:  set `Backupstore Poll Interval` backup to **nonzero value**
- On Cluster A: Create a new backup of volume `XA`.

**Expected result:**  `XA_DR`'s `Last Backup At` value on `Volume` page will not be updated

**Comment by ywei88** [comment]
> On Cluster B Settings page: set Backupstore Poll Interval backup to nonzero value
> On Cluster A: Create a new backup of volume XA.
> Expected result: XA_DR's Last Backup At value on Volume page will not be updated

Actually when you set the backupstore poll interval to nonzero value, the backup polling should be enabled again and the XA_DR's Last Backup At value on volume page should be updated

**Comment by meldafrawi** [comment]
it was a typo, i updated it, thank you.
