### ISSUE TITLE
[Feature request] Restore backup schedule when restoring volume or allow choosing storage class with schedules

### ISSUE THREAD

**Issue by vitobotta** [longhorn/longhorn#578]
At the moment, if I create a storage class that defines snapshot/backup schedules, whenever I create a volume with that storage class the volume inherits the snapshot/backup schedules. However when I restore the volume from backup, those schedules are lost so you need to remember to reschedule the backups manually from the UI. It would be nice if either the schedules were saved with the backup or, perhaps better, if we could choose the storage class to use when restoring the volume, so that the storage class' schedules are applied to the restored volume. Is this possible? Thanks!

**Comment by yasker** [comment]
@vitobotta 

It would be weird for the backup to store the scheduling since it's hard to say this volume will always have the same backup scheduling.

Storage Class does support `fromBackup`, you may able to copy the original storage class, then add this field to create the volume. It's a bit cumbersome, but Kubernetes doesn't allow extra per PV/PVC parameters currently.

If you are restoring the volume from the UI, I am thinking something like #467 , which make it easier to apply the similar policy to a bunch of volumes.

**Comment by innobead** [comment]
already implemented in https://github.com/longhorn/longhorn/issues/2227

cc @mantissahz
