### ISSUE TITLE
[BUG] Prevent Longhorn uninstallation from getting stuck due to backups in error

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5868]
## Describe the bug (🐛 if you encounter this issue)

If a backup is in error state and its backup volume doesn't exist, the Longhorn uninstallation will be stuck.
The workaround is deleting the backups in error and then uninstalling Longhorn.

## To Reproduce

1. Setup a NFS backup target and list the Backup UI page
2. Shutdown the NFS server
3. Create a volume
4. Back up the volume
5. The backup will be in error state in the end, and the backup volume resource of the volume is not created
6. Uninstall the Longhorn system. Then uninstallation will be stuck.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: v1.4.x and master-head (older version should have the same issue)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by ChanYiLin** [comment]
The reason is that when doing uninstalling
1. we first unset the `backupTartget` which leads to the cleanup of `backupVolume`: [ref](https://github.com/longhorn/longhorn-manager/blob/master/controller/backup_target_controller.go#L341)
2. The deletion of `backupVolume` will also delete all the `backups` of the `backupVolume`
3. Thus, in `uninstall_controller.go`, both `backupVolume` and `backup` should not be found. https://github.com/longhorn/longhorn-manager/blob/master/controller/uninstall_controller.go#L423-L437

But in this case, since the `backupVolume` was not found, the unset of `backupTartget` didn't cleanup any backupVolume and thus the `backup` was not deleted.

We should manual delete those backup who doesn't have backupVolume.

**Comment by mantissahz** [comment]
Verified Passed:
Both in longhorn master ([3fb1815](https://github.com/longhorn/longhorn-manager/commit/3fb181527a6e940403ede238206253c9c81a0c8f)) and 1.5.x head ([98c2a4f](https://github.com/longhorn/longhorn-manager/commit/98c2a4f1ae56bf616b092d6df420aa8a1397012c)) by [test steps](https://github.com/longhorn/longhorn/issues/5868#issuecomment-1581804471)
