### ISSUE TITLE
Suggestion: Announce replica state via Pod annotations

### ISSUE THREAD

**Issue by rbq** [longhorn/longhorn#589]
Would it be possible make Longhorn annotate Pods belonging to replicas with their individual replication state, as well as the volume's state?

The reason: I'm running [kured](https://github.com/weaveworks/kured) (Kubernetes Reboot Daemon) to trigger (one at a time) node reboots when the OS requests one by creating `/var/run/reboot-required`. I'd very much like to block this for nodes which currently run any part of a degraded volume, especially a healthy replica. I think the easiest way to achieve this with kured would be with [Pod labels](https://github.com/weaveworks/kured#blocking-reboots-via-pods).

**Comment by yasker** [comment]
@rbq 

Currently, our replica pods will always have the label `longhorn-volume-replica=test` on them. Any running replica will either be healthy or rebuilding. Faulted replica won't be running on the node.

Though in the next release v0.6.0, we're going to change the way of deploying engine and replicas. We are going to use two DaemonSet act as a container for the engine and replicas, and creating engine or replica processes in it instead of spinning up a pod for each every time. It will be faster for attaching/detaching, as well as solved the 110 pods per node limitation for Kubernetes.

We need to think about how to deal with your use case then...

**Comment by rbq** [comment]
@yasker Okay, thanks!
