### ISSUE TITLE
manager: scheduler retry for replica is too quick, result in unnecessary system load

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#599]
Noticed it when checking #570 . Tried the scheduling failure case and notice an abnormal. The retrying for scheduling happens too quick when there is obviously no way to schedule another replica. We need to somehow slow that down (the easy way) or don't retry scheduling until a certain condition is met (need more thoughts).

**Comment by ttpcodes** [comment]
Regarding the first approach, we can follow something similar to the Kubernetes `CrashLoopBackOff` that gradually slows down the retry attempts as subsequent attempts fail and it becomes apparent that the cause of the scheduling failure will take longer to resolve. We should, of course, modify this logic a bit so it doesn't time out progressing or reach absurdly long back off wait times.

Regarding the second approach, we need to identify the conditions under which a `Replica` might become eligible for scheduling again. From what I see, these are the conditions that can allow for a `Replica` to be scheduled after it's encountered a scheduling failure (assuming `Disk` size, `Tags`, `Affinity`, and other requirements are met:
1. A new `Node` comes online, so a `Replica` can be scheduled on that new `Node`.
2. `Replica Hard Anti-Affinity` is disabled, so a `Replica` can be scheduled on a `Node` with an existing `Replica`.
3. A `Node` gets updated `Tags`, so a `Replica` can now be scheduled to that `Node` since the `Tags` match.
4. A `Node` now has sufficient available `Disk` space, so a `Replica` can now be scheduled to that `Node` and fit on the `Disk` without issues.
There may be a few cases I've missed. 

It looks like based on the conditions that could allow for a `Replica` to be scheduled, what we can do is listen for the `Node` and `Settings` updates, and limit our attempts to retry scheduling for when we receive one of these events.

**Comment by yasker** [comment]
@ttpcodes Yeah, those changes you listed should trigger volume's reconciliation. I think the current retry mechanism due to other volume related state change as well. We can implement a backoff by putting a volume specific `lastSchedulingFailed` in the volume controller. Kubernetes's maximum retry period for pod failure is 5 minutes, though I am not sure how Kubernetes handles scheduling failure (I don't think it can be 5 minutes).

**Comment by ttpcodes** [comment]
Oh yeah, changes to `Volumes` such as a `Volume` having one less `Replica` could free up space and potentially allow a previously failing `Replica` to be scheduled.

Based on my own experience with Kubernetes `Deployments`, if a `Pod` fails to get scheduled somehow, such as due to a lack of requested resources, the same `CrashLoopBackOff` retry logic seems to apply silently in the background. Kubernetes doesn't explicitly report a `CrashLoopBackOff`, but it still times out after a scheduling failure 10 minutes later, which is the same time that a `Pod` `CrashLoopBackOff` gives up. It also waits for the end of the `CrashLoopBackOff` period before attempting to run whatever scheduling logic it uses, just like with a `Pod` `CrashLoopBackOff`, so I'm inclined to believe that the logic is the same.

In fact, I did some looking around and found what `Kubernetes` seems to use to manage `CrashLoopBackOff`. The `client-go` library [has a package named flowcontrol](https://godoc.org/k8s.io/client-go/util/flowcontrol) that allows you to instantiate an instance of `Backoff`, which appears to be a store that allows you to track the individual `Backoff` states of various objects identified by `string` keys. It can also be instantiated with custom back-off periods and maximum back-off times so we can customize it as we need for `longhorn-manager` to handle `back-off` appropriately.

**Comment by yasker** [comment]
Sounds good. 

We don't want a backoff to 10 minutes though. Let's set the maximum backoff to 1 minute for now.

**Comment by yasker** [comment]
@meldafrawi Reproduce steps:

1. Enable hard anti-affinity option
2. Create a volume with 3 replicas on 3 nodes.
3. disable scheduling on one node.
4. Delete one replica.

Without the fix, you should see the replica was created then deleted rapidly (e.g. one per second). in the volume detail page.

**Comment by meldafrawi** [comment]
Validation: PASSED
