### ISSUE TITLE
[BUG] longhorn manager fails to startup: unable to get image on v1.4.2 with K8s v1.25

### ISSUE THREAD

**Issue by Phoenixfan** [longhorn/longhorn#6051]
## Describe the bug (🐛 if you encounter this issue)

Similar to #5963 my RKE2 cluster self updated to k8s 1.25 while v1.3.2 of Longhorn was still installed. This in turn caused all pvc and deployments as described in #4003 not to work anymore. Panicing due to every service being unavailable I made the rash decision to downgrade RKE2 to k8s 1.24 by putting the old binary files and upgrade longhorn to v1.4.2. Then I upgraded K8s back to v1.25.

However currently the longhorn manager isn't starting up properly anymore and crash loops. Therefore the UI isn't available either and throws 502. 

```
time="2023-06-01T08:00:15Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: failed to execute: nsenter [--mount=/host/proc/18083/ns/mnt --net=/host/proc/18083/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n: exit status 2"
...
time="2023-06-01T08:00:15Z" level=warning msg="Error syncing Longhorn replica longhorn-system/pvc-63e9eb2f-4d0b-446d-960a-538c5c9585d8-r-438240cc" controller=longhorn-replica error="failed to sync replica for longhorn-system/pvc-63e9eb2f-4d0b-446d-960a-538c5c9585d8-r-438240cc: failed to cleanup the related replica process before deleting replica pvc-63e9eb2f-4d0b-446d-960a-538c5c9585d8-r-438240cc: failed to get engine image object based on image name rancher/mirrored-longhornio-longhorn-engine:v1.2.3: engineimage.longhorn.io \"ei-47b59147\" not found" node=kgg
```
The error while getting the engine image is repeated for every pvc present and in the end it fails with the following statement:
```
time="2023-06-01T08:00:15Z" level=fatal msg="Error starting manager: admission webhook \"validator.longhorn.io\" denied the request: failed to set the setting taint-toleration with invalid value : cannot modify toleration setting before all volumes are detached"
```

Down below there is a full log attached. At this point I'm not sure on what to do anymore. There are backups of every volume in S3 created using a recurring backup job within the longhorn ui. But without the longhorn manager I won't be able to load them. Also I'm really sorry if this is a duplicated or not the right way to report this. My Longhorn setup ran 500 days without issues and I spend days trying to fix it on my own but at this point I'm outmatched.

## To Reproduce

1. Install Longhorn 1.3.2 on RKE2/K8s 1.24
2. Upgrade RKE2/K8s to 1.25 and have Longhorn fail
3. Downgrade RKE2/K8s to 1.24 and upgrade Longhorn using Helm to 1.4.2
4. Upgrade RKE2/K8s to 1.25

## Expected behavior

Longhorn manager reaches the healthy state and UI is responsive.

## Log or Support bundle

Unable to obtain a Support bundle due to the manager being in a Crashloopbackoff.

## Environment

 - Longhorn version: 1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.25.10+rke2r1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Arch Linux
   - CPU per node: 6
   - Memory per node: 64GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: single node setup
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: ~30

## Additional context

Attached is the full longhorn manager log file downloaded using rancher.
[longhorn-manager-t6wzr_longhorn-manager.log](https://github.com/longhorn/longhorn/files/11634493/longhorn-manager-t6wzr_longhorn-manager.log)

**Comment by ejweber** [comment]
Hello @Phoenixfan. I'm glad to hear Longhorn has been working out for you for the last 500 days and I'm sorry to hear about the current issue. 

It may become necessary, if you're absolutely sure that you have all volumes backed up, to unset your backup target (`kubectl edit -n longhorn-system setting backup-target`) and attempt to uninstall/reinstall Longhorn. Once Longhorn is installed, you can restore backups to new volumes, though it won't be particularly convenient, and you will lose configuration, etc.

For now, it seems like longhorn-manager is failing because it thinks you are trying to update the taint-toleration setting, but you are not allowed to do so because volumes are attached. Some possible actions to take:

- You may be able to set the status of any "attached" volumes to "detached". It's possible that this will allow longhorn-manager to proceed, since there is no longhorn-manager to reset it.
- You might check if you have the setting CR taint-toleration `kubectl get -n longhorn-system taint-toleration`. Compare its value to anything you find in the longhorn-default-setting ConfigMap. If the values are different, that could be causing the failed update.

**Comment by Phoenixfan** [comment]
Thank you so much @ejweber.
I was able to confirm that all volumes were indeed in my backup and from right before the incident. Following that I had to remove the backup target and some finazilers from remaining resources similar to https://github.com/longhorn/longhorn/issues/5963#issuecomment-1566226111. After that the helm unstall went through and was able to create a fresh setup. The import of the backup is mostly done and my cluster is operational again. 
Thanks again!
