### ISSUE TITLE
UI: Replica Hard Anti Affinity checkbox

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#607]
**Longhorn UI version:

**Settings page:**
  - `Replica Hard Anti Affinity` **checkbox** need to go up adjacent to the text, and help info get  aligned with the rest of help info in the page.

![Screenshot from 2019-06-28 23-23-49](https://user-images.githubusercontent.com/18232258/60372131-dde31a80-99fb-11e9-8024-d2c8bdf9df57.png)

**Comment by vincent99** [comment]
"Required" has no meaning on a checkbox; it's impossible to not provide a value.

Instead of a negative title (`Anti-`) and negative description (`Prevent...`), consider flipping it:

`[ ] Allow scheduling more than one healthy replica of a volume per node`

Or two radio buttions:

```
( ) Suggested: Require each healthy volume replica to be on a distinct node
(*) Advanced: Allow a volume to have multiple healthy replicas on a single node
```

</random UX drive-by>

**Comment by yasker** [comment]
@vincent99 Yeah, flip it makes sense. @ttpcodes Can we flip the option and set the default to be true?

The reason there is a "required" for the checkbox is that we have other required non-empty fields in the setting, so the property is included in the schema of the setting, and "required=false" doesn't sound like a correct choice.

@smallteeths Can you check if we can have a better layout for the checkboxes in the settings? It's indeed not aligned with others.

**Comment by meldafrawi** [comment]
fixed
