### ISSUE TITLE
[IMPROVEMENT] Minor UX changes for Longhorn SPDK

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6126]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Some changes for a better user experience (only user-facing part, we don't need to change anything internally). Also, for all changes below, need to update the doc accordingly if needed. 

## Describe the solution you'd like

- [x] Use v1 for the current engine, and v2 for the SPDK-based engine instead of Longhorn vs SPDK
- [x] Change `DO NOT CHANGE THIS SETTING WITH ATTACHED VOLUMES. Longhorn will try to block this setting update when there are attached volumes.`  Remove `try`, just said `Longhorn will block ..`.
- [x] Add a known issue about the actual size unable to display in the doc. Also, need a corresponding issue for later SPDK part improvement. 
  - tracked in https://github.com/longhorn/longhorn/issues/5947
- [x] Change replica number to 3 https://github.com/longhorn/longhorn/blob/master/examples/spdk/storageclass.yaml#L11, also the original storage class example for the old stack. 
- [x] We already highlight CPU usage for SPDK in doc but suggest emphasizing it to the setting as well to notice users actively. 

## Additional context

cc @longhorn/dev-data-plane

**Comment by derekbit** [comment]
>  Use v1 for the current engine, and v2 for the SPDK-based engine instead of Longhorn vs SPDK

We need to change instance-manager, longhorn-manager, longhorn-ui and chart.

**Comment by derekbit** [comment]
@smallteeths
Not sure if UI needs changes, can you help check it on UI part?
longhorn->v1
spdk->v2

**Comment by derekbit** [comment]
@innobead 

`SPDK Data Engine` -> do we need to rename it to `V2 Data Engine`? Sounds a bit weird...

**Comment by innobead** [comment]
> @innobead
> 
> `SPDK Data Engine` -> do we need to rename it to `V2 Data Engine`? Sounds a bit weird/confusing...

Let's discuss this later.

**Comment by shuo-wu** [comment]
Found one more thing that may be improved:
When adding a new disk via UI, the UI will automatically add `/` at the end of the path if the disk type is not set to `Block` in advance.
I think this behavior is redundant... Can we remove it?

**Comment by derekbit** [comment]
> Found one more thing that may be improved: When adding a new disk via UI, the UI will automatically add `/` at the end of the path if the disk type is not set to `Block` in advance. I think this behavior is redundant... Can we remove it?

cc @smallteeths

**Comment by smallteeths** [comment]
> Found one more thing that may be improved: When adding a new disk via UI, the UI will automatically add `/` at the end of the path if the disk type is not set to `Block` in advance. I think this behavior is redundant... Can we remove it?

Alright, Derekbit also noticed this issue. We started discussing adjusting the input order of path and type. However, it seems that even with this adjustment, the user experience is still not satisfactory. I'm planning to remove the frontend's default logic of adding `/`. cc @Derekbit

**Comment by roger-ryao** [comment]
**Verified on v1.5.x-head 20230619**

- longhorn v1.5.x-head https://github.com/longhorn/longhorn/commit/428f1d54c1e4fad33b33782888f30125cf56c725
- longhorn-ui v1.5.x-head https://github.com/longhorn/longhorn-ui/commit/8fd8e1e3e9f93d587e5f6322776e4a67791adcf8
- longhorn-manager v1.5.x-head https://github.com/longhorn/longhorn-manager/commit/0e9970f253be577df477f1d14c34a32d6021728f
- longhorn-instance-manager v1.5.x-head https://github.com/longhorn/longhorn-instance-manager/commit/bd0102536141edb9772de7299335b53f8184db60


**Verified on master-head 20230619**

- longhorn master-head https://github.com/longhorn/longhorn/commit/2cd1af070eaeb37ec45d75c44e5c78d2c4f4eb41
- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/26c115f7656a58f255079cced41e3538b4eb2a1b
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/c322b37091839d50dfdcf331a8fa0ea6004d9fd1
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/4f3d40da7dcf8bfeb8f6cae5c377892967b812e1


**The test steps**
https://github.com/longhorn/longhorn/issues/6126#issue-1757839771

**Result**

- [x] 1. Use `v1` for the current engine, and `v2` for the `SPDK-based engine` instead of Longhorn vs SPDK
- [x] 2. Change `DO NOT CHANGE THIS SETTING WITH ATTACHED VOLUMES. Longhorn will try to block this setting update when there are attached volumes.`  Remove `try`, just said `Longhorn will block ..` on the Longhorn UI and [web](https://longhorn.io/docs/1.5.0/references/settings/#v2-data-engine).
- [x] 3. Add a known issue about the actual size unable to display in the doc. Also, need a corresponding issue for later SPDK part improvement. 
  - tracked in https://github.com/longhorn/longhorn/issues/5947
- [x] 4. Change replica number to 3 https://github.com/longhorn/longhorn/blob/master/examples/v2/storageclass.yaml#L11, also the original storage class example for the old stack. 
- [ ] 5. We have already highlighted CPU usage for SPDK in [the documentation](https://longhorn.io/docs/1.5.0/spdk/#cpu), specifically in the doc. However, when enabling the `V2 Data Engine`, we did not receive any notice or alert regarding CPU usage. Do we have any plans to implement that in the Longhorn UI?

cc @derekbit

**Comment by derekbit** [comment]
For point 5, https://github.com/longhorn/longhorn-manager/pull/2010

**Comment by roger-ryao** [comment]
**Verified on v1.5.x-head 20230619**

- longhorn v1.5.x-head https://github.com/longhorn/longhorn/commit/e651a6a368bc521c71b6383d0ba99cb54a973185
- longhorn-ui v1.5.x-head https://github.com/longhorn/longhorn-ui/commit/8fd8e1e3e9f93d587e5f6322776e4a67791adcf8
- longhorn-manager v1.5.x-head https://github.com/longhorn/longhorn-manager/commit/2c7f9fb87a58500ef4c537a25d6975fe5f3f17fb
- longhorn-instance-manager v1.5.x-head https://github.com/longhorn/longhorn-instance-manager/commit/7d08b6e28f9dd1b030237d199d21eb76c2d894af


**Verified on master-head 20230620**

- longhorn master-head https://github.com/longhorn/longhorn/commit/a601ecc4684435093a9d92dd05621b837d77a5ad
- longhorn-ui master-head https://github.com/longhorn/longhorn-ui/commit/26c115f7656a58f255079cced41e3538b4eb2a1b
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/fd272ea791b1b0bf9d7df2fc52cfd2ff81ece61a
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/e1fa7623179316b0236eb2e110ddef25030c3712

**Result**
    

- [x] 1. `Master-head` & `v1.5.x-head`  have been tested and passed. 



![Screenshot_20230620_160639](https://github.com/longhorn/longhorn/assets/104337648/84a6a723-d9e6-47d6-ab04-63d607c75f85)
