### ISSUE TITLE
[TEST] Upgrade test failed: unable to detach volume

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6200]
## What's the test to develop? Please describe

Recently upgrade test case failed in our daily regression like:
https://ci.longhorn.io/job/public/job/v1.5.x/job/v1.5.x-longhorn-upgrade-tests-sles-arm64/28/testReport/junit/tests/test_upgrade/test_upgrade_from_stable_/
https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/512/testReport/junit/tests/test_upgrade/test_upgrade_from_stable_/

It tried to detach a volume after upgrade, but failed.

Probably related to the volume attach/detach refactoring https://github.com/longhorn/longhorn/issues/3715.

But we don't have this issue in `v1.5.0-rc2`.

## Describe the items of the test development (DoD, definition of done) you'd like
> Please use a task list for items on a separate line with a clickable checkbox https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

- [ ] `item 1`

## Additional context

Add any other context or screenshots about the test request here.

**Comment by innobead** [comment]
cc @longhorn/qa 

Is this able to reproduce manually?

**Comment by yangchiu** [comment]
Yes. It's all about the parameter of volume detach API, but need @PhanLe1010 to confirm this behavior change is desirable.

**Comment by PhanLe1010** [comment]
Looks like the Longhorn manager's upgrade path create attachment ticket with ID `longhorn-ui` because it is assume that all attachment ticket which is not created by CSI and ShareManager is from Longhorn UI. This is mostly correct for a regular user because they will either use UI or CSI flow. However, Longhorn e2e test is not aware of this so we can fix the upgrade test.

I am expecting this issue to happen with the e2e test only. @yangchiu Could you give the steps for manual reproducing?

**Comment by PhanLe1010** [comment]
Acutallly there is another issue when PV and Longhorn volume name is not the same. Will push a PR soon to show this point

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-test cd204c8). Upgrade test can pass: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4354/
