### ISSUE TITLE
[IMPROVEMENT] Improve upgrade path and make it more solid

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6294]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

A few users have reported successful upgrades of Longhorn systems, but the resources are not being updated as expected. At present, we do not have a set of reproducible steps. Nonetheless, it appears that the upgrade path lacks sufficient resilience.
The objective of the ticket is to reassess the upgrade path and enhance its solidity.

Related issues:
https://github.com/longhorn/longhorn/issues/6259
https://github.com/longhorn/longhorn/issues/6582
https://github.com/longhorn/longhorn/issues/6688

## Additional context

https://github.com/longhorn/longhorn/issues/6259

**Comment by PhanLe1010** [comment]
### Reproduce steps:
1. To simulate a slow cluster, I Introduce some delay when longhorn-manager pods and webhook pods are being terminated to longhorn-manager v1.4.3 (see the code [here](https://github.com/PhanLe1010/longhorn/commit/78d8b540c605de31589f80b02d48222c12348d45)). In a 3-node cluster, this modification will make:
    * longhorn manager pod on the node with smallest name take 0 second to
      be terminated
    * longhorn manager pod on the node with 2nd smallest name take 10 second to
      be terminated
    * longhorn manager pod on the node with biggest name take 20 second to
      be terminated
    * all webhook pods take 26 seconds to be terminated
2. On a 3-node cluster, deploy Longhorn v1.4.3 with this customized longhorn-manager image `phanle1010/longhorn-manager:v1-4-3-added-slow-termination`. You can use this yaml for your convenience https://github.com/PhanLe1010/longhorn/commit/78d8b540c605de31589f80b02d48222c12348d45. 
3. Create about 12 Longhorn volume of 4 replicas and attach 4 volumes to each nodes
4. Upgrade Longhorn to v1.5.1 by `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/deploy/longhorn.yaml`
5. Get all volume yaml by `kubectl get volumes -n longhorn-system -oyaml > temp`
6. Verify that some volume doesn't have the field `status.offlineReplicaRebuildingRequired` which indicate that the upgrade path is broken due to old Longhorn manager took a long time to be terminated thus it was running while the new Longhorn manager on a new node has been started upgrading.

**Comment by PhanLe1010** [comment]
### Test steps:

**Case 1: Test the reproducing steps**

1. Repeat [the reproducing steps](https://github.com/longhorn/longhorn/issues/6294#issuecomment-1724914808) above with the modification that instead of upgrading to v1.5.1 we upgrade to v1.5.x version 
1. Make sure that in the `temp_output`, once  `current-longhorn-version` is set to `v1.5.1`, there is NOT old Longhorn manager. 
1. Repeat this test 3 times

**Case 1: Test upgrade paths**

Make sure that the following upgrade path is ok. Each upgrade should have some basic volume operations in the between:
1. `v1.3.3` to `v1.4.x-head`
1. `v1.4.3` to `v1.5.x-head`
1. `v1.4.x-head` to `v1.5.x-head`
1. `v1.5.1` to `v1.5.x-head`
1. `v1.5.x` to `master-head`

**Comment by roger-ryao** [comment]
Need @PhanLe1010  to provide the commit on `v1.5.x`, similar to what [he did previously for v1.4.3](https://github.com/PhanLe1010/longhorn-manager/commit/66e73f92b84cad799cf97b8e433999727dfe892f#diff-ef0bcd55c1d2292c666ecebf69ede458d884fc5bb514a4c9bf512f55cecd69f7R207-R237).

After building these customized `v1.5.x` Longhorn Manager images, I will test the following upgrade scenarios:
For milestone 1.6.0:
`v1.5.x-head-added-slow-termination` upgrade to `master-head`
`v1.5.1-added-slow-termination`           upgrade to `master-head`

**Comment by PhanLe1010** [comment]
Provided `https://github.com/PhanLe1010/longhorn-manager/commit/8b5e39f7e82036176bb3846b2f9286418ead513d`

**Comment by roger-ryao** [comment]
**Verified on master-head 20231116**

- longhorn master-head https://github.com/longhorn/longhorn/commit/74d829d6e81c937baa25a6bc78041f27b361b5e5
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/483ef28241deeae04cb193d1fd22d1b213915835

**The test steps**

https://github.com/longhorn/longhorn/issues/6294#issuecomment-1724914808

**Result Passed**

- [x] 1. `v1.5.x-head-added-slow-termination` upgrade to `master-head`
- [x] 2. `v1.5.1-head-added-slow-termination` upgrade to `master-head`
