### ISSUE TITLE
failed to acquire lease

### ISSUE THREAD

**Issue by jocarren** [longhorn/longhorn#632]
I have a rancher cluster with 2 nodes running Longhorn, both nodes are in different locations linked by a layer 2 tinc vpn. 
When I create a pod, the PVC gets created but only replicas in one of the nodes are healthy, replicas on the other node are "failed". 

csi-attacher logs on failed node: 

> I0712 17:55:01.024351 1 leaderelection.go:271] lock is held by csi-attacher-799cdf866b-2kdq5 and has not yet expired
I0712 17:55:01.024378 1 leaderelection.go:192] failed to acquire lease longhorn-system/external-attacher-leader-io-rancher-longhorn
I0712 17:55:10.811745 1 leaderelection.go:271] lock is held by csi-attacher-799cdf866b-2kdq5 and has not yet expired
I0712 17:55:10.811783 1 leaderelection.go:192] failed to acquire lease longhorn-system/external-attacher-leader-io-rancher-longhorn
I0712 17:55:19.745053 1 leaderelection.go:271] lock is held by csi-attacher-799cdf866b-2kdq5 and has not yet expired
I0712 17:55:19.745084 1 leaderelection.go:192] failed to acquire lease longhorn-system/external-attacher-leader-io-rancher-longhorn
I0712 17:55:27.519571 1 leaderelection.go:271] lock is held by csi-attacher-799cdf866b-2kdq5 and has not yet expired
I0712 17:55:27.519608 1 leaderelection.go:192] failed to acquire lease longhorn-system/external-attacher-leader-io-rancher-longhorn
I0712 17:55:35.315378 1 leaderelection.go:271] lock is held by csi-attacher-799cdf866b-2kdq5 and has not yet expired

**Comment by yasker** [comment]
@jocarren The csi attacher's log is normal.

Longhorn needs a good underlying network to work. Normally it runs on top of the network with at least 1Gb bandwidth between the nodes. Since it's a storage software, imagine pumping hundreds of MB's data using the slow network, it will result in connection failure or volume failure because block device has a strict requirement on how long the timeout can be. The block layer won't wait for the data forever. That's likely the reason why one of the replicas (which runs on the other node across the VPN) failed.

I would not recommend using Longhorn in this case.

**Comment by jocarren** [comment]
Well, maybe I'm a bit too ambitious.
