### ISSUE TITLE
Snapshots Causing Volumes to Increase in Size

### ISSUE THREAD

**Issue by cisiever** [longhorn/longhorn#647]
Some of our volumes have grown to be between 3.5x-4x the allocated size. There are snapshots when I "Show System Hidden" on each volume. All 4 of our nodes have become unschedulable due to this.

Example:

![image](https://user-images.githubusercontent.com/3027961/61823711-533ee100-ae2a-11e9-9748-92980872627c.png)

![image](https://user-images.githubusercontent.com/3027961/61823685-40c4a780-ae2a-11e9-8d34-31dd0759c038.png)

Show System Hidden Toggled on:

![image](https://user-images.githubusercontent.com/3027961/61823761-6baefb80-ae2a-11e9-8303-373d5aa6fd1a.png)

---
Version: `v0.5.0`

**Comment by yasker** [comment]
Hi @cisiever 

Those snapshots are created when some interruptions happened to the cluster cause the volume to rebuild in order to remain healthy. You can create a new snapshot then delete one of the snapshots to trigger clean up process. You can see how it works with more informations here https://github.com/longhorn/longhorn/issues/478#issuecomment-485930147

**Comment by cisiever** [comment]
Thanks, I'll give that a try.

**Comment by cisiever** [comment]
@yasker 
I tried creating a snapshot and deleting and left overnight, it did not do any cleanup. 

Now multiple volumes are showing > 10 failed replicas.

![image](https://user-images.githubusercontent.com/3027961/61958219-eb55db00-af8e-11e9-909e-31bc1ae4a0f3.png)


![image](https://user-images.githubusercontent.com/3027961/61958275-09234000-af8f-11e9-8afd-42ce0dcc405b.png)

**Comment by yasker** [comment]
@cisiever Those replicas that failed to allocate is due to running out of space. As long as you saw it's `N/A` there in the replica details, those are safe to delete.

Can you send the support bundle to `longhorn-support-bundle@rancher.com` ? How many volumes you have in trouble? Currently, the most important thing is to clean up space on the second and third node. We will check how things went wrong.

**Comment by cisiever** [comment]
Sent the support bundle.

Currently 19 of 34 volumes are degraded or detached.

**Comment by yasker** [comment]
@cisiever We found there are two problems. One is the timeout is too aggressive (#653 ), which exposed the second problem, which is manager keep trying adding the replica already in rebuild mode to the engine but the engine didn't reset the state of the replica, which we should have fixed in the next release.

For the big volume you have, you can manually run `longhorn purge` command to clean up the snapshots to workaround the timeout issue: 
```
kubectl -n longhorn-system exec -it <enginePod> longhorn snapshot purge
```
And the engine pod is the one named `<volumename>-e-xxxx`. And it's better to do it one volume after another. This will run for some time, but eventually, the volume should become smaller than the nominal size.

My suggestion is to detach the volumes that have failed replicas. As a part of the detaching process, Longhorn should automatically clean up the extra replicas. Then you can attach the volume one by one, probably starting from the smaller ones.

**Comment by cisiever** [comment]
@yasker 
I ran the purge on the larger volumes and cleaned up a lot of space. So all good there.

Currently there are a lot of volumes that are stuck detaching or attaching for the past few days. I sent a support bundle created today to longhorn-support-bundle@rancher.com

**Comment by yasker** [comment]
@cisiever I am stilling check the log. Some of the pods stuck in the detaching should be deleted already but it didn't happen. Anything abnormal happened during the process?

**Comment by yasker** [comment]
@cisiever something is wrong with node `o-kube03-de` and `o-kube06-de`. The managers running on those two nodes seems out of sync with Kubernetes. Can you try to delete the managers `longhorn-manager-fsxwx` and `longhorn-manager-msr6v`? They should be recreated automatically and once they're back to the service, the status sync should continue. I am still trying to figure out what's happened.

**Comment by cisiever** [comment]
I actually restarted the managers one at a time on the nodes and it cleaned up most of the stuck pods, save for 2.  Nothing abnormal going on. I held off doing anything else for a few days to see if it was too much load causing the pods not to detach.
