### ISSUE TITLE
[TEST] Design a mechanism to reference/manage resources created in a test case involved multiple volumes  

### ISSUE THREAD

**Issue by weizhe0422** [longhorn/longhorn#6498]
## What's the test to develop? Please describe

The current design/PR(https://github.com/longhorn/longhorn-tests/pull/1300) method is indeed only for one test volume in a case, and for the situation that multiple test volumes exist at the same time, it should has more discussion to have a clearer and better the design. 

## Describe the tasks for the test

More details: https://github.com/longhorn/longhorn/issues/6498#issuecomment-1674407922

## Additional context

https://github.com/longhorn/longhorn-tests/pull/1300#discussion_r1289732675

**Comment by yangchiu** [comment]
This should have higher priority since it could affect the design.

**Comment by yangchiu** [comment]
The current design is: when a volume created, it will automatically call `Set Test Variable` to set the generated volume name into a variable visible within the current test case scope, so following test steps don't need to explicitly pass the volume name, and __the volume name part_ of the test step can be omitted. e.g.

`Wait for replica of volume 1 on node 1 complete rebuilding`
becomes
`Wait for replica on node 1 complete rebuilding`

It's reasonable since if there's only one volume in the test case, it's obvious what volume we are referring to, and it's tedious to keep repeating `volume 1` for each step. And in the keyword implementation, it's also obvious that the default volume name variable set when the volume created should be used.

On the other hand, if there are 2 volumes in the same test case, people would write test steps like `Wait for replica of volume 1 on node 1 complete rebuilding`, since it already points out which volume they're referring to, all we need to do is look up the generated volume name (when it's created) of volume 1, so we need a map like:
```
{
"volume 1": "vol-xyz",
"volume 2": "vol-abc",
"volume n": "vol-randomly-generated-suffix"
}
``` 
which is what we haven't implemented yet. 

In addition to volume, other resources have the same problem, too. For example, create multiple snapshots in a test case:
```
create snapshot snap1
create snapshot snap2
create snapshot snap3
revert to snap3
revert to snap2
revert to snap1
```  
We will need a map to find the actual snapshot object or name from the user provided name:
```
{
"snap1": volume.snapshotList()[i].name,
"snap2": volume.snapshotList()[j].name,
"snap3": volume.snapshotList()[k].name
}
```
Then we are able to call:
```
volume.snapshotRevert(name=volume.snapshotList()[k].name)
```
So eventually we probably need a table to store the hierarchy/relations of volume and its custom resources.

Another way to deal with it is return the name from the keyword to users, and let users handle it, but it causes test steps clumsy and more like code:
```
${snap1_name} = create snapshot snap1
Set Test Variable    ${snap1_name}
${snap2_name} = create snapshot snap2
Set Test Variable    ${snap2_name}
${snap3_name} = create snapshot snap3
Set Test Variable    ${snap3_name}
revert to ${snap3_name}
revert to ${snap2_name}
revert to ${snap1_name}
```

cc @longhorn/qa @innobead Correct me if things are not that complicated.

**Comment by yangchiu** [comment]
Currently investigate/design this by implementing negative test case **6. Heavy writing and recurring jobs exists in the Longhorn system** in https://confluence.suse.com/pages/viewpage.action?spaceKey=LON&title=Negative+Testing, which is the only test case involves multiple volumes.

**Comment by yangchiu** [comment]
> Currently investigate/design this by implementing negative test case **6. Heavy writing and recurring jobs exists in the Longhorn system** in https://confluence.suse.com/pages/viewpage.action?spaceKey=LON&title=Negative+Testing, which is the only test case involves multiple volumes.

PR https://github.com/longhorn/longhorn-tests/pull/1526 created. But this test case is too simple to demonstrate the original problem, it only requires an extra array to store created volumes to work, since it doesn't try to create and reference different backups/snapshots of different volumes.

I'll try to pick up an existing test case in `manager/integration/tests` which involves different backups/snapshots referencing and implement it to really address the problem.

Also, need to spend some time on robot library, class instances lifecycle to make sure it doesn't mess up when running multiple test cases in the same round. Currently look like there are some problems here.

cc @longhorn/qa @innobead

**Comment by yangchiu** [comment]
> 
> Also, need to spend some time on robot library, class instances lifecycle to make sure it doesn't mess up when running multiple test cases in the same round. Currently look like there are some problems here.
> 

This refined in PR https://github.com/longhorn/longhorn-tests/pull/1526. We are able to execute all the test cases at a time without problems now.

**Comment by yangchiu** [comment]
> I'll try to pick up an existing test case in manager/integration/tests which involves different backups/snapshots referencing and implement it to really address the problem.

e.g.
`test_settings.py::test_setting_concurrent_rebuild_limit`
`test_basic.py::test_snapshot`
`test_basic.py::test_restore_inc`
`test_basic.py::test_backup_volume_list`

**Comment by yangchiu** [comment]
Not a priority. Deferred until we actually encounter an issue.
