### ISSUE TITLE
[Question] Compatibily with Kubernetes 1.14.3

### ISSUE THREAD

**Issue by Angelinsky7** [longhorn/longhorn#651]
Hi,
I would like to know if the current version of longhorn (0.5.0) is compatible with the 1.14.3 version of kubernetes. I tried to do the update but longhorn stopped working without any error (the volumes didn't mount) i revert back to 1.13.7 so i cannot give you more information...

Could it be possible to have this kind of information on the first page of the wiki ?
like that we won't update a cluster thinking : it's ok it should be compatible because longhorn is Kubernetes v1.8+. Recommend v1.12+ compatible...

Anyway thanks a lot for everything !!!

**Comment by yasker** [comment]
@Angelinsky7 Thanks for the information, let us reproduce it in our lab first.

**Comment by yasker** [comment]
@Angelinsky7 

Brand new installation of v1.14.3 (RKE) works for us.

Can you describe how did you upgrade Kubernetes? Have you stopped the workload before upgrading? The only thing we've found is iscsiadm acts weirdly when we did the upgrade and we guess it's probably due to the overlay network change. But you should able to remount the volume after it's done.

For references, iscsiadm decides to reconnect to the target in our upgrade test, from 1.13.7 to 1.14.3
>syslog:Jul 27 00:18:48 longhorn-tests-03 iscsid: Connection1:0 to [target: iqn.2014-09.com.rancher:pvc-13cf1797-b004-11e9-a66a-ea03c1dbf8dc, portal: 10.42.2.10,3260] through [iface: default] is operational now
syslog:Jul 27 00:27:16 longhorn-tests-03 iscsid: Connection1:0 to [target: iqn.2014-09.com.rancher:pvc-13cf1797-b004-11e9-a66a-ea03c1dbf8dc, portal: 10.42.2.10,3260] through [iface: default] is shutdown.
syslog:Jul 27 00:27:22 longhorn-tests-03 iscsid: Connection2:0 to [target: iqn.2014-09.com.rancher:pvc-13cf1797-b004-11e9-a66a-ea03c1dbf8dc, portal: 10.42.2.10,3260] through [iface: default] is operational now

**Comment by Angelinsky7** [comment]
@yasker 
Thanks for your time and answers again !
I tried the update again... this time draining all the nodes and shutting down longhorn volumes before and the update went without (almost) any issues...
So sorry for the noise... and thank you very much for trying for me.
