### ISSUE TITLE
[IMPROVEMENT] `toomanysnapshots` UI element not prominent enough to prevent runaway snapshots

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6560]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

The `tooManySnapshots` warning is not prominent enough in the UI. When viewing the list of volumes, you cannot tell if one is in a warning state either. On both the volume list page and the volume page itself, the `tooManySnapshots` warning (or complete error) should be more prominent enough to get the user to take action. Currently an icon changes color which may not be enough for some users to take action.

**Comment by a110605** [comment]
Related issue and PR
- https://github.com/longhorn/longhorn/issues/496#issuecomment-720658923
- https://github.com/longhorn/longhorn-ui/pull/336

**Comment by roger-ryao** [comment]
**Verified on master-head 20240530**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/cd4d7235de3547e74ef6aeb71c6ba2c97ac8a9ba
- longhorn-ui `master-head` https://github.com/longhorn/longhorn-ui/commit/409957fd4728b209d355ae91a6a00f6fdc51e19b

**The test steps**
https://github.com/longhorn/longhorn/issues/6560#issuecomment-2121547241


**Result Passed**

1. By creating 100 snapshots using the script, we can observe the expected behavior on the Longhorn UI.
2. I found a minor issue. I only created 100 snapshots, but the UI shows the message: "Snapshots count is 101, over the warning threshold of 100." 
   After discussing with Andy, we need to check the backend to find out why the snapshot number is reported as one extra. I created the ticket https://github.com/longhorn/longhorn/issues/8668 to track this issue.
   
   cc @a110605 @derekbit
