### ISSUE TITLE
Disaster recovery restoration

### ISSUE THREAD

**Issue by jocarren** [longhorn/longhorn#660]
According to #534 and the docs, when creating a disaster recovery volume, it shouldn't be possible to activate it until the icon turns from grey to blue. 

But when I created a disaster recovery volume from a 60 GB backup (in a machine off site), the blue icon appears immediately and the "activate" option is available.

For testing purposes I activated the DR volume and created a PVC wich I can attach and mount in a pod. There I can see the volume grow in "actual size".

**Comment by yasker** [comment]
@jocarren 

The first time DR volume was attached, the first backup has already been restored automatically. That's why it shows blue immediately. When the newer backups are created later, the icon will become grey while the incremental restoration in progress, and turn back to blue while it's ready to be activated.

If you want to simply restore a backup to a volume, you can choose the backup after click the volume name in the `Backup` page, then create the volume from the backup directly there.

**Comment by jocarren** [comment]
I see, thanks.

Just to be clear: Actual data transfer from backupstore to backupcluster begins once the DR recovery volume is attached to a node in backupcluster. Not when DR volume is created.

**Comment by yasker** [comment]
@jocarren Yeah, we will make it easier in the next release to automatically attach the DR volume once it's created. And the only way to detach it would be to activate the volume.

**Comment by yasker** [comment]
In v0.6.1, DR volume is automatically attached.
