### ISSUE TITLE
[IMPROVEMENT] Add s3 ObjectStore adoption to Longhorn telemetry

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6720]
With the introduction of [s3 ObjectStore native support in Longhorn](https://github.com/longhorn/longhorn/issues/4154), we would like to monitor the s3 ObjectStore adoption by adding it into Longhorn telemetry

**Comment by l-mb** [comment]
This is not directly necessary as such - s3gw already includes telemetry itself (and can report whether it's hosted on LH, that could be passed in via the controller if needed?): https://github.com/aquarist-labs/s3gw/issues/202

**Comment by m-ildefons** [comment]
Seeing how many s3gw instances are hosted on LH or integrated with LH is different from seeing how many LH instances have an object store and/or how many object stores there are per LH instance.
In order to do the latter, LH needs to report at least if, and preferably how many, object stores there are deployed.
It's also good for cross-checking our interpretation of the s3gw telemetry. E.g. an outlier installation of LH with many s3gw instances may skew our perception, especially while adoption is still low.
Certainly a nice-to-have.

**Comment by l-mb** [comment]
Right, that _would_ be a good metric to add to LH core, and then we can pass the telemetry on/off setting via the controller to the object store instances for more detailed reporting. Good point, thanks.

**Comment by innobead** [comment]
Let's revisit this later.
