### ISSUE TITLE
[DOC] FS Trim for RWX is supported, but docs are out of date.

### ISSUE THREAD

**Issue by james-munson** [longhorn/longhorn#6733]
## What's the document you plan to update? Why? Please describe
https://longhorn.io/docs/1.5.1/volumes-and-nodes/trim-filesystem/#rwx-volumes

The section states that trimming RWX volumes via the UI is not supported, and documents a workaround that involves exec'ing into the share-manager pod to execute commands.  It also references https://github.com/longhorn/longhorn/issues/5143, which was actually implemented and closed before 1.5.0 was released.

## Additional context

This came up in Slack thread https://suse.slack.com/archives/C02BW9KEJHG/p1695131173272519 
I will update this ticket with a Longhorn issue number when it is filed.

**Comment by innobead** [comment]
@chriscchien noticed you mentioned you verified this and mentioned RWX volume was able to trim via UI? Can u help confirm this? 

https://github.com/longhorn/longhorn/issues/5143#issuecomment-1535796677

**Comment by innobead** [comment]
Oh it is supported but the doc is outdated. Thanks @james-munson . 

@longhorn/qa generally when we verify any new features, should check if doc is updated as well. Sometimes, the doc was missing from the issues, but please still check if doc is required, since you are the gatekeeper before closing issues. Thanks.

@khushboo-rancher please see how to improve this in the future.
