### ISSUE TITLE
[IMPROVEMENT] Use nvme-cli in instance-manager pod instead

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#6798]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Using nvme-cli in the host environment can be frustrating due to the variations in versions and unexpected crashes encountered in some releases. Resolving these issues often involves time-consuming investigations.

To mitigate this unnecessary hassle, using nvme-cli within an instance-manager pod is a better approach.

## Additional context

Segfault in nvme 2.0 https://github.com/longhorn/longhorn/discussions/6493#discussioncomment-7078153
Weird nvme output: https://github.com/longhorn/longhorn/issues/6795
Unsupported format in old nvme (< v1.12): https://longhorn.io/docs/1.5.1/spdk/quick-start/#install-nvme-userspace-tool-and-load-nvme-tcp-kernel-module

**Comment by derekbit** [comment]
cc @shuo-wu

**Comment by c3y1huang** [comment]
Duplicated to https://github.com/longhorn/longhorn/issues/6517?

**Comment by derekbit** [comment]
Yeah, sorry, I wasn't aware of the ticket.
Can I take over it? I can test it together.

cc @innobead

**Comment by c3y1huang** [comment]
> Yeah, sorry, I wasn't aware of the ticket. Can I take over it? I can test it together.
> 
> cc @innobead

Fine with me.

**Comment by derekbit** [comment]
Except for the issues mentioned in https://github.com/longhorn/longhorn/issues/6798#issue-1914718798
I also found `nvme list-subsys -o json` cannot list subsystems using nvme v2.5.
Becase nvme v2.x is more or less problematic in nvme v2.x, I will use v1.16 in the instance-manager pod.

**Comment by chriscchien** [comment]
Hi @derekbit ,

Does the environment check [script](https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh) need to be updated too? Because the script will still check system nvme-cli version, thank you.
```
[INFO]  Checking nvme-cli...
[ERROR] Failed to check nvme-cli version on node ip-172-31-44-162
[ERROR] Failed to check nvme-cli version on node ip-172-31-44-241
[ERROR] Failed to check nvme-cli version on node ip-172-31-46-50
```

In addition, the V2 volume behavior verified **pass** in longhorn master (longhorn-manager `35beba`) with [steps](https://longhorn.io/docs/1.6.0/spdk/quick-start/)

In Ubuntu 22.04 and SUSE Linux Enterprise Server 15
1. Setup V2 engine environment by [steps](https://longhorn.io/docs/1.6.0/spdk/quick-start/)
2. Remove system `nvme-cli`
3. Deploy Longhorn, create block disks
4. Below V2 volume function verified
- Volume with workload, write into mount point
- Scale down/up the deployment, volume detached and healthy, data intact
- Replica offline rebuilding, after rebuild complete, volume can be attached by workload and data intact

**Comment by derekbit** [comment]
@chriscchien 
We can remove the check.

**Comment by chriscchien** [comment]
Close this ticket. the behavior verified [here](https://github.com/longhorn/longhorn/issues/6798#issuecomment-1807690173) and the environment script no longer check `nvme-cli` now
