### ISSUE TITLE
[TASK] Bump the versions of dependent libs or components

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7001]
## What's the task? Please describe

For 1.6.0, let's bump the versions of the following items to a newer supported version. 

- Kubernetes libs
- CSI side car components
- Go version to the latest, 1.21
- Kubernetes version support, min 1.26 to align with upstream ([1.29 is planned to be released on 12/5](https://www.kubernetes.dev/resources/release/#summary), 1.28 and 1.27 are actively supported. 1.25 was EOS on 10/27.)
  - As per https://metrics.longhorn.io/, 1.25 and 1.24 are primary installed versions. 
  - Rancher supported downstream cluster is RKE/2 1.26
  - RKE2 is supporting 1.28 - 1.26 which is aligned with upstream.
  - For the current Longhorn-supported versions, we will not change the existing supported min version of Kubernetes. 

There were #2757 #3891 for reference. 

## Describe the sub-tasks

- [ ] Resolve any incompatibility issues
- [ ] Run e2e tests to ensure all passed including installation and upgrade
- [ ] Support the supported K8s versions without issues
- [ ] Prevent upgrading from any unsupported K8s versions with notice info, especially for helm chart installation

## Additional context

- https://kubernetes.io/docs/reference/using-api/deprecation-guide/
- https://endoflife.date/kubernetes

cc @longhorn/dev

**Comment by innobead** [comment]
@c3y1huang is working on some package updates for CVE fixes, so we can take this time to update the dependencies.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master (longhorn `07a87d`)

 - [x] Resolve any incompatibility issues
    - Longhorn install success by yaml and helm 
 - [ ] Run e2e tests to ensure all passed including installation and upgrade
    - AMD64 build [729](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/729/) - 8 failures
   - AMD64 2 stage upgrade build [362](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/362/) - 8 failures
   - ARM64 build [677](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/677/) - 7 failures
   - ARM64 2 stage upgrade build [353](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/353/#showFailuresLink) - 10 failures 
   - All pipeline have the same failure : https://github.com/longhorn/longhorn/issues/7143
   - All pipeline have the same failure : https://github.com/longhorn/longhorn/issues/7172
- [x] Support the supported K8s versions without issues
   - Core test on `v1.27.1+k3s1` all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5289/testReport/tests/)
   - Core test on `v1.28.2+k3s1` all passed
  
![image](https://github.com/longhorn/longhorn/assets/73337386/ddaf4715-4c40-4447-a1ba-12f7a57dd442)

 - [ ] Prevent upgrading from any unsupported K8s versions with notice info, especially for helm chart installation
   - We have manual test [Kubernetes upgrade test](https://longhorn.github.io/longhorn-tests/manual/pre-release/upgrade/kubernetes-upgrade-test/) and maybe this item can leave to v1.6.0 release testing since at that time kubernetes v1.29 will ready
