### ISSUE TITLE
[BUG] duplicate MIME type "text/html" in `/var/config/nginx/nginx.conf`

### ISSUE THREAD

**Issue by votdev** [longhorn/longhorn#7002]
## Describe the bug (🐛 if you encounter this issue)

nginx is reporting the warning
```
nginx: [warn] duplicate MIME type "text/html" in /var/config/nginx/nginx.conf:7
```

According to the [nginx docs](http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types) the MIME type `text/html` does not need to be mentioned.

> Enables gzipping of responses for the specified MIME types in addition to “text/html”.

## Expected behavior

No warning is reported.

## Environment
LH-UI 1.6-dev

**Comment by innobead** [comment]
@votdev for any issue requiring QA verification before closing it, please update the Zenhub pipeline to change the issue status accordingly. When the status of an issue is `ready for testing`, QA will help with the manual test as per the info you provide. If everything works as expected, the issue will be closed; otherwise, it will be moved back to `implement` status.

For the detailed issue status (Zenhub), please check https://github.com/longhorn/longhorn/wiki/Issue-Management. I believe @m-ildefons @nitendra-suse should know about that, so you can consult with them if it's not clear. 

P.S. If you don't have access permission to the Zenhub board (you need to install a Zenhub plugin on your browser), please check with @rebeccazzzz . She will help with the permission.
