### ISSUE TITLE
The endpoint of `Healthy` volume is empty sometimes

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#707]
```
=================================== FAILURES ===================================
_____________________________ test_endpoint_empty ______________________________

client = <longhorn.Client object at 0x7f6694a2bd90>
volume_name = 'longhorn-testvol-4fxeei'

    @pytest.mark.debug   # NOQA
    def test_endpoint_empty(client, volume_name):  # NOQA
        for i in range(100):
            print >> sys.stderr, "test", i, "start"
            volume = create_and_check_volume(client, volume_name)
            host_id = get_self_host_id()
            volume.attach(hostId=host_id)
            volume = wait_for_volume_healthy(client, volume_name)
            assert len(volume["replicas"]) == 3

>           data = write_volume_random_data(volume)

test_tmp.py:21:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
common.py:1334: in write_volume_random_data
    dev = get_volume_endpoint(volume)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

v = {'frontend': u'blockdev', 'recurringJobs': None, 'size': u'16777216', 'controllers': [{'endpoint': u'', 'name': u'long...u'2019-08-31 01:57:43 +0000 UTC', 'standby': False, 'robustness': u'healthy', 'lastBackup': u'', 'numberOfReplicas': 3}

    def get_volume_endpoint(v):
        engine = get_volume_engine(v)
        endpoint = engine["endpoint"]
>       assert endpoint != ""
E       assert '' != ''

common.py:1663: AssertionError
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
===================== 99 tests deselected by "-m 'debug'" ======================
================== 1 failed, 99 deselected in 3242.78 seconds ==================
```

**Comment by yasker** [comment]
Cannot reproduce this in the recent nightly tests.

**Comment by yasker** [comment]
Show up in the `test_backup` again today.

```
clients = {'longhorn-tests-01': <longhorn.Client object at 0x7f4ad69ce690>, 'longhorn-tests-02': <longhorn.Client object at 0x7f4ad6950e90>, 'longhorn-tests-03': <longhorn.Client object at 0x7f4ad6a8b5d0>}
volume_name = 'longhorn-testvol-tn05lz'

    @pytest.mark.coretest   # NOQA
    def test_backup(clients, volume_name):  # NOQA
>       backup_test(clients, volume_name, SIZE)

test_basic.py:413: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_basic.py:447: in backup_test
    backupstore_test(client, lht_hostId, volume_name, size)
test_basic.py:549: in backupstore_test
    check_volume_data(volume, data)
common.py:1355: in check_volume_data
    dev = get_volume_endpoint(volume)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

v = {'frontend': u'blockdev', 'recurringJobs': None, 'size': u'16777216', 'controllers': [{'endpoint': u'', 'name': u'long...u'2019-09-18 08:44:33 +0000 UTC', 'standby': False, 'robustness': u'healthy', 'lastBackup': u'', 'numberOfReplicas': 2}

    def get_volume_endpoint(v):
        engine = get_volume_engine(v)
        endpoint = engine["endpoint"]
>       assert endpoint != ""
E       assert '' != ''

common.py:1689: AssertionError
```

**Comment by yasker** [comment]
Very hard to reproduce locally. Move out of v0.6.0.

**Comment by yasker** [comment]
Got the volume object from debug log when the error happens:
> {Resource:{Id:longhorn-testvol-041ddy Type:volume Links:map[] Actions:map[]} Name:longhorn-testvol-041ddy Size:16777216 Frontend:blockdev DisableFrontend:false FromBackup: NumberOfReplicas:2 StaleReplicaTimeout:0 State:attached Robustness:healthy EngineImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 CurrentImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 BaseImage: Created:2019-09-20 04:11:06 +0000 UTC MigrationNodeID: LastBackup: LastBackupAt: Standby:false InitialRestorationRequired:false DiskSelector:[] NodeSelector:[] RecurringJobs:[] Conditions:map[scheduled:{Type:scheduled Status:True LastProbeTime: LastTransitionTime:2019-09-20T04:11:07Z Reason: Message:}] KubernetesStatus:{PVName: PVStatus: Namespace: PVCName: LastPVCRefAt: WorkloadsStatus:[] LastPodRefAt:} Replicas:[{Instance:{Name:longhorn-testvol-041ddy-r-79cedc6d NodeID:yasker-longhorn-dev-3 Address:10.42.2.5 Running:true EngineImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 CurrentImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 InstanceManagerName:instance-manager-r-be5d60f7} DiskID:b6c9838019c84945 DataPath:/var/lib/rancher/longhorn/replicas/longhorn-testvol-041ddy-53829e9c Mode: FailedAt:} {Instance:{Name:longhorn-testvol-041ddy-r-d159d4aa NodeID:yasker-longhorn-dev-1 Address:10.42.0.89 Running:true EngineImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 CurrentImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 InstanceManagerName:instance-manager-r-cb5633e4} DiskID:b6c9838019c84945 DataPath:/v
ar/lib/rancher/longhorn/replicas/longhorn-testvol-041ddy-8fd42e84 Mode: FailedAt:}] Controllers:[{Instance:{Name:longhorn-testvol-041ddy-e-71326cc3 NodeID:yasker-longhorn-dev-3 Address:10.42.2.6 Running:true EngineImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 CurrentImage:longhornio/longhorn-test:upgrade-test.2-2.2-2.1-1 InstanceManagerName:instance-manager-e-5291484f} Endpoint: LastRestoredBackup: RequestedBackupRestore:}] BackupStatus:[] RestoreStatus:[] PurgeStatus:[] Timestamp:2019-09-20T04:11:23.788939617Z}"
```
Notice the controller and replicas' data are not consistent. Volume shows as healthy but the controller doesn't have `Endpoint`, replicas' `Mode` are empty as well.

**Comment by yasker** [comment]
I think the root cause is (again) etcd's eventual consistency:
1. The debug log in volume reconciliation logic and engine monitoring logic wasn't triggered during the attaching process. From instance manager, since we're starting replicas with the engine, it guarantees that before the device creation process completed, the [GRPC server won't be up](https://github.com/longhorn/longhorn-engine/blob/905e520af1611e72b8fcddd078f2142b05c2aaad/app/controller.go#L104), so the state of the engine won't be updated to `Running`. So the inconsistency in the engine state is unlikely the answer.
2. The volume shows `healthy`, which should only happen after [the volume has found the desired number of replicas in the engine](https://github.com/longhorn/longhorn-manager/blob/36b37fcb5955ef5b45ca53cb0dea630806d24541/controller/volume_controller.go#L457). Since both the log and logic ensures that once the engine is up, the replicas should be ready in RW mode and endpoint should be updated, we know at least the owner controller of the volume has seen the updated engine.
3. But 2 is not consistent with the debug output above. In the volume object above, the volume is `healthy`, but there is no information on the engine's endpoint or replicas' modes. Both pieces of the information was retrieved from the [engine](https://github.com/longhorn/longhorn-manager/blob/36b37fcb5955ef5b45ca53cb0dea630806d24541/api/model.go#L628) [CRD](https://github.com/longhorn/longhorn-manager/blob/master/api/model.go#L684) instead of volume CRD. So it looks like the manager didn't get the latest version of engine object.
4. Further looking into the managers. We found out the manager responses to the API call is not the owner of the volume (the attached node of the volume). The owner of the volume should have the latest information since it's the one that updated the volume object in the first place, but we cannot guarantee the other managers always have the latest information regarding both volume object and engine object.

So I think the etcd's eventual consistency is the problem. And it's probably the reason why it's so hard to reproduce.

Against the theory:
1. If we can get a stale version of Engine, we can also get a stale version of Volume or Replica, why haven't we seen that?
    1. I think it's because if the volume object is stale, it won't show healthy, and we will simply wait for the state to change to healthy, so it won't cause a test failure.

Probably fix:
1. Move the `endpoint` field to the volume.
    1. We don't want to store duplicate status in the objects if possible.
2. Let the owner of the volume handle the `get` request.
    1. In the case of the volume attached node is down, we won't able to get any volume information, which is undesired. We can build more mechanism around it but it seems overcomplicated for now.
3. In the API response, don't show `healthy` if the endpoint is empty.
     1. We don't really know what state the volume was before the current state. It's not ideal to change the state in the function that should only expose it.
4. Change the test to wait for the endpoint to be not empty to workaround the issue.
     1. Seems like the best way for now...

We might want to revisit this issue in the future to see if we can get a better solution.

**Comment by yasker** [comment]
Done, for now.
