### ISSUE TITLE
[IMPROVEMENT] Have a setting to disable snapshot purge for maintenance purpose

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#7075]
It might be helpful to have a global setting to disable snapshot purge in the whole cluster. This will help the case when there is a disk that is almost full and we need to salvage volumes. Doing snapshot purge may increase the disk usage and push the almost full disk at risk of being completely full and we cannot recover the volume

That being said, I think it is not necessary to have it at volume level since it is very rare that we need this feature. Only in emergency/corner case

**Comment by derekbit** [comment]
It sounds good. BTW, we can enhance the error message for hinting users disable the setting when volume space is not enough while  purging snapshot.

**Comment by ejweber** [comment]
### Manual test steps:

#### Setting manipulation:

1. Try to enable `disable-snapshot-purge` with `auto-cleanup-system-generated-snapshots` enabled. This should fail.
2. Try to enable `auto-cleanup-system-generated-snapshots` with `disable-snapshot-purge` enabled. This should fail.
3. Try any other any other combination of these settings. This should succeed.

#### API / UI:

1. Enable `disable-snapshot-purge`.
2. Create a volume.
3. Attach the volume to a node.
4. Create multiple snapshots.
5. Try to delete one of the snapshots in the UI.
6. See an error like `cannot purge snapshots while %v setting is true`.
7. The snapshot is marked as removed (now hidden in the UI), but it is not gone.
8. Disable `disable-snapshot-purge`.
9. Try to delete another snapshot in the UI.
10. Both snapshots are gone.

#### kubectl:

1. Enable `disable-snapshot-purge`.
2. Create a volume.
3. Attach the volume to a node.
4. Create multiple snapshots.
5. Try to delete one of the snaphshot CRs.
6. The `deletionTimestamp` is set, but the snapshot CR is never gone.
7. See a warning like `Cannot start SnapshotPurge to delete snapshot %v while %v setting is true` in the `longhorn-manager` logs.
8. Disable `disable-snapshot-purge`.
9. The snapshot CR is gone.

(Try the same thing but detach the volume before deleting one of the snapshot CRs. Notice that the volume is not immediately attached when the snapshot CR is deleted. Later when `disable-snapshot-purge` is disabled, the volume immediately attaches for snapshot deletion.)

**Comment by ejweber** [comment]
This is a new setting for v1.6.0. Should it be backported @innobead?

**Comment by innobead** [comment]
Theoretically, we should not backport any new features to maintained branches, but always there will be some exceptions, especially related to support.

I would suggest backporting this. WDYT?

**Comment by ejweber** [comment]
> I would suggest backporting this. WDYT?

I agree because:

- Risk is relatively low. The setting is disabled by default, so no change will be observed for most users.
- In the rare case it is needed, the setting can greatly simplify support.

**Comment by roger-ryao** [comment]
**Verified on master-head 20231218**

- longhorn master-head https://github.com/longhorn/longhorn/commit/a91f7966185ae0d5e19e1c2946ac551163bb0ebc
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/51524e0ace25b472fd369a2f182b9b543586b5ae

**The test steps**

1. https://github.com/longhorn/longhorn/issues/7075#issuecomment-1834630195

2. Retrieve the current value of disable-snapshot-purge using kubetail: `kubectl -n longhorn-system get lhs disable-snapshot-purge`
3. Update the configuration using the command: `kubectl -n longhorn-system patch lhs disable-snapshot-purge -p '{"value": "true"}' --type=merge`

**Result **

- [x] 1. From the Longhorn UI, attempting to enable `Disable Snapshot Purge` with `Automatically Cleanup System Generated Snapshot` enabled results in failure.
      An error on the UI states: "**Failed to set the setting disable-snapshot-purge with the invalid value true: Cannot set disable-snapshot-purge setting to true when auto-cleanup-system-generated-snapshot setting is also true.**"
- [ ] 3. require/doc : https://github.com/longhorn/website/pull/805
- [ ] 4. area/chart : https://github.com/longhorn/longhorn/pull/7256

Hi @ejweber 
I found that https://github.com/longhorn/longhorn/pull/7256 doesn't have a commit on the file `chart/templates/default-setting.yaml`. So, if we edit `disableSnapshotPurge` to `true` in `chart/values.yaml` and then helm install Longhorn, the configuration will not take effect. I'm not sure if this is expected because `disableSnapshotPurge` and `autoCleanupSystemGeneratedSnapshot` cannot both be `true` at the same time. If we allow users to edit it before installing Longhorn, maybe we also need to add a note about this.

**Comment by ejweber** [comment]
Good catch @roger-ryao. This was unintentional. I submitted https://github.com/longhorn/longhorn/pull/7374 to correct it.

> I'm not sure if this is expected because disableSnapshotPurge and autoCleanupSystemGeneratedSnapshot cannot both be true at the same time.

I did some testing around https://github.com/longhorn/longhorn/pull/7374 to ensure this property would still work as expected.

Because of the way the code flows in the Kubernetes ConfigMap controller, we:

- First apply all settings with their default values as defined in `longhorn-manager`.
- Then apply the values of default settings from the `longhorn-default-setting` ConfigMap.

https://github.com/longhorn/longhorn-manager/blob/ae6b6aa99d0e2eb12fd0d868f5e67105bb6b685c/datastore/longhorn.go#L69-L73

This means before `autoCleanupSystemGeneratedSnapshots == true` and `disableSnapshotPurge == false` before we apply `disableSnapshotPurge = true` from the ConfigMap. When we try, the webhook stops us (as expected). So there should be no way for the user to accidentally make both true at the same time, even if they use Helm default settings.

```
autoCleanupSystemGeneratedSnapshots: ~
disableSnapshotPurge: true

eweber@laptop:~/longhorn> kubetail -n longhorn-system -l app=longhorn-manager --since 1h | grep disable-snapshot
[longhorn-manager-drn9l] time="2023-12-18T14:59:04Z" level=warning msg="Invalid customized default setting disable-snapshot-purge with value true, will continue applying other customized settings" func="datastore.(*DataStore).filterCustomizedDefaultSettings" file="longhorn.go:110" error="failed to set the setting disable-snapshot-purge with invalid value true: cannot set disable-snapshot-purge setting to true when auto-cleanup-system-generated-snapshot setting is true"
[longhorn-manager-drn9l] time="2023-12-18T14:59:04Z" level=warning msg="Invalid customized default setting disable-snapshot-purge with value true, will continue applying other customized settings" func="datastore.(*DataStore).filterCustomizedDefaultSettings" file="longhorn.go:110" error="failed to set the setting disable-snapshot-purge with invalid value true: cannot set disable-snapshot-purge setting to true when auto-cleanup-system-generated-snapshot setting is true"
[longhorn-manager-xwhkz] time="2023-12-18T14:58:59Z" level=warning msg="Invalid customized default setting disable-snapshot-purge with value true, will continue applying other customized settings" func="datastore.(*DataStore).filterCustomizedDefaultSettings" file="longhorn.go:110" error="failed to set the setting disable-snapshot-purge with invalid value true: cannot set disable-snapshot-purge setting to true when auto-cleanup-system-generated-snapshot setting is true"
[longhorn-manager-xwhkz] time="2023-12-18T14:58:59Z" level=warning msg="Invalid customized default setting disable-snapshot-purge with value true, will continue applying other customized settings" func="datastore.(*DataStore).filterCustomizedDefaultSettings" file="longhorn.go:110" error="failed to set the setting disable-snapshot-purge with invalid value true: cannot set disable-snapshot-purge setting to true when auto-cleanup-system-generated-snapshot setting is true"
[longhorn-manager-qsjlr] time="2023-12-18T14:58:59Z" level=warning msg="Invalid customized default setting disable-snapshot-purge with value true, will continue applying other customized settings" func="datastore.(*DataStore).filterCustomizedDefaultSettings" file="longhorn.go:110" error="failed to set the setting disable-snapshot-purge with invalid value true: cannot set disable-snapshot-purge setting to true when auto-cleanup-system-generated-snapshot setting is true"
[longhorn-manager-qsjlr] time="2023-12-18T14:58:59Z" level=warning msg="Invalid customized default setting disable-snapshot-purge with value true, will continue applying other customized settings" func="datastore.(*DataStore).filterCustomizedDefaultSettings" file="longhorn.go:110" error="failed to set the setting disable-snapshot-purge with invalid value true: cannot set disable-snapshot-purge setting to true when auto-cleanup-system-generated-snapshot setting is true"
```

```
autoCleanupSystemGeneratedSnapshots: false
disableSnapshotPurge: true

eweber@laptop:~/longhorn> kl get setting.longhorn.io disable-snapshot-purge
NAME                     VALUE   AGE
disable-snapshot-purge   true    8m47s
```

**Comment by roger-ryao** [comment]
**Verified on master-head 20231218**

- longhorn master-head https://github.com/longhorn/longhorn/commit/d2e351a656656bea402cd0476510dc1ee6967e50

**The test steps**
https://github.com/longhorn/longhorn/issues/7075#issuecomment-1859841018

**Result Passed**
