### ISSUE TITLE
Copying All Replica Content to Another Node 

### ISSUE THREAD

**Issue by akuscu-smartpulse** [longhorn/longhorn#714]
I have 1 master 2 nodes kubernetes cluster.I am trying to deal with node failure and i deployed mongodb on slave1.In the slave 2 i have prometheus and i am sniffin incoming network traffic.I have 50 mb data in my mongodb.When i try to add 3 mb data to mongodb it syncronizing 53 mb to other node.I think it suppose to transmit only 3mb data to slave2 node.Is this act normal or am i wrong about transmitting style between nodes? (Node failure feature is working correctly).
Also, although i have 350 Mb data in my volume directory(i look with du -hs command inside container) , volume size about 1.1 Gb.This size looks like too much in my opinion.On my real database i have about 200 Gb data and it looks dangerous to use longhorn for this big database ?

**Comment by yasker** [comment]
1. I think it's something else. Longhorn is not synchronizing replicas from each other when the volume is being used. The data written to the replica is from the block level command. From the block device's POV, it doesn't know if you've added 3MB data or not. It only knows there is certain amount of data was written by the write command on the block level. So it's possible that the data written by the write command on the block level is bigger than what you think you've written.
2. Longhorn also keeps the data's history in the form of snapshot. When replica lost happened, snapshot will be taken automatically in order to rebuild a new replica. And snapshot would take up space. You can delete the unnecessary snapshots to recover some space.

**Comment by akuscu-smartpulse** [comment]
1.Ok it was my fail because i sniffed all traffic not only longhorn so i though it is copying all 
 the replicas.My bandwith use was 2-3 MBps when writing data to database.It seems ok for databases.(For information :  when i copy a 400 MB file to the volume my bandwiths use around 16-20 MBps.)
2.So you mean snapshots only using for rebuilding failed replicas.And all the data do not have to copying from other node.So rebuilding is also incremental.(please tell me if i am wrong)

**Comment by yasker** [comment]
@akuscu-smartpulse Thanks.

And yes, ideally we should able to rebuild using the existing replica, which can minimize the network traffic for the rebuild. Though we've decided not to do it now since it will make things more complicated. There were a few discussion (e.g. https://github.com/longhorn/longhorn/issues/570) about it before. No worries, we still keep this idea on the radar.
