### ISSUE TITLE
[QUESTION] The server has been rebooted, but the CSI plugin cannot start, causing all services to be paralyzed. What should I do?

### ISSUE THREAD

**Issue by noahge** [longhorn/longhorn#7146]
I also attempted to restore using the etcd backup of k3s, but still cannot start. What else can I do?

**Comment by noahge** [comment]
longhorn-csi-plugin is waiting for the longhorn-admission-webhook, The replicaset for longhorn-admission-webhook is reporting an error with the following message: 'Error creating: Internal error occurred: failed calling webhook "consul-connect-injector.consul.hashicorp.com": failed to call webhook: Post "[https://consul-connect-injector.consul.svc:443/mutate?timeout=10s](https://consul-connect-injector.consul.svc/mutate?timeout=10s)": no endpoints available for service "consul-connect-injector." why need consul？

**Comment by ejweber** [comment]
Unfortunately, this error message has very little to do with Longhorn. It sounds like your Kubernetes cluster is configured to use a Consul service mesh. The webhook being called here is a Consul-maintained mutating webhook intended to inject some or all of the pods in your cluster with sidecar containers (https://developer.hashicorp.com/consul/docs/k8s/connect#installation-and-configuration). The CSI plugin pods cannot start because communication with the Consul webhook is failing. You will have to troubleshoot and/or remove your Consul deployment. Please consult the Consul maintainers as necessary for help.

I'm going to close this one for now. Please feel free to open a new discussion or issue if you manage to get past this Consul issue and are still having trouble with Longhorn.
