### ISSUE TITLE
[TASK] Fix creating backport issues failed if the assignee isn't a longhorn member

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7201]
## What's the task? Please describe

Fix creating backport issues failed if the assignee isn't a longhorn member.

**Comment by innobead** [comment]
It's better to describe why the action failed when the assignee is a non-org user. 

This is a failed action example: https://github.com/longhorn/longhorn/actions/runs/6846727542/job/18613788025#step:7:12

The failed reason is because the assignee of the original user has no right permissions. 
https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28

![image](https://github.com/longhorn/longhorn/assets/899492/e953e807-95e9-4116-8025-37a3fb61279f)

**Comment by yangchiu** [comment]
> It's better to describe why the action failed when the assignee is a non-org user.

Like creating a ticket manually, it's not possible to randomly assign this ticket to a random person on Github. The greatest power we can get is taking control of our own organization, and have the power to assign a ticket to a member of the organization.
