### ISSUE TITLE
[IMPROVEMENT] Filters on the Backup page

### ISSUE THREAD

**Issue by vanchaxy** [longhorn/longhorn#7219]
### Problem Description

The current lack of filters on the backup page makes the process of restoring volumes cumbersome. Specifically, when attempting to restore a single namespace, users are required to manually locate and select each PVC individually. This becomes a time-consuming task, especially when dealing with a large number of volumes.

### Proposed Solution:
Implement a set of filters on the Backup page that align with the existing filters on the Volumes page. The UI already receives all the necessary data from the API, and the code for filters is already implemented on the Volumes page. Therefore, it should be relatively straightforward to replicate and integrate these filters onto the Backup page.

<img width="1273" alt="image" src="https://github.com/longhorn/longhorn/assets/36510601/588b6883-866c-4ed7-93c5-74de845194a2">
<img width="1268" alt="image" src="https://github.com/longhorn/longhorn/assets/36510601/3a348086-85af-4053-b14a-7d570399a957">

**Comment by ejweber** [comment]
This seems like a good idea to me. I'll move it along the pipeline to be triaged.

I think this won't be quite as straightforward as described because the backups tab is obtaining its information from the BackupVolumes API instead of the Volumes API. However, the information you are most interested in (namespace) appears to be included in `backupVolume.status.labels.kubernetesStatus`, so this can probably still be implemented fairly easily.

Any chance you want to take a crack at it @vanchaxy?

**Comment by vanchaxy** [comment]
Unfortunately, I'm mostly backend and don't have time for this right now. If no one takes this for a while then I probably will try to do it myself.
