### ISSUE TITLE
[BUG] Download backing image failed with HTTP 502 error if Storage Network configured

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#7236]
## Describe the bug (🐛 if you encounter this issue)
If the Storage Network is configured, downloading backing image will fail with `HTTP 502 error`, and LH manager appears error message `http: proxy error: dial tcp xxxxx:8001: i/o timeout` 

## To Reproduce
Steps:
- Creating Harvester cluster (single node is sufficient)
- Uploading an image to Harvester
- Enable Storage Network
- Download the image from Harvester UI

Result:
- Backing image download will fail with `HTTP 502 error`

## Expected behavior
Backing image download success

## Environment

 - Longhorn version: v1.4.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Harvester v1.2.1

## Some LH source code observation
It's brought by LH manager tries to access backing-image-manager via URL from Storage-Network, but LH manager pods itself are not included in Storage-Network, following are the details:
- As LH manager receives download request, it gets the target backing image manager pod address by [gRPC PrepareDownload](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/api/forwarder.go#L253)
- Backing image manager server [response with the address of Storage-Network URL](https://github.com/longhorn/backing-image-manager/blob/00de674e0c86ecea5e65464bafc807c3b17c94d6/pkg/util/http_util.go#L61-L73)
- LH manager [forwards the request to backing image manager](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/api/forwarder.go#L214-L218) with the retrieved address, however, it's not accessible from LH manager

I've tried to [have modifications to LH manager](https://github.com/WebberHuang1118/longhorn-manager/tree/v1.4.3_bi_download) (force access backing image manager with pod IP) and updated it to my environment, the image could be downloaded during Storage-Network configured.

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by ChanYiLin** [comment]
For this issue, we can either
1. fix the backing-image-manager service PrepareDownload API to make it return podIP instead of storage-network ip when storage-network is set.
2. fix longhorn-manager as @WebberHuang1118 did, to use the podIP anyway when downloading the backing-image

I prefer the second one, because the backing-image-manager service PrepareDownload API might also be used by other components and should still follow the storage network.

cc @c3y1huang @shuo-wu

**Comment by innobead** [comment]
@c3y1huang @shuo-wu which parts backing the image manager/data source are using storage IP? I assume it's only for syncing files between managers?

**Comment by ChanYiLin** [comment]
The storage network ip was introduced when this feature was developed 
https://github.com/longhorn/backing-image-manager/pull/56/commits/b84b074ad2b9e95f3d1e30b61a2cc556e45d60e4#diff-2b03cce424a492f023f352f86f119a92efebeedb9737b9aae2f66b5cefe4329fR440

And `address, err := util.ConvertToStorageAddress(m.syncAddress)` is actually only used in this feature 
I think it was because this function was to proxy longhorn-manager to the sync service
but actually longhorn-manager was not in the storage-network so it shouldn't need storage-network IP?

**Comment by innobead** [comment]
Actually, I meant backing image manager pod instead of longhorn manager pod.

**Comment by c3y1huang** [comment]
> @c3y1huang @shuo-wu which parts backing the image manager/data source are using storage IP? I assume it's only for syncing files between managers?

The backing image manager uses the storage IP to [fetch from the data source](https://github.com/longhorn/longhorn-manager/blob/v1.5.3/controller/backing_image_manager_controller.go#L690-L691) and [sync files across managers](https://github.com/longhorn/longhorn-manager/blob/v1.5.3/controller/backing_image_manager_controller.go#L752).

**Comment by roger-ryao** [comment]
**Verified on master-head 20231221**

- longhorn master-head https://github.com/longhorn/longhorn/commit/a879c2b7deb686761af623bb4c03c6871e318556
- backing-image-manager master-head https://github.com/longhorn/backing-image-manager/commit/8f1909ac0b9cd95f52b2a9f263ba2efe6543b4b5

**The test steps**
- 1. Setup Storage Network 
  - Ref: [test-storage-network](https://github.com/longhorn/longhorn-tests/blob/master/docs/content/manual/release-specific/v1.6.0/test-storage-network.md)
- 2. Create a BackingImage 
- 3. Can download it successfully

**Result Passed**
