### ISSUE TITLE
[IMPROVEMENT] Reconcile engine/replica instance state of v2 volume like v1 volume

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7326]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

For v1 volume, Longhorn does
1. In the first reconciliation, create an instance process ([codes](https://github.com/longhorn/longhorn-manager/blob/master/controller/instance_handler.go#L314)). Instance manager always responds without regardless of the failure or succeed ([codes](https://github.com/longhorn/longhorn-instance-manager/blob/master/pkg/process/process_manager.go#L193-L203)).
2. In the second reconciliation, synchronize the instance's state with the instance manager ([codes](https://github.com/longhorn/longhorn-manager/blob/master/controller/instance_handler.go#L355)).
3. Take action based on the current state ([codes](https://github.com/longhorn/longhorn-manager/blob/master/controller/instance_handler.go#L356-L391))

However, creation can be failed in creation step ([codes](https://github.com/longhorn/longhorn-spdk-engine/blob/main/pkg/spdk/engine.go#L100-L139)) for v2 volumes. This breaks the subsequent reconciliation.  To ensure consistency in behaviors between v1 and v2 volumes, [engine.Create()](https://github.com/longhorn/longhorn-spdk-engine/blob/main/pkg/spdk/engine.go#L77) and [replica.Create()](https://github.com/longhorn/longhorn-spdk-engine/blob/main/pkg/spdk/replica.go#L474) can

- Set the instance state to error 
- Store the `err.Error()` in `errorMsg`
- Return a `nil` error instead

**Before**
  ```
	  defer func() {
		  if err != nil && e.State != types.InstanceStateError {
			  e.State = types.InstanceStateError
		  }
	  }()
  ```

**After**
  ```
	  defer func() {
		  if err != nil {
			  e.log.WithError(err).Errorf("Failed to create engine %s", e.Name)
			  if e.State != types.InstanceStateError {
				  e.State = types.InstanceStateError
			  }
			  e.ErrorMsg = err.Error()
  
			  ret = e.getWithoutLock()
			  err = nil
		  }
	  }()
  ```

**Comment by roger-ryao** [comment]
**Verified on master-head 20231227**

- longhorn master-head https://github.com/longhorn/longhorn/commit/07bdb419a968633059c24db35ec66d7d68d73f4c
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/a42748a41d2d79f3be58e78d808859e6456576cf
- longhorn-spdk-engine main https://github.com/longhorn/longhorn-spdk-engine/commit/779b72c5fcf823ffbcc1c97eafbe21b11247ae18
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/00268adaa2715245797bdf260a72e249b71be563

**Result**

We are currently unable to create v2 volumes on the `master-head` due to a known issue. @derekbit rek is working on resolving this problem.

![Screenshot_20231227_165948](https://github.com/longhorn/longhorn/assets/104337648/f867d59f-f3af-437c-8098-a980d37d5c3b)

**Comment by chriscchien** [comment]
Verified **pass** on longhorn maseter (longhorn-spdk-engine `a3e2a2`)

Use custom image `derekbit/longhorn-instance-manager:test-5` to trigger v2 volume replicas can not get ports symptom, in CR `instancemanagers.longhorn.io` can see "failed to allocate port range" in below:
```
status:
  apiMinVersion: 1
  apiVersion: 4
  currentState: running
  instanceReplicas:
    pvc-915c1cec-2fac-43d6-bfbd-7c1b8fb388e5-r-7315a259:
      spec:
        backendStoreDriver: ""
        dataEngine: v2
        name: pvc-915c1cec-2fac-43d6-bfbd-7c1b8fb388e5-r-7315a259
            status:
        endpoint: ""
        errorMsg: failed to allocate port range
        listen: ""
        portEnd: 0
        portStart: 0
        resourceVersion: 0
        state: error
        type: replica
```
