### ISSUE TITLE
[QUESTION] Why does this project load Javascript from Alibaba/Alipay?

### ISSUE THREAD

**Issue by abctaylor** [longhorn/longhorn#7508]
Hi, why does Longhorn's frontend UI load javascript from **alipayobjects.com?** Asking from an infosec perspective as I can't see why this is necessary.

The particular line in the codebase I found is:

I see this is not just me and someone else also comes across this when calling the **longhorn-frontend** endpoint (https://github.com/longhorn/longhorn/issues/3235)

The network in question being contacted:
<img width="603" alt="image" src="https://github.com/longhorn/longhorn/assets/30197206/add5b931-32c2-4914-9e1c-e3933c65bc30">

**Comment by abctaylor** [comment]
Appending the line as an image since Github removed it
<img width="1006" alt="image" src="https://github.com/longhorn/longhorn/assets/30197206/fb938ada-a82c-420b-87fd-1ac1a0dcefa3">

**Comment by james-munson** [comment]
In the codebase, that appears to come from https://github.com/longhorn/longhorn-ui/blob/be240854f0dcefa7d6e95a2fb0fb2cd447db9dba/src/index.ejs#L10 and goes back to the initial check-in 7 years ago.

**Comment by m-ildefons** [comment]
Hi @abctaylor 
I looked a bit at what is being loaded as well as the comment block itself.
There is an [internet explorer specific feature](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537512(v=vs.85)?redirectedfrom=MSDN) that's being used here to load two additional bits of javascript in case a user is using internet explorer 10 or older (or a browser that likes to pretend it is IE 10 or older).

The two javascript pieces in question are [console-polyfill](https://www.npmjs.com/package/console-polyfill) and [media-match](https://www.npmjs.com/package/media-match).
The first one simply defines a global function to take the place of `console.log()`, which is necessary because on internet explorer (presumably older versions), this function is not defined unless the developer tools are enabled. If this function is called when it isn't defined, the UI crashes.
The second one defines a function that enables the UI to respond to the screen having certain properties, like being very small or being vertical or similar. I suppose again that this is again a case of internet explorer not supporting this function out of the box in all cases.

Why are they loaded from a subdomain of Alibaba? Longhorn UI utilizes [ant design](https://ant.design/) as a UI library on top of React. This library was created by engineers at Alibaba and it's very likely that the code blob requesting the two java script packages was provided in the documentation of antd at the time.

In any case, I agree with you that this is not optimal, and it should be evaluated if these two dependencies are even needed at all anymore.
Thanks for reporting the issue.

**Comment by abctaylor** [comment]
Thanks for the nice detective work here. I have no opinion on how the project wishes to proceed, but given how infrequently we see IE-only environments out there I guess there is little harm removing it entirely. I noticed telemetry is on by default so imagine someone has intel on what user agents are being used out there, I’d guess IE is sub 0.1%.

Andrew


On 2 Jan 2024, at 08:47, Moritz Röhrich ***@***.***> wrote:
﻿

Hi @abctaylor<https://github.com/abctaylor>
I looked a bit at what is being loaded as well as the comment block itself.
There is an internet explorer specific feature<https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537512(v=vs.85)?redirectedfrom=MSDN> that's being used here to load two additional bits of javascript in case a user is using internet explorer 10 or older (or a browser that likes to pretend it is IE 10 or older).

The two javascript pieces in question are console-polyfill<https://www.npmjs.com/package/console-polyfill> and media-match<https://www.npmjs.com/package/media-match>.
The first one simply defines a global function to take the place of console.log(), which is necessary because on internet explorer (presumably older versions), this function is not defined unless the developer tools are enabled. If this function is called when it isn't defined, the UI crashes.
The second one defines a function that enables the UI to respond to the screen having certain properties, like being very small or being vertical or similar. I suppose again that this is again a case of internet explorer not supporting this function out of the box in all cases.

Why are they loaded from a subdomain of Alibaba? Longhorn UI utilizes ant design<https://ant.design/> as a UI library on top of React. This library was created by engineers at Alibaba and it's very likely that the code blob requesting the two java script packages was provided in the documentation of antd at the time.

In any case, I agree with you that this is not optimal, and it should be evaluated if these two dependencies are even needed at all anymore.
Thanks for reporting the issue.
