### ISSUE TITLE
PoC: Reattach volume when docker reboot

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#762]
PoC for #686 .

- [x] Is it possible to observe the Docker reboot event from Longhorn? e.g. via Kubernetes state change.

**Comment by shuo-wu** [comment]
The main issue is that the `nodeBootID` won't change after docker reboot then Longhorn cannot handle it as a kind of node reboot case. And we cannot observe anything from Kubernetes state for the Docker reboot event.

For this docker reboot case, the Kubernetes actually behaves like node reboot case:
1. If the docker is rebooted within the around 6 mins, Kubernetes will restart pods and directly reuse volumes (without re-attaching volumes and cleaning up VolumeAttachment) after healing.
2. If the docker is rebooted after 6 mins, Kubernetes will try to restart pods, then wait for the old VolumeAttachment cleanup and re-attach volumes. 
3. If the StatefulSet/Deployment pod on the down docker node is forced delete before rebooting, Kubernetes will clean up the VolumeAttachment, detach and re-attach the volumes after 6 mins.

Because docker reboot is exactly the same as node reboot in scenarios 2 and 3 mentioned above, We don't need to worry about them.
For scenario 1, Longhorn cannot distinguish the docker reboot case from the common engine process error case then won't automatically re-attach volumes, see [here](https://github.com/longhorn/longhorn-manager/blob/568e5802d6d62ae33c84b2ea37b5b73b5e444e96/controller/volume_controller.go#L588) for details. Because the `nodeBootID` won't change and there is no observation that helps Longhorn distinguish the docker reboot case from other cases. --> We may need to maintain one more field such as `containerBootID` in our Longhorn system for this issue.

**Comment by shuo-wu** [comment]
Additional issue observed in the PoC:
For scenario 2, Longhorn v0.6.2 will take a long time to detach the volume. Since the instance manager pods on the docker reboot node are being restarted then deleting the instances in the instance manager will fail. This long detachment will lead to VolumeAttachment cleanup timeout then delay the pod restarting/recovery. The recovery time of Longhorn v0.5.0 is less than 1 min but the time of Longhorn v0.6.2 is 6 mins after node ready.

**Comment by yasker** [comment]
Done.
