### ISSUE TITLE
[BUG] Volume could not be remounted after engine process killed

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#7751]
## Describe the bug

In test case `test_volume_reattach_after_engine_sigkill`:

```
"""
[HA] Test if the volume can be reattached after using SIGKILL
to crash the engine process

1. Create StorageClass and StatefulSet.
2. Write random data to the pod and get the md5sum.
3. Crash the engine process by SIGKILL in the engine manager.
4. Wait for volume to `faulted`, then `healthy`.
5. Wait for K8s to terminate the pod and statefulset to bring pod to
    `Pending`, then `Running`.
6. Check volume path exist in the pod.
7. Check md5sum of the data in the pod.
8. Check new data written to the volume is successful.
"""
```

After engine process killed in `step 3`, and volume recovered to `healthy` in `step 4`, the statefulset pod could not be recreated to remount the volume:

https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-arm64/8/testReport/junit/tests/test_ha/test_volume_reattach_after_engine_sigkill/
https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/421/testReport/junit/tests/test_ha/test_volume_reattach_after_engine_sigkill/

```
client = <longhorn.Client object at 0xffff7d497af0>
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0xffff7d6c35e0>
storage_class = {'allowVolumeExpansion': True, 'apiVersion': 'storage.k8s.io/v1', 'kind': 'StorageClass', 'metadata': {'name': 'longhorn-test'}, ...}
sts_name = 'longhorn-teststs-hhecdb'
statefulset = {'apiVersion': 'apps/v1', 'kind': 'StatefulSet', 'metadata': {'name': 'longhorn-teststs-hhecdb', 'namespace': 'default...usybox:1.34.0', 'imagePullPolicy': 'IfNotPresent', 'name': 'sleep', ...}], 'terminationGracePeriodSeconds': 10}}, ...}}

    def test_volume_reattach_after_engine_sigkill(client, core_api, storage_class, sts_name, statefulset):  # NOQA
        """
        [HA] Test if the volume can be reattached after using SIGKILL
        to crash the engine process
    
        1. Create StorageClass and StatefulSet.
        2. Write random data to the pod and get the md5sum.
        3. Crash the engine process by SIGKILL in the engine manager.
        4. Wait for volume to `faulted`, then `healthy`.
        5. Wait for K8s to terminate the pod and statefulset to bring pod to
           `Pending`, then `Running`.
        6. Check volume path exist in the pod.
        7. Check md5sum of the data in the pod.
        8. Check new data written to the volume is successful.
        """
        vol_name, pod_name, md5sum = \
            common.prepare_statefulset_with_data_in_mb(
                client, core_api, statefulset, sts_name, storage_class)
    
        crash_engine_process_with_sigkill(client, core_api, vol_name)
    
>       wait_pod_for_remount_request(client, core_api, vol_name, pod_name, md5sum)

test_ha.py:1863: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_ha.py:625: in wait_pod_for_remount_request
    wait_for_pod_remount(core_api, pod_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0xffff7d6c35e0>
pod_name = 'longhorn-teststs-hhecdb-0', chk_path = '/data/lost+found'

    def wait_for_pod_remount(core_api, pod_name, chk_path="/data/lost+found"):
        check_command = [
            '/bin/sh',
            '-c',
            'ls ' + chk_path
        ]
    
        ready = False
        for i in range(RETRY_EXEC_COUNTS):
            try:
                output = stream(core_api.connect_get_namespaced_pod_exec,
                                pod_name,
                                'default',
                                command=check_command,
                                stderr=True, stdin=False,
                                stdout=True, tty=False)
                if "Input/output error" not in output:
                    ready = True
                    break
            except Exception:
                pass
            if ready:
                break
            time.sleep(RETRY_EXEC_INTERVAL)
>       assert ready
E       AssertionError

common.py:4932: AssertionError
```

Seems `longhorn-manager` is flooded with `Volume request remount` messages:

![remount](https://github.com/longhorn/longhorn/assets/5709208/94ad81a7-3b87-4b27-b482-2588d2a2abbc)

```
2024-01-23T00:54:07.193269120Z time="2024-01-23T00:54:07Z" level=info msg="Volume request remount at 2024-01-23T00:54:07Z due to engine detected read-only filesystem" func="controller.(*VolumeController).requestRemountIfFileSystemReadOnly" file="volume_controller.go:1482" accessMode=rwo controller=longhorn-volume frontend=blockdev migratable=false node=ip-10-0-2-138 owner=ip-10-0-2-138 state=attached volume=pvc-c0387c67-ce3e-4ce0-a63b-465eeda79781
2024-01-23T00:54:07.193385769Z time="2024-01-23T00:54:07Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-c0387c67-ce3e-4ce0-a63b-465eeda79781\", UID:\"6c272859-9b99-4a8c-b823-532228049b5d\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"153277\", FieldPath:\"\"}): type: 'Normal' reason: 'Remount' Volume pvc-c0387c67-ce3e-4ce0-a63b-465eeda79781 requested remount at 2024-01-23T00:54:07Z due to engine detected read-only filesystem" func="record.(*eventBroadcasterImpl).StartLogging.func1" file="event.go:298"
```

But the statefulset pod is never recreated and stuck in `Input/output error`:
```
# kubectl get pods 
NAME                        READY   STATUS    RESTARTS      AGE
longhorn-test-minio         1/1     Running   0             18h
longhorn-test-nfs           1/1     Running   1 (18h ago)   18h
longhorn-test               2/2     Running   0             18h
longhorn-teststs-yoij4o-0   1/1     Running   0             13h
# kubectl exec -it longhorn-teststs-yoij4o-0 -- /bin/sh
/data # echo ok > ok
/bin/sh: can't create ok: Input/output error
```

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6041/console

## To Reproduce

Run test case `test_volume_reattach_after_engine_sigkill`.

The reproducibility is about ~ `1/300`.

## Support bundle for troubleshooting

[supportbundle_846e2484-667c-4742-b6ce-dbf5fd40a0df_2024-01-23T00-54-01Z.zip](https://github.com/longhorn/longhorn/files/14017099/supportbundle_846e2484-667c-4742-b6ce-dbf5fd40a0df_2024-01-23T00-54-01Z.zip)

## Environment

 - Longhorn version: master-head, v1.6.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl 
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.28.4+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by shuo-wu** [comment]
[Field `v.Status.RemountRequestedAt` **keeps** being updated](https://github.com/longhorn/longhorn-manager/blob/c5e363ff225573f19fb1b1a9c21d3ee5e28b0427/controller/volume_controller.go#L1454-L1487) as long as the corresponding workload pod is not removed or the volume is not detached. That's why the remount log is flooded.

But the weird thing is, I don't know why [the pod cleanup logic](https://github.com/longhorn/longhorn-manager/blob/c5e363ff225573f19fb1b1a9c21d3ee5e28b0427/controller/kubernetes_pod_controller.go#L341-L351) is not triggered. I cannot find any related log `Deleted pod %v so that Kubernetes will handle remounting volume`.

I checked the volume and the corresponding statefulset pod YAML. Based on the pod deletion condition `podStartTime.Before(remountRequestedAt) && timeNow.After(remountRequestedAt.Add(delayDuration))`, the pod and remount timestamp should match and the possible exception may be `timeNow` and 5-second `delayDuration`.
```
- apiVersion: longhorn.io/v1beta2
  kind: Volume
  metadata:
    creationTimestamp: "2024-01-22T11:32:41Z"
    name: pvc-c0387c67-ce3e-4ce0-a63b-465eeda79781
    namespace: longhorn-system
    resourceVersion: "153197"
    uid: 6c272859-9b99-4a8c-b823-532228049b5d
  spec:
    nodeID: ip-10-0-2-138
  status:
    kubernetesStatus:
      lastPVCRefAt: "null"
      lastPodRefAt: "null"
      namespace: default
      pvName: pvc-c0387c67-ce3e-4ce0-a63b-465eeda79781
      pvStatus: Bound
      pvcName: pod-data-longhorn-teststs-yoij4o-0
      workloadsStatus:
      - podName: longhorn-teststs-yoij4o-0
        podStatus: Running
        workloadName: longhorn-teststs-yoij4o
        workloadType: StatefulSet
    ownerID: ip-10-0-2-138
    remountRequestedAt: "2024-01-23T00:53:37Z"
    robustness: healthy
    state: attached
```
```
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2024-01-22T11:32:41Z"
    generateName: longhorn-teststs-yoij4o-
    name: longhorn-teststs-yoij4o-0
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: longhorn-teststs-yoij4o
      uid: 03e7156a-9662-4395-99e1-b72fcc3ac88a
    resourceVersion: "73062"
    uid: 6da4d871-2595-4b5a-a722-6ca727345b1a
  spec:
    hostname: longhorn-teststs-yoij4o-0
    nodeName: ip-10-0-2-138
    volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: pod-data-longhorn-teststs-yoij4o-0
  status:
    phase: Running
    startTime: "2024-01-22T11:32:45Z"
```

@ChanYiLin Will field `v.Status.RemountRequestedAt` be constantly updated before introducing `imtypes.EngineConditionFilesystemReadOnly`?

**Comment by ChanYiLin** [comment]
I think it is possible that the `v.Status.RemountRequestedAt` keeps updating every reconcile 
I will do a quick test

**Comment by ChanYiLin** [comment]
No wait, the filesystem became ro only when we issue IO after engine crashes
In my test environment, when I crash the engine and wait for it to reattach
The filesystem is still "rw" because there is not IO to trigger it.
There is no IO in the test after the engine crashes either.

I think the engine request remount first and then @yangchiu access into pod to perform IO to trigger read-only situation
- engine request remount at `09:19:16`
- read-only request remount happened after `09:19:30`
and Notice, the request remount because of read-only **updated every 30 secs, that is our reconcile interval**
So the problem is **Why didn't the pod being deleted** 
![Screenshot from 2024-01-23 18-06-46](https://github.com/longhorn/longhorn/assets/7100904/4b758823-ffce-4288-8bea-4ecc82cf9cb2)

**Comment by shuo-wu** [comment]
> In my test environment, when I crashed the engine and waited for it to reattach
The filesystem was still "rw" because there is not IO to trigger it.

> From my local test, my workload was not restart either, even v.Status.RemountRequestedAt had already been set

Wait... How can `v.Status.RemountRequestedAt` be set if the filesystem is still rw?  And does this feature still work fine without an extra IO (to trigger filesystem ro)?

> I think the engine request remount first and then @yangchiu access into pod to perform IO to trigger read-only situation

I don't think @yangchiu will enter into the test workload pod before triggering this issue

**Comment by ChanYiLin** [comment]
Hi @shuo-wu 
We do request remount after engine crashes
This is a feature long time ago
https://github.com/longhorn/longhorn-manager/blob/5fbee1338dc10a15f633afa39742f0eaa5bf70ef/controller/volume_controller.go#L1397-L1425

**Comment by ChanYiLin** [comment]
You can also check my HackWeek summary of how we handle engine crashing
https://docs.google.com/presentation/d/1aFtPX5yY53TGbndy3D2IRs5SrBxZigBRCiuLt3fMaW4/edit#slide=id.g26073da28eb_0_530

**Comment by ChanYiLin** [comment]
The request remount feature here is to capture other cases that lead to filesystem "ro" instead of engine crashing.

**Comment by ChanYiLin** [comment]
I am going to print some info in pod deletion part to see the time relation

**Comment by ChanYiLin** [comment]
Oh by the way, from my own local testing when implementing request remount feature
Only when we perform "write" can we trigger the filesystem read-only error and the mount point become "ro"

In our test, what we do here is only "read"
and that is to test if engine comes back, because if it doesn't, we got IO Error for even "read"
But that won't caused the filesystem into `read-only error`

```
def wait_for_pod_remount(core_api, pod_name, chk_path="/data/lost+found"):
    check_command = [
        '/bin/sh',
        '-c',
        'ls ' + chk_path
    ]

    ready = False
    for i in range(RETRY_EXEC_COUNTS):
        try:
            output = stream(core_api.connect_get_namespaced_pod_exec,
                            pod_name,
                            'default',
                            command=check_command,
                            stderr=True, stdin=False,
                            stdout=True, tty=False)
            if "Input/output error" not in output:
                ready = True
                break
        except Exception:
            pass
        if ready:
            break
        time.sleep(RETRY_EXEC_INTERVAL)
    assert ready
```

**Comment by yangchiu** [comment]
> I am going to print some info in pod deletion part to see the time relation https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6058 100/100 PASSED https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6062 100/100 PASSED https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6063 100/100 PASSED

@ChanYiLin What's been modified in these test runs? This test case randomly fails from time to time in master and other branches.

**Comment by ChanYiLin** [comment]
I only print the information to see why the pod is not being deleted, I didn't change any code logic and test logic

**Comment by ChanYiLin** [comment]
I think I confirmed the issue
It is like what @shuo-wu said here

Take this case for example
```
test_ha.py::test_volume_reattach_after_engine_sigkill[41-100] 
Exception waiting for pod pending,could have missed it
wait for pod longhorn-teststs-ca4bzq-0 remount ... (0)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (1)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (2)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (3)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (4)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (5)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (6)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (7)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (8)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (9)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (10)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (11)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (12)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (13)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (14)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (15)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (16)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (17)
wait for pod longhorn-teststs-ca4bzq-0 remount ... (18)
...
```

1. We crash the engine and then wait the volume become faulty first and then become health
2. We then wait the pod become pending first and then become running (Restarting)
3. And then check if volume is remounted by checking the IO

```
 def wait_pod_for_remount_request(...):
    try:
        # this line may fail if the recovery is too quick
        wait_for_volume_faulted(client, volume_name)
    except AssertionError:
        print("\nException waiting for volume faulted,"
              "could have missed it")

    wait_for_volume_healthy(client, volume_name)

    try:
        common.wait_for_pod_phase(core_api, pod_name, pod_phase="Pending")
    except AssertionError:
        print("\nException waiting for pod pending,"
              "could have missed it")
    common.wait_for_pod_phase(core_api, pod_name, pod_phase="Running")

    wait_for_pod_remount(core_api, pod_name)
    ...
```

```
def wait_for_pod_remount(core_api, pod_name, chk_path="/data/lost+found"):
    check_command = [
        '/bin/sh',
        '-c',
        'ls ' + chk_path
    ]

    ready = False
    for i in range(RETRY_EXEC_COUNTS):
        try:
            output = stream(core_api.connect_get_namespaced_pod_exec,
                            pod_name,
                            'default',
                            command=check_command,
                            stderr=True, stdin=False,
                            stdout=True, tty=False)
            if "Input/output error" not in output:
                ready = True
                break
        except Exception:
            pass
        if ready:
            break
        time.sleep(RETRY_EXEC_INTERVAL)
    assert ready
```

The problem here is that
1. The engine indeed restarted and the volume became healthy
2. The volume-controller request remount because volume detach accidentally [here](https://github.com/longhorn/longhorn-manager/blob/5fbee1338dc10a15f633afa39742f0eaa5bf70ef/controller/volume_controller.go#L1397-L1425)
3. but the pod hadn't yet. And **our test thought it just missed the restart process and assumed it restarted because it was now running (See the exception we catch in the test)** 
4. Our test then performed some IO which made the filesystem read-only
5. Engine detect the read-only, and then request remount every 30 sec (CRD reconcile time interval)

Our Pod deletion is executed in kubernetes_pod_controller.go and it reconcile pods every 30 secs
If **request remount every 30 sec** just overlaps with **reconcile pods every 30 secs**, then it won't delete the pod because we check `podStartTime.Before(remountRequestedAt) && timeNow.After(remountRequestedAt.Add(delayDuration))`

cc @shuo-wu @innobead

**Comment by ChanYiLin** [comment]
I think what we can do here is to not update the request remount every time when we detect read-only condition
Maybe we update it every 1 mins so pod reconciliation could still have the chance to delete the pod

Cleanup filesystem readonly condition after set request remount won't work, because we periodically sync the condition from instance-manager every 30 secs.

**Comment by shuo-wu** [comment]
I realized the reconciliation interval of the kubernetes pod controller would be the cause as well last night. 

> I think what we can do here is to not update the request remount every time when we detect read-only condition
Maybe we update it every 1 mins so pod reconciliation could still have the chance to delete the pod

This is one of the simplest fix for this issue now. Or we can re-queue the pod if `podStartTime.Before(remountRequestedAt)`  but `!timeNow.After(remountRequestedAt.Add(delayDuration))`

**Comment by ChanYiLin** [comment]
I think to slow down the request remount might be more proper
re-queueing the pod could introduce the overhead to the controller because it will keep re-queueing the obj  in that 5 secs

**Comment by shuo-wu** [comment]
I am fine with either. BTW, requeuing an object will add a backoff. There won't be too much overhead.

**Comment by yangchiu** [comment]
Verified passed on master-head (longhorn-manager 9aec52) by running test case `test_volume_reattach_after_engine_sigkill` 500 times. 

They all passed: 
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6082/ ~ https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6086/

I'll run it on v1.6.x-head later.

**Comment by yangchiu** [comment]
Verified passed on v1.6.x-head (longhorn-manager 706870) by running test case `test_volume_reattach_after_engine_sigkill` 300 times.

They all passed:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6102/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6103/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6105/
