### ISSUE TITLE
[TASK] Add 1.6.0 performance report

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#7829]
## What's the task? Please describe

Add 1.6.0 performance report to https://github.com/longhorn/longhorn/wiki/Performance-Benchmark.

**Comment by derekbit** [comment]
Need v2 volume (amd64 and arm64) as well?

**Comment by innobead** [comment]
Sounds good.

IIRC, we have an automatic pipeline. Can we use that eventually to generate an automatic report? Probably can run several times to reduce bias.

If this automation is beyond the pipeline, then we can create a ticket to improve it later.

**Comment by innobead** [comment]
@derekbit don't forget this.

**Comment by derekbit** [comment]
Performance report is added.
https://github.com/longhorn/longhorn/wiki/Performance-Benchmark#v160
cc @innobead

**Comment by derekbit** [comment]
The IOPS/throughput drop of 3-replicas RWO volume on Equinix machines with Ubuntu 22.04 is observed. I tried replace the kernel, but the drop remains.

The network bandwidth between two nodes is 25 Gb/s.

![image](https://github.com/longhorn/longhorn/assets/12527233/f0746e88-1fe3-458e-a84f-3c6212b88270)

However, the issue is not observed on 
- Equinix machines with Rocky Linux 9
- AWS EC2 with Ubuntu 22.04

cc @PhanLe1010 @shuo-wu @innobead

**Comment by shuo-wu** [comment]
The latency looks problematic. Would you help check which part introduces such a large number for the latency? The iscsi frontend? The TCP connection between engines and replicas (may be affected by some configs like MTU?)? Or the replica to disk r/w?

**Comment by shuo-wu** [comment]
Besides, do we need to update the blog/article like [this](https://longhorn.io/blog/performance-scalability-report-aug-2020/) on our official website?
