### ISSUE TITLE
[feature] Add a percentage meter of the size of the volume in the list

### ISSUE THREAD

**Issue by Angelinsky7** [longhorn/longhorn#785]
Hi,
Could it be possible to have a percentage meter of the actual size of the volume in the volume list, like that we could directly see when a volume is near the 100%. 

It is certainly possible to create an alarm about that and go to grafana to see them but it would we really easier to have it there (or in any other way)

(and i didn't find a way in the rancher grafana instance to see the size)

thanks

**Comment by yasker** [comment]
It's a bit hard for the block device to decide it's full or not since it's the filesystem on top of the block device determines that. But I understand the need for this.

This will require us to somehow access the pod created by Kubernetes and get information from there if possible. We will look into this later.

**Comment by Angelinsky7** [comment]
@yasker if i understand correctly the actual size written in the picture is in fact the size of the file in the filesystem (with all the snapshot) and not the actual size of the "mount"

![image](https://user-images.githubusercontent.com/13157968/65997589-f26efd00-e499-11e9-940a-b4e3817ade3a.png)

**Comment by yasker** [comment]
@Angelinsky7 Yeah, it's the size each replica of the volume occupied on the hard drive, which includes all the snapshots.
