### ISSUE TITLE
Longhorn UI Taint-toleration settings

### ISSUE THREAD

**Issue by HHT02** [longhorn/longhorn#806]
Related to https://github.com/longhorn/longhorn/issues/805.

After editing the default setting YAML and applying it to our deployment, we were seeing a different result within the Longhorn UI than was in our deployment. We previously added an incorrect key/value pair to the deployment and when trying to overwrite it we were still seeing the old key/value pair instead of the newer one.

Our default-setting.yaml looked like the following: 

```
backup-target:
backup-target-credential-secret:
create-default-disk-labeled-nodes: 
default-data-path: /var/lib/rancher/longhorn/
replica-soft-anti-affinity: true
storage-over-provisioning-percentage: 600
storage-minimal-available-percentage: 15
upgrade-checker: false
default-replica-count: 2
guaranteed-engine-cpu:
default-longhorn-static-storage-class: longhorn
backupstore-poll-interval:
taint-toleration: dedicated=storage:NoSchedule
```

**Comment by shuo-wu** [comment]
I think you just want to modify the toleration setting for the existing Longhorn system. If Yes, you can check this doc for more info and instructions: [taint toleration setting](https://github.com/longhorn/longhorn/blob/master/docs/taint-toleration.md#after-longhorn-has-been-installed)

The default setting YAML file is for the Longhorn system that hasn't been deployed only, rather than the existing Longhorn system. The docs for these new features may confuse you since we forget to include these details in them. We will update the doc for these cases soon. 

Thank you for your reporting! And feel free to post issues if there are more questions confusing you.

**Comment by ChrisScottThomas** [comment]
> The default setting YAML file is for the Longhorn system that hasn't been deployed only, rather than the existing Longhorn system. The docs for these new features may confuse you since we forget to include these details in them. We will update the doc for these cases soon.

The confusion comes because this isn't really Kubernetes intuitive.  We want, and expect, to be able to declare the state of workloads via the YAMLs, not via a UI.  Really this configMap, if used, should be the source of truth for the Longhorn workloads, not the UI.

**Comment by yasker** [comment]
@ChrisScottThomas There is no way for us to validate the config map. So it cannot be the source of truth.

We're using CRDs in Kubernetes to store the metadata for Longhorn managers. Currently, we don't recommend to modify it directly, since there was no way of validation. We're working on #791 to adding validation hooks and transiting the API to more Kubernetes native way.

For now, you can use `kubectl -n longhorn-system get setting.longhorn.rancher.io` to see the configuration we stored. But they're not ready for update through kubectl yet.

**Comment by ChrisScottThomas** [comment]
Looking forward to the updates, thanks for the information
