### ISSUE TITLE
[QUESTION] Kubernetes 1.29 support

### ISSUE THREAD

**Issue by harryzcy** [longhorn/longhorn#8191]
## Question

I see in the doc that [Kubernetes Version](https://github.com/longhorn/website/blob/master/content/docs/1.6.1/best-practices.md#kubernetes-version) still shows 1.28, 1.27, and 1.26 for the upcoming release. But version 1.29 has been released for a while, and both k3s and rke2 has 1.29 released.

How do I know when it will be tested to be supported? like is there anything I can track what's being tested?

From the [metric], I do see quite a few nodes running Kubernetes 1.29.

## Environment

 - Longhorn version: 1.6.0
 - Kubernetes version:
 - Node config
   - OS type and version
   - Kernel version
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by ejweber** [comment]
This is a good question. I will compile some information here and discuss with the team:

- [Kubernetes v1.29](https://kubernetes.io/releases/) has been out since December. v1.29.2 has been released.
- Our [public test pipelines](https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/76/parameters/) for `master` and `v1.6.x` branches currently test on `v1.28.4`.
- Our [Kubernetes Version Update policy](https://github.com/longhorn/longhorn/wiki/Version-Update-Policy#kubernetes-version-update) states that we will test active Kubernetes versions, but doesn't give clear guidelines as to exactly what this means (e.g., if a Longhorn version releases the same day as a Kubernetes version, we obviously cannot test the combination).
- [This PR](https://github.com/longhorn/website/pull/804/files) added the linked documentation for v1.6.0. Previously we did not document it.

**Comment by innobead** [comment]
We should improve the doc. The purpose of mentioning K8s versions is to let users know what versions have been verified during the release, but it does not mean we only support them. 

For any actively maintained K8s versions, Longhorn should support them if it's compatible. 

> * [This PR](https://github.com/longhorn/website/pull/804/files) added the linked documentation for v1.6.0. Previously we did not document it.

cc @c3y1huang @jillian-maroket

**Comment by roger-ryao** [comment]
> * [Kubernetes v1.29](https://kubernetes.io/releases/) has been out since December. v1.29.2 has been released.
> * Our [public test pipelines](https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/76/parameters/) for `master` and `v1.6.x` branches currently test on `v1.28.4`.
> * Our [Kubernetes Version Update policy](https://github.com/longhorn/longhorn/wiki/Version-Update-Policy#kubernetes-version-update) states that we will test active Kubernetes versions, but doesn't give clear guidelines as to exactly what this means (e.g., if a Longhorn version releases the same day as a Kubernetes version, we obviously cannot test the combination).

Hi @ejweber :
    I previously discussed with @innobead  that our **public test pipelines** Kubernetes version will be updated one to two months before the planned release of `master-head rc1`. Last time we updated, v1.29 hadn't been released yet. I'll be updating the Kubernetes version used by our master-head to v1.29 soon.
    
Hi @innobead 
     If there are any adjustments or changes, please let us know.
     
cc @longhorn/qa
