### ISSUE TITLE
[BUG] Longhorn RWX volumes eventually fail to attach

### ISSUE THREAD

**Issue by vvash94** [longhorn/longhorn#8205]
## Describe the bug

We are running RWX volumes using Longhorn. The volumes do attach fine, but if we scale up the number of pods attached to more than 20, we start seeing volume attach errors and the pods get stuck in Init state.

## To Reproduce

Create RWX volume and attach it to about 20 pods.

## Expected behavior

We expect the pods to attach the RWX volumes successfully.

## Environment

 - Longhorn version: 1.6.0
 - Impacted volume (PV): pvc-7d3960af-9e0c-4c5b-8095-1f8a55185e62
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: 1.28.6
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 31
 - Node config
   - OS type and version: Rocky 8
   - Kernel version: 5.4.212
   - CPU per node: 4
   - Memory per node: 16
   - Disk type (e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes (Gbps): 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 36

**Comment by vvash94** [comment]
How do I send the support bundle? I cant attach nor mail it. It is 347 MB.

**Comment by ejweber** [comment]
Hello @vvash94. Unfortunately, we don't currently have a portal that you can directly upload the bundle to. Many users upload their bundles to some existing cloud file storage they are subscribed to and share a link (either on GitHub or via longhorn-support-bundle@suse.com). I have also seen users upload to free file sharing sites like Filemail or file.io and similarly share the link. Sorry for the inconvenience!

**Comment by vvash94** [comment]
@ejweber No worries. I have uploaded it to an S3 bucket. Here is the URL: https://sentient-external-logs-bucket.s3.us-west-2.amazonaws.com/supportbundle_916fb743-a573-45eb-ad43-f5ae95c8b784_2024-03-19T03-23-02Z.zip

**Comment by vvash94** [comment]
@ejweber do let me know if you need anything more from me. We are holding the environment in this state so we can help with any debugging. I would be happy to provide any info needed

**Comment by ejweber** [comment]
Sorry @vvash. I was unable to get to this yesterday. I will review the support bundle over the next couple of hours and let you know what I find out or if I need some additional information.

**Comment by ejweber** [comment]
I think you are probably hitting https://github.com/longhorn/longhorn/issues/7301#issuecomment-1847150646 (https://github.com/nfs-ganesha/nfs-ganesha/issues/825 and https://github.com/cilium/cilium/issues/21541).

At "2024-03-16T18:40:07Z"` a remount for `pvc-7d3960af-9e0c-4c5b-8095-1f8a55185e62` was requested by the system. Probably this was because the previous share manager hit an error, but I don't think we have the logs any more to determine the exact cause.

For the current, pending pod issue, it seems the issues linked above are the culprit. The new share manager has a new IP address, but the other system components attempt to communicate with it via the cluster IP of its service. Apparently, in Cilium environments with a certain configuration and kernel, this can cause NFS to be unable to reconnect.

Evidence:

- The existence of Cilium pods show that Cilium is enabled in this environment.
- The `cilium-config` config map has `kube-proxy-replacement: strict`. (Apparently Cilium environments without `kube-proxy-replacement` can operate as expected.)
- The kernel version of the nodes is `4.18.0-425.10.1.el8_7`. (I am not sure whether https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=0bdf399342c5, which landed in kernel v6.6, has been backported to a Rocky kernel you have access to.)

**Comment by vvash94** [comment]
@ejweber Thanks for the analysis. Yes we are indeed using Cilium in kube-proxy-replacement mode. Let me redeploy this environment ASAP with the setting turned off. I will report back here once we test it out. Should I keep this issue open or close it temporarily?

**Comment by ejweber** [comment]
Feel free to leave it open until you can check it out. Thanks!

**Comment by jrife** [comment]
@ejweber 

> Apparently, in Cilium environments with a certain configuration and kernel, this can cause NFS to be unable to reconnect.

When using `kube-proxy-replacement` with an unpatched kernel, NFS mounts made to a Service's cluster IP will break (be left trying to remount the old endpoint IP) if the endpoint IP changes (e.g. a new NFS ganesha pod is spun up). Does this sound like what might be happening?

> The kernel version of the nodes is 4.18.0-425.10.1.el8_7. 

I see `5.4.212` in the bundle above? @vvash94 Did you upgrade your kernel version? Rocky Linux's [docs](https://wiki.rockylinux.org/rocky/version/) mention Rocky 8.7 being shipped with `4.18.0-425.3.1`. I imagine you'd have to upgrade in order to use it with `kube-proxy-replacement` which [requires](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/) `4.19` or higher.

> (I am not sure whether https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=0bdf399342c5, which landed in kernel v6.6, has been backported to a Rocky kernel you have access to.)

The patch has been backported to all [supported](https://kernel.org/) upstream kernels, but different distros backport fixes from upstream at different rates. The patch is fully backported on Ubuntu kernels AFAIK, but Rocky linux follows RHEL and I'm not sure RHEL has backported this fix into any of their kernels.

**Comment by akalenyu** [comment]
Did you ever figure this out? sounds very similar to what we're seeing in https://github.com/kubevirt/kubevirt/pull/13443
but the k8s node's VM has a kernel with the fix.
