### ISSUE TITLE
Write Performance is about 100X slow and cannot fnish exec kubectl cp

### ISSUE THREAD

**Issue by sigezhao** [longhorn/longhorn#8302]
## Describe the bug

I copy a directory full of small files with  its size 326M, when i copy on local node, it cost 0.368 second
![image](https://github.com/longhorn/longhorn/assets/7226882/242a9dff-acb3-461f-ac2e-f3b50d4ea601)

when I use kubectl cp to upload the directory to longhorn cluster, its write speed about 1M/s，and the command couldn't finish. 
the directory's size on longhorn is stop at 325.1M.
![image](https://github.com/longhorn/longhorn/assets/7226882/43526c12-e99f-4f21-8403-3648c87d0081)

## Environment
 - Longhorn version: v1.6.0
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.28.8+k3s1
   - Number of control plane nodes in the cluster:3
   - Number of worker nodes in the cluster:3
 - Node config
   - OS type and version:CentOS Linux release 7.6.1810 (Core) 
   - Kernel version: 3.10.0-1160.108.1.el7.x86_64
   - CPU per node: 2
   - Memory per node: 4G
   - Disk type (e.g. SSD/NVMe/HDD):SSD
   - Network bandwidth between the nodes (Gbps): 1000
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):KVM
 - Number of Longhorn volumes in the cluster:3

**Comment by james-munson** [comment]
It may be misleading to compare cumulative sizes directly, since the storage layout is a bit different.  A more informative comparison would be a cumulative count of files.  It would be expected that if the `cp` finished without error, the counts would match.

The notes do not say whether this was an RWX volume, but that could play a role in the write performance.  Longhorn uses an NFS server layer to support multiple write access, and NFS is recognized to have impeded performance on small files.

One other thing to note:  this installation is a recent version of Longhorn, but rather an old OS and kernel.  The [best practices](https://longhorn.io/docs/1.6.0/best-practices/#operating-system) documentation suggests a kernel of at least 5.8, to be able to use filesystem optimizations and improvements in that release.

**Comment by sigezhao** [comment]
> It may be misleading to compare cumulative sizes directly, since the storage layout is a bit different. A more informative comparison would be a cumulative count of files. It would be expected that if the `cp` finished without error, the counts would match.
> 
> The notes do not say whether this was an RWX volume, but that could play a role in the write performance. Longhorn uses an NFS server layer to support multiple write access, and NFS is recognized to have impeded performance on small files.
> 
> One other thing to note: this installation is a recent version of Longhorn, but rather an old OS and kernel. The [best practices](https://longhorn.io/docs/1.6.0/best-practices/#operating-system) documentation suggests a kernel of at least 5.8, to be able to use filesystem optimizations and improvements in that release.

Because kubectl cp could not finish，the command block the terminal，so I use du command to compare.Why it block
The volume is an RWX volume，I Change to RWO volume，test a big file 53M，it with 15X write performance slow，is it meets expectations？
![image](https://github.com/longhorn/longhorn/assets/7226882/3e9c420d-c0fa-480b-b611-0a8704224c57)

I‘ll update kernel version later
