### ISSUE TITLE
[IMPROVEMENT] Prevent unnecessary updates of instanceManager status

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8420]
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

If the engine or replica process map from an instance manager is empty, `instanceManager.status.InstanceEngines` or `instanceManager.status.InstanceReplicas` will be a `nil` map.

`reflect.DeepEqual` function treats two maps `var m1 map[string]process` and `m2 := map[string]process` as different maps. Therefore, to prevent unnecessary updates, we must check both that the length of the maps is zero and that the maps are identical.

https://github.com/longhorn/longhorn-manager/blob/master/controller/instance_manager_controller.go#L1636-L1638

**Comment by chriscchien** [comment]
Verified **pass** on longhorn master(longhorn-manager `1cda0e`)

On daily regression, did not see outsatnding issue related to instanceManager.

In build [946 ](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/946/#showFailuresLink) , all failed test case have found the root cause and have related ticket

- test_backup_lock_creation_during_deletion
   - https://github.com/longhorn/longhorn/issues/8269
- test_filesystem_trim
   - https://github.com/longhorn/longhorn/issues/5463
- test_system_backup_and_restore_volume_with_backingimage
   https://github.com/longhorn/longhorn/issues/8650
- tests.test_basic.test_backuptarget_invalid
   - https://github.com/longhorn/longhorn-tests/pull/1941
- tests.test_csi.test_csi_encrypted_block_volume
- tests.test_csi.test_csi_encrypted_migratable_block_volume
   - https://github.com/longhorn/longhorn/issues/8688
