### ISSUE TITLE
Node Disk gets disabled randomly

### ISSUE THREAD

**Issue by maxaudron** [longhorn/longhorn#849]
After some time my two nvme SSD disk will be disabled in longhorn, trying to reenable them only yields this message in the logs:
```
Update disk on node jupiter warning: The disk /mnt/longhorn/nvme0/ has changed file system, please mount it back or remove it
```

The disks are mounted with the flags `default,noatime` and a xfs filesystem.

For now the only easy way that i've found to reenable them is restart the node,
I can't unmount them as longhorn is still using them

**Comment by yasker** [comment]
@maxaudron Are the disks' filesystem changed? Longhorn records the filesystem ID to make sure it won't accidentally write into another disk due to e.g. the disk was umounted.

The following command can be used to get fsid
```
stat -fc "{\"path\":\"%n\",\"fsid\":\"%i\",\"type\":\"%T\",\"freeBlock\":%f,\"totalBlock\":%b,\"blockSize\":%S}" /mnt/longhorn/nvme0/
```

If longhorn detected the filesystem change for the directory(e.g. the disk was reformatted or umounted), the disk would be disabled automatically, to prevent unintended consequences.

**Comment by maxaudron** [comment]
I had removed the noatime mount option a few days ago to try it out, took two reboots to get the volume recognized again but now it hasn't been disabled since.

The fsid was indeed changed, while it was still the same disk mounted, though i couldn't find any hint to the drive actually having been remounted. Seems to be a problem with the underlying filesystem so closing this for now.
