### ISSUE TITLE
[BUG] Volume failed to create healthy replica after data locality and replica count changed and got stuck in degraded state forever

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#8522]
## Describe the bug

In case 4 of test case `test_data_locality_basic`:

1. There are 3 nodes: `node 0`, `node 1`, `node 2`
2. Disable scheduling of `node 2`
3. Create a volume with `replica count  = 1`, `data locality = best-effort`
4. Attach the volume to `node 2`, and wait for the volume healthy
5. Update replica count to `3`, and wait for the volume degraded
6. Update replica count to `2`, and wait for the volume healthy
7. Update replica count to `1`, and wait for the volume healthy
8. Update replica count to `2` and `data locality = `disabled`, although the volume is unable to create a replica on the same node of the volume attached, the volume should still be able to create 2 replicas and become healthy state, but it's possible that the volume failed to create healthy replica after data locality and replica count changed and got stuck in degraded state forever:

![locality1](https://github.com/longhorn/longhorn/assets/5709208/00e6d040-1e2a-4f8d-a278-b96b47c4fde9)

![locality2](https://github.com/longhorn/longhorn/assets/5709208/6f781d61-897b-4ffc-ac44-5d164ce29ca7)

![locality3](https://github.com/longhorn/longhorn/assets/5709208/11c3bb3e-19a3-4cd0-843b-15ef0387b3ea)

![locality4](https://github.com/longhorn/longhorn/assets/5709208/b122417d-8be6-47da-9fe6-ecde93451e94)

## To Reproduce

Run test case `test_data_locality_basic` repeatedly.

The reproducibility could be less than `1/100`.

## Support bundle for troubleshooting

[supportbundle_8bf4c37f-96ac-4fcd-b75a-c62ac6b6e9ff_2024-05-08T10-58-10Z.zip](https://github.com/longhorn/longhorn/files/15248944/supportbundle_8bf4c37f-96ac-4fcd-b75a-c62ac6b6e9ff_2024-05-08T10-58-10Z.zip)

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.29.3+k3s1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3
 - Node config
   - OS type and version: sles 15-sp5
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): aws
 - Number of Longhorn volumes in the cluster:

## Additional context

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/830/testReport/tests/test_scheduling/test_data_locality_basic/

**Comment by derekbit** [comment]
@yangchiu Do v1.5.5 and v1.6.1 hit the issue as well?

**Comment by ejweber** [comment]
> @yangchiu Do v1.5.5 and v1.6.1 hit the issue as well?

Please let me know if you are able to run a similar repeat test and hit the issue on a different version.

For now I don't quite understand how the test normally passes.

We disable `dataLocality` while we have 1 running replica and 1 failed to schedule local replica. Then we set the `numberOfReplicas = 2`.

```
        assert v4_node1_replica_count + v4_node2_replica_count == 1
        assert v4_failed_replica_count == 1
    
        volume4 = volume4.updateDataLocality(dataLocality="disabled")
        volume4 = volume4.updateReplicaCount(replicaCount=2)
```

Since `dataLocality == disabled`, we have to count the failed to schedule local replica as usable, meaning we have two "usable" replicas and return `getReplenishCount == 0`. So we can't create a new replica and we can't schedule the one we have, leading to the failure. Maybe we are normally saved by a race somehow?

https://github.com/longhorn/longhorn-manager/blob/f7e2d5363978081477cfa6ee46436c0244a1482a/controller/volume_controller.go#L2610-L2613

I will monitor the behavior when the test passes and see if I can understand what I am missing.

**Comment by yangchiu** [comment]
Currently I can't find the same error on other branches from the daily regression history. I only observed it once from recent master branch daily regression: https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/907/testReport/tests/test_scheduling/test_data_locality_basic/ and reproduced it once after 500 repeatedly runs: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6815/.

It could be extremely difficult to reproduce ...

**Comment by ejweber** [comment]
Thank you for the clarification! It looks like we normally delete the failed to schedule replica in https://github.com/longhorn/longhorn-manager/blob/f7e2d5363978081477cfa6ee46436c0244a1482a/controller/volume_controller.go#L1032-L1047 and get unstuck. In your test case, we didn't. I will investigate more.

**Comment by ejweber** [comment]
## Root cause

I have no particular reason to believe this is a regression, though it is possible recent changes made it more likely to occur.

At the moment preceding the failure, the volume has:

- One healthy replica on the "wrong" node.
- One local replica that failed to schedule (because the "right" node is disabled).
- `spec.numberOfReplicas = 1`

The test does the following two operations in quick successtion:

```
volume4 = volume4.updateDataLocality(dataLocality="disabled")
volume4 = volume4.updateReplicaCount(replicaCount=2)
```

In the following reproduce scenarios, we find that either operation, if completed first, results in the desired behavior.

DataLocality first:

- The volume is already healthy, because it has one healthy replica.
- The (now) extra local replica is cleaned up in [cleanupFailedToScheduleReplicas](https://github.com/longhorn/longhorn-manager/blob/f7e2d5363978081477cfa6ee46436c0244a1482a/controller/volume_controller.go#L1031-L1050).
- When ReplicaCount is scaled up, a new one is replenished.

ReplicaCount first:

- An extra replica is needed, because the local replica that failed to schedule [doesn't count](https://github.com/longhorn/longhorn-manager/blob/f7e2d5363978081477cfa6ee46436c0244a1482a/controller/volume_controller.go#L2609-L2613) while `DataLocality == best-effort`.
- Another replica is created.
- When DataLocality is disabled, the local replica is deleted.

If both fields are updated simultaneously, we cannot handle it correctly.

- The local replica cannot be deleted because there aren't enough healthy replicas (1 < 2).
- A new replica can't be replenished, because the local replica is only ignored when checking if replenishment is necessary if DataLocality is enabled.

Almost every time we run the test, the volume controller reconciles between the `DataLocality` update and the `NumberOfReplicas` update. However, this is not guaranteed. If it is busy, it may only reconcile after both changes have been made.

## Reproduce

- Create a volume with `NumberOfReplicas == `` and `DataLocality == best-effort` on a three node cluster.
- Disable scheduling on a node.
- Attach the volume to the disabled node.
- Wait for the volume to have one healthy replica and one failed to schedule local replica.
- In a single `kubectl edit` change `NumberOfReplicas = 2` and `DataLocality = disabled`.
- Observe that the failed to schedule local replica is never deleted and a new replica is never created.

![image](https://github.com/longhorn/longhorn/assets/24213029/a021f4ff-2c70-45ab-821f-0b9c5521ad9a)

**Comment by ejweber** [comment]
I prefer to backport this to `v1.6.3` instead of `v1.6.2`. The impact is very minor and it is very unlikely to be triggered in the wild. Better to give the fix time to soak in the end-to-end pipeline then to risk a short test cycle before the `v1.6.2` release.

**Comment by derekbit** [comment]
> I prefer to backport this to `v1.6.3` instead of `v1.6.2`. The impact is very minor and it is very unlikely to be triggered in the wild. Better to give the fix time to soak in the end-to-end pipeline then to risk a short test cycle before the `v1.6.2` release.

@ejweber Sure! Let's put it in v1.6.3. Thank you.

**Comment by roger-ryao** [comment]
**Verified on master-head 20240528**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/cd4d7235de3547e74ef6aeb71c6ba2c97ac8a9ba
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/aebb5a8a1c5d5b9463c0c39b7ad4ae0766795477

**The test steps**
https://github.com/longhorn/longhorn/issues/8522#issuecomment-2105011487


**Result Passed**

- [x] 1. manual : Repeat the steps in the comment at https://github.com/longhorn/longhorn/issues/8608#issuecomment-2123765968. After executing `kubectl edit` on the volume, change  `numberOfReplicas: 2` and `dataLocality: disabled`. The failed local replica was deleted, and a new replica was subsequently created.

- [x] 2. regression : Execute the failed test case 200 times. We didn't observer the issue in the regression test runs https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6974/ & https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6968/.
