### ISSUE TITLE
Update Replicas Count not working when decrease number of replicas.

### ISSUE THREAD

**Issue by shinebayar-g** [longhorn/longhorn#867]
I installed longhorn using default options. However after reading [wiki](https://github.com/longhorn/longhorn/wiki/Settings#default-replica-count), I decided to change default number of replicas to 2. I found 2 issues while operating.

1. When I update values (Default Replica Count 3 to 2) using rancher catalog UI it didn't change settings in Longhorn. I checked this by entering Longhorn UI -> Settings -> General and noticed **Default Replica Count** was still 3.

2. I created volume with 3 replica, then I change number of replica for this volume from Longhorn UI -> Volume -> Select appropriate volume -> Update replicas count 3 to 2. But it didn't take effect. However increasing number of replica count works as expected.

Longhorn latest release 0.6.2

**Comment by yasker** [comment]
@shinebayar-g 

1. The catalog UI provides the default setting before installing Longhorn. After Longhorn is installed, you would need to use `Longhorn UI-> Setting` to change the default replica count. And if you're using the StorageClass (mostly likely), you need to change the default replica count in the StorageClass as well since that would be the one applied to the volume created by the StorageClass.

2. We do not automatically remove the replicas currently since it contains valid user data. You can choose and remove replica manually. See https://github.com/longhorn/longhorn/blob/f35e7ac323e4fa85e477d6b0f8a81b0c4a3a8854/docs/volume.md#changing-replica-count-of-the-volumes for details.

**Comment by shinebayar-g** [comment]
I see. Thanks for explanation.
