### ISSUE TITLE
Updating replica count to 1, still creating 3

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#894]
![image](https://user-images.githubusercontent.com/28725423/69004235-ddc9b580-08dd-11ea-81d4-cad4c381729f.png)

![image](https://user-images.githubusercontent.com/28725423/69004240-fcc84780-08dd-11ea-8076-42ed1ff8d08c.png)

**Comment by shuo-wu** [comment]
I guess this volume is created by [the StorageClass](https://github.com/longhorn/longhorn/blob/67698435d07b33f192c1768322ed634338cc9d6f/deploy/longhorn.yaml#L423). 
Right now this `Default Replica Count` setting only works for the volumes created via Longhorn UI.

**Comment by ainiml** [comment]
> I guess this volume is created by [the StorageClass](https://github.com/longhorn/longhorn/blob/67698435d07b33f192c1768322ed634338cc9d6f/deploy/longhorn.yaml#L423).
> Right now this `Default Replica Count` setting only works for the volumes created via Longhorn UI.

Should there be a difference between volumes created by storage class versus from the UI? 

Wondering about the use case where they are different

**Comment by yasker** [comment]
Different storage classes can have different numbers of replicas.

For example, for workloads that can scale horizontally, they might not need the HA feature provided by Longhorn. But snapshot/backup and data mobility features would still be useful. They can set the replica count to 1 (since they can replicate by themselves) and still take advantage of other features of Longhorn. Those would require a different number of replicas than the others.
