### ISSUE TITLE
[UI][IMPROVEMENT] Display `ReUploadedDataSize` and `NewlyUploadedDataSize` of each backup on Backup page

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8975]
## Describe the bug

To clearly display the backup information to users, we can
1. Display `ReUploadedDataSize` and `NewlyUploadedDataSize` of each backup

**Comment by derekbit** [comment]
cc @ChanYiLin @innobead

**Comment by derekbit** [comment]
Hello @houhoucoop 
Need to complete the `Pre Ready-For-Testing Checklist` and then move to `Ready For Testing`. QA will verify the ticket and close it.

**Comment by innobead** [comment]
It is also advisable to include a short video or at least a screenshot for any UI changes, so QA can quickly understand the behavior of the changes. @houhoucoop @a110605

**Comment by yangchiu** [comment]
Verified on master-head (longhorn-ui 5113aa2). However, the `ReUploadedDataSize` and `NewlyUploadedDataSize` are displayed on `Backup` page instead of `Volume` page as indicated in the issue title. @derekbit Could you please confirm if it's what you intended? Thank you!

![backup](https://github.com/user-attachments/assets/caa953e7-1843-4345-8e88-85a1cb22f091)

**Comment by derekbit** [comment]
I think yes. WDYT? @ChanYiLin

**Comment by ChanYiLin** [comment]
Hi @yangchiu 
As discussed with @derekbit 
Yes it is correct to display this info in backup page
The title is incorrect.
I will correct the title and we can close the issue
