### ISSUE TITLE
Logs display "RegisterPlugin error" while deployed on k3s

### ISSUE THREAD

**Issue by ShylajaDevadiga** [longhorn/longhorn#899]
Version:
Longhorn version v0.7.0
k3s version v1.0.0-rc5

Issue:
Logs display ```Nov 18 19:16:40 ip-172-31-2-48 k3s[2203]: E1118 19:16:40.199202    2203 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock" failed. No retries permitted until 2019-11-18 19:18:42.19917879 +0000 UTC m=+9725.332346661 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"```

Steps to reproduce:
Install k3s v1.0.0-rc5, 3 node cluster
Deploy longhorn v0.7.0
Check the system logs.

**Comment by shuo-wu** [comment]
In one word, this is [a harmless Kubernetes bug](https://github.com/kubernetes/kubernetes/issues/70485#issuecomment-434711753). 
This `GetInfo` RPC call is used by the Kubelet to register the plugins. And actually the CSI node registrar has already implemented this plugin registration parts for all CSI plugins, see [here](https://github.com/kubernetes-csi/node-driver-registrar/blob/6ef000ae529ad4c8e2928f0803d65ac25f3f9fcf/cmd/csi-node-driver-registrar/main.go#L76) for details.

The solution for this issue:
Since the host directory `/var/lib/kubelet/plugins/` is watched by the Kubernetes plugin-manger for plugin changes. Avoid putting the Longhorn CSI socket directory in this folder can fix this issue.

**Comment by shuo-wu** [comment]
Reproduce steps:
1. Launch **a brand new** Kubernetes cluster with version  v1.15+
2. Deploy Longhorn `v0.7.0`/`master`
3. Check the kubelet logs on hosts:
- For Longhorn `v0.7.0`, kubelet will constantly display the error logs like
```
E0106 23:40:42.891103   26464 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock" failed. No retries permitted until 2020-01-06 23:42:44.891082033 +0000 UTC m=+412.027533768 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```
- For Longhorn `master`, no above logs.

**Comment by meldafrawi** [comment]
Validation: **PASSED**
