### ISSUE TITLE
[DOC] https://longhorn.io/docs/1.6.2/references/settings/#replica-node-level-soft-anti-affinity

### ISSUE THREAD

**Issue by hchyue** [longhorn/longhorn#9003]
## What's the document you plan to update? Why? Please describe
![image](https://github.com/user-attachments/assets/0f01f912-affe-49a0-b522-a17fd7e466db)

## Additional context
I think the meaning is just the opposite, "Anti-" should be removed

**Comment by derekbit** [comment]
@c3y1huang @shuo-wu @PhanLe1010 @innobead  Any thoughts?

**Comment by ejweber** [comment]
I can understand the confusion, but I disagree.

Longhorn scheduling only has the concept of ANTI affinity. Under no circumstance will we TRY to schedule replicas to the same zone, node, or disk as a related replicas. Instead, we always try to distribute replicas across valid zones, nodes, and disks.

The operative word here is SOFT, where the alternative is HARD. We use SOFT similar to the way the Kubernetes docs. For example:

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity
```
This example defines one Pod affinity rule and one Pod anti-affinity rule. The Pod affinity rule uses the "hard" requiredDuringSchedulingIgnoredDuringExecution, while the anti-affinity rule uses the "soft" preferredDuringSchedulingIgnoredDuringExecution.
```

When SOFT anti-affinity is enabled, Longhorn TRIES to keep replicas away from each other (similar to Kubernetes `preferredDuringScheduling...`, but it will put two replicas in the same zone, node, or disk if it doesn't have a choice. When SOFT anti-affinity is disabled, Longhorn REFUSES to put two replicas in the same zone, node, or disk (similar to Kubernetes `requiredDuringScheduling`).

So I think we do not need to remove ANTI from these settings (especially since they are already used for their intended purpose in many clusters). However, we may be able to improve the descriptions to emphasize that enabling soft anti-affinity is loosening restrictions on replica scheduling as an alternative to the hard anti-affinity Longhorn would otherwise use.

WDYT?

**Comment by hchyue** [comment]
@ejweber  thankyou , I'm not confused now .
