### ISSUE TITLE
[BUG] Replica deletion fails at the end of longhorn-spdk-engine unit test

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#9121]
## Describe the bug

Sometimes, at the cleanup stage of the unit test, we will encounter several kinds of errors:

#### Case 1:
Somehow the shallow copy reports error `Invalid argument`:
```
time="2024-08-01T20:57:42Z" level=error msg="failed to delete lvol test-disk/test-vol-0-replica-3-snap-rebuild-e46b0d77(5cea03c1-05a6-4a10-8187-0f7d916ae5bf) from the lvol tree with root test-disk/test-vol-0-replica-3-snap-snap11(f08fbd07-826c-4ae6-b639-9b1c700328ce), this lvol may accidentally have some leftover orphans chidlren [], will continue" error="error sending message, id 83965, method bdev_lvol_delete, params {5cea03c1-05a6-4a10-8187-0f7d916ae5bf}: {\"code\": -32603,\"message\": \"Invalid argument\"}" lvsName=test-disk lvsUUID=0a5ba14d-38c9-4b96-a1c1-697c2ba78db5 replicaName=test-vol-0-replica-3
```
`spdk_tgt` error logs:
```
[2024-08-01 20:51:59.769830] vbdev_lvol_rpc.c:1583:rpc_bdev_lvol_start_shallow_copy: *INFO*: Shallow copying lvol
[2024-08-01 20:51:59.773393] blobstore.c:7274:bs_shallow_copy_blob_read_cpl: *ERROR*: blob 0x100000002 shallow copy, blob read error -22
[2024-08-01 20:51:59.773447] lvol.c:2528:lvol_shallow_copy_cb: *ERROR*: Could not make a shallow copy of lvol 5cea03c1-05a6-4a10-8187-0f7d916ae5bf, error -22
[2024-08-01 20:51:59.773455] vbdev_lvol.c:2008:_vbdev_lvol_shallow_copy_cb: *ERROR*: Could not make a shallow copy of lvol test-vol-0-replica-3-snap-rebuild-e46b0d77 due to error: -22
```

The only place to invoke `bs_shallow_copy_blob_read_cpl` is [blob_request_submit_op_single](https://github.com/longhorn/spdk/blob/c7483b0e06b5c3bbf61d5d03dc6a8394c91c5776/lib/blob/blobstore.c#L7306-L7309). Inside this function, [the regular SPDK_BLOB_READ ](https://github.com/longhorn/spdk/blob/c7483b0e06b5c3bbf61d5d03dc6a8394c91c5776/lib/blob/blobstore.c#L3142-L3160)during shallow copy won't lead to `EINVAL` error, the only possible place is [this](https://github.com/longhorn/spdk/blob/c7483b0e06b5c3bbf61d5d03dc6a8394c91c5776/lib/blob/blobstore.c#L3120).

#### Case 2:
Somehow the lvol deletion reports error `Invalid argument`:
```
time="2024-08-01T20:57:42Z" level=error msg="failed to delete lvol test-disk/test-vol-0-replica-3-snap-rebuild-e46b0d77(5cea03c1-05a6-4a10-8187-0f7d916ae5bf) from the lvol tree with root test-disk/test-vol-0-replica-3-snap-snap11(f08fbd07-826c-4ae6-b639-9b1c700328ce), this lvol may accidentally have some leftover orphans chidlren [], will continue" error="error sending message, id 83965, method bdev_lvol_delete, params {5cea03c1-05a6-4a10-8187-0f7d916ae5bf}: {\"code\": -32603,\"message\": \"Invalid argument\"}" lvsName=test-disk lvsUUID=0a5ba14d-38c9-4b96-a1c1-697c2ba78db5 replicaName=test-vol-0-replica-3
```
The corresponding `spdk_tgt` error logs may be:
```
[2024-08-01 20:57:50.331261] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2b40fb0
[2024-08-01 20:57:50.331271] lvol.c:1046:lvol_close_blob_cb: *INFO*: Lvol 45aba068-ea0b-4ef9-a967-b9e66f8a289c closed
[2024-08-01 20:57:50.331389] lvol.c:1073:lvol_delete_blob_cb: *INFO*: Lvol 45aba068-ea0b-4ef9-a967-b9e66f8a289c deleted
[2024-08-01 20:57:50.431332] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2b40fb0
[2024-08-01 20:57:50.431343] vbdev_lvol.c: 775:vbdev_lvol_dump_info_json: *ERROR*: Cannot obtain clone name
[2024-08-01 20:57:50.431375] vbdev_lvol.c: 775:vbdev_lvol_dump_info_json: *ERROR*: Cannot obtain clone name
[2024-08-01 20:57:50.431388] vbdev_lvol.c: 483:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x2b40fb0
```

#### Case 3:
The previous child snapshot deletion failures lead to the parent snapshot lvol containing multiple children. Then directly deleting this kind of parent snapshot lvol would trigger error `Operation not permitted`:
```
time="2024-08-01T20:57:42Z" level=error msg="failed to delete lvol test-disk/test-vol-0-replica-3-snap-snap11(f08fbd07-826c-4ae6-b639-9b1c700328ce) from the lvol tree with root test-disk/test-vol-0-replica-3-snap-snap11(f08fbd07-826c-4ae6-b639-9b1c700328ce), this lvol may accidentally have some leftover orphans chidlren [test-vol-0-replica-3-snap-snap13 test-vol-0-replica-3-snap-snap32 test-vol-0-replica-3-snap-snap41], will continue" error="error sending message, id 83981, method bdev_lvol_delete, params {f08fbd07-826c-4ae6-b639-9b1c700328ce}: {\"code\": -32603,\"message\": \"Operation not permitted\"}" lvsName=test-disk lvsUUID=0a5ba14d-38c9-4b96-a1c1-697c2ba78db5 replicaName=test-vol-0-replica-3
```

## To Reproduce

Running unit test ci has a chance of triggering it. For example https://github.com/longhorn/longhorn-spdk-engine/actions/runs/10088048671/job/27893576381

## Expected behavior

There should not be any error.

## Environment

 - Longhorn version:  v1.7.0-rc2

**Comment by innobead** [comment]
cc @DamiaSan

**Comment by chriscchien** [comment]
When testing https://github.com/longhorn/longhorn/issues/9190, there had a change to hit a issue that 1 replica remained in running but the other 2 replicas kept in rebuilding/fail loop, in instance manager log can see `Invalid argument` log like this ticket mentioned

```log
[longhorn-instance-manager] time="2024-08-15T08:02:43Z" level=error msg="Engine failed to do the shallow copy for replica e2e-test-volume-0-r-70847652 add" func="spdk.(*Engine).ReplicaAdd.func3.1" file="engine.go:973" endpoint=/dev/longhorn/e2e-test-volume-0 engineName=e2e-test-volume-0-e-0 error="rebuilding error during shallow copy for snapshot rebuild-8cf72c21: Invalid argument" frontend=spdk-tcp-blockdev ip=10.42.6.16 port=20006 replicaAddressMap="map[e2e-test-volume-0-r-491dba6e:10.42.6.16:20001 e2e-test-volume-0-r-70847652:10.42.5.14:20011]" volumeName=e2e-test-volume-0
[longhorn-instance-manager] time="2024-08-15T08:03:33Z" level=error msg="Engine failed to do shallow copy from src replica e2e-test-volume-0-r-491dba6e to dst replica e2e-test-volume-0-r-94ef43de, will mark the rebuilding replica mode from ERR to ERR" func="spdk.(*Engine).replicaShallowCopy.func2" file="engine.go:1089" endpoint=/dev/longhorn/e2e-test-volume-0 engineName=e2e-test-volume-0-e-0 error="rebuilding error during shallow copy for snapshot rebuild-f1d82f18: Invalid argument" frontend=spdk-tcp-blockdev ip=10.42.6.16 port=20006 replicaAddressMap="map[e2e-test-volume-0-r-491dba6e:10.42.6.16:20001 e2e-test-volume-0-r-94ef43de:10.42.4.16:20001]" volumeName=e2e-test-volume-0
[longhorn-instance-manager] time="2024-08-15T08:03:33Z" level=error msg="Engine failed to do the shallow copy for replica e2e-test-volume-0-r-94ef43de add" func="spdk.(*Engine).ReplicaAdd.func3.1" file="engine.go:973" endpoint=/dev/longhorn/e2e-test-volume-0 engineName=e2e-test-volume-0-e-0 error="rebuilding error during shallow copy for snapshot rebuild-f1d82f18: Invalid argument" frontend=spdk-tcp-blockdev ip=10.42.6.16 port=20006 replicaAddressMap="map[e2e-test-volume-0-r-491dba6e:10.42.6.16:20001 e2e-test-volume-0-r-94ef43de:10.42.4.16:20001]" volumeName=e2e-test-volume-0
[longhorn-instance-manager] time="2024-08-15T08:03:50Z" level=error msg="Failed to delete lvol block-disk/e2e-test-volume-0-r-491dba6e-snap-rebuild-f1d82f18(ce8f129a-44d4-4b35-8df4-b56000ad1cb8) from the lvol tree with root block-disk/e2e-test-volume-0-r-491dba6e-snap-rebuild-f1d82f18(ce8f129a-44d4-4b35-8df4-b56000ad1cb8), this lvol may accidentally have some leftover orphans children [e2e-test-volume-0-r-491dba6e-snap-rebuild-285a343c], will continue" func=spdk.CleanupLvolTree file="util.go:132" error="error sending message, id 83351, method bdev_lvol_delete, params {ce8f129a-44d4-4b35-8df4-b56000ad1cb8}: {\"code\": -32603,\"message\": \"Invalid argument\"}" lvsName=block-disk lvsUUID=2313b442-64ef-48f4-bbea-8dfd4a401a57 replicaName=e2e-test-volume-0-r-491dba6e
```

Environment
- volume name: e2e-test-volume-0
- instance manager name: instance-manager-58b1505bda36b86ef0f3a721b1c5071c
[supportbundle_35a626c0-0618-4d1a-8582-64c478b1d9b7_2024-08-15T07-46-21Z.zip](https://github.com/user-attachments/files/16623124/supportbundle_35a626c0-0618-4d1a-8582-64c478b1d9b7_2024-08-15T07-46-21Z.zip)

cc @derekbit @shuo-wu @DamiaSan @innobead

**Comment by derekbit** [comment]
Thanks @chriscchien. It is a known issue. Let's fix it in v1.8.0.

**Comment by DamiaSan** [comment]
Hi @shuo-wu , after a couple of days of investigation maybe I have found something to start from.
Looking at the SPDK logs I saw many `bdev_lvol_get_xattr` errors of lvol not found. So I disabled the `monitoring` go routine that could lead to this kind of error, because it calls  `BdevLvolGet` with empty `name` parameter which perform the following operations:

- get a list of all bdevs
- for each bdev, try to get some xattrs

So, if the list is quite long, it can happen that before to reach a bdev to retrieve its xattrs, this bdev is deleted by the functions under unit test.
But, unexpectedly, also after having disabled the `monitoring`, these kind of errors continued to happen. Let me make an example, I have enabled all RPC that arrive to SPDK
```
[2024-08-20 17:07:19.849603] request: {	"id": 4870,	"jsonrpc": "2.0",	"method": "bdev_get_bdevs",	"params": null}

[2024-08-20 17:07:20.319063] request: {	"id": 4916,	"jsonrpc": "2.0",	"method": "bdev_lvol_delete",	"params": {		"name": "test-disk/test-vol-3-replica-1-snap-snap12"	}}

[2024-08-20 17:07:20.993002] request: {	"id": 4984,	"jsonrpc": "2.0",	"method": "bdev_lvol_get_xattr",	"params": {		"name": "test-disk/test-vol-3-replica-1-snap-snap12",		"xattr_name": "user_created"	}}
[2024-08-20 17:07:20.997007] response: {"jsonrpc":"2.0","id":4984,"error":{"code":-19,"message":"No such device"}}
```
The `bdev_get_bdevs` request is executed at the beginning of `BdevLvolGet` and `bdev_lvol_get_xattr` is executed after in the same `BdevLvolGet`, but the lvol `test-disk/test-vol-3-replica-1-snap-snap12` that was present when we got the list, was deleted before to get xattrs for it. I put a breakpoint in `longhorn-spdk-engine` when the `bdev_lvol_get_xattr` get an error and from the stack trace I see that `BdevLvolGet` was called by `GetBdevLvolMap`, which was called by `SnapshotRevert`.
So, in some way, we have someone that is deleting a lvol during a snapshot revert operation. Maybe the error that the test sometimes get in lvol deletion or shallow copy can be dut to a similar race condition, i.e. some other operations are made on the same lvol which can lead to errors.

**Comment by DamiaSan** [comment]
Other considerations.

**Case 1**
The chain of function calls is the following: `blob_request_submit_op_single` -> `bs_batch_read_dev` -> `bdev_blob_read` -> `spdk_bdev_read_blocks` -> `bdev_read_blocks_with_md`. This last functions, if the blocks to be read are not valid, return `EINVAL` like in our case. `bdev_blob_read`, in case of `rc != 0`, calls the callback `bs_batch_completion` which set batch's errno.

**Case 2**
The log you posted are not related to a lvol deletion error, because if the following log is present
```
[2024-08-01 20:57:50.331389] lvol.c:1073:lvol_delete_blob_cb: *INFO*: Lvol 45aba068-ea0b-4ef9-a967-b9e66f8a289c deleted
```
then the deletion has been correctly executed and the reply to the caller is without error. But the subsequent log
```
[2024-08-01 20:57:50.431343] vbdev_lvol.c: 775:vbdev_lvol_dump_info_json: *ERROR*: Cannot obtain clone name
```
means that something as I described in the comment above has happened in `vbdev_lvol_dump_info_json`:

- `spdk_blob_get_clones` returns a list of `blob_id` of the clones of the snapshot
- `vbdev_lvol_find_name` can't find the lvol relative of one of the `blob_id` returned by the function above

So, in the meanwhile, it is possible that this clone has been deleted.

**Comment by shuo-wu** [comment]
For case 1, currently, I have no idea which blob can suddenly become invalid during the shallow copy. I don't think we allow any kind of dangerous deletion operation when the shallow copy is in progress. The only exception may be that the related replica is somehow crashed. On the other hand, during the shallow copy, is there a lock to protect the pending blob?

For case 2, YES the successfully deleted lvol `45aba068-ea0b-4ef9-a967-b9e66f8a289c` is not the problematic lvol `5cea03c1-05a6-4a10-8187-0f7d916ae5bf`. Do you mean that somehow one clone is already disappeared when we try to delete `5cea03c1-05a6-4a10-8187-0f7d916ae5bf`? In this case, should SPDK fail the deletion call?

**Comment by DamiaSan** [comment]
**Case 1**
Shallow copy has a lock shared with other operations like set_parent, resize, delete, snapshot create, clone create, ... so that only one of these operations can happen at one time on a blob. But looking at what is done when a `bdev_lvol_delete` is received, before to delete the blob, SPDK perform a bdev unregister operation, which abort all queued and ongoing ios. So, if during a shallow copy, we try to delete the source lvol, the shallow copy will abort with error. 
And from the analyses I made  with the report above, it seems that in some way there are lvol deletions that happen during other operations. Don't know how it can happen but I think this is the direction we should investigate. Could it be an issue of the unit test only?

**Case 2**
The `vbdev_lvol_dump_info_json` function is called byt the RPC `bdev_get_bdevs` and it seems that during the execution of this function a clone is deleted, something similar to what happen in `BdevLvolGet` of  `longhorn-spdk-engine`: there is a function that first retrieves a list of lvols and after, inside a loop over this list, one of this lvol has been deleted.

**Comment by shuo-wu** [comment]
### Case 2 Pre Ready-For-Testing Checklist:

- [x] Fix PRs:
https://github.com/longhorn/go-spdk-helper/pull/151
https://github.com/longhorn/longhorn-spdk-engine/pull/229

- [x] Manual test:
    **Test 1:** 
        1. Pull `longhorn-spdk-engine` repo PR https://github.com/longhorn/longhorn-spdk-engine/pull/229
        2. Run `make`
        3. During the unit test, exec into the docker container and monitor the spdk_tgt log `docker exec -it <container id> tail -f /var/log/spdk_tgt.log`. Verify there is no log like `vbdev_lvol.c: 775:vbdev_lvol_dump_info_json: *ERROR*: Cannot obtain clone name`
    **Test 2**:
    1. Deploy a complete Longhorn containing this PR
    2. Launch and attach lots of v2 volumes, and create snapshots for these volumes
    3. Monitor the spdk_tgt log in instance manager pods `kubectl -n longhorn-system exec -it <IM pod name> -- tail -f /var/log/spdk_tgt.log`
    4. Delete all volumes simultaneously
    5. Verify there is no log like `vbdev_lvol.c: 775:vbdev_lvol_dump_info_json: *ERROR*: Cannot obtain clone name`
    
    Both tests can be executed multiple times

**Comment by shuo-wu** [comment]
We plan to track case 1 at https://github.com/longhorn/longhorn/issues/9705.
And let's wrap up case 2 here.

**Comment by chriscchien** [comment]
Hi @shuo-wu 

When I run `make`  from longhorn-spdk-engine master, it will fail with below messages
```bash
Successfully built 16a2e90d8551
Successfully tagged longhorn-spdk-engine:main
# github.com/longhorn/longhorn-spdk-engine/pkg/spdk
pkg/spdk/engine.go:1815:46: e.ReplicaAddressMap undefined (type *Engine has no field or method ReplicaAddressMap)
pkg/spdk/engine.go:1816:9: e.ReplicaModeMap undefined (type *Engine has no field or method ReplicaModeMap)
FATA[0432] exit status 1                  
> 
```

I already have set the v2 data engine env and environment check script passed on the build machine, could you take a look on this? thank you.

**Comment by chriscchien** [comment]
> Hi [@shuo-wu](https://github.com/shuo-wu)
> 
> When I run `make` from longhorn-spdk-engine master, it will fail with below messages
> 
> Successfully built 16a2e90d8551
> Successfully tagged longhorn-spdk-engine:main
>> github.com/longhorn/longhorn-spdk-engine/pkg/spdk
> pkg/spdk/engine.go:1815:46: e.ReplicaAddressMap undefined (type *Engine has no field or method ReplicaAddressMap)
> pkg/spdk/engine.go:1816:9: e.ReplicaModeMap undefined (type *Engine has no field or method ReplicaModeMap)
> FATA[0432] exit status 1                  
> > 
> I already have set the v2 data engine env and environment check script passed on the build machine, could you take a look on this? thank you.

Need to wait https://github.com/longhorn/longhorn/issues/9761 be resloved first

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev-20241117 (longhorn-spdk-engine `cfd1f1`) 

Perform [steps of test 2](https://github.com/longhorn/longhorn/issues/9121#issuecomment-2399516583) several times, did not see `*ERROR*: Cannot obtain clone name`  log appeared in v2 volume instance-manager-pod
