### ISSUE TITLE
[BUG] should set backing image minNumberOfCopies to 1 when upgrading Longhorn

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#9352]
## Describe the bug

When upgrading Longhorn to v1.7.x
The BackingImage will have `minNumberOfCopies = 0`
Need to set the default value in upgrade path. 

There is no impact if the minNumberOfCopies is 0
- when clean up unused backingimage, we set the minNumberOfCopies to 1 if it is 0
https://github.com/longhorn/longhorn-manager/blob/master/controller/node_controller.go#L1403
- when replenish backing image, there is no way `nonEvictingCount < bi.Spec.MinNumberOfCopies`, so it won't replenish backing image if `MinNumberOfCopies = 0`. Thus it is the same behavior as `MinNumberOfCopies=1`
https://github.com/longhorn/longhorn-manager/blob/master/controller/backing_image_controller.go#L364

## To Reproduce

.

## Expected behavior

.

## Support bundle for troubleshooting
.

## Environment
.

## Additional context
Thanks to @WebberHuang1118 's report
cc @WebberHuang1118 

## Workaround and Mitigation

.

**Comment by chriscchien** [comment]
Verified **pass** on longhorn v1.8.0-dev-20240908(https://github.com/longhorn/longhorn-manager/commit/68a4591905469a5e2c1087c2ba60e60fcfae70b1)

Tested in below steps because it is not allowed to upgrade from v1.6.3 to v1.8.0-dev:
- Create backingimage with `minNumberOfCopies` to `0` and `3` in v1.7.1 then upgrade to v1.8.0-dev-20240908, after upgrade complete `minNumberOfCopies` not hanged.
