### ISSUE TITLE
Change tags of PV afterwards (e.g. after restoring from backup)

### ISSUE THREAD

**Issue by cr0** [longhorn/longhorn#939]
Hi,
when restoring a PV from backup, there is no option to add node or disk tags to that volume.
For existing PVs, one can update the replica count, but it is not possible to alter the volume's tags. Hence, tags seem to be lost for ever after backup.
Do I miss something?

**Comment by yasker** [comment]
Thanks for reporting @cr0 . The restoration menu from backup should have the same option as create volume, including a way to specify node and disk tag. We will fix that.

Currently, node and disk tags are not changeable, since it affects how replicas of the volume were scheduled in the first place.

**Comment by meldafrawi** [comment]
Validation: **PASS**

Longhorn UI version: `wangsiye/longhorn-ui:17c8c9a`

Steps to test:
  - In Node page, add `Node Tags`  and `Disk tags`
  - Create a volume, attach it to a node.
  - Create a backup.
  - Restore volume backup, and specify Node tags/Disk tags and click `OK`
  > Ensure replicas are created based on Node tags/Disk tags specified.  **(PASS)**
