### ISSUE TITLE
[TASK] Verify Longhorn on Kubernetes v1.31 

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#9676]
## What's the task? Please describe

Start a e2e/regression test on v1.31 to check if Longhorn work works without issues. 

Ref: https://github.com/rancher/rancher/issues/46853

**Comment by derekbit** [comment]
@roger-ryao Let's finish it and update the results before Oct 24. Thank you.

cc @longhorn/qa  @khushboo-rancher @PhanLe1010 @innobead

**Comment by PhanLe1010** [comment]
From the code perspective, there is no deprecated/removed API in K8s v1.31 or 1.32 that Longhorn uses. 
So we should be good if QA verification passes. Ref https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**Comment by PhanLe1010** [comment]
Btw, could we test the support bundle downloading as part of the test? Support bundle usually touch many API resources and has higher chance of failure if some API is broken

**Comment by Nemric** [comment]
My 2 cents : 
I'm using Longhorn with Kubernetes v1.31.1 and it works fine with default argocd/helm install
I did the update from v1.7.1 to 1.7.2 without any errors
My use of Longhorn is very basic for now, 1 volume, 3 nodes, 1 nfs backup

**Comment by roger-ryao** [comment]
The test result for `v1.31.1+rke2r1`.
**master-head** : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7685/ : 1 failure
**v1.7.2** : https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-amd64/103/ : 3 failures
**v1.6.3** : https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-amd64/278/ : 1 failure

The test result for `v1.31.1+k3s1`.
**master-head** : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7684/ : 1 failure
**v1.7.2** : https://ci.longhorn.io/job/public/job/v1.7.x/job/v1.7.x-longhorn-tests-sles-arm64/104/ : 0 failure
**v1.6.3** : https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-tests-sles-arm64/273/ : 1 failure

**The test result failed due to a flaky test case without any outstanding issues.**
