### ISSUE TITLE
PVC Path and Host Mount Point 

### ISSUE THREAD

**Issue by WoodProgrammer** [longhorn/longhorn#970]
Hi all,

PVC volume name and rancher path is not same and clear when I check the related path on the `/var/lib/rancher/longhorn/` path and there is no directory with same shown name on the screen  end of the that , I have find hover on the UI and find the real path with different name with pvc . 

![Screen Shot 2019-12-18 at 6 01 17 PM](https://user-images.githubusercontent.com/16826090/71099849-0555bb80-21c5-11ea-9e08-48175bff88f4.png)

**Comment by shuo-wu** [comment]
1. PVC name is not the same as Longhorn volume name. When you create PVC/PV manually in Longhorn UI, you can name the PVC as your wish.
2. The directory used the replica (and the result of hovering on the UI) is like `<data path>/replicas/<replica name>/`. Here the data path is `/var/lib/rancher/longhorn`. If you had never attached that volume to any nodes, the corresponding directory won't be created. BTW, the path is the path of host node rather than that of any workload containers.

**Comment by janeczku** [comment]
@shuo-wu OP is expecting that when provisioning a PV using a PVC the corresponding Longhorn volume should inherit the name of the PVC. What do you think about that?

@WoodProgrammer Can you explain the benefit of having the file path on the worker nodes match the PVC name?

**Comment by WoodProgrammer** [comment]
@janeczku any downtime, I need the recover my disk space, so that if I have to know name-in convention of the path of the replica disk space and mount point of `dev` disk

**Comment by WoodProgrammer** [comment]
some disaster time I think we can use skillset of ISCSI just idea

**Comment by yasker** [comment]
@WoodProgrammer Since PVC is per namespace not per cluster, multiple namespaces might have the same-named PVC. That's one of the reasons Kubernetes doesn't provide PVC name to storage vendor. PV names are unique per cluster, so we can use it as the unique volume name across the whole cluster.

We do provide the associate PVC name to the volume through our UI and API.

**Comment by WoodProgrammer** [comment]
thank for your helping I understand UI design and lognhorn between PV and PVC on k8s site
