### ISSUE TITLE
Improve Failure Handling Documentation

### ISSUE THREAD

**Issue by pvtpogopuschel** [longhorn/longhorn#973]
Hey everbody!

The current description of Node Failure documentation ([this one](https://github.com/longhorn/longhorn/blob/master/docs/node-failure.md)) is somewhat limited or at least ambiguous according to my understanding right now.

It does explain how StatefulSets and Deployments and their volumes are affected during a node failure, but several details and needed actions to be taken are - if at all - only briefly covered in the node recovering chapter.

I would like to raise some questions that could be added to the documentation:
- The first chapter only refers to manual pod deletion. What happens if the pod eviction timeout is exceeded (regardless of the node coming back) and k8s deletes the pod automatically? Does it behave like a manual deletion, especially in regards of regular deployments without a stable identity? Are there manual steps involved if that happens?
- What is the background of the six minute time frame to delete the VolumeAttachment? Can this be shortened? The documentation in general refers a lot to a default k8s setup. It might be valuable to know what parameters/settings influence the mentioned timings.
- Does the node recovery within the first five to six minute time frame involve manual steps? Is longhorn handling this completely automatically?

Thank you very much!

**Comment by shuo-wu** [comment]
1. The pod eviction means that Kubernetes will set DeletionTimestamp for the pod when the timeout is exceeded. For the node-down case, the pod will get stuck in `Terminating` state and won't be forced deleting automatically. Users need to decide if they can/need to force deleting the pod.

2. In node-down case, Kubernetes will automatically evict the pod on the lost node then re-create a new one **with old volumes** for deployments. Because the old pod will get stuck in `Terminating` state and the attached Longhorn volumes cannot be released/reused, the new pod will get stuck in `ContainerCreating` state. --> If you want to make the new pod become `Running` state, you need to recover the node or force deleting the old pod (so that the old Longhorn volumes can be reused by the new pod).

3. It seems that the 6-minute time frame for the VolumeAttachment cleanup is actually hardcoded by [this parameter in Kubernetes](https://github.com/kubernetes/kubernetes/blob/5e31799701123c50025567b8534e1a62dbc0e9f6/pkg/controller/volume/attachdetach/attach_detach_controller.go#L95): If the pod on the lost node is forced delete, the volume won't be unmounted correctly hence Kubernetes will wait for this timeout then clean up the VolumeAttachment object.

4. In both the node recovery scenarios, Longhorn will handle those steps automatically with the association of Kubernetes. The doc for this part is to let users know what happens during the recovery.
