### ISSUE TITLE
Over 3000 volumes created, Longhorn unusable

### ISSUE THREAD

**Issue by phal0r** [longhorn/longhorn#976]
Due to an error using an operator, there were over 3000 volumes created in a 3-node cluster. All workloads are online, including Longhorn, but most of the volumes cannot be assigned due to scheduling limits being reached. But most of the volumes are already delete in Kubernetes (PVs and PVCs), but the volumes stay in Longhorn in stopped mode. New volumes cannot be assinged and the ui cannot handle this many volumes. What is the best way to delete the stopped volumes now?

Deleting a single volume by opening a deeplink to the volume detail page does not work either.

**Comment by yasker** [comment]
@phal0r The steps would a bit complex and probably needs more scripting. But here is the basic idea: we can find which volumes are not scheduled and doesn't contain any data, then delete them using the command line. One thing needs extra attention is: since if a volume was used once but later failed to schedule more replicas to replace the failed ones, it will failed scheduling but still contains data. We will not want to delete those.

(Below assuming you're using v0.7.0, otherwise, the CRD name would be `volumes.longhorn.rancher.io` instead of `volumes.longhorn.io`)

1. Figure out what volumes failed the scheduling, by using
```
`kubectl -n longhorn-system get volumes.longhorn.io -o custom-columns=NAME:.metadata.name,SCHED:status.conditions.scheduled.status
```
You should get a list like
```
NAME       SCHED
test       False
wp-mysql   True
wp-wp      True
```
The one with `False` in `SCHED` (e.g. test above) are failed scheduling. You can get a list of SCHED failed volume by pumping the result into `grep "False"|awk '{print $1}'`. But this is NOT the final list.

2. Use the following command to get the replicas with data or not
```
kubectl -n longhorn-system get replicas.longhorn.io -o custom-columns=NAME:.metadata.name,VOLUME:.spec.volumeName,HEALTHY:.spec.healthyAt
```
You will get 
```
NAME                  VOLUME     HEALTHY
test-r-08278029       test
test-r-b43df307       test
test-r-c2e73948       test
test2-r-2c3eeeb1      test2      2019-12-23T18:35:57Z
test2-r-b38863bb      test2
test2-r-c4bbc9d7      test2      2019-12-23T18:35:57Z
wp-mysql-r-49775c67   wp-mysql   2019-11-21T01:41:09Z
wp-mysql-r-5e85972a   wp-mysql   2019-11-21T01:41:10Z
wp-mysql-r-c2cf25a9   wp-mysql   2019-11-21T01:41:10Z
wp-wp-r-10af6315      wp-wp      2019-11-21T01:40:08Z
wp-wp-r-168a4154      wp-wp      2019-11-21T01:40:08Z
wp-wp-r-9af71264      wp-wp      2019-11-21T01:40:07Z
```
You can get the list of volumes contain data by pumping the result into `grep "T.*:.*:.*Z"|awk '{print $2}'|sort -u`. So those are the volumes CONTAINS data.

3. REMOVE any volume that shows up in both list from list 1. For example, list 1 is 
```
test
test2
```
list 2 is 
```
test2
wp-mysql
wp-wp
```
The final list should be
```
test
```

4. Run the following command to delete the volumes that not scheduled and has no data
```
kubectl -n longhorn-system delete volumes.longhorn.io <volume-name>
```

The last command should clean up the extra volumes.

Let me know if any step is unclear.

**Comment by phal0r** [comment]
Thanks for the fast response @yasker .

I will try it and report back.

**Comment by phal0r** [comment]
I couldn't complete this procedure and cannot report back if it worked, sorry. We recreated the cluster. Issue closed.
