### ISSUE TITLE
Ability to set tags via labels/annotations

### ISSUE THREAD

**Issue by msnelling** [longhorn/longhorn#991]
We use Terraform to spin-up/tear-down clusters in our vSphere environment, specifying the hardware configuration, disks etc, as code. It would a useful feature to be able to specify the node and disk tags through standard labels and annotation metadata to match the Terraform spec, rather than having to go into the UI and set the tags by hand.

**Comment by yasker** [comment]
Node management through Kubernetes API is one of the more common feature requests we've received. I think we need to come with some designs of user experience for this feature.

Previously we've implemented #583 and #582 to allow users to specify if they want to automatically add default disk and specify the location of the default disk.

We want to improve the user experience by providing the ability to handle nodes and disks in the command line, preferably using kubectl.

Node tag/schedulable should be straightforward since we can monitor and update the Kubernetes node annotations/labels. But how about the disk tag/path/schedulable? I don't have a good idea about it right now since Kubernetes doesn't have the concept of `disk`, but adding the information to the Kubernetes node as annotations/labels seem cumbersome.

**Comment by msnelling** [comment]
@yasker I agree that mapping the concept of disk onto annotations or labels isn't ideal, it was my initial, naive solution. Perhaps through CRD's?

**Comment by meldafrawi** [comment]
Validation: **PASSED**
> Validation matched test plan in [enhancement doc](https://github.com/longhorn/longhorn/blob/master/enhancements/20200319-default-disks-and-node-configuration.md#test-plan)

Steps to test:
- Create a single node k8s cluster
- Install Longhorn (master)
- In UI, `Setting/General`, enable `Create Default Disk on Labeled Nodes` and click `Save`
- Scale k8s cluster to 3 nodes
- In UI, `Node` page, newly added nodes shouldn't contain any disks or tags.
- In one of new nodes,
  - Create a directory on the root disk ( path1 = /home/longhorn ) 
  - Attach a new disk to the node, mount it to a directory ( path2 = /mnt/disk )
  - Add the following label  `node.longhorn.io/create-default-disk: "config"`
   and  Annotation
    ```
    node.longhorn.io/default-disks-config:
        '[{"path":"<path1>","allowScheduling":false},
          {"path":"<path2>","allowScheduling":true,"storageReserved":1024,"tags":["ssd","fast"]}]'
    node.longhorn.io/default-node-tags: '["fast","storage"]'
    ```  
     to the node
  - Node disks and tags will be created and match the annotations. **(PASSED)**
  - In UI, `Node` page, delete all disks and tags from the node
  - Disks and tags will be recreated immediately and match the annotations.

- In other node:
 
  - Use add the following label and invalid annotation:
    ```
     labels:
    node.longhorn.io/create-default-disk: "config"

    annotations:
        node.longhorn.io/default-disks-config:
            '[{"path":"<non-existing data path>","allowScheduling":false},
        node.longhorn.io/default-node-tags: '["slow",".*invalid-tag"]' 
    ```
   - In UI, `Node` page, node disk and tags should still be empty

  - Create a directory on the root disk ( path1 = /home/longhorn )
  - Correct path in node annotation
  - Node disks and tags should be created and match the new annotation
